### PR TITLE
BUG/BLD: special: Ensure symbols in `sf_error_state` shared library are exported/imported on MSVC

### LINKED ISSUE #20840: BUG: first shared library in scipy fails to be consumed by MSVC
While [building](https://github.com/conda-forge/scipy-feedstock/pull/277) scipy 1.14.0rc1 for conda-forge, I ran into:
```
lld-link: error: undefined symbol: scipy_sf_error_get_action
```
@rgommers noted
> That is a shared library, new in 1.14.0: [scipy/scipy#20321](https://github.com/scipy/scipy/pull/20321). It's the first one, so not surprised there is a hiccup with it.

My analysis:
> In that case it's probably a regular symbol-visibility-in-shared-windows-libraries issue, which needs `__declspec(dllimport)` / `__declspec(dllexport)` to work ([example](https://github.com/abseil/abseil-cpp/blob/20240116.2/absl/base/config.h#L736-L753)), which could look like
> 
> ```c
> // SF_ERR_DLL
> // inspired by https://github.com/abseil/abseil-cpp/blob/20240116.2/absl/base/config.h#L736-L753
> //
> // When building sf_error_state as a DLL, this macro expands to `__declspec(dllexport)`
> // so we can annotate symbols appropriately as being exported. When used in
> // headers consuming a DLL, this macro expands to `__declspec(dllimport)` so
> // that consumers know the symbol is defined inside the DLL. In all other cases,
> // the macro expands to nothing.
> // Note: SF_ERR_DLL_EXPORTS is set in CMakeLists.txt when building shared sf_error_state
> //       SF_ERR_DLL_IMPORTS is set by us as part of the interface for consumers of the DLL
> #if defined(SF_ERR_DLL_EXPORTS)
> #define SF_ERR_DLL __declspec(dllexport)
> #elif defined(SF_ERR_DLL_IMPORTS)
> #define SF_ERR_DLL__declspec(dllimport)
> #else
> #define SF_ERR_DLL
> #endif // defined(SF_ERR_DLL_EXPORTS)
> ```
> 
> plus an equivalent of the following CMake code:
> 
> ```cmake
> # for building sf_error_state target
> if(WIN32 AND MSVC)
>   set_target_properties(sf_error_state PROPERTIES DEFINE_SYMBOL "SF_ERR_DLL_EXPORTS")
>   if(BUILD_SHARED_LIBS)
>     target_compile_definitions(sf_error_state INTERFACE SF_ERR_DLL_IMPORTS)
>   endif()
> endif()
> ```
> 
> I have more experience with this than I'd like to, e.g. from long [efforts](https://github.com/conda-forge/grpc-cpp-feedstock/pull/243) around shared library builds in conda-forge.
> 
> The takeaway: _**Shared libraries with MSVC generally need source-code level annotations.**_ There's one limited escape hatch on CMake (`CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS`), but even that doesn't work for global data symbols. Unless meson has a magic bullet here, that's what we'll need to do IMO.
> 
> CC @steppi

Moving to issue here as requested by Ralf:
> Oh yes, fair. We keep being caught out by not having CI coverage for this at all - nothing but MinGW in SciPy CI and wheel builds :(
>
> Could you please move this to a new SciPy issue? This is a blocker for 1.14.0.

### PR DESCRIPTION
**Pull request by steppi**
#### Reference issue

Attempts to close #20840 

#### What does this implement/fix?

Following @h-vetinari's suggestion here, https://github.com/scipy/scipy/issues/20840#issue-2326546518, I've ensured symbols from the `sf_error_state` shared library are visible when compiling with MSVC by setting up macros for `_declspec(dllexport)` and `_declspec(dllimport)`, and defining relevant symbols within `meson.build`.

I've also added `intel-llvm-cl` to `scipy/scipy/meson.build` as suggested by @rgommers here, https://github.com/scipy/scipy/issues/20840#issuecomment-2159174627.

I also needed to remove some designated initializers in `scipy/scipy/special/_special_ufuncs.cpp` and `scipy/scipy/special/_gufuncs.cpp`. I was not aware that designated initializers are a C++20 feature which just happen to be available as GCC and Clang extensions when the standard is set at C++17.

#### Additional information

I'm still unable to build locally on Windows. I'm running into an error coming from Pythran that I haven't investigated yet. I'm just making this and marking it as draft for visibility.

```
....\micromamba\envs\scipy-dev\Lib\site-packages\pythran\pythonic/include/types/ndarray.hpp(479): error C2559: 'std::enable_if<anonymous-namespace'::pythonic::types::is_numexpr_arg<F>::value&&std::is_same<bool,F::dtype>::value&&F::value==1&&!anonymous-namespace'::pythonic::types::is_pod_array::value,anonymous-namespace'::pythonic::types::numpy_vexpr<anonymous-namespace'::pythonic::types::ndarray<double,anonymous-namespace'::pythonic::types::pshape<long,long>>,anonymous-namespace'::pythonic::types::ndarray<long,anonymous-namespace'::pythonic::types::pshape<long>>>>::type anonymous-namespace'::pythonic::types::ndarray<double,`anonymous-namespace'::pythonic::types::pshape<long,long>>::operator [](const F &) const': cannot overload a member function without ref-qualifier with a member function with ref-qualifier
```

### CODE REVIEW

**Comment by steppi** [comment]
Marking this ready for review since the Pythran error is unrelated and I saw @h-vetinari already added it to backport in https://github.com/conda-forge/scipy-feedstock/pull/277/files/f45d18587fa4de6116cb66777b1eab4b385a603e..2be00ed07518d08fbd2610d135d4b76db3d12053.

**Comment by h-vetinari** [comment]
> Marking this ready for review since the Pythran error is unrelated and I saw @h-vetinari already added it to backport in

Very attentive! I did that to test it in our infrastructure and was going to report back with the results. :)

**Comment by h-vetinari** [comment]
There's something that seems to be going wrong with the way `sf_error_state_consumer_extra_args` works.
```
[1274/1383] Linking target scipy/special/_special_ufuncs.cp311-win_amd64.pyd
FAILED: scipy/special/_special_ufuncs.cp311-win_amd64.pyd 
"lld-link"  /MACHINE:x64 /OUT:scipy/special/_special_ufuncs.cp311-win_amd64.pyd scipy/special/_special_ufuncs.cp311-win_amd64.pyd.p/_special_ufuncs.cpp.obj scipy/special/_special_ufuncs.cp311-win_amd64.pyd.p/_special_ufuncs_docs.cpp.obj scipy/special/_special_ufuncs.cp311-win_amd64.pyd.p/sf_error.cc.obj "/nologo" "/OPT:REF" "/DLL" "/IMPLIB:scipy\special\_special_ufuncs.cp311-win_amd64.lib" "--target=x86_64-pc-windows-msvc" "-nostdlib" "-Xclang" "--dependent-lib=msvcrt" "-fuse-ld=lld" "-Wl,-defaultlib:%BUILD_PREFIX%/Library/lib/clang/17/lib/windows/clang_rt.builtins-x86_64.lib" "scipy/special/sf_error_state.lib" "%PREFIX%\libs\python311.lib" "kernel32.lib" "user32.lib" "gdi32.lib" "winspool.lib" "shell32.lib" "ole32.lib" "oleaut32.lib" "uuid.lib" "comdlg32.lib" "advapi32.lib"
lld-link: error: undefined symbol: scipy_sf_error_get_action
>>> referenced by scipy/special/_special_ufuncs.cp311-win_amd64.pyd.p/sf_error.cc.obj:(void __cdecl sf_error_v(char const *, enum sf_error_t, char const *, char *))
```

From looking at the diff here, `scipy_sf_error_get_action` is annotated with `SCIPY_DLL`, and `_special_ufuncs` uses `sf_error_state_consumer_extra_args` which contains `-DSCIPY_DLL_IMPORTS`, so I'm a bit stumped where this is going wrong.

Looking at the [logs](https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/952593/logs/80), I see that the linker is looking for `scipy/special/sf_error_state.lib`, but I don't see that import library being created anywhere in the logs. The only times "sf_error_state." comes up (other than the failure above) are:
```
[44/1383] Compiling C object scipy/special/sf_error_state.dll.p/sf_error_state.c.obj
[331/1383] Linking target scipy/special/sf_error_state.dll
[850/1383] Generating symbol file scipy/special/sf_error_state.dll.p/sf_error_state.dll.symbols
```

Searching for "import library" and meson, I [find](https://mesonbuild.com/Reference-manual_functions.html) that there's an `implib: bool|str` argument, which we probably need to set.

**Comment by h-vetinari** [comment]
> Searching for "import library" and meson, I [find](https://mesonbuild.com/Reference-manual_functions.html) that there's an `implib: bool|str` argument, which we probably need to set.

As it turns out, this only works for executables, not for libraries. 😑 

The FAQ has an [answer](https://mesonbuild.com/FAQ.html#my-project-works-fine-on-linux-and-mingw-but-fails-to-link-with-msvc-due-to-a-missing-lib-file-fatal-error-lnk1181-why) (set symbol visibility; if no symbols exported), however that seems backwards/irrelevant to me, since we're already doing the visibility annotation with `__declspec(dllexport)`, and so AFAICT an import library _should_ have been produced for `sf_error_state`. I'm not certain from the log that it _wasn't_ - perhaps it just doesn't get a dedicated line...

OTOH, that means I'm out of answers for now...

**Comment by rgommers** [comment]
Cc @czgdp1807, since it's relevant to the MSVC CI job you're in the process of adding. Also, could you comment on whether this works for you?

**Review by czgdp1807 — COMMENTED** [review]
The changes look good to me. Let me check on my Azure VM if they work with MSVC + ifx + OpenBLAS. I will comment here shortly with the approval.

File: scipy/_build_utils/src/scipy_dll.h [hunk 1]
```diff
@@ -0,0 +1,9 @@
+#pragma once
+
+#if defined(SCIPY_DLL_EXPORTS)
+    #define SCIPY_DLL __declspec(dllexport)
+#elif defined(SCIPY_DLL_IMPORTS)
+    #define SCIPY_DLL __declspec(dllimport)
```
Comment (rgommers) [inline scipy/_build_utils/src/scipy_dll.h:6]: https://github.com/conda-forge/scipy-feedstock/pull/277#issuecomment-2140839770 contains a detailed example with code comments that would be useful to take over here.

File: scipy/special/meson.build [hunk 2]
```diff
@@ -25,10 +25,18 @@ _ufuncs_pxi_pxd_sources = [
...
+else
+  sf_error_state_extra_args = []
+  sf_error_state_consumer_extra_args = []
+endif
+
 sf_error_state_lib = shared_library('sf_error_state',
   ['sf_error_state.c'],
   include_directories: ['../_lib', '../_build_utils/src'],
-  cpp_args: ['-DSP_SPECFUN_ERROR'],
+  cpp_args: ['-DSP_SPECFUN_ERROR'] + sf_error_state_extra_args,
```
Comment (rgommers) [inline scipy/special/meson.build:39]: `-DSP_SPECFUN_ERROR` and `DSCIPY_DLL_EXPORTS`/`DSCIPY_DLL_EXPORTS` always go together, so it'd be better to combine them in a single variable in the `if meson.get_compiler('cpp').get_id() == 'msvc' block, and remove the separate `'-DSP_SPECFUN_ERROR'` usages

**Comment by rgommers** [comment]
> From looking at the diff here, `scipy_sf_error_get_action` is annotated with `SCIPY_DLL`, and `_special_ufuncs` uses `sf_error_state_consumer_extra_args` which contains `-DSCIPY_DLL_IMPORTS`, so I'm a bit stumped where this is going wrong.

It isn't annotated in all files. The `_special_ufuncs` uses `sf_error.cc`, which contains `scipy_sf_error_get_action`, and that file isn't touched in this PR yet.

**Comment by h-vetinari** [comment]
> It isn't annotated in all files. The `_special_ufuncs` uses `sf_error.cc`, which contains `scipy_sf_error_get_action`, and that file isn't touched in this PR yet.

That file only contains a single
https://github.com/scipy/scipy/blob/e1fecdfb0eb4f1bc01345b0a39930ab1cc94e1da/scipy/special/sf_error.cc#L41
and it's important to note that _usage_ of such functions doesn't need to be annotated, just the _declaration_.

**Comment by rgommers** [comment]
> and it's important to note that _usage_ of such functions doesn't need to be annotated, just the _declaration_.
2G
Good point. Note that `sf_error.pxd` does contain a declaration, but that's also not the problem - Cython [documents](https://cython.readthedocs.io/en/latest/src/userguide/external_C_code.html#referencing-c-header-files) to leave out `__declspec`.

* * *

Next guess at the problem: this PR uses `__declspec` only for MSVC, but conda-forge uses Clang-cl. The latter does support it, and it's enabled with `-fms-extensions` which is the default on Windows. Could you try whether adding `'clang-cl'` as the compiler ID fixes things for conda-forge?

**Comment by h-vetinari** [comment]
> Could you try whether adding `'clang-cl'` as the compiler ID fixes things for conda-forge?

great catch, thanks!

**Review by czgdp1807 — COMMENTED** [review]
The changes here are not working. I have to use the following diff to get it built with MSVC + ifx + OpenBLAS,

```diff
-    SCIPY_DLL void scipy_sf_error_set_action(sf_error_t code, sf_action_t action);
+    __declspec(dllexport) void scipy_sf_error_set_action(sf_error_t code, sf_action_t action);

-    SCIPY_DLL sf_action_t scipy_sf_error_get_action(sf_error_t code);
+    __declspec(dllexport) sf_action_t scipy_sf_error_get_action(sf_error_t code);
```

**Comment by h-vetinari** [comment]
> I have to use the following diff to get it built with MSVC + ifx + OpenBLAS,

Unfortunately that's not a workable solution. It seems you're running into a variant of the issue described just above by @rgommers, i.e. the `SCIPY_DLL_{EX,IM}PORT` machinery may not be activated for the meson-IDs of the compilers that you're using. I'm testing the following diff in conda-forge right now, feel free to give this a shot as well. In any case, we cannot hard-code the `__declspec` in the sources.
```diff
--- a/scipy/special/meson.build
+++ b/scipy/special/meson.build
@@ -25,7 +25,7 @@ _ufuncs_pxi_pxd_sources = [
   fs.copyfile('_ufuncs_extra_code_common.pxi'),
 ]

-if meson.get_compiler('cpp').get_id() == 'msvc'
+if meson.get_compiler('cpp').get_id() in ['msvc', 'clang-cl', 'intel-cl']
   sf_error_state_extra_args = ['-DSCIPY_DLL_EXPORTS']
   sf_error_state_consumer_extra_args = ['-DSCIPY_DLL_IMPORTS']
```

**Comment by czgdp1807** [comment]
Correct. I just hardcoded to test SciPy locally. Adding to the main is -1 by me as well. Well I am using `cl` on Windows. May be, extra IDs should work.

**Comment by steppi** [comment]
The core problem was that I was only passing `SCIPY_DLL_EXPORTS` and `SCIPY_DLL_IMPORTS` in `cpp_args`, but there are some places where it also needs to be passed in `cargs` (https://github.com/scipy/scipy/issues/20840#issuecomment-2161201064). I had to build without Pythran in order to observe this locally. The error due to the missing symbol happens after the Pythran error I was seeing.

I'm still seeing another build error, but it may be environment specific.

```
LINK : fatal error LNK1181: cannot open input file 'gfortran.lib'
```

I'm building with `ifx`, so I guess this may be an inadvertent compiler mixing problem.

File: scipy/_build_utils/src/scipy_dll.h (hunk 1 above)
Comment (h-vetinari) [inline scipy/_build_utils/src/scipy_dll.h:6]:
```suggestion
// SCIPY_DLL
// inspired by https://github.com/abseil/abseil-cpp/blob/20240116.2/absl/base/config.h#L736-L753
//
// When building sf_error_state as a DLL, this macro expands to `__declspec(dllexport)`
// so we can annotate symbols appropriately as being exported. When used in
// headers consuming a DLL, this macro expands to `__declspec(dllimport)` so
// that consumers know the symbol is defined inside the DLL. In all other cases,
// the macro expands to nothing.
// Note: SCIPY_DLL_{EX,IM}PORTS are set in scipy/special/meson.build
#if defined(SCIPY_DLL_EXPORTS)
    #define SCIPY_DLL __declspec(dllexport)
#elif defined(SCIPY_DLL_IMPORTS)
    #define SCIPY_DLL __declspec(dllimport)
```

Comment (h-vetinari) [reply scipy/_build_utils/src/scipy_dll.h:6]: There's a slight mismatch here, how the name `SCIPY_DLL` is scipy-wide, but it's defined in scipy/special. This isn't much of an issue right now, but if we ever have another shared library, and one shared library needs to use symbols from the other, then we'll need to split `SCIPY_DLL` into two, or rather, one per separate shared library.

Not a blocker for now, but noting it for context.

File: scipy/special/_special_ufuncs.cpp [hunk 3]
```diff
@@ -206,9 +206,15 @@ extern const char *yve_doc;
 extern "C" int wrap_PyUFunc_getfperr() { return PyUFunc_getfperr(); }
 
 static PyModuleDef _special_ufuncs_def = {
-    .m_base = PyModuleDef_HEAD_INIT,
-    .m_name = "_special_ufuncs",
-    .m_size = -1,
```
Comment (h-vetinari) [inline scipy/special/_special_ufuncs.cpp:211]: It's a pity, I like the designated initializer syntax much better. All supported (non-EOL) MSVC versions have full support for C++20, so I'd be open to consider using C++20 on windows (without touching the C++17 baseline for now, yet still enabling designated initializer use because GCC/clang have it as an extension in earlier standard versions).

**Review by h-vetinari — COMMENTED** [review]
Fresh run underway in conda-forge. I had thought about the C/C++ difference but only looked at the consuming libraries (which _are_ C++), so missed that `sf_error_state` itself was a C-lib...

**Comment by h-vetinari** [comment]
Can confirm that this now builds successfully! 🥳 

I'd still consider keeping the designated initializers and bumping to C++20 on windows.

File: scipy/_build_utils/src/scipy_dll.h (hunk 1 above)
Comment (steppi) [reply scipy/_build_utils/src/scipy_dll.h:6]: That's a great point @h-vetinari! I did not at all consider the situation where we have two shared libraries and one of them needs symbols from the other. Like you said, there would be places  where we'd need separate macros, one expanding to  `__declspec(dllexport)` and the other to `__declspec(dllimport)`. I think I was just hoping to keep things simple for now.

Also, thanks for the comment! I was working on one locally, but was torn between documenting this specifically for `sf_error_state`, or giving the general conditions where one would use this. I'll consider this settled.

File: scipy/special/_special_ufuncs.cpp (hunk 3 above)
Comment (steppi) [reply scipy/special/_special_ufuncs.cpp:211]: I'd be 100% onboard with changing the standard to C++20 on Windows. Can we do this? Does it need a discussion first?

Comment (h-vetinari) [reply scipy/special/_special_ufuncs.cpp:211]: As long as @rgommers doesn't object, I'd consider this settled. I spent quite a bit of time on the various standards and features supported across the compiler landscape, and using C++20 has no cost in terms of compatibility.

The only "price" is would be using different standards between windows and unix.

Comment (rgommers) [reply scipy/special/_special_ufuncs.cpp:211]: Different standard across platforms doesn't sound like a healthy idea to me, nor is it technically correct to then use designated initializers - we don't only worry about what we have in CI, but also niche compilers that we can't test. And our roadmap says _"Given how big of a release the C++20 standard was, it is expected that it will take a [while yet](https://discourse.llvm.org/t/rfc-clang-17-0-6-would-be-minimum-version-to-build-llvm-in-c-20/75345/8) before we can start considering moving our baseline."_

This is a quite trivial change and we have many `PyModuleDef`'s that look like this across the code base. So nothing much is lost by sticking with C++17.

Last reason that comes to mind: we're going to get other platform-specific differences - I've already seen one recently with Pythran. The bump to C17 also wasn't smooth, there's always some hiccup.

Comment (h-vetinari) [reply scipy/special/_special_ufuncs.cpp:211]: Yeah, I wrote that line. :)

But the roadmap talks about C++20 support across all compilers - the situation can be different for a single one.

> but also niche compilers that we can't test.

That's an interesting point - we do make quite a bit of effort to survey the platform landscape, but we say nothing about niche compilers. Is there any platform we care about that doesn't use gcc/clang/msvc?

> Different standard across platforms doesn't sound like a healthy idea to me

I agree of course, though in this case I'm tempted to think the benefits might outweigh the costs. Initialising structs without designated initializers is a minefield, whereas with them the intent becomes perfectly obvious & safe. I prefer the added safety, and would be willing to accept the cost of shaking out some C++20 bugs.

Comment (rgommers) [reply scipy/special/_special_ufuncs.cpp:211]: > Is there any platform we care about that doesn't use gcc/clang/msvc?

Sure:
- Intel compilers are a major one we don't currently test (Spack does have CI for SciPy + oneAPI),
- Emscripten comes to mind (for Pyodide support), we don't test it in CI yet, but hopefully will in the near future.
- AIX uses both GCC and IBM's compilers (XL C/C++). The latter we've regularly broken in the past, not sure what the status is now.
- I'm aware that there are proprietary ones too, like Fujitsu has one for the Fukagu supercomputer - no idea how different it is, just that at least in NumPy there's been some PRs to support it in the past.

File: scipy/special/meson.build (hunk 2 above)
Comment (rgommers) [reply scipy/special/meson.build]: @steppi did you see this comment? Unless I'm mistaken about these flags always going together, this would be nice to address.

File: scipy/special/_special_ufuncs.cpp (hunk 3 above)
Comment (h-vetinari) [reply scipy/special/_special_ufuncs.cpp:211]: Alright, consider the suggestion withdrawn, seems we'll wait a couple more years for designated initializers 🥲

BTW, the XL compilers are actually mentioned in the toolchain, but we could add Intel and Emscripten. I'll add it to https://github.com/scipy/scipy/issues/19815

**Review by h-vetinari — APPROVED** [review]
Thanks @steppi!

File: scipy/special/meson.build (hunk 2 above)
Comment (steppi) [reply scipy/special/meson.build]: Sorry, I saw it but forget I didn’t respond. I don’t think these always go together. `-DSPECUN_ERROR` goes in the `cpp_args` of all extensions which use special function error handling, regardless of platform. If it isn’t set, then  all calls to `set_error` in special become no-ops. The DLL related args should only be passed in when the compiler is `msvc ` or one of the other windows compilers . There are also some places where the DLL related args need to go into `c_args` ( for the C `sf_error_state` shared library itself of course, but also in all extensions which have C source files which use special error handling.)

Comment (rgommers) [reply scipy/special/meson.build]: That doesn't quite mean they don't go together. Here is what I meant: https://github.com/rgommers/scipy/commit/e1206e30a20b22eb5ccb430573ef12041f95906d

Works for me locally, and does what you describe I believe. I think it should work with MSVC too. Looks a bit cleaner to me, but not a blocking comment - if you think it helps please use it, if not then let's merge this as is.

Comment (steppi) [reply scipy/special/meson.build]: Ah, got it. Thanks, that does look better. I’ll use it.

**Review by rgommers — APPROVED** [review]
LGTM too, let's get this in. Thanks @steppi and @h-vetinari!

File: scipy/special/_gufuncs.cpp [hunk 4]
```diff
@@ -53,9 +53,15 @@ extern const char *sph_harm_all_doc;
 extern "C" int wrap_PyUFunc_getfperr() { return PyUFunc_getfperr(); }
 
 static PyModuleDef _gufuncs_def = {
-    .m_base = PyModuleDef_HEAD_INIT,
-    .m_name = "_gufuncs",
-    .m_size = -1,
+    PyModuleDef_HEAD_INIT,
+    "_gufuncs",
```
Comment (tylerjereddy) [inline scipy/special/_gufuncs.cpp:57]: I had to resolve 1-2 merge conflicts when backporting to gh-20933 but full testsuite was happy locally at least. I'll flush the full CI later today probably.
