### PR TITLE
DOC: special: Fix Airy Documentation

### LINKED ISSUE #24093: DOC: Mistake in scipy.special.airy documentation
### Issue with current documentation:

I think there is a mistake in the Notes for scipy.special.airy. The text there shows the conversion between the Airy and modified Bessel functions. However, there is a factor 'z' missing in the relation between Ai(z) and K_{1/3}(t). The correct formula is given in Equation 10.4.26 in the Handbook of Mathematical Functions by Abramowitz & Stegun (1965) – see screenshots attached.

### Idea or request for content:

_No response_

### Additional context (e.g. screenshots, GIFs)

Image

Image

### PR DESCRIPTION
**Pull request by fbourgey**
Closes #24093

### CODE REVIEW

File: scipy/special/_special_ufuncs_docs.cpp [hunk 1]
```diff
@@ -442,28 +442,29 @@ const char *airy_doc = R"(
...
     .. math::
 
-        Ai(z) = \frac{1}{\pi \sqrt{3}} K_{1/3}(t)
-
-        Ai'(z) = -\frac{z}{\pi \sqrt{3}} K_{2/3}(t)
-
-        Bi(z) = \sqrt{\frac{z}{3}} \left(I_{-1/3}(t) + I_{1/3}(t) \right)
-
-        Bi'(z) = \frac{z}{\sqrt{3}} \left(I_{-2/3}(t) + I_{2/3}(t)\right)
+        \operatorname{Ai}(z) = \frac{1}{\pi}\sqrt{\frac{z}{3}} \, K_{1/3}(t)
```
Comment (tylerjereddy) [inline scipy/special/_special_ufuncs_docs.cpp:461]: I looked at the rendered version of the docs and this does indeed better match equation 6 from https://mathworld.wolfram.com/AiryFunctions.html (they are now identical if you swap z for x).

This is way outside my wheelhouse though, so let's let a `special` regular confirm.

File: scipy/special/_special_ufuncs_docs.cpp [hunk 2]
```diff
@@ -442,28 +442,29 @@ const char *airy_doc = R"(
 
     Notes
     -----
-    The Airy functions Ai and Bi are two independent solutions of
+    The Airy functions :math:`\operatorname{Ai}` and :math:`\operatorname{Bi}` are two 
+    independent solutions of
 
     .. math:: y''(x) = x y(x).
```
Comment (j-bowhay) [inline scipy/special/_special_ufuncs_docs.cpp]: For consistency maybe we should have 
```suggestion
    .. math:: y''(z) = z y(z).
```

**Review by j-bowhay — APPROVED** [review]
Thanks, keep them coming!

**Comment by j-bowhay** [comment]
Actually sorry one last thing, can you change the text in the example which currently says `Plot Ai(x) and Bi(x).` to also be consistent. Also for documentation only changes please can you add `[docs only]` to your commit message to save resources

**Comment by j-bowhay** [comment]
Thanks again!
