### PR TITLE
BLD: add `-std=c99` flag to scipy.special extensions using cosine.c

### LINKED ISSUE #13840: manylinux1 builds are failing because of C99 usage in `special/_cosine.c`
Example build log from `scipy-wheels` CI: [link](https://dev.azure.com/numpy/numpy/_build/results?buildId=16513&view=results)

Should be fixed either by passing in the `-std=c99` flag correctly, using the `_c99compat.h` include, or dropping `manylinux1`. Will have a look at that now.
```
error: Command "gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wl,-strip-all -I/usr/local/include -fPIC -DHAVE_CBLAS -I/io/scipy/scipy/special -I/opt/python/cp37-cp37m/lib/python3.7/site-packages/numpy/core/include -I/opt/python/cp37-cp37m/include/python3.7m -Iscipy/_lib -Iscipy/_build_utils/src -I/opt/python/cp37-cp37m/lib/python3.7/site-packages/numpy/core/include -I/opt/python/cp37-cp37m/lib/python3.7/site-packages/numpy/core/include -I/opt/python/cp37-cp37m/lib/python3.7/site-packages/numpy/core/include -I/opt/python/cp37-cp37m/include/python3.7m -c scipy/special/_cosine.c -o build/temp.linux-x86_64-3.7/scipy/special/_cosine.o -MMD -MF build/temp.linux-x86_64-3.7/scipy/special/_cosine.o.d" failed with exit status 1
In file included from /opt/python/cp37-cp37m/include/python3.7m/Python.h:8:0,
                 from /opt/python/cp37-cp37m/lib/python3.7/site-packages/numpy/core/include/numpy/npy_common.h:11,
                 from scipy/special/cephes/polevl.h:65,
                 from scipy/special/_cosine.c:20:
/opt/python/cp37-cp37m/include/python3.7m/pyconfig.h:1526:0: warning: "_POSIX_C_SOURCE" redefined [enabled by default]
 #define _POSIX_C_SOURCE 200809L
 ^
In file included from /usr/include/stdio.h:28:0,
                 from scipy/special/_cosine.c:17:
/usr/include/features.h:198:0: note: this is the location of the previous definition
 #  define _POSIX_C_SOURCE 200112L
 ^
scipy/special/_cosine.c: In function ‘_poly_approx’:
scipy/special/_cosine.c:207:12: warning: unused variable ‘px’ [-Wunused-variable]
     double px;
            ^
scipy/special/_cosine.c: In function ‘cosine_invcdf’:
scipy/special/_cosine.c:237:16: error: ‘NAN’ undeclared (first use in this function)
         return NAN;
                ^
scipy/special/_cosine.c:237:16: note: each undeclared identifier is reported only once for each function it appears in
In file included from /opt/python/cp37-cp37m/include/python3.7m/Python.h:8:0,
                 from /opt/python/cp37-cp37m/lib/python3.7/site-packages/numpy/core/include/numpy/npy_common.h:11,
                 from scipy/special/cephes/polevl.h:65,
                 from scipy/special/_cosine.c:20:
/opt/python/cp37-cp37m/include/python3.7m/pyconfig.h:1526:0: warning: "_POSIX_C_SOURCE" redefined [enabled by default]
 #define _POSIX_C_SOURCE 200809L
 ^
In file included from /usr/include/stdio.h:28:0,
                 from scipy/special/_cosine.c:17:
/usr/include/features.h:198:0: note: this is the location of the previous definition
 #  define _POSIX_C_SOURCE 200112L
 ^
scipy/special/_cosine.c: In function ‘_poly_approx’:
scipy/special/_cosine.c:207:12: warning: unused variable ‘px’ [-Wunused-variable]
     double px;
            ^
scipy/special/_cosine.c: In function ‘cosine_invcdf’:
scipy/special/_cosine.c:237:16: error: ‘NAN’ undeclared (first use in this function)
         return NAN;
                ^
scipy/special/_cosine.c:237:16: note: each undeclared identifier is reported only once for each function it appears in
```

### PR DESCRIPTION
**Pull request by rgommers**
This fixes the manylinux1 builds. Closes gh-13840

Also clean up an outdated try-catch.

### CODE REVIEW

**Comment by rgommers** [comment]
Still a 32-bit Windows failure. This code is quite fishy:
```
    // M_PI is not exactly π.  In fact, float64(π - M_PI) is
    // 1.2246467991473532e-16.  h is supposed to be x + π, so to compute
    // h accurately, we write the calculation as:
    h = (x + M_PI) + 1.2246467991473532e-16;
```
Not only should you not rely on `M_PI` being available, but if it is available, the exact numerical value is going to be a compiler-dependent approximation to `\pi`. It's very hard to believe that all implementations are going to be off by exactly `np.finfo(np.float64).eps - 1e-16`.

I'd prefer to mark this as a knownfail and open an issue to follow up (if desired, it's quite a niche failure). @WarrenWeckesser can you have a look at this?

File: scipy/special/_cosine.c [hunk 1]
```diff
@@ -19,6 +19,9 @@
 
 #include "cephes/polevl.h"
 
+#if !defined(M_PI)
+#define M_PI 3.1415926535897932384626433832795028841971
```
Comment (WarrenWeckesser) [inline scipy/special/_cosine.c:23]: Can you try this?
```suggestion
#define M_PI 0x1.921fb54442d18p+1
```
That should be the exact 64 bit floating point value that is closest to π.   I don't know if this will make a difference, but it is worth a shot.  Without having the actual compiler to test, I don't know if it parses the extra long decimal representation in a way that ends up being different from the best 64 bit approximation to π.

Comment (WarrenWeckesser) [reply scipy/special/_cosine.c:23]: > Not only should you not rely on M_PI being available, ...

And I even knew that, but forgot to handle it here.

> ... but if it is available, the exact numerical value is going to be a compiler-dependent approximation to \pi. It's very hard to believe that all implementations are going to be off by about `np.finfo(np.float64).eps - 1e-16`.

The code was written under the assumption that a C `double` would be a IEEE 754 64 bit floating point value.   The C language standard does not make such a guarantee, and if a C `double` is something else, then you are correct, this code won't work as I expected.

Comment (rgommers) [reply scipy/special/_cosine.c:23]: Or just see what the actual defines in `math.h` are. Just checked in GCC 9.3.0 on macOS, and it's
```
#define M_PI        3.14159265358979323846264338327950288   /* pi             */
```

Comment (rgommers) [reply scipy/special/_cosine.c]: Giving this a go. That's a funky-looking way to write a floating-point number.

**Comment by rgommers** [comment]
That hexadecimal representation fixed it, merging. Thanks @WarrenWeckesser

**Comment by ev-br** [comment]
Maybe upstream it to `npy_math.h`'s definition of `NPY_PI` ?

**Comment by rgommers** [comment]
That could make sense. Would you want to do that @WarrenWeckesser?
