### PR TITLE
BUG: special: Fix unchecked malloc in stirling2.h

### LINKED ISSUE #22336: BUG: special: Unchecked malloc in stirling2.h
`malloc()` is called here, but the possible NULL return value is not handled:

https://github.com/scipy/scipy/blob/171d671bbc4bf3ad30bf349f8121e6b5090dce33/scipy/special/stirling2.h#L43

If `malloc()` fails, dereferencing `curr` will crash Python.

### PR DESCRIPTION
**Pull request by j-bowhay**
#### Reference issue

Closes #22336
#### What does this implement/fix?

Replaces use of `malloc` with `std::vector`.

### CODE REVIEW

**Comment by WarrenWeckesser** [comment]
Thanks, @j-bowhay, but this doesn't fix the problem.  `std::vector` will raise `std::bad_alloc` is there is not sufficient memory for the vector.

**Comment by j-bowhay** [comment]
Ah ok I wasn't quite sure about this, should I catch this and throw a `PyErr_NoMemory()` error?

**Comment by j-bowhay** [comment]
Updated, hopefully this is more along the right lines @WarrenWeckesser. I guess this should use `SF_ERROR_NOMEM` when #22080 is merged

**Comment by j-bowhay** [comment]
Thanks done

File: scipy/special/stirling2.h [hunk 1]
```diff
@@ -40,7 +43,11 @@ double _stirling2_dp(double n, double k){
         return 0.;
     }
     int arraySize = k <= n - k + 1 ? k : n - k + 1;
-    double *curr = (double *) malloc(arraySize * sizeof(double));
+    auto curr = std::unique_ptr<double[]>{new (std::nothrow) double[arraySize]()};
```
Comment (WarrenWeckesser) [inline scipy/special/stirling2.h:46]:
```suggestion
    auto curr = std::unique_ptr<double[]>{new (std::nothrow) double[arraySize]};
```
Those parentheses cause the array to be initialized with zeros.  This is not needed, since `curr` will be initialized to 1 below.

File: scipy/special/stirling2.h [hunk 2]
```diff
@@ -40,7 +43,11 @@ double _stirling2_dp(double n, double k){
...
+    if (curr == nullptr){
```
Comment (WarrenWeckesser) [inline scipy/special/stirling2.h:47]:
```suggestion
    if (curr == nullptr) {
```
Whitespace nit.

File: scipy/special/stirling2.h [hunk 3]
```diff
@@ -49,7 +56,6 @@ double _stirling2_dp(double n, double k){
             for (int j = 1; j < k; j++){
                 curr[j] = (j + 1) * curr[j] + curr[j - 1];
                 if (isinf(curr[j])){
-                    free(curr);
```
Comment (WarrenWeckesser) [inline scipy/special/stirling2.h:52]: Might as well fix this while touching this file: here and below, on overflow, call `sf_error` with the appropriate arguments:

```
                    sf_error("stirling2", SF_ERROR_OVERFLOW, NULL);
```

**Review by WarrenWeckesser — CHANGES_REQUESTED** [review]
I suggested a few tweaks to the code.

File: scipy/special/stirling2.h (hunk 2 above)
Comment (j-bowhay) [reply scipy/special/stirling2.h:47]: I considered it this but it seemed inconsistent with the rest of the file?

Comment (WarrenWeckesser) [reply scipy/special/stirling2.h:47]: Actually, the file is not completely consistent. I can't imagine any C/C++ coding standard that would not put a space here. And barring the adoption of some other style guide, my fallback is [PEP 7](https://peps.python.org/pep-0007/), which at least has an example of an `if` statement that has a space before the opening bracket of the code block. (See also [Google's style guide](https://google.github.io/styleguide/cppguide.html#Formatting_Looping_Branching), which includes the space.)  So let's use the more common convention in new code here.

And if you want, go ahead and fix the other missing spaces (but that's not a blocker).

**Review by steppi — APPROVED** [review]
This looks good to me. Thanks @j-bowhay. Thanks for the good suggestions @WarrenWeckesser. I'll wait for you  to approve or dismiss the requested changes before merging or I guess you can just merge it.

**Review by WarrenWeckesser — APPROVED** [review]

File: scipy/special/stirling2.h (hunk 3 above)
Comment (WarrenWeckesser) [reply scipy/special/stirling2.h:52]: It turns out that this condition can't happen, because currently `_stirling2_dp(n, k)` is called only if `n <= 50`, and for values of `n` that small, there is no overflow.  The change was still worthwhile, since how the code is called could change in the future.
