### PR TITLE
ENH:MAINT: sparse.linalg: rewrite ARPACK in C

### LINKED ISSUE #9023: Opportunity to add a seed or a random_state parameter to scipy.sparse.linalg.eigs eigsh and svds ?
scipy.sparse.linalg.eigs eigsh and svds cannot be seeded if the v0 parameter is not passed which leads to reproducibility issue in those cases. It might be useful to add a random_state or seed parameter to those functions to allow users to still set a seed without passing v0. This seed would then be used to initialize v0.

This request is related to a scikit-learn issue (https://github.com/scikit-learn/scikit-learn/issues/5545) and you can find more details there.

### LINKED ISSUE #9185: BUG: sparse.linalg: ARPACK error 1
Hi, I get this error : 

scipy.sparse.linalg.eigen.arpack.arpack.ArpackError: ARPACK error 1: The Schur form computed by LAPACK routine dlahqr could not be reordered byLAPACK routine dtrsen. Re-enter subroutine dneupd  with IPARAM(5)NCV and increase the size of the arrays DR and DI to have dimension at least dimension NCV and allocate at least NCV columns for Z. NOTE: Not necessary if Z and V share the same space. Please notify the authors if this erroroccurs.

So I notify.

The code _sometimes_ producing this error is rather large, but it happens there (I say _sometimes_ because it seems that the result changes at each run... which is also strange...):

```
from scipy.sparse.linalg import eigs
from scipy.sparse import bmat
from pickle import load
with open("ABpickle.dump", "rb") as file: 
    A=load(file)
    B=load(file)
λ, v = eigs(A, 1, bmat([[B, None], [None, B]], format="csc"), which="LR", tol=1e-6) 
print(λ)
```
The pickle dump of A and B can be found [here](https://www.dropbox.com/s/alv4cuyqx0ltvo4/ABpickle.dump?dl=0).

python 3.6.6
scipy 1.1.0
macOS

### LINKED ISSUE #9460: BUG: sparse.linalg.eigs: sorting behavior reliability
Related to #9453 and discussions with @rc and @lobpcg. Short summary is that I'm still ok with forcing the sort order in the test because I don't see any connection between the recent `lobpcg` adjustments and the observed sorting issue -- looks to be some vendored `ARPACK` stuff not related to recent merges -- a new test added for other behavior just happens to pick up on this instability in `eigs()`. But would be good to sort out, no pun intended, eventually.

I did a bit of `git bisection` style analysis on the problematic `vals` array sort order returned by `vals, vecs = eigs(A, k=2)` in `test_eigs_consistency`. I used 500 repeat trials to measure the consistency in the sorted results over git commit history, where a "consistency" is measured as either real or complex result that is sorted to be equivalent to reverse order `np.array([[5., 4.]])` -- I think the "imaginary" component of the number is always reported in the results, but didn't distinguish, my focus was the sort order.

- on current master ( a905607) in 500 trials `eigs` produces the "correct" sort order **94.8 %** of the time
- when I merged the largest option lobpcg fix ( 43193b90 ) 500 trials of eigs() still only sorts with **94.8%** fidelity
- if I go back to some commit from July 2018 ( c61e36fd )  -- still **94.8 %**
- if I go back to some commit from 2017 ( 541c0ee31 ) -- still **94.8 %**
- if I go back to before some ARPACK bundling changes in 2016 ( 0fbef6d6 ) -- **92.0 %**

The specific script used during my tests, which could still be cleaned up a bit more to focus on just 1 case, etc.:

```python
import numpy as np
import scipy
import scipy.sparse
from scipy.sparse.linalg.eigen.lobpcg import lobpcg
from scipy.sparse.linalg import eigs
from scipy.sparse import spdiags
from numpy.testing import assert_allclose

correct_counter = 0
for n, atol in [[20, 1e-3], [5, 1e-8]]:
    for i in range(500):
        vals = np.arange(1, n+1, dtype=np.float64)
        A = spdiags(vals, 0, n, n)
        vals, vecs = eigs(A, k=2)
        print("vals:", vals)
        
        if np.allclose(vals, np.array([[5., 4.]])):
           correct_counter += 1

print("Percent correct result sorting:", correct_counter / 5.)
```

### LINKED ISSUE #10744: BUG: sparse.linalg: Test failures with BLIS BLAS
Several tests related to linalg module fail when using [BLIS BLAS](https://github.com/flame/blis) (installed from conda-forge)

#### Reproducing code example:

```
conda create -c conda-forge -n numpy-blis numpy "blas=*=blis" scipy pytest python=3.7`
conda activate numpy-blis
pytest --pyargs scipy
```

#### Error message:

Following unit tests fail,
 - [ ] `TestVectorNorms.test_overflow`
 - [ ] `TestVectorNorms.test_stable`
 - [ ] `TestEigBanded.test_dgbtrf`
 - [ ] `TestQRinsert_d.test_sqr_p_col`
 - [ ] `TestQRinsert_d.test_non_unit_strides_p_col`
 - [ ] `TestQRinsert_d.test_neg_strides_p_col`
 - [ ] `TestQRinsert_d.test_non_itemsize_strides_p_col`
 - [ ] `TestQRinsert_d.test_non_native_byte_order_p_col`
 - [ ] `TestQRinsert_d.test_overwrite_qu_rank_p`
 - [ ] `test_zero_rhs[lgmres]`
 - [ ] `TestInt32Overflow.test_matvecs`
 - [ ] `TestCorrPearsonr.test_very_small_input_values`
 - [ ] `TestCorrPearsonr.test_extremely_large_input_values`

<details>

see full details below,
```
________________________________________________________ TestVectorNorms.test_overflow ________________________________________________________

self = <scipy.linalg.tests.test_basic.TestVectorNorms object at 0x7f5180a2c910>

    def test_overflow(self):
        # unlike numpy's norm, this one is
        # safer on overflow
        a = array([1e20], dtype=float32)
>       assert_almost_equal(norm(a), a)

/home/rth/.miniconda3/envs/sklearn-blis/lib/python3.7/site-packages/scipy/linalg/tests/test_basic.py:1323: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

x = array(nan), y = array([1.e+20], dtype=float32), func = <ufunc 'isnan'>, hasval = 'nan'

    def func_assert_same_pos(x, y, func=isnan, hasval='nan'):
        """Handling nan/inf.
    
        Combine results of running func on x and y, checking that they are True
        at the same locations.
    
        """
        x_id = func(x)
        y_id = func(y)
        # We include work-arounds here to handle three types of slightly
        # pathological ndarray subclasses:
        # (1) all() on `masked` array scalars can return masked arrays, so we
        #     use != True
        # (2) __eq__ on some ndarray subclasses returns Python booleans
        #     instead of element-wise comparisons, so we cast to bool_() and
        #     use isinstance(..., bool) checks
        # (3) subclasses with bare-bones __array_function__ implementations may
        #     not implement np.all(), so favor using the .all() method
        # We are not committed to supporting such subclasses, but it's nice to
        # support them if possible.
        if bool_(x_id == y_id).all() != True:
            msg = build_err_msg([x, y],
                                err_msg + '\nx and y %s location mismatch:'
                                % (hasval), verbose=verbose, header=header,
                                names=('x', 'y'), precision=precision)
>           raise AssertionError(msg)
E           AssertionError: 
E           Arrays are not almost equal to 7 decimals
E           
E           x and y nan location mismatch:
E            x: array(nan)
E            y: array([1.e+20], dtype=float32)

/home/rth/.miniconda3/envs/sklearn-blis/lib/python3.7/site-packages/numpy/testing/_private/utils.py:745: AssertionError
_________________________________________________________ TestVectorNorms.test_stable _________________________________________________________

self = <scipy.linalg.tests.test_basic.TestVectorNorms object at 0x7f518035ce50>

    def test_stable(self):
        # more stable than numpy's norm
        a = array([1e4] + [1]*10000, dtype=float32)
        try:
            # snrm in double precision; we obtain the same as for float64
            # -- large atol needed due to varying blas implementations
>           assert_allclose(norm(a) - 1e4, 0.5, atol=1e-2)

/home/rth/.miniconda3/envs/sklearn-blis/lib/python3.7/site-packages/scipy/linalg/tests/test_basic.py:1331: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

actual = array(0.48339844), desired = array(0.5), rtol = 1e-07, atol = 0.01, equal_nan = True, err_msg = '', verbose = True

    def assert_allclose(actual, desired, rtol=1e-7, atol=0, equal_nan=True,
                        err_msg='', verbose=True):
        """
        Raises an AssertionError if two objects are not equal up to desired
        tolerance.
    
        The test is equivalent to ``allclose(actual, desired, rtol, atol)`` (note
        that ``allclose`` has different default values). It compares the difference
        between `actual` and `desired` to ``atol + rtol * abs(desired)``.
    
        .. versionadded:: 1.5.0
    
        Parameters
        ----------
        actual : array_like
            Array obtained.
        desired : array_like
            Array desired.
        rtol : float, optional
            Relative tolerance.
        atol : float, optional
            Absolute tolerance.
        equal_nan : bool, optional.
            If True, NaNs will compare equal.
        err_msg : str, optional
            The error message to be printed in case of failure.
        verbose : bool, optional
            If True, the conflicting values are appended to the error message.
    
        Raises
        ------
        AssertionError
            If actual and desired are not equal up to specified precision.
    
        See Also
        --------
        assert_array_almost_equal_nulp, assert_array_max_ulp
    
        Examples
        --------
        >>> x = [1e-5, 1e-3, 1e-1]
        >>> y = np.arccos(np.cos(x))
        >>> np.testing.assert_allclose(x, y, rtol=1e-5, atol=0)
    
        """
        __tracebackhide__ = True  # Hide traceback for py.test
        import numpy as np
    
        def compare(x, y):
            return np.core.numeric.isclose(x, y, rtol=rtol, atol=atol,
                                           equal_nan=equal_nan)
    
        actual, desired = np.asanyarray(actual), np.asanyarray(desired)
        header = 'Not equal to tolerance rtol=%g, atol=%g' % (rtol, atol)
        assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
>                            verbose=verbose, header=header, equal_nan=equal_nan)

/home/rth/.miniconda3/envs/sklearn-blis/lib/python3.7/site-packages/numpy/testing/_private/utils.py:1510: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

comparison = <function assert_allclose.<locals>.compare at 0x7f5180670d40>, x = array(0.48339844), y = array(0.5)
err_msg = '\nMismatch: 100%\nMax absolute difference: 0.01660156\nMax relative difference: 0.03320312', verbose = True
header = 'Not equal to tolerance rtol=1e-07, atol=0.01', precision = 6, equal_nan = True, equal_inf = True

    def assert_array_compare(comparison, x, y, err_msg='', verbose=True,
                             header='', precision=6, equal_nan=True,
                             equal_inf=True):
        __tracebackhide__ = True  # Hide traceback for py.test
        from numpy.core import array, array2string, isnan, inf, bool_, errstate
    
        x = array(x, copy=False, subok=True)
        y = array(y, copy=False, subok=True)
    
        # original array for output formatting
        ox, oy = x, y
    
        def isnumber(x):
            return x.dtype.char in '?bhilqpBHILQPefdgFDG'
    
        def istime(x):
            return x.dtype.char in "Mm"
    
        def func_assert_same_pos(x, y, func=isnan, hasval='nan'):
            """Handling nan/inf.
    
            Combine results of running func on x and y, checking that they are True
            at the same locations.
    
            """
            x_id = func(x)
            y_id = func(y)
            # We include work-arounds here to handle three types of slightly
            # pathological ndarray subclasses:
            # (1) all() on `masked` array scalars can return masked arrays, so we
            #     use != True
            # (2) __eq__ on some ndarray subclasses returns Python booleans
            #     instead of element-wise comparisons, so we cast to bool_() and
            #     use isinstance(..., bool) checks
            # (3) subclasses with bare-bones __array_function__ implementations may
            #     not implement np.all(), so favor using the .all() method
            # We are not committed to supporting such subclasses, but it's nice to
            # support them if possible.
            if bool_(x_id == y_id).all() != True:
                msg = build_err_msg([x, y],
                                    err_msg + '\nx and y %s location mismatch:'
                                    % (hasval), verbose=verbose, header=header,
                                    names=('x', 'y'), precision=precision)
                raise AssertionError(msg)
            # If there is a scalar, then here we know the array has the same
            # flag as it everywhere, so we should return the scalar flag.
            if isinstance(x_id, bool) or x_id.ndim == 0:
                return bool_(x_id)
            elif isinstance(x_id, bool) or y_id.ndim == 0:
                return bool_(y_id)
            else:
                return y_id
    
        try:
            cond = (x.shape == () or y.shape == ()) or x.shape == y.shape
            if not cond:
                msg = build_err_msg([x, y],
                                    err_msg
                                    + '\n(shapes %s, %s mismatch)' % (x.shape,
                                                                      y.shape),
                                    verbose=verbose, header=header,
                                    names=('x', 'y'), precision=precision)
                raise AssertionError(msg)
    
            flagged = bool_(False)
            if isnumber(x) and isnumber(y):
                if equal_nan:
                    flagged = func_assert_same_pos(x, y, func=isnan, hasval='nan')
    
                if equal_inf:
                    flagged |= func_assert_same_pos(x, y,
                                                    func=lambda xy: xy == +inf,
                                                    hasval='+inf')
                    flagged |= func_assert_same_pos(x, y,
                                                    func=lambda xy: xy == -inf,
                                                    hasval='-inf')
    
            elif istime(x) and istime(y):
                # If one is datetime64 and the other timedelta64 there is no point
                if equal_nan and x.dtype.type == y.dtype.type:
                    flagged = func_assert_same_pos(x, y, func=isnat, hasval="NaT")
    
            if flagged.ndim > 0:
                x, y = x[~flagged], y[~flagged]
                # Only do the comparison if actual values are left
                if x.size == 0:
                    return
            elif flagged:
                # no sense doing comparison if everything is flagged.
                return
    
            val = comparison(x, y)
    
            if isinstance(val, bool):
                cond = val
                reduced = array([val])
            else:
                reduced = val.ravel()
                cond = reduced.all()
    
            # The below comparison is a hack to ensure that fully masked
            # results, for which val.ravel().all() returns np.ma.masked,
            # do not trigger a failure (np.ma.masked != True evaluates as
            # np.ma.masked, which is falsy).
            if cond != True:
                mismatch = 100. * (reduced.size - reduced.sum(dtype=intp)) / ox.size
                remarks = ['Mismatch: {:.3g}%'.format(mismatch)]
    
                with errstate(invalid='ignore', divide='ignore'):
                    # ignore errors for non-numeric types
                    with contextlib.suppress(TypeError):
                        error = abs(x - y)
                        max_abs_error = error.max()
                        if error.dtype == 'object':
                            remarks.append('Max absolute difference: '
                                            + str(max_abs_error))
                        else:
                            remarks.append('Max absolute difference: '
                                            + array2string(max_abs_error))
    
                        # note: this definition of relative error matches that one
                        # used by assert_allclose (found in np.isclose)
                        max_rel_error = (error / abs(y)).max()
                        if error.dtype == 'object':
                            remarks.append('Max relative difference: '
                                            + str(max_rel_error))
                        else:
                            remarks.append('Max relative difference: '
                                            + array2string(max_rel_error))
    
                err_msg += '\n' + '\n'.join(remarks)
                msg = build_err_msg([ox, oy], err_msg,
                                    verbose=verbose, header=header,
                                    names=('x', 'y'), precision=precision)
>               raise AssertionError(msg)
E               AssertionError: 
E               Not equal to tolerance rtol=1e-07, atol=0.01
E               
E               Mismatch: 100%
E               Max absolute difference: 0.01660156
E               Max relative difference: 0.03320312
E                x: array(0.483398)
E                y: array(0.5)

/home/rth/.miniconda3/envs/sklearn-blis/lib/python3.7/site-packages/numpy/testing/_private/utils.py:836: AssertionError

During handling of the above exception, another exception occurred:

self = <scipy.linalg.tests.test_basic.TestVectorNorms object at 0x7f518035ce50>

    def test_stable(self):
        # more stable than numpy's norm
        a = array([1e4] + [1]*10000, dtype=float32)
        try:
            # snrm in double precision; we obtain the same as for float64
            # -- large atol needed due to varying blas implementations
            assert_allclose(norm(a) - 1e4, 0.5, atol=1e-2)
        except AssertionError:
            # snrm implemented in single precision, == np.linalg.norm result
            msg = ": Result should equal either 0.0 or 0.5 (depending on " \
                  "implementation of snrm2)."
>           assert_almost_equal(norm(a) - 1e4, 0.0, err_msg=msg)
E           AssertionError: 
E           Arrays are not almost equal to 7 decimals
E           : Result should equal either 0.0 or 0.5 (depending on implementation of snrm2).
E            ACTUAL: 0.4833984375
E            DESIRED: 0.0

/home/rth/.miniconda3/envs/sklearn-blis/lib/python3.7/site-packages/scipy/linalg/tests/test_basic.py:1336: AssertionError
__________________________________________________________ TestEigBanded.test_dgbtrf __________________________________________________________

self = <scipy.linalg.tests.test_decomp.TestEigBanded object at 0x7f5180688b50>

    def test_dgbtrf(self):
        """Compare dgbtrf  LU factorisation with the LU factorisation result
           of linalg.lu."""
        M,N = shape(self.real_mat)
        lu_symm_band, ipiv, info = dgbtrf(self.bandmat_real, self.KL, self.KU)
    
        # extract matrix u from lu_symm_band
        u = diag(lu_symm_band[2*self.KL,:])
        for i in xrange(self.KL + self.KU):
            u += diag(lu_symm_band[2*self.KL-1-i,i+1:N], i+1)
    
        p_lin, l_lin, u_lin = lu(self.real_mat, permute_l=0)
>       assert_array_almost_equal(u, u_lin)
E       AssertionError: 
E       Arrays are not almost equal to 6 decimals
E       
E       Mismatch: 6%
E       Max absolute difference: 10.8
E       Max relative difference: nan
E        x: array([[ 2.      , -1.      ,  1.      , -3.      , -2.      ,  0.      ,
E                0.      ,  0.      ,  0.      ,  0.      ],
E              [ 0.      , -2.5     , -2.5     ,  1.5     ,  1.      ,  0.      ,...
E        y: array([[ 2.      , -1.      ,  1.      , -3.      , -2.      ,  0.      ,
E                0.      ,  0.      ,  0.      ,  0.      ],
E              [ 0.      , -2.5     , -2.5     ,  1.5     ,  1.      ,  0.      ,...

/home/rth/.miniconda3/envs/sklearn-blis/lib/python3.7/site-packages/scipy/linalg/tests/test_decomp.py:619: AssertionError
________________________________________________________ TestQRinsert_d.test_sqr_p_col ________________________________________________________

self = <scipy.linalg.tests.test_decomp_update.TestQRinsert_d object at 0x7f51805ceb50>

    def test_sqr_p_col(self):
        # sqr + cols --> fat always
        a, q, r, u = self.generate('sqr', which='col', p=3)
        for col in range(r.shape[1] + 1):
            q1, r1 = qr_insert(q, r, u, col, 'col', overwrite_qru=False)
            a1 = np.insert(a, col*np.ones(3, np.intp), u, 1)
>           check_qr(q1, r1, a1, self.rtol, self.atol)

/home/rth/.miniconda3/envs/sklearn-blis/lib/python3.7/site-packages/scipy/linalg/tests/test_decomp_update.py:683: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

q = array([[-8.17686039e-02,  8.34187444e-03,  8.45298644e-01,
        -3.58749906e-01, -1.91427524e-01, -5.83632065e-03,
...-2.61799111e-01,
        -1.87655292e-01, -9.05043648e-02, -7.00071030e-01,
         1.02877387e-01,  2.90912431e-01]])
r = array([[-1.74632781, -0.69081356, -0.71036723, -1.414354  , -0.81666228,
        -1.41818703, -1.23224926, -1.37507309....        ,  0.        ,
         0.        ,  0.        ,  0.35380013, -0.00364703,  0.18484456,
         0.42304265]])
a = array([[0.14279479, 0.06374039, 0.89841842, 0.36852295, 0.97637554,
        0.73179659, 0.68487472, 0.39762759, 0.3175...2088, 0.58438573, 0.39822214,
        0.17540698, 0.50686261, 0.84034989, 0.21569725, 0.06281709,
        0.64568342]])
rtol = 1e-13, atol = 2.220446049250313e-15, assert_sqr = True

    def check_qr(q, r, a, rtol, atol, assert_sqr=True):
        assert_unitary(q, rtol, atol, assert_sqr)
        assert_upper_tri(r, rtol, atol)
>       assert_allclose(q.dot(r), a, rtol=rtol, atol=atol)
E       AssertionError: 
E       Not equal to tolerance rtol=1e-13, atol=2.22045e-15
E       
E       Mismatch: 4.55%
E       Max absolute difference: 0.61821572
E       Max relative difference: 1.
E        x: array([[0.142795, 0.06374 , 0.898418, 0.368523, 0.976376, 0.731797,
E               0.684875, 0.397628, 0.317581, 0.773892, 0.      ],
E              [0.671919, 0.134616, 0.002911, 0.205554, 0.572386, 0.937139,...
E        y: array([[0.142795, 0.06374 , 0.898418, 0.368523, 0.976376, 0.731797,
E               0.684875, 0.397628, 0.317581, 0.773892, 0.618216],
E              [0.671919, 0.134616, 0.002911, 0.205554, 0.572386, 0.937139,...

/home/rth/.miniconda3/envs/sklearn-blis/lib/python3.7/site-packages/scipy/linalg/tests/test_decomp_update.py:34: AssertionError
_________________________________________________ TestQRinsert_d.test_non_unit_strides_p_col __________________________________________________

self = <scipy.linalg.tests.test_decomp_update.TestQRinsert_d object at 0x7f517fb859d0>

    def test_non_unit_strides_p_col(self):
>       self.base_non_simple_strides(make_strided, 0, 3, 'col')

/home/rth/.miniconda3/envs/sklearn-blis/lib/python3.7/site-packages/scipy/linalg/tests/test_decomp_update.py:1010: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/home/rth/.miniconda3/envs/sklearn-blis/lib/python3.7/site-packages/scipy/linalg/tests/test_decomp_update.py:970: in base_non_simple_strides
    check_qr(q1, r1, ai, self.rtol, self.atol)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

q = array([[-8.17686039e-02,  8.34187444e-03,  8.45298644e-01,
        -3.58749906e-01, -1.91427524e-01, -5.83632065e-03,
...-2.61799111e-01,
        -1.87655292e-01, -9.05043648e-02, -7.00071030e-01,
         1.02877387e-01,  2.90912431e-01]])
r = array([[-1.74632781, -0.69081356, -0.71036723, -1.414354  , -0.81666228,
        -1.41818703, -1.23224926, -1.37507309....        ,  0.        ,
         0.        ,  0.        ,  0.35380013, -0.00364703,  0.18484456,
         0.42304265]])
a = array([[0.14279479, 0.06374039, 0.89841842, 0.36852295, 0.97637554,
        0.73179659, 0.68487472, 0.39762759, 0.3175...2088, 0.58438573, 0.39822214,
        0.17540698, 0.50686261, 0.84034989, 0.21569725, 0.06281709,
        0.64568342]])
rtol = 1e-13, atol = 2.220446049250313e-15, assert_sqr = True

    def check_qr(q, r, a, rtol, atol, assert_sqr=True):
        assert_unitary(q, rtol, atol, assert_sqr)
        assert_upper_tri(r, rtol, atol)
>       assert_allclose(q.dot(r), a, rtol=rtol, atol=atol)
E       AssertionError: 
E       Not equal to tolerance rtol=1e-13, atol=2.22045e-15
E       
E       Mismatch: 4.55%
E       Max absolute difference: 0.61821572
E       Max relative difference: 1.
E        x: array([[0.142795, 0.06374 , 0.898418, 0.368523, 0.976376, 0.731797,
E               0.684875, 0.397628, 0.317581, 0.773892, 0.      ],
E              [0.671919, 0.134616, 0.002911, 0.205554, 0.572386, 0.937139,...
E        y: array([[0.142795, 0.06374 , 0.898418, 0.368523, 0.976376, 0.731797,
E               0.684875, 0.397628, 0.317581, 0.773892, 0.618216],
E              [0.671919, 0.134616, 0.002911, 0.205554, 0.572386, 0.937139,...

/home/rth/.miniconda3/envs/sklearn-blis/lib/python3.7/site-packages/scipy/linalg/tests/test_decomp_update.py:34: AssertionError
____________________________________________________ TestQRinsert_d.test_neg_strides_p_col ____________________________________________________

self = <scipy.linalg.tests.test_decomp_update.TestQRinsert_d object at 0x7f51805f8310>

    def test_neg_strides_p_col(self):
>       self.base_non_simple_strides(negate_strides, 0, 3, 'col')

/home/rth/.miniconda3/envs/sklearn-blis/lib/python3.7/site-packages/scipy/linalg/tests/test_decomp_update.py:1022: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/home/rth/.miniconda3/envs/sklearn-blis/lib/python3.7/site-packages/scipy/linalg/tests/test_decomp_update.py:970: in base_non_simple_strides
    check_qr(q1, r1, ai, self.rtol, self.atol)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

q = array([[-8.17686039e-02,  8.34187444e-03,  8.45298644e-01,
        -3.58749906e-01, -1.91427524e-01, -5.83632065e-03,
...-2.61799111e-01,
        -1.87655292e-01, -9.05043648e-02, -7.00071030e-01,
         1.02877387e-01,  2.90912431e-01]])
r = array([[-1.74632781, -0.69081356, -0.71036723, -1.414354  , -0.81666228,
        -1.41818703, -1.23224926, -1.37507309....        ,  0.        ,
         0.        ,  0.        ,  0.35380013, -0.00364703,  0.18484456,
         0.42304265]])
a = array([[0.14279479, 0.06374039, 0.89841842, 0.36852295, 0.97637554,
        0.73179659, 0.68487472, 0.39762759, 0.3175...2088, 0.58438573, 0.39822214,
        0.17540698, 0.50686261, 0.84034989, 0.21569725, 0.06281709,
        0.64568342]])
rtol = 1e-13, atol = 2.220446049250313e-15, assert_sqr = True

    def check_qr(q, r, a, rtol, atol, assert_sqr=True):
        assert_unitary(q, rtol, atol, assert_sqr)
        assert_upper_tri(r, rtol, atol)
>       assert_allclose(q.dot(r), a, rtol=rtol, atol=atol)
E       AssertionError: 
E       Not equal to tolerance rtol=1e-13, atol=2.22045e-15
E       
E       Mismatch: 4.55%
E       Max absolute difference: 0.61821572
E       Max relative difference: 1.
E        x: array([[0.142795, 0.06374 , 0.898418, 0.368523, 0.976376, 0.731797,
E               0.684875, 0.397628, 0.317581, 0.773892, 0.      ],
E              [0.671919, 0.134616, 0.002911, 0.205554, 0.572386, 0.937139,...
E        y: array([[0.142795, 0.06374 , 0.898418, 0.368523, 0.976376, 0.731797,
E               0.684875, 0.397628, 0.317581, 0.773892, 0.618216],
E              [0.671919, 0.134616, 0.002911, 0.205554, 0.572386, 0.937139,...

/home/rth/.miniconda3/envs/sklearn-blis/lib/python3.7/site-packages/scipy/linalg/tests/test_decomp_update.py:34: AssertionError
_______________________________________________ TestQRinsert_d.test_non_itemsize_strides_p_col ________________________________________________

self = <scipy.linalg.tests.test_decomp_update.TestQRinsert_d object at 0x7f5180240290>

    def test_non_itemsize_strides_p_col(self):
>       self.base_non_simple_strides(nonitemsize_strides, 0, 3, 'col')

/home/rth/.miniconda3/envs/sklearn-blis/lib/python3.7/site-packages/scipy/linalg/tests/test_decomp_update.py:1034: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/home/rth/.miniconda3/envs/sklearn-blis/lib/python3.7/site-packages/scipy/linalg/tests/test_decomp_update.py:970: in base_non_simple_strides
    check_qr(q1, r1, ai, self.rtol, self.atol)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

q = array([[-8.17686039e-02,  8.34187444e-03,  8.45298644e-01,
        -3.58749906e-01, -1.91427524e-01, -5.83632065e-03,
...-2.61799111e-01,
        -1.87655292e-01, -9.05043648e-02, -7.00071030e-01,
         1.02877387e-01,  2.90912431e-01]])
r = array([[-1.74632781, -0.69081356, -0.71036723, -1.414354  , -0.81666228,
        -1.41818703, -1.23224926, -1.37507309....        ,  0.        ,
         0.        ,  0.        ,  0.35380013, -0.00364703,  0.18484456,
         0.42304265]])
a = array([[0.14279479, 0.06374039, 0.89841842, 0.36852295, 0.97637554,
        0.73179659, 0.68487472, 0.39762759, 0.3175...2088, 0.58438573, 0.39822214,
        0.17540698, 0.50686261, 0.84034989, 0.21569725, 0.06281709,
        0.64568342]])
rtol = 1e-13, atol = 2.220446049250313e-15, assert_sqr = True

    def check_qr(q, r, a, rtol, atol, assert_sqr=True):
        assert_unitary(q, rtol, atol, assert_sqr)
        assert_upper_tri(r, rtol, atol)
>       assert_allclose(q.dot(r), a, rtol=rtol, atol=atol)
E       AssertionError: 
E       Not equal to tolerance rtol=1e-13, atol=2.22045e-15
E       
E       Mismatch: 4.55%
E       Max absolute difference: 0.61821572
E       Max relative difference: 1.
E        x: array([[0.142795, 0.06374 , 0.898418, 0.368523, 0.976376, 0.731797,
E               0.684875, 0.397628, 0.317581, 0.773892, 0.      ],
E              [0.671919, 0.134616, 0.002911, 0.205554, 0.572386, 0.937139,...
E        y: array([[0.142795, 0.06374 , 0.898418, 0.368523, 0.976376, 0.731797,
E               0.684875, 0.397628, 0.317581, 0.773892, 0.618216],
E              [0.671919, 0.134616, 0.002911, 0.205554, 0.572386, 0.937139,...

/home/rth/.miniconda3/envs/sklearn-blis/lib/python3.7/site-packages/scipy/linalg/tests/test_decomp_update.py:34: AssertionError
_______________________________________________ TestQRinsert_d.test_non_native_byte_order_p_col _______________________________________________

self = <scipy.linalg.tests.test_decomp_update.TestQRinsert_d object at 0x7f5180486250>

    def test_non_native_byte_order_p_col(self):
>       self.base_non_simple_strides(make_nonnative, 0, 3, 'col')

/home/rth/.miniconda3/envs/sklearn-blis/lib/python3.7/site-packages/scipy/linalg/tests/test_decomp_update.py:1046: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/home/rth/.miniconda3/envs/sklearn-blis/lib/python3.7/site-packages/scipy/linalg/tests/test_decomp_update.py:970: in base_non_simple_strides
    check_qr(q1, r1, ai, self.rtol, self.atol)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

q = array([[-8.17686039e-02,  8.34187444e-03,  8.45298644e-01,
        -3.58749906e-01, -1.91427524e-01, -5.83632065e-03,
...-2.61799111e-01,
        -1.87655292e-01, -9.05043648e-02, -7.00071030e-01,
         1.02877387e-01,  2.90912431e-01]])
r = array([[-1.74632781, -0.69081356, -0.71036723, -1.414354  , -0.81666228,
        -1.41818703, -1.23224926, -1.37507309....        ,  0.        ,
         0.        ,  0.        ,  0.35380013, -0.00364703,  0.18484456,
         0.42304265]])
a = array([[0.14279479, 0.06374039, 0.89841842, 0.36852295, 0.97637554,
        0.73179659, 0.68487472, 0.39762759, 0.3175...2088, 0.58438573, 0.39822214,
        0.17540698, 0.50686261, 0.84034989, 0.21569725, 0.06281709,
        0.64568342]])
rtol = 1e-13, atol = 2.220446049250313e-15, assert_sqr = True

    def check_qr(q, r, a, rtol, atol, assert_sqr=True):
        assert_unitary(q, rtol, atol, assert_sqr)
        assert_upper_tri(r, rtol, atol)
>       assert_allclose(q.dot(r), a, rtol=rtol, atol=atol)
E       AssertionError: 
E       Not equal to tolerance rtol=1e-13, atol=2.22045e-15
E       
E       Mismatch: 4.55%
E       Max absolute difference: 0.61821572
E       Max relative difference: 1.
E        x: array([[0.142795, 0.06374 , 0.898418, 0.368523, 0.976376, 0.731797,
E               0.684875, 0.397628, 0.317581, 0.773892, 0.      ],
E              [0.671919, 0.134616, 0.002911, 0.205554, 0.572386, 0.937139,...
E        y: array([[0.142795, 0.06374 , 0.898418, 0.368523, 0.976376, 0.731797,
E               0.684875, 0.397628, 0.317581, 0.773892, 0.618216],
E              [0.671919, 0.134616, 0.002911, 0.205554, 0.572386, 0.937139,...

/home/rth/.miniconda3/envs/sklearn-blis/lib/python3.7/site-packages/scipy/linalg/tests/test_decomp_update.py:34: AssertionError
___________________________________________________ TestQRinsert_d.test_overwrite_qu_rank_p ___________________________________________________

self = <scipy.linalg.tests.test_decomp_update.TestQRinsert_d object at 0x7f5180240dd0>

    def test_overwrite_qu_rank_p(self):
        # when inserting rows, the size of both Q and R change, so only
        # column inserts can potentially overwrite Q.  In practice, only
        # F ordered Q are overwritten with a rank p update.
        a, q0, r, u, = self.generate('sqr', which='col', p=3)
        q = q0.copy('F')
        a1 = np.insert(a, np.zeros(3, np.intp), u, 1)
    
        # don't overwrite
        q1, r1 = qr_insert(q, r, u, 0, 'col', overwrite_qru=False)
>       check_qr(q1, r1, a1, self.rtol, self.atol)

/home/rth/.miniconda3/envs/sklearn-blis/lib/python3.7/site-packages/scipy/linalg/tests/test_decomp_update.py:1091: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

q = array([[-8.17686039e-02,  8.34187444e-03,  8.45298644e-01,
        -3.58749906e-01, -1.91427524e-01, -5.83632065e-03,
...-2.61799111e-01,
        -1.87655292e-01, -9.05043648e-02, -7.00071030e-01,
         1.02877387e-01,  2.90912431e-01]])
r = array([[-1.74632781, -0.69081356, -0.71036723, -1.414354  , -0.81666228,
        -1.41818703, -1.23224926, -1.37507309....        ,  0.        ,
         0.        ,  0.        ,  0.35380013, -0.00364703,  0.18484456,
         0.42304265]])
a = array([[0.14279479, 0.06374039, 0.89841842, 0.36852295, 0.97637554,
        0.73179659, 0.68487472, 0.39762759, 0.3175...2088, 0.58438573, 0.39822214,
        0.17540698, 0.50686261, 0.84034989, 0.21569725, 0.06281709,
        0.64568342]])
rtol = 1e-13, atol = 2.220446049250313e-15, assert_sqr = True

    def check_qr(q, r, a, rtol, atol, assert_sqr=True):
        assert_unitary(q, rtol, atol, assert_sqr)
        assert_upper_tri(r, rtol, atol)
>       assert_allclose(q.dot(r), a, rtol=rtol, atol=atol)
E       AssertionError: 
E       Not equal to tolerance rtol=1e-13, atol=2.22045e-15
E       
E       Mismatch: 4.55%
E       Max absolute difference: 0.61821572
E       Max relative difference: 1.
E        x: array([[0.142795, 0.06374 , 0.898418, 0.368523, 0.976376, 0.731797,
E               0.684875, 0.397628, 0.317581, 0.773892, 0.      ],
E              [0.671919, 0.134616, 0.002911, 0.205554, 0.572386, 0.937139,...
E        y: array([[0.142795, 0.06374 , 0.898418, 0.368523, 0.976376, 0.731797,
E               0.684875, 0.397628, 0.317581, 0.773892, 0.618216],
E              [0.671919, 0.134616, 0.002911, 0.205554, 0.572386, 0.937139,...

/home/rth/.miniconda3/envs/sklearn-blis/lib/python3.7/site-packages/scipy/linalg/tests/test_decomp_update.py:34: AssertionError
____________________________________________________________ test_zero_rhs[lgmres] ____________________________________________________________

solver = <function lgmres at 0x7f51889f97a0>

    @pytest.mark.parametrize("solver", [cg, cgs, bicg, bicgstab, gmres, qmr, minres, lgmres, gcrotmk])
    def test_zero_rhs(solver):
        np.random.seed(1234)
        A = np.random.rand(10, 10)
        A = A.dot(A.T) + 10 * np.eye(10)
    
        b = np.zeros(10)
        tols = np.r_[np.logspace(np.log10(1e-10), np.log10(1e2), 7)]
    
        for tol in tols:
            with suppress_warnings() as sup:
                sup.filter(DeprecationWarning, ".*called without specifying.*")
    
                x, info = solver(A, b, tol=tol)
                assert_equal(info, 0)
                assert_allclose(x, 0, atol=1e-15)
    
                x, info = solver(A, b, tol=tol, x0=ones(10))
                assert_equal(info, 0)
                assert_allclose(x, 0, atol=tol)
    
                if solver is not minres:
                    x, info = solver(A, b, tol=tol, atol=0, x0=ones(10))
                    if info == 0:
>                       assert_allclose(x, 0)
E                       AssertionError: 
E                       Not equal to tolerance rtol=1e-07, atol=0
E                       
E                       Mismatch: 100%
E                       Max absolute difference: 1.19386456e-164
E                       Max relative difference: inf
E                        x: array([ 5.155324e-165,  7.054654e-165,  4.341326e-165, -1.193865e-164,
E                              -2.713329e-165, -7.597320e-165, -5.426657e-166, -4.341326e-165,
E                               3.255994e-165, -8.682651e-165])
E                        y: array(0)

/home/rth/.miniconda3/envs/sklearn-blis/lib/python3.7/site-packages/scipy/sparse/linalg/isolve/tests/test_iterative.py:440: AssertionError
_______________________________________________________ TestInt32Overflow.test_matvecs ________________________________________________________

self = <scipy.sparse.tests.test_sparsetools.TestInt32Overflow object at 0x7f518081b810>

    @pytest.mark.slow
    def test_matvecs(self):
        # Check *_matvecs routines
        n = self.n
    
        i = np.array([0, n-1])
        j = np.array([0, n-1])
        data = np.array([1, 2], dtype=np.int8)
        m = coo_matrix((data, (i, j)))
    
        b = np.ones((n, n), dtype=np.int8)
        for sptype in (csr_matrix, csc_matrix, bsr_matrix):
            m2 = sptype(m)
>           r = m2.dot(b)

/home/rth/.miniconda3/envs/sklearn-blis/lib/python3.7/site-packages/scipy/sparse/tests/test_sparsetools.py:143: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/home/rth/.miniconda3/envs/sklearn-blis/lib/python3.7/site-packages/scipy/sparse/base.py:363: in dot
    return self * other
/home/rth/.miniconda3/envs/sklearn-blis/lib/python3.7/site-packages/scipy/sparse/base.py:472: in __mul__
    return self._mul_multivector(other)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <50000x50000 sparse matrix of type '<class 'numpy.int8'>'
        with 2 stored elements in Compressed Sparse Row format>
other = array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]], dtype=int8)

    def _mul_multivector(self, other):
        M, N = self.shape
        n_vecs = other.shape[1]  # number of column vectors
    
        result = np.zeros((M, n_vecs),
>                         dtype=upcast_char(self.dtype.char, other.dtype.char))
E       numpy.core._exceptions.MemoryError: Unable to allocate array with shape (50000, 50000) and data type int8

/home/rth/.miniconda3/envs/sklearn-blis/lib/python3.7/site-packages/scipy/sparse/compressed.py:482: MemoryError
________________________________________________ TestCorrPearsonr.test_very_small_input_values ________________________________________________

self = <scipy.stats.tests.test_stats.TestCorrPearsonr object at 0x7f517c1ff450>

    def test_very_small_input_values(self):
        # Very small values in an input.  A naive implementation will
        # suffer from underflow.
        # See https://github.com/scipy/scipy/issues/9353
        x = [0.004434375, 0.004756007, 0.003911996, 0.0038005, 0.003409971]
        y = [2.48e-188, 7.41e-181, 4.09e-208, 2.08e-223, 2.66e-245]
        r, p = stats.pearsonr(x,y)
    
        # The expected values were computed using mpmath with 80 digits
        # of precision.
>       assert_allclose(r, 0.7272930540750450)

/home/rth/.miniconda3/envs/sklearn-blis/lib/python3.7/site-packages/scipy/stats/tests/test_stats.py:312: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

x = array(nan), y = array(0.72729305), func = <ufunc 'isnan'>, hasval = 'nan'

    def func_assert_same_pos(x, y, func=isnan, hasval='nan'):
        """Handling nan/inf.
    
        Combine results of running func on x and y, checking that they are True
        at the same locations.
    
        """
        x_id = func(x)
        y_id = func(y)
        # We include work-arounds here to handle three types of slightly
        # pathological ndarray subclasses:
        # (1) all() on `masked` array scalars can return masked arrays, so we
        #     use != True
        # (2) __eq__ on some ndarray subclasses returns Python booleans
        #     instead of element-wise comparisons, so we cast to bool_() and
        #     use isinstance(..., bool) checks
        # (3) subclasses with bare-bones __array_function__ implementations may
        #     not implement np.all(), so favor using the .all() method
        # We are not committed to supporting such subclasses, but it's nice to
        # support them if possible.
        if bool_(x_id == y_id).all() != True:
            msg = build_err_msg([x, y],
                                err_msg + '\nx and y %s location mismatch:'
                                % (hasval), verbose=verbose, header=header,
                                names=('x', 'y'), precision=precision)
>           raise AssertionError(msg)
E           AssertionError: 
E           Not equal to tolerance rtol=1e-07, atol=0
E           
E           x and y nan location mismatch:
E            x: array(nan)
E            y: array(0.727293)

/home/rth/.miniconda3/envs/sklearn-blis/lib/python3.7/site-packages/numpy/testing/_private/utils.py:745: AssertionError
_____________________________________________ TestCorrPearsonr.test_extremely_large_input_values ______________________________________________

self = <scipy.stats.tests.test_stats.TestCorrPearsonr object at 0x7f517df41c10>

    def test_extremely_large_input_values(self):
        # Extremely large values in x and y.  These values would cause the
        # product sigma_x * sigma_y to overflow if the two factors were
        # computed independently.
        x = np.array([2.3e200, 4.5e200, 6.7e200, 8e200])
        y = np.array([1.2e199, 5.5e200, 3.3e201, 1.0e200])
        r, p = stats.pearsonr(x, y)
    
        # The expected values were computed using mpmath with 80 digits
        # of precision.
>       assert_allclose(r, 0.351312332103289)

/home/rth/.miniconda3/envs/sklearn-blis/lib/python3.7/site-packages/scipy/stats/tests/test_stats.py:339: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

x = array(nan), y = array(0.35131233), func = <ufunc 'isnan'>, hasval = 'nan'

    def func_assert_same_pos(x, y, func=isnan, hasval='nan'):
        """Handling nan/inf.
    
        Combine results of running func on x and y, checking that they are True
        at the same locations.
    
        """
        x_id = func(x)
        y_id = func(y)
        # We include work-arounds here to handle three types of slightly
        # pathological ndarray subclasses:
        # (1) all() on `masked` array scalars can return masked arrays, so we
        #     use != True
        # (2) __eq__ on some ndarray subclasses returns Python booleans
        #     instead of element-wise comparisons, so we cast to bool_() and
        #     use isinstance(..., bool) checks
        # (3) subclasses with bare-bones __array_function__ implementations may
        #     not implement np.all(), so favor using the .all() method
        # We are not committed to supporting such subclasses, but it's nice to
        # support them if possible.
        if bool_(x_id == y_id).all() != True:
            msg = build_err_msg([x, y],
                                err_msg + '\nx and y %s location mismatch:'
                                % (hasval), verbose=verbose, header=header,
                                names=('x', 'y'), precision=precision)
>           raise AssertionError(msg)
E           AssertionError: 
E           Not equal to tolerance rtol=1e-07, atol=0
E           
E           x and y nan location mismatch:
E            x: array(nan)
E            y: array(0.351312)

/home/rth/.miniconda3/envs/sklearn-blis/lib/python3.7/site-packages/numpy/testing/_private/utils.py:745: AssertionError
============================================================== warnings summary ===============================================================
/home/rth/.miniconda3/envs/sklearn-blis/lib/python3.7/site-packages/_pytest/mark/structures.py:332
/home/rth/.miniconda3/envs/sklearn-blis/lib/python3.7/site-packages/_pytest/mark/structures.py:332
/home/rth/.miniconda3/envs/sklearn-blis/lib/python3.7/site-packages/_pytest/mark/structures.py:332
/home/rth/.miniconda3/envs/sklearn-blis/lib/python3.7/site-packages/_pytest/mark/structures.py:332
/home/rth/.miniconda3/envs/sklearn-blis/lib/python3.7/site-packages/_pytest/mark/structures.py:332
  /home/rth/.miniconda3/envs/sklearn-blis/lib/python3.7/site-packages/_pytest/mark/structures.py:332: PytestUnknownMarkWarning: Unknown pytest.mark.slow - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
    PytestUnknownMarkWarning,

/home/rth/.miniconda3/envs/sklearn-blis/lib/python3.7/site-packages/_pytest/mark/structures.py:332
/home/rth/.miniconda3/envs/sklearn-blis/lib/python3.7/site-packages/_pytest/mark/structures.py:332
/home/rth/.miniconda3/envs/sklearn-blis/lib/python3.7/site-packages/_pytest/mark/structures.py:332
/home/rth/.miniconda3/envs/sklearn-blis/lib/python3.7/site-packages/_pytest/mark/structures.py:332
  /home/rth/.miniconda3/envs/sklearn-blis/lib/python3.7/site-packages/_pytest/mark/structures.py:332: PytestUnknownMarkWarning: Unknown pytest.mark.xslow - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
    PytestUnknownMarkWarning,

stats/tests/test_stats.py::TestCorrPearsonr::test_very_small_input_values
  /home/rth/.miniconda3/envs/sklearn-blis/lib/python3.7/site-packages/scipy/stats/stats.py:3429: PearsonRNearConstantInputWarning: An input array is nearly constant; the computed correlation coefficent may be inaccurate.
    warnings.warn(PearsonRNearConstantInputWarning())

stats/tests/test_stats.py::TestCorrPearsonr::test_very_small_input_values
  /home/rth/.miniconda3/envs/sklearn-blis/lib/python3.7/site-packages/scipy/stats/stats.py:3431: RuntimeWarning: divide by zero encountered in true_divide
    r = np.dot(xm/normxm, ym/normym)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
======================== 13 failed, 15520 passed, 1466 skipped, 102 xfailed, 9 xpassed, 11 warnings in 780.77 seconds =========================
````

</details>

I'm not sure if the issue is with scipy, too strict tests or BLIS (probably needs considering case by case). For numpy 1.17.1 all tests pass (except one unrelated in `numpy.distutils`) in the same environement with BLIS. 

#### Scipy/Numpy/Python version information:

```
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.3.1 1.17.1 sys.version_info(major=3, minor=7, micro=4, releaselevel='final', serial=0)
```
and
```
conda list | grep blis 
# packages in environment at /home/rth/.miniconda3/envs/sklearn-blis:
blas                      2.12                       blis    conda-forge
blis                      0.6.0                h516909a_0    conda-forge
libblas                   3.8.0                   12_blis    conda-forge
libcblas                  3.8.0                   12_blis    conda-forge
```

### LINKED ISSUE #11805: Fatal Python error: Segmentation fault - test_arpack.py::test_symmetric_modes
My issue is about a segmentation fault when trying to run tests. 

#### Reproducing code example:

```
python runtests.py -v -s  sparse
```

#### Error message:

```
scipy/sparse/linalg/eigen/arpack/tests/test_arpack.py::test_symmetric_modes Fatal Python error: Segmentation fault

Current thread 0x00007fe14f9fa740 (most recent call first):
  File "/home/kaleab/Documents/Code/scipy/build/testenv/lib/python3.7/site-packages/scipy/_lib/_util.py", line 121 in _aligned_zeros
  File "/home/kaleab/Documents/Code/scipy/build/testenv/lib/python3.7/site-packages/scipy/sparse/linalg/eigen/arpack/arpack.py", line 518 in __init__
  File "/home/kaleab/Documents/Code/scipy/build/testenv/lib/python3.7/site-packages/scipy/sparse/linalg/eigen/arpack/arpack.py", line 1681 in eigsh
  File "/home/kaleab/Documents/Code/scipy/build/testenv/lib/python3.7/site-packages/scipy/sparse/linalg/eigen/arpack/tests/test_arpack.py", line 244 in eval_evec
  File "/home/kaleab/Documents/Code/scipy/build/testenv/lib/python3.7/site-packages/scipy/sparse/linalg/eigen/arpack/tests/test_arpack.py", line 404 in test_symmetric_modes
  File "/home/kaleab/.conda/envs/scipy/lib/python3.7/site-packages/_pytest/python.py", line 184 in pytest_pyfunc_call
  File "/home/kaleab/.conda/envs/scipy/lib/python3.7/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/kaleab/.conda/envs/scipy/lib/python3.7/site-packages/pluggy/manager.py", line 87 in <lambda>
  File "/home/kaleab/.conda/envs/scipy/lib/python3.7/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/home/kaleab/.conda/envs/scipy/lib/python3.7/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/kaleab/.conda/envs/scipy/lib/python3.7/site-packages/_pytest/python.py", line 1479 in runtest
  File "/home/kaleab/.conda/envs/scipy/lib/python3.7/site-packages/_pytest/runner.py", line 135 in pytest_runtest_call
  File "/home/kaleab/.conda/envs/scipy/lib/python3.7/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/kaleab/.conda/envs/scipy/lib/python3.7/site-packages/pluggy/manager.py", line 87 in <lambda>
  File "/home/kaleab/.conda/envs/scipy/lib/python3.7/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/home/kaleab/.conda/envs/scipy/lib/python3.7/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/kaleab/.conda/envs/scipy/lib/python3.7/site-packages/_pytest/runner.py", line 217 in <lambda>
  File "/home/kaleab/.conda/envs/scipy/lib/python3.7/site-packages/_pytest/runner.py", line 244 in from_call
  File "/home/kaleab/.conda/envs/scipy/lib/python3.7/site-packages/_pytest/runner.py", line 217 in call_runtest_hook
  File "/home/kaleab/.conda/envs/scipy/lib/python3.7/site-packages/_pytest/runner.py", line 186 in call_and_report
  File "/home/kaleab/.conda/envs/scipy/lib/python3.7/site-packages/_pytest/runner.py", line 100 in runtestprotocol
  File "/home/kaleab/.conda/envs/scipy/lib/python3.7/site-packages/_pytest/runner.py", line 85 in pytest_runtest_protocol
  File "/home/kaleab/.conda/envs/scipy/lib/python3.7/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/kaleab/.conda/envs/scipy/lib/python3.7/site-packages/pluggy/manager.py", line 87 in <lambda>
  File "/home/kaleab/.conda/envs/scipy/lib/python3.7/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/home/kaleab/.conda/envs/scipy/lib/python3.7/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/kaleab/.conda/envs/scipy/lib/python3.7/site-packages/_pytest/main.py", line 272 in pytest_runtestloop
  File "/home/kaleab/.conda/envs/scipy/lib/python3.7/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/kaleab/.conda/envs/scipy/lib/python3.7/site-packages/pluggy/manager.py", line 87 in <lambda>
  File "/home/kaleab/.conda/envs/scipy/lib/python3.7/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/home/kaleab/.conda/envs/scipy/lib/python3.7/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/kaleab/.conda/envs/scipy/lib/python3.7/site-packages/_pytest/main.py", line 247 in _main
  File "/home/kaleab/.conda/envs/scipy/lib/python3.7/site-packages/_pytest/main.py", line 191 in wrap_session
  File "/home/kaleab/.conda/envs/scipy/lib/python3.7/site-packages/_pytest/main.py", line 240 in pytest_cmdline_main
  File "/home/kaleab/.conda/envs/scipy/lib/python3.7/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/kaleab/.conda/envs/scipy/lib/python3.7/site-packages/pluggy/manager.py", line 87 in <lambda>
  File "/home/kaleab/.conda/envs/scipy/lib/python3.7/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/home/kaleab/.conda/envs/scipy/lib/python3.7/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/kaleab/.conda/envs/scipy/lib/python3.7/site-packages/_pytest/config/__init__.py", line 125 in main
  File "/home/kaleab/Documents/Code/scipy/build/testenv/lib/python3.7/site-packages/scipy/_lib/_testutils.py", line 67 in __call__
  File "runtests.py", line 313 in main
  File "runtests.py", line 525 in <module>
Segmentation fault (core dumped)
```

#### Scipy/Numpy/Python version information:
```
Python 3.7.7/python 3.6.0, pytest-5.4.1/ pytest 4.0.0 , py-1.8.1, pluggy-0.13.1, numpy 1.18.1 
```

### LINKED ISSUE #13222: porting scipy's Fortran code to NAG's nagfor compiler
After the recently merged numpy's https://github.com/numpy/numpy/pull/17950 `nagfor` still cannot compile all of `scipy`'s Fortran code.

Using numpy's master with the PR just mentioned in, one still gets:
```
$ python3 setup.py build -j 1 config_fc --fcompiler=nagfor install --prefix $HOME/.local
...
nagfor:f77: scipy/integrate/odepack/srcma.f
Option warning: -c option specified twice, continuing
NAG Fortran Compiler Release 7.0(Yurakucho) Build 7036
Evaluation trial version of NAG Fortran Compiler Release 7.0(Yurakucho) Build 7036
Obsolescent: scipy/integrate/odepack/srcma.f, line 1: Fixed source form
Obsolescent: scipy/integrate/odepack/srcma.f, line 27: DO 10 ends neither with CONTINUE nor ENDDO
Obsolescent: scipy/integrate/odepack/srcma.f, line 29: DO 15 ends neither with CONTINUE nor ENDDO
Obsolescent: scipy/integrate/odepack/srcma.f, line 32: DO 20 ends neither with CONTINUE nor ENDDO
Obsolescent: scipy/integrate/odepack/srcma.f, line 34: DO 25 ends neither with CONTINUE nor ENDDO
Error: scipy/integrate/odepack/srcma.f, line 36: First subscript (49) is greater than upper bound (1) for array ISAV
Error: scipy/integrate/odepack/srcma.f, line 37: First subscript (50) is greater than upper bound (1) for array ISAV
Obsolescent: scipy/integrate/odepack/srcma.f, line 42: DO 110 ends neither with CONTINUE nor ENDDO
Obsolescent: scipy/integrate/odepack/srcma.f, line 44: DO 115 ends neither with CONTINUE nor ENDDO
Obsolescent: scipy/integrate/odepack/srcma.f, line 47: DO 120 ends neither with CONTINUE nor ENDDO
Obsolescent: scipy/integrate/odepack/srcma.f, line 49: DO 125 ends neither with CONTINUE nor ENDDO
Error: scipy/integrate/odepack/srcma.f, line 51: First subscript (49) is greater than upper bound (1) for array ISAV
Error: scipy/integrate/odepack/srcma.f, line 52: First subscript (50) is greater than upper bound (1) for array ISAV
[NAG Fortran Compiler error termination, 4 errors, 9 warnings]
```

This one is easy to fix (apparently natfor does not grok `dimension`?):
```diff
diff --git a/scipy/integrate/odepack/srcma.f b/scipy/integrate/odepack/srcma.f
index 62c07a571..aa3ba1e22 100644
--- a/scipy/integrate/odepack/srcma.f
+++ b/scipy/integrate/odepack/srcma.f
@@ -11,12 +11,11 @@ c        job  = 1 if common is to be saved (written to rsav/isav)
 c        job  = 2 if common is to be restored (read from rsav/isav)
 c        a call with job = 2 presumes a prior call with job = 1.
 c-----------------------------------------------------------------------
-      integer isav, job
+      integer isav(*), job
       integer ieh, ils, ilsa
       integer i, lenrls, lenils, lenrla, lenila
-      double precision rsav
+      double precision rsav(*)
       double precision rls, rlsa
-      dimension rsav(1), isav(1)
       common /ls0001/ rls(218), ils(39)
       common /lsa001/ rlsa(22), ilsa(9)
       common /eh0001/ ieh(2)
```
After this fix, the next error, not very clear either:
```
nagfor:f77: scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/cnaitr.f
Option warning: -c option specified twice, continuing
NAG Fortran Compiler Release 7.0(Yurakucho) Build 7036
Evaluation trial version of NAG Fortran Compiler Release 7.0(Yurakucho) Build 7036
Warning: scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/cnaitr.f, line 850: Unused dummy variable NB
Obsolescent: scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/cnaitr.f, line 208: Fixed source form
Error: scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/cnaitr.f, line 666: Inconsistent structure for arg 3 in call to SVOUT
Error: scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/cnaitr.f, line 737: Inconsistent structure for arg 3 in call to SVOUT
[NAG Fortran Compiler error termination, 2 errors, 2 warnings]
error: Command "/usr/local/bin/nagfor -fixed -O4 -Iscipy/sparse/linalg/eigen/arpack/ARPACK/SRC -I/home/dimpase/.local/lib/python3.7/site-packages/numpy-1.21.0.dev0+137.g91d9bbebc-py3.7-linux-x86_64.egg/numpy/core/include -c -c scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/cnaitr.f -o build/temp.linux-x86_64-3.7/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/cnaitr.o" failed with exit status 2
```

Any ideas for this latter?

### LINKED ISSUE #13692: scipy.sparse.linalg.eigsh hangs for complex matrices on macOS
Attempts to diagonalise complex Hermitian sparse matrices leave the system hanging on macOS Big Sur with python 3.9.

#### Reproducing code example:

```
import scipy.sparse.linalg as lin
import scipy.sparse as sp

B = sp.random(1000,1000,density=0.1)
%time lin.eigsh(B+B.T)
# CPU times: user 124 ms, sys: 3.63 ms, total: 128 ms
# Wall time: 155 ms

B = (1+0j)*sp.random(1000,1000,density=0.1) + 1j*sp.random(1000,1000,density=0.1)
%time lin.eigsh(B+B.conj().T)
# Hangs, never gets past this point. Uses 100% of CPU, but never gets anywhere.

```
The above code was tested in IPython, but the same occurs in the python shell.

#### Scipy/Numpy/Python version information:
```
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.5.3 1.20.1 sys.version_info(major=3, minor=9, micro=2, releaselevel='final', serial=0)
```

This issue is specific to python 3.9 on my machine, 3.7 and 3.8 work as expected.

### LINKED ISSUE #13780: reprodcibility of scipy.sparse.linalg.svds
`scipy.sparse.linalg.svds` sometimes gives slightly different results when calling it for the second time. It is not easy to reproduce this behavior for me. I need to use a special input array that I uploaded here: https://sharing.crt-dresden.de/index.php/s/zkgBd6MQj2hd2zq/download 

The data I uploaded is single cell data. So far, I didn't manage to create a random sparse matrix showing the same issue.

I do run the code below in a Jupyter Lab notebook. It is important that I restart the Python kernel and run the code. Then, the reproducibility issue will happen. If I run the code again, without restarting the kernel, successive calls usually give the same result.

I came across the issue when using scanpy, where `svds` is used to do principal components analysis (https://github.com/theislab/scanpy/issues/1749). 

#### Reproducing code example:

```python
import numpy as np
from scipy.sparse import load_npz
from scipy.sparse.linalg import LinearOperator, svds

X = load_npz('X.npz')
np.random.seed(42)
v0 = np.random.rand(2700)

def linear_operator(X):
    mu = X.mean(0).A.flatten()[None, :]
    mdot = mu.dot
    mmat = mdot
    mhdot = mu.T.dot
    mhmat = mu.T.dot
    Xdot = X.dot
    Xmat = Xdot
    XHdot = X.T.conj().dot
    XHmat = XHdot
    ones = np.ones(X.shape[0])[None, :].dot

    def matvec(x):
        return Xdot(x) - mdot(x)

    def matmat(x):
        return Xmat(x) - mmat(x)

    def rmatvec(x):
        return XHdot(x) - mhdot(ones(x))

    XL = LinearOperator(
        matvec=matvec,
        dtype=X.dtype,
        matmat=matmat,
        shape=X.shape,
        rmatvec=rmatvec
    )
    return XL


XL = linear_operator(X)


_, s0, _ = svds(XL, solver='arpack', k=50, v0=v0)
_, s, _ = svds(XL, solver='arpack', k=50, v0=v0)
print(np.array_equal(s0, s))

print(s0)
print(s)
```

#### Output:

I would expect a `True` in the first line and the exact same values for the two arrays. The values are only approximately the same.  

```
False
[ 278.30255  281.411    284.99527  287.63443  291.7871   295.71402
  298.26492  299.56052  303.0501   309.24493  310.1185   312.63315
  315.82254  316.74927  319.27026  319.75082  326.31787  328.99042
  334.83572  336.02936  337.44098  346.24493  353.1684   362.29474
  365.06183  373.71198  376.8522   382.48376  387.80975  409.9564
  416.49933  428.44943  438.2156   456.71884  473.25833  480.61197
  486.87122  493.66934  504.4133   533.55255  581.6367   725.28375
  799.1953   907.3372  1107.4529  1161.2765  1378.3331  1664.9464
 3205.3774  3608.9746 ]
[ 278.30252  281.41095  284.9953   287.63443  291.7871   295.714
  298.26505  299.5605   303.05014  309.245    310.11847  312.63306
  315.82245  316.74924  319.2703   319.75064  326.3178   328.9904
  334.8356   336.02936  337.44092  346.24493  353.1683   362.29456
  365.0619   373.71204  376.85217  382.48367  387.8097   409.9564
  416.49933  428.44934  438.2155   456.71884  473.25833  480.61185
  486.8711   493.66928  504.4132   533.5527   581.63684  725.2845
  799.19574  907.3374  1107.4526  1161.2762  1378.3326  1664.9454
 3205.3777  3608.9749 ]
```

#### Scipy/Numpy/Python version information:

```
1.6.0 1.20.1 sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)
```
I am running the code in this singularity container: https://singularity-hub.org/collections/5095

### LINKED ISSUE #18736: TST: `test_hermitian_modes` test failure
This test in the "Linux Meson tests / Meson build (3.11, false)" workflow has been failing on most recent CI runs. 

The test passes on the Python 3.10 workflow, and nearly always (but not always) fails on the Python 3.11 workflow. The difference between the two is that the 3.11 workflow installs dependencies from git instead of from PyPI. I went ahead and bisected the differences, and found that the test fails if numpy is installed from git but passes if numpy is installed from PyPI:

Screenshot 2023-06-24 at 12 56 55 AM

I ran several test runs of each because sometimes the test passes (even on the git version of numpy).

In other words, the test passes with this:
```
python -m pip install numpy
```
and fails with this:
```
python -m pip install git+https://github.com/numpy/numpy.git
```

Note that this installs the main branch of numpy, which is currently at 2.0.0dev0 with active development.

My contribution to fixing this is identifying this direction. I hope someone more familiar with the arpack code and/or numpy can track it down further.

### LINKED ISSUE #19756: BUG: sparse.linalg.eigsh: output eigenvector non-deterministic for multiple eigenvalues
### Describe your issue.

I utilize scipy.sparse.linalg.eigsh() to calculate eigenvalues and eigenvectors within my algorithm. I hope the outputs of scipy.sparse.linalg.eigsh() are same for the same input matrix. But I found not. Especially for the matrix with multiple eigenvalues, Within a 'For' loop, I got different eigenvectors for the same input matrix. How to solve it? Thx.

For example, I want to calculate the eigenvectors of a identity matrix, 'eigsh()' doesn't have a parameter, such as random_seed, to fix the output eigenvectors to be same.

### Reproducing Code Example

```python
import scipy.sparse.linalg
import numpy as np
from scipy.sparse import csr_matrix
A = csr_matrix(np.identity(3))
for i in range(10):
    eigenvalue, eigenvector = scipy.sparse.linalg.eigsh(A,
                              2,
                              which= 'SM',
                              ncv = 43,
                              v0 = np.ones(A.shape[0]),
                              maxiter = 13615)
    print('第', i, '轮')
    print('特征值：', eigenvalue)
    print('特征向量：', eigenvector)
```

### Error message

```shell
第 0 轮
特征值： [1. 1.]
特征向量： [[-0.55721834  0.59680347]
 [ 0.79545614  0.1841635 ]
 [-0.2382378  -0.78096698]]
第 1 轮
特征值： [1. 1.]
特征向量： [[-0.32737847 -0.74799064]
 [-0.48408967  0.65751339]
 [ 0.81146813  0.09047725]]
第 2 轮
特征值： [1. 1.]
特征向量： [[-0.41217449  0.70482541]
 [-0.40430947 -0.70936628]
 [ 0.81648395  0.00454087]]
第 3 轮
特征值： [1. 1.]
特征向量： [[ 0.14981898 -0.80263375]
 [-0.77001071  0.27156984]
 [ 0.62019173  0.53106392]]
第 4 轮
特征值： [1. 1.]
特征向量： [[ 0.78405184 -0.22788019]
 [-0.58937595 -0.56506872]
 [-0.19467589  0.7929489 ]]
第 5 轮
特征值： [1. 1.]
特征向量： [[-0.39290435  0.71574635]
 [-0.42340235 -0.69813832]
 [ 0.8163067  -0.01760803]]
第 6 轮
特征值： [1. 1.]
特征向量： [[ 0.80576724  0.13193114]
 [-0.51713934  0.63184933]
 [-0.2886279  -0.76378047]]
第 7 轮
特征值： [1. 1.]
特征向量： [[-0.77464117  0.25806534]
 [ 0.16382944 -0.7998916 ]
 [ 0.61081173  0.54182626]]
第 8 轮
特征值： [1. 1.]
特征向量： [[ 0.14187153 -0.57735027]
 [ 0.62541498 -0.57735027]
 [-0.7672865  -0.57735027]]
第 9 轮
特征值： [1. 1.]
特征向量： [[-0.69006985 -0.43642899]
 [ 0.72299352 -0.37940353]
 [-0.03292367  0.81583252]]
```

### SciPy/NumPy/Python version and system information

```shell
1.11.4 1.26.2 sys.version_info(major=3, minor=9, micro=18, releaselevel='final', serial=0)
{
  "Compilers": {
    "c": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.3.0",
      "commands": "cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "0.29.36",
      "commands": "cython"
    },
    "c++": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.3.0",
      "commands": "c++"
    },
    "fortran": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.3.0",
      "commands": "gfortran"
    },
    "pythran": {
      "version": "0.14.0",
      "include directory": "C:\\Users\\runneradmin\\AppData\\Local\\Temp\\pip-build-env-v6zpuvvi\\overlay\\Lib\\site-packages/pythran"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "cross-compiled": true
  },
  "Build Dependencies": {
    "blas": {
      "name": "openblas",
      "found": true,
      "version": "0.3.21.dev",
      "detection method": "pkgconfig",
      "include directory": "/c/opt/64/include",
      "lib directory": "/c/opt/64/lib",
      "openblas configuration": "USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS= NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2",
      "pc file directory": "c:/opt/64/lib/pkgconfig"
    },
    "lapack": {
      "name": "openblas",
      "found": true,
      "version": "0.3.21.dev",
      "detection method": "pkgconfig",
      "include directory": "/c/opt/64/include",
      "lib directory": "/c/opt/64/lib",
      "openblas configuration": "USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS= NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2",
      "pc file directory": "c:/opt/64/lib/pkgconfig"
    },
    "pybind11": {
      "name": "pybind11",
      "version": "2.11.0",
      "detection method": "config-tool",
      "include directory": "unknown"
    }
  },
  "Python Information": {
    "path": "C:\\Users\\runneradmin\\AppData\\Local\\Temp\\cibw-run-msxnhclq\\cp39-win_amd64\\build\\venv\\Scripts\\python.exe",
    "version": "3.9"
  }
}
```

### LINKED ISSUE #20339: BUG: Segfault in complex sparse eigen solver
### Describe your issue.

The sparse eigen solver segfault with version 1.11.4 on github action.
We run a series of automated test and only one specific cases fail and I can't reproduce it locally.
https://github.com/Ericgig/qutip/actions/runs/8444488021/job/23130123226

### Reproducing Code Example

```python
import numpy as np
import scipy
import pytest
import scipy.sparse

@pytest.mark.parametrize("N", [10, 100])
def test_sparse_eigen(N):
    matrix = scipy.sparse.random(N, N, format="csr", dtype=np.complex128, random_state=2)
    out = scipy.sparse.linalg.eigs(matrix, 4)
```

### Error message

```shell
============================= test session starts ==============================
platform linux -- Python 3.11.8, pytest-8.1.1, pluggy-1.4.0
rootdir: /home/runner/work/qutip/qutip/qutip/tests
configfile: pytest.ini
Fatal Python error: Segmentation fault
Current thread 0x00007fc7f5498440 (most recent call first):
  File "/usr/share/miniconda/envs/test/lib/python3.11/site-packages/scipy/sparse/linalg/_eigen/arpack/arpack.py", line 880 in extract
  File "/usr/share/miniconda/envs/test/lib/python3.11/site-packages/scipy/sparse/linalg/_eigen/arpack/arpack.py", line 1354 in eigs
plugins: rerunfailures-14.0, fail-slow-0.5.0, cov-5.0.0
collected 12670 items / 12668 deselected / 2 selected
  File "/home/runner/work/qutip/qutip/qutip/tests/test_scipy.py", line 19 in test_sparse_eigen
  File "/usr/share/miniconda/envs/test/lib/python3.11/site-packages/_pytest/python.py", line 195 in pytest_pyfunc_call
  File "/usr/share/miniconda/envs/test/lib/python3.11/site-packages/pluggy/_callers.py", line 102 in _multicall
  File "/usr/share/miniconda/envs/test/lib/python3.11/site-packages/pluggy/_manager.py", line 119 in _hookexec
  File "/usr/share/miniconda/envs/test/lib/python3.11/site-packages/pluggy/_hooks.py", line 501 in __call__
  File "/usr/share/miniconda/envs/test/lib/python3.11/site-packages/_pytest/python.py", line 1772 in runtest
  File "/usr/share/miniconda/envs/test/lib/python3.11/site-packages/_pytest/runner.py", line 172 in pytest_runtest_call
  File "/usr/share/miniconda/envs/test/lib/python3.11/site-packages/pluggy/_callers.py", line 102 in _multicall
  File "/usr/share/miniconda/envs/test/lib/python3.11/site-packages/pluggy/_manager.py", line 119 in _hookexec
  File "/usr/share/miniconda/envs/test/lib/python3.11/site-packages/pluggy/_hooks.py", line 501 in __call__
  File "/usr/share/miniconda/envs/test/lib/python3.11/site-packages/_pytest/runner.py", line 240 in <lambda>
  File "/usr/share/miniconda/envs/test/lib/python3.11/site-packages/_pytest/runner.py", line 340 in from_call
  File "/usr/share/miniconda/envs/test/lib/python3.11/site-packages/_pytest/runner.py", line 239 in call_and_report
  File "/usr/share/miniconda/envs/test/lib/python3.11/site-packages/_pytest/runner.py", line 134 in runtestprotocol
  File "/usr/share/miniconda/envs/test/lib/python3.11/site-packages/_pytest/runner.py", line 115 in pytest_runtest_protocol
  File "/usr/share/miniconda/envs/test/lib/python3.11/site-packages/pluggy/_callers.py", line 102 in _multicall
  File "/usr/share/miniconda/envs/test/lib/python3.11/site-packages/pluggy/_manager.py", line 119 in _hookexec
  File "/usr/share/miniconda/envs/test/lib/python3.11/site-packages/pluggy/_hooks.py", line 501 in __call__
  File "/usr/share/miniconda/envs/test/lib/python3.11/site-packages/_pytest/main.py", line 364 in pytest_runtestloop
  File "/usr/share/miniconda/envs/test/lib/python3.11/site-packages/pluggy/_callers.py", line 102 in _multicall
  File "/usr/share/miniconda/envs/test/lib/python3.11/site-packages/pluggy/_manager.py", line 119 in _hookexec
  File "/usr/share/miniconda/envs/test/lib/python3.11/site-packages/pluggy/_hooks.py", line 501 in __call__
  File "/usr/share/miniconda/envs/test/lib/python3.11/site-packages/_pytest/main.py", line 339 in _main
  File "/usr/share/miniconda/envs/test/lib/python3.11/site-packages/_pytest/main.py", line 285 in wrap_session
  File "/usr/share/miniconda/envs/test/lib/python3.11/site-packages/_pytest/main.py", line 332 in pytest_cmdline_main
  File "/usr/share/miniconda/envs/test/lib/python3.11/site-packages/pluggy/_callers.py", line 102 in _multicall
  File "/usr/share/miniconda/envs/test/lib/python3.11/site-packages/pluggy/_manager.py", line 119 in _hookexec
  File "/usr/share/miniconda/envs/test/lib/python3.11/site-packages/pluggy/_hooks.py", line 501 in __call__
  File "/usr/share/miniconda/envs/test/lib/python3.11/site-packages/_pytest/config/__init__.py", line 174 in main
  File "/usr/share/miniconda/envs/test/lib/python3.11/site-packages/_pytest/config/__init__.py", line 197 in console_main
  File "/usr/share/miniconda/envs/test/bin/pytest", line 8 in <module>
Extension modules: mkl._mklinit, mkl._py_mkl_service, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, matplotlib._c_internal_utils, PIL._imaging, matplotlib._path, kiwisolver._cext, scipy._lib._ccallback_c, scipy.special._ufuncs_cxx, scipy.special._ufuncs, scipy.special._specfun, scipy.special._comb, scipy.linalg._fblas, scipy.linalg._flapack, scipy.linalg.cython_lapack, scipy.linalg._cythonized_array_utils, scipy.linalg._solve_toeplitz, scipy.linalg._decomp_lu_cython, scipy.linalg._matfuncs_sqrtm_triu, scipy.linalg.cython_blas, scipy.linalg._matfuncs_expm, scipy.linalg._decomp_update, scipy.sparse._sparsetools, _csparsetools, scipy.sparse._csparsetools, scipy.sparse.linalg._isolve._iterative, scipy.sparse.linalg._dsolve._superl
/home/runner/work/_temp/af43e5c4-0488-4a42-a013-6138da4e8588.sh: line 13:  2263 Segmentation fault      (core dumped) pytest qutip/tests -k test_scipy
```

### SciPy/NumPy/Python version and system information

```shell
Numpy Version: 1.26.4, Build: py311h08b1b3b_0
Scipy Version: 1.11.4, Build: pypi_0
Python Version: 3.11.8, Build: h955ad1f_0

When using conda build (py311h08b1b3b_0) instead, it worked fine.

1.11.4 1.26.4 sys.version_info(major=3, minor=11, micro=8, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.21.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.21.dev
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.11.0
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 0.29.36
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  pythran:
    include directory: ../../tmp/pip-build-env-lzd6dam0/overlay/lib/python3.11/site-packages/pythran
    version: 0.14.0
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  cross-compiled: true
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /opt/python/cp311-cp311/bin/python
  version: '3.11'
```

### LINKED ISSUE #21137: BUG: ARPACK error -9: Starting vector is zero when calling scipy.sparse.linalg.svds on zeros
### Describe your issue.

The scikit-learn nightly build CI has found a recent regression:

- https://github.com/scikit-learn/scikit-learn/pull/29428

The reproducer below fails on recent nightly builds of scipy while it use to output the following the last stable release of scipy:

```
scipy version: 1.14.0
[[1.]
 [0.]]
[0.]
[[-0.47655702 -0.87914356]]
```

### Reproducing Code Example

```python
import numpy as np
import scipy
import scipy.sparse as sp

print(f"scipy version: {scipy.__version__}")

for out in sp.linalg.svds(np.zeros((2, 2)), k=1):
    print(out)
```

### Error message

```shell
scipy version: 
Traceback (most recent call last):
  File "/Users/ogrisel/tmp/repro_arpack.py", line 7, in <module>
    for out in sp.linalg.svds(np.zeros((2, 2)), k=1):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ogrisel/miniforge3/envs/scipy-dev/lib/python3.12/site-packages/scipy/sparse/linalg/_eigen/_svds.py", line 515, in svds
    _, eigvec = eigsh(XH_X, k=k, tol=tol ** 2, maxiter=maxiter,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ogrisel/miniforge3/envs/scipy-dev/lib/python3.12/site-packages/scipy/sparse/linalg/_eigen/arpack/arpack.py", line 1701, in eigsh
    params.iterate()
  File "/Users/ogrisel/miniforge3/envs/scipy-dev/lib/python3.12/site-packages/scipy/sparse/linalg/_eigen/arpack/arpack.py", line 574, in iterate
    raise ArpackError(self.info, infodict=self.iterate_infodict)
scipy.sparse.linalg._eigen.arpack.arpack.ArpackError: ARPACK error -9: Starting vector is zero.
```

### SciPy/NumPy/Python version and system information

```shell
1.15.0.dev0+1098.a2c613f 2.1.0.dev0+git20240706.f76def3 sys.version_info(major=3, minor=12, micro=3, releaselevel='final', serial=0)
/Users/ogrisel/miniforge3/envs/scipy-dev/lib/python3.12/site-packages/scipy/__config__.py:154: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)
{
  "Compilers": {
    "c": {
      "name": "clang",
      "linker": "ld64",
      "version": "15.0.0",
      "commands": "cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.10",
      "commands": "cython"
    },
    "c++": {
      "name": "clang",
      "linker": "ld64",
      "version": "15.0.0",
      "commands": "c++"
    },
    "fortran": {
      "name": "gcc",
      "linker": "ld64",
      "version": "13.3.0",
      "commands": "gfortran"
    },
    "pythran": {
      "version": "0.16.1",
      "include directory": "../../../../../../private/var/folders/h9/l1shxhdd69nct08ylzq0n6q00000gn/T/pip-build-env-olf25eqk/overlay/lib/python3.12/site-packages/pythran"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "aarch64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    },
    "build": {
      "cpu": "aarch64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    },
    "cross-compiled": false
  },
  "Build Dependencies": {
    "blas": {
      "name": "accelerate",
      "found": true,
      "version": "unknown",
      "detection method": "extraframeworks",
      "include directory": "unknown",
      "lib directory": "unknown",
      "openblas configuration": "unknown",
      "pc file directory": "unknown"
    },
    "lapack": {
      "name": "accelerate",
      "found": true,
      "version": "unknown",
      "detection method": "extraframeworks",
      "include directory": "unknown",
      "lib directory": "unknown",
      "openblas configuration": "unknown",
      "pc file directory": "unknown"
    },
    "pybind11": {
      "name": "pybind11",
      "version": "2.13.1",
      "detection method": "config-tool",
      "include directory": "unknown"
    }
  },
  "Python Information": {
    "path": "/private/var/folders/h9/l1shxhdd69nct08ylzq0n6q00000gn/T/cibw-run-tcdwbs37/cp312-macosx_arm64/build/venv/bin/python",
    "version": "3.12"
  }
}
```

### LINKED ISSUE #22310: BUG: <Please write a comprehensive title after the 'BUG: ' prefix>
### Describe your issue.

Dear all,

I would like to report that ``scipy.sparse.linalg.eigsh`` returns an error when the argument is a ``LinearOperator`` with a ``dtype`` equals to ``None``.
I also tried ``scipy.sparse.linalg.svds`` that works fine.
Do I miss something that explains the different behavior between ``eigsh`` and ``svds`` ?

Thank you for your help.
Pascal

### Reproducing Code Example

```python
>>> from scipy.sparse.linalg import eigsh, LinearOperator, aslinearoperator, svds
>>> import numpy as np
>>> A = np.random.randn(10, 10)
>>> L = aslinearoperator(A)
>>> L.dtype = None
>>> eigsh(L)
>>> svds(L)
```

### Error message

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pcarriva/venvs/test/lib/python3.11/site-packages/scipy/sparse/linalg/_eigen/arpack/arpack.py", line 1694, in eigsh
    params = _SymmetricArpackParams(n, k, A.dtype.char, matvec, mode,
                                          ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'char'
```

### SciPy/NumPy/Python version and system information

```shell
1.14.1 2.0.2 sys.version_info(major=3, minor=11, micro=2, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.9/lib/python3.11/site-packages/scipy_openblas32/include
    lib directory: /opt/_internal/cpython-3.11.9/lib/python3.11/site-packages/scipy_openblas32/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27.dev DYNAMIC_ARCH NO_AFFINITY Zen MAX_THREADS=64
    pc file directory: /project
    version: 0.3.27.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.9/lib/python3.11/site-packages/scipy_openblas32/include
    lib directory: /opt/_internal/cpython-3.11.9/lib/python3.11/site-packages/scipy_openblas32/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27.dev DYNAMIC_ARCH NO_AFFINITY Zen MAX_THREADS=64
    pc file directory: /project
    version: 0.3.27.dev
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.12.0
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.11
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  pythran:
    include directory: ../../tmp/pip-build-env-k6xvzqr5/overlay/lib/python3.11/site-packages/pythran
    version: 0.16.1
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /opt/python/cp311-cp311/bin/python
  version: '3.11'
```

### PR DESCRIPTION
**Pull request by ilayn**
#### Reference issue
Towards #18566

#### What does this implement/fix?
ARPACK in C as a static (or shared lib with BLAS/LAPACK dependency, it's complicated...) library.

#### Additional information

 - I included a hand-written version of the notorious `(cz)dotc` BLAS functions so hopefully we will never hear from them.
 - Now ARPACK is thread-safe and reentrant since all SAVE'd variables are taken out to the reverse communication layer with a struct. Hence closed but still needs testing against #5846 EDIT: **Checked and verified**
 - Some of the functions are very confusing and perform Dijkstra-raging goto tricks such as `?NAPPS.f` so I partially rewrote them instead of translating, because each time another week was being spent in debugging if something was not right.
 - Now the pseudo-random generation happens outside ARPACK hence `rng` keyword is added. To be able to use it, new job codes `ido = 4` and `ido = 5` are introduced and `ido = -1` is removed.
 - Since now ARPACK is thread-safe/reentrant, those tests that are testing for "no crash" behavior are removed/let passed.
 - LAPACK `dlamch('E')` by default resolves to `0.5*eps`, in this PR `eps` is used for tolerance tests.

#### All open issues regarding ARPACK

 - [ ] #3716 
 - [ ] #6827 
 - [ ] #9284 
 - [ ] #11232 
 - [ ] #11261  ILP64
 - [ ] #13033 Add the picture
 - [ ] #17632 LinearOperator support
 - [ ] #19235 Performance
 - [ ] #20808 More hanging tests

Closes #9023 
Closes #9185
Closes #9460
Closes #10744
Closes #11805 
Closes #13222 
Closes #13692 
Closes #13780 
Closes #14823 
Closes #18191 
Closes #18736
Closes #19756 
Closes #20339
Closes #21137 
Closes #22310

### CODE REVIEW

**Comment by ilayn** [comment]
Took a while but now ready for review. Nonsymmetric tests locally pass. Symmetric solver has a minor issue that I will follow-up when I have a bit more time.

**Comment by dschmitz89** [comment]
This is the largest diff I've ever seen. Any suggestions how to review? ;)

From top of my head: are there tests for the new numpy rng seeding mechanism?

**Comment by ilayn** [comment]
I have them, currently the symmetric part is broken so I didn't send those parts. There is really no diff on the low-level code as it is old out, new in. I will have some time in the weekend to fix and we can start pounding with test problems, small or large.

**Comment by szhorvat** [comment]
I'll attempt to test this with igraph the week after next, which should help with gaining confidence in correctness.

It'd be nice to go towards refactoring this into a standalone library so it can be used by, and contributed to, by multiple projects.

**Comment by ilayn** [comment]
> I'll attempt to test this with igraph the week after next, which should help with gaining confidence in correctness.

It would be much appreciated. The more tests, the merrier, in the meantime I'll figure out the remaining details, I found a bug in `dstqrb` and will try to fix it in the evening. 

>  It'd be nice to go towards refactoring this into a standalone library so it can be used by, and contributed to, by multiple projects.

If all goes OK, we can yank it out to make it a submodule for SciPy.

File: scipy/sparse/linalg/_eigen/arpack/ARPACK/_arpack_n_double.c [hunk 1]
```diff
@@ -0,0 +1,2116 @@
...
+static int sortc_LM(const double, const double, const double, const double);
+static int sortc_SM(const double, const double, const double, const double);
+static int sortc_LR(const double, const double, const double, const double);
+static int sortc_SR(const double, const double, const double, const double);
+static int sortc_LI(const double, const double, const double, const double);
+static int sortc_SI(const double, const double, const double, const double);
+
+static const double unfl = 2.2250738585072014e-308;
+// static const double ovfl = 1.0 / 2.2250738585072014e-308;
+static const double ulp = 2.220446049250313e-16;
```
Comment (szhorvat) [inline scipy/sparse/linalg/_eigen/arpack/ARPACK/_arpack_n_double.c:14]: Is there any reason you are not using `DBL_MIN` and `DBL_EPSILON` instead of these?

**Comment by szhorvat** [comment]
Are you planning to keep this API-compatible with ARPACK? It does not seem to be compatible at the moment.

In igraph, we provide an option to either link to an external ARPACK, or use the vendored one (to make compilation simple, including on Windows). My question is whether we can continue to do the same if using this C translation.

BLAS and LAPACK have at this point become de-facto _interfaces_ instead of libraries. There are multiple implementations in multiple programming languages, all conforming to the same interface. In principle, the same could happen with ARPACK.

Better yet, a long-term goal could be to rewrite ARPACK-NG in C and maintain the C implementation going forward. Have you spoken with the ARPACK-NG maintainers? My impression was that the lack of Fortran expertise has been an issue for them as well, so they might actually prefer doing this.  But it would only work if API-compatibility is maintained.

**Comment by ilayn** [comment]
> Are you planning to keep this API-compatible with ARPACK? It does not seem to be compatible at the moment.

Yes, the API has changed, or broken, depending on how you look at it. there are many issues that can't be solved without changing the API and nobody wants to call functions with 23 arguments. There is no way to control the determinism with its quirky random number generator, somehow mysteriously segfaults which nobody can figure out why, F77 building requires bunch of nasty tricks and warning silencing and so on. Hence this is a hail-mary attempt to get rid of this maintenance burden. 

That's why I decided to reach out to you folks and others, in case folks also want to move on. But I can understand this is not everyone's favorite move. 

> In principle, the same could happen with ARPACK.

I don't believe that ARPACK or even LAPACK should have been in this state for the last decades (much longer diatribe here https://github.com/scientific-python/faster-scientific-python-ideas/issues/7). After 30 years, it is very difficult to change things indeed but every time this argument is invoked, we are poisoning the future to save the past. The very existence of ARPACK-NG is a proof of that. There have been a lot of attempts or independent libraries; a handful new ?PACKs, Spectra, Feast, many Julia libraries and so on. All of them somehow start from scratch but do not reach to the feature complete state of ARPACK for some reason. I am aware that I am in the minority in this line of thinking, but I don't think there is any other way. 

My goal here is to provide the functionality to SciPy without the F77 luggage, close as many open issues as possible, but not really maintain ARPACK further. There are about 800+ open issues mentioning ARPACK on Github. I don't have any appetite to be the attention center of that much trouble. 

> Have you spoken with the ARPACK-NG maintainers? My impression was that the lack of Fortran expertise has been an issue for them as well, so they might actually prefer doing this. But it would only work if API-compatibility is maintained.

No I have not. But in the past, we have also similar interactions with them and they also made it very clear that they don't want to touch the code but make sure that systems keep building and packaging it. I can't blame them. Even though I know exactly what ARPACK is doing (at research level), I still get tripped up in the go to mess and spend days staring at it. 

I think you are exactly on point that we probably should not call this ARPACK, but rename it and move on.

File: scipy/sparse/linalg/_eigen/arpack/ARPACK/_arpack_n_double.c (hunk 1 above)
Comment (ilayn) [reply scipy/sparse/linalg/_eigen/arpack/ARPACK/_arpack_n_double.c:14]: No, not really but let me change it anyways.

**Comment by szhorvat** [comment]
Are you aware of Spectra? https://github.com/yixuan/spectra/ 

It claims to implement the same or similar algorithms to ARPACK, it's written in modern C++, and it is maintained.

The reason why we don't use it in igraph is the hard dependency on eigen. I'm not sure if this is an issue for SciPy.

**Comment by ilayn** [comment]
Unfortunately it is a blocker. But I checked Sandia Labs' Anasazi/Trilinos (Lehoucq is also an author) but it went over my head very quickly. I don't think it is separable easily.

**Comment by yixuan** [comment]
Hi, this is the author of [Spectra](https://github.com/yixuan/spectra).

I came from https://github.com/igraph/igraph/issues/551 and just realized that there are several scientific computing projects considering the re-implementation of ARPACK, so I try to share some of my experience regarding this issue.

One of the motivations of starting the Spectra project is exactly what @ilayn and @szhorvat encounter today: ARPACK was written in FORTRAN 77 code, which causes various compiling warnings/errors on modern building systems. Moreover, the API of ARPACK is very "classic", and using ARPACK is not as simple as calling a function -- it requires you to organize your whole program according to the structure of the algorithm: you are responsible of initializing the problem, implementing the linear operators, and responding to the return values of the ARPACK functions, etc. All of these designs are okay in the time when ARPACK was created, but it is hardly a pleasant experience to include ARPACK into your own project nowadays.

So Spectra is a complete rewriting of ARPACK, or more precisely, a re-implementation of the algorithm that ARPACK is based on. The current status is that all solvers in ARPACK have been realized except for the non-Hermitian complex eigen solvers. Yes, it depends on the Eigen library, which seems to be the main reason that igraph and SciPy cannot directly use it. Let me just explain it a little bit. Eigen is useful to me since it is convenient to manage matrix objects, and it is header-only, meaning that I even do not need to depend on BLAS and LAPACK libraries. But the essential part of Spectra is somewhat independent of Eigen: the internal implementation still heavily uses pointers, and I can replace matrix-related functions by BLAS/LAPACK calls.

If there is indeed a demand, I would be interested in creating a BLAS/LAPACK version of Spectra, but I want to understand whether this is what you want. Could you kindly comment on the following questions if interested?

1. Do you allow C++ code, and if yes, in what standard?
2. Do you need a completely API-compatible alternative to ARPACK? If this is the case, then probably the only choice is to do a language-level F2C translation.
3. For matrix operations, do you prefer calling BLAS/LAPACK as much as possible, or prefer minimizing external libraries as much as possible?
4. Do you need the computation result to be exactly equal to the ARPACK version? In my own experience, this is the hardest part, since different implementations may have different rounding and convergence properties. ARPACK is based on an iterative algorithm, so various errors may be accumulated during the iterations. ARPACK also has some cryptic tricks in the code that are hard to interpret.
5. Apart from the Eigen dependence, how do you feel about Spectra's API? Does it fit your potential need?

I am trying to collect this information to see whether it is of value to make a version of Spectra that is independent of Eigen. In fact, I have done this once before, when I used Spectra-derived code (e.g., the `newarp_*` files in [here](https://gitlab.com/conradsnicta/armadillo-code/-/tree/14.4.x/include/armadillo_bits)) to implement the `eigs_sym()` and `eigs_gen()` functions in [Armadillo](https://gitlab.com/conradsnicta/armadillo-code).

**Comment by ilayn** [comment]
Hi @yixuan first of all, on behalf of all community, a true congratulations from me for attacking this problem in such a comprehensive fashion. A very commendable work indeed. 

First, I should clarify why I have done this work; it is to clean up the F77 from SciPy so that we resolve a lot of decades long issues all in one go. Hence it is slightly different picture when it comes to our motivation. It is getting significantly difficult to maintain this codebase while the rest of the ecosystem is moving to better ergonomics and tooling. Hence it is one of many items we have tackled all listed in #18566. This does not take away any great value ARPACK provided thanklessly over the decades and still do. However the way it provides the value has been a continuous source of pain. Hence this work. 

Regarding your questions, let me first get them all at once and I can comment at the end;

 1. Yes we do allow, and in fact we have Highs and unuran libraries already. Our standard is C++17.  
 2. No I already broke the API by collecting all `SAVE`d variables into a struct and pass it back and forth for reverse communication layer. You can see the definition in the `_arpack.h` file. This allows us to use ARPACK in thread-safe envs or in re-entrant use cases. I am not sure if I understand if you tackled this or not since I don't know the new names of the variables. 
 3. Yes, we only use BLAS/LAPACK interface. The backend whether OpenBLAS/MKL/Blis etc. can be swapped. We don't want to have homebaked versions of the linalg routines as they typically rot in a decade as LAPACK moves on.
 4. Bitwise equivalence is not sought after. I think that is an unreasonable requirement, but if results matches to a reasonable degree we consider it acceptable. Precise definition of reasonable is unfortunately on a case-by-case bases. 
 5. I think the API looks good and clean. Nice work there. For us we don't mind too much about the potential API as it is going to be buried behind the Python layer.

A quick comment on the API compatible ARPACK. Though it sounds like much, the work here is an independent rewrite of ARPACK, mostly mechanical line-by-line translation (as f2c would do) but rewritten partially where the codebase does some unhinged stuff predominantly `??apps.f` and the `?stqrb.f`. So it is pretty much a painstaking translation (SPAG or LLMs did not help one bit unfortunately against this codebase). Whether an API compatible ARPACK is needed I can't judge however I think we should stop using the F77 code regardless of its convenience. 

So because the save variables are now in a struct, you'll see a lot of `V->xxx` in the code which is the struct that the caller sends in to preserve the state. If needed those can be re-expanded by regex + copy pasta and you can regain the API compatibility. Note that you only need to do this for the exposed functions hence 8 function in total. That's quite doable. Hence if you need compatible ARPACK it can be done but then you need to add static keywords to preserve the statefulness to all relevant variables. It's not complicated or tedious but it's work.

I didn't because I am trying to solve the thread-safety problem and not try to offer a drop-in replacement for ARPACK hence the breakage. But today I'll fix the last bugs in the symmetric solver and then we have an all green tested and feature complete working ARPACK.

I am still trying to guess if a rename is going to be better or complicate the matters.

**Comment by ev-br** [comment]
A partial and opinionated wishlist:

> Do you allow C++ code, and if yes, in what standard?

SciPy allows C++17, cf https://scipy.github.io/devdocs/dev/toolchain.html

> Do you need a completely API-compatible alternative to ARPACK? If this is the case, then probably the only choice is to do a language-level F2C translation.

No. We would welcome an API which takes the best of ARPACK and leaves the rest of ARPACK :-).

> For matrix operations, do you prefer calling BLAS/LAPACK as much as possible, or prefer minimizing external libraries as much as possible?

We're talking about a single dependency on a BLAS/LAPACK provider, I think. A tricky part, for SciPy at least,  is that we allow several of those: OpenBLAS, MKL, BLIS, Accelerate, ATLAS etc. While the API is fixed, ABI and build details differ quite a bit between them. 

In an ideal world, dense linear algebra is tucked into a mix-and-match layer, so that one user library can build with Eigen and no LAPACK, SciPy can use its LAPACK-selection logic, scipy redistributors (distros, for example), use their logic, and so on. We will also want to be able to switch between 32-bit integer and 64-bit integer variants (LP64 vs ILP64) at build time.

I fully realize this asks for a substantial bump in complexity from a header-only library! 

> Do you need the computation result to be exactly equal to the ARPACK version? ... ARPACK also has some cryptic tricks in the code that are hard to interpret.
 
Exact equivalence is probably not achievable and certainly not sought after.
The _cryptic tricks_ would be great to enumerate/document somewhere. Some of these are likely artifacts from the era; some might amount to a chapter of somebody's PhD thesis some time ago, and could be still useful to take along. Having some pointers would be of immense help---even if investigating these cryptic tricks will amount to a PhD thesis chapter tomorrow or the day after.

**Comment by ev-br** [comment]
> I am still trying to guess if a rename is going to be better or complicate the matters.

The former, I'd say. It's not exactly compatible, so a rename would be helpful. Together with a README or something, listing basically your comment Ilhan, https://github.com/scipy/scipy/pull/22748#issuecomment-2953897553

**Comment by szhorvat** [comment]
Hi @yixuan, thanks for joining the discussion. If you were to create a BLAS/LAPACK version of Spectra, it would be my preferred choice for igraph from a technical perspective (details to be discussed with the igraph team). I remember asking you about this in the past, though I can't find our conversation anymore. Let me answer the questions, and also ping @ntamas in case he might want to comment on my answers.

1. Yes, we allow C++. The current standard is C++14, but personally I'd be happy to bump this to C++17 if necessary (to be discussed with the igraph team).
2. No, we do not need API-compatibility with ARPACK. I would prefer to rely on a library that is maintained in the long term, and its author understands the implemented algorithms. This is true for Spectra. As I understand, it is not quite true for the ARPACK translation in this PR, as @ilayn was looking to create a simple code translation, but was not planning to tweak the algorithms to correct issues that might appear in the future. (Please correct me if I miunderstood, @ilayn.) The reason why I asked about API compatibility is not to get stuck on a translation of a specific ARPACK version, and be cut off from future ARPACK improvements, especially given how often igraph tends to trigger convergence issues in ARPACK ... This concern does not apply to an independently maintained library like Spectra.
3. I might be misunderstanding this question here, so please see the response to point 5 as well. igraph already has a hard dependency on BLAS/LAPACK and we'd prefer to avoid additional external dependencies.
4. No, we do not require the result to be identical to ARPACK's. In fact, this requirement doesn't even make much sense: ARPACK results depend on what BLAS/LAPACK implementation is used (e.g. OpenBLAS vs Apple Accelerate vs reference BLAS), what floating point system is used by the CPU (e.g. x87 vs SSE), the ARPACK version, as well as ARPACK's internal random state. For these reasons, ARPACK has proven to be very finicky to work with in the past. We are looking for basic reliability, not ARPACK compatibility. We understand that any similar library is likely to suffer from these issues to some extent.
5. We need something akin the ARPACK's "reverse communication interface", i.e. the library should not require being able to access the matrix who eigenvalues are being computed. It should only pass a vector to igraph, and ask igraph to multiply it by the matrix. Spectra already provides this.

Here's a summary of the basic requirements from igraph's part:

 - We need solvers both for symmetric and non-symmetric problems, but we are only interested in real-valued results.
 - Currently igraph makes use of various orderings of eigenvalues (e.g. largest by magnitude, largest by real part, smallest, etc.). I'd have to review the code to determine which are essential. Does Spectra provide these?
 - We try to keep igraph buildable (possibly with reduced functionality) without any external dependencies, as much of our userbase are academics, not software developers. For this reason, hard dependencies are all vendored (while maintaining the option to link to external versions).  This is one of the reasons why eigen would be a problematic dependency.
 - We need a compatible license. Currently, igraph is licensed under GPLv2. I'm pushing to move towards more permissive licensing (LGPL or BSD/MIT) but this is difficult due to copyright fragmentation and existing dependencies.

Moving to Spectra would require some API-breaking changes on igraph's part. We are planning a major release (1.0 finally, after 20 years!) at the end of the summer, which would be a good opportunity to make these changes. Otherwise, there's always a 2.0 later.

To give you an idea, all eigenvalue computations go through these two (symmetric / non-symmetric) functions:

https://igraph.org/c/html/latest/igraph-Arpack.html#igraph_arpack_rnsolve
https://igraph.org/c/html/latest/igraph-Arpack.html#igraph_arpack_rssolve

**Comment by ilayn** [comment]
> I would prefer to rely on a library that is maintained in the long term, and its author understands the implemented algorithms. This is true for Spectra. As I understand, it is not quite true for the ARPACK translation in this PR, as @ilayn was looking to create a simple code translation, but was not planning to tweak the algorithms to correct issues that might appear in the future. (Please correct me if I miunderstood, @ilayn.)

I do have some understanding of the underlying algorithm and also the codebase (thanks to this work). What I wanted to emphasize is to create a false expectation that this is the new ARPACK offering and drawing the attention of all libraries that wraps the F77 version. Otherwise we will maintain this codebase and track arpack-ng in case they find new bugs. We do this with say, SuperLU and a few other libraries, even keep our own patches on top of the official branch.

There are two main complaints for ARPACK that is very common to have in almost all libraries across github (skipping the build failures, `(c/z)dotc` wrapper segfaulty problems and so on). One is the randomization which is quite arcane, and two it can't be re-entrant. So that's what I did here. Like I mentioned I did rewrite parts of the code but a complete rewrite requires a larger chunk of time that I can't afford now. But unlike f2c all code is rewritten from scratch though the steps are mechanical, the indices and the conventions are all recoded. 

That's what I tried to mean above. Otherwise SciPy will be maintaining this (or if we create a separate repo for it) for the foreseeable future. 

So to summarize, the functionality and feature-completeness is identical to original F77 ARPACK. I fixed a few bugs here and there and kinda-sorta modernized the code. API is incompatible but hopefully for a better one. Let me get this in a proper completed shape so you can start testing the results for yourself and decide using SciPy interface. If you are convinced then we can yank it out to a common place where you can use your own wrapper.

**Comment by szhorvat** [comment]
Thanks for the clarification @ilayn and sorry about the misunderstandings!

> One is the randomization which is quite arcane, and two it can't be re-entrant.

These are issues for us as well.

> Let me get this in a proper completed shape so you can start testing the results for yourself and decide using SciPy interface.

Will definitely try it out.

**Comment by ilayn** [comment]
Let me provide some concrete details what we mean by API breakage, take non-symmetric double precision purifier `dneupd`

```Fortran
      subroutine dneupd (rvec , howmny, select, dr    , di,
     &                   z    , ldz   , sigmar, sigmai, workev,
     &                   bmat , n     , which , nev   , tol,
     &                   resid, ncv   , v     , ldv   , iparam,
     &                   ipntr, workd , workl , lworkl, info)
```

Instead of this now the equivalent call is 

```C++
dneupd(struct ARPACK_arnoldi_update_vars_d *V, int rvec, int howmny, int* select,
       double* dr, double* di, double* z, int ldz, double sigmar, double sigmai,
       double* workev, double* resid, double* v, int ldv, int* ipntr, double* workd,
       double* workl)
```

It's not too different since most of these are array arguments and can't be tucked in anywhere but the complete state is now hidden inside that initial V, if I may compress the fields

```C++
struct ARPACK_arnoldi_update_vars_d {
    double tol,getv0_rnorm0, aitr_betaj, aitr_rnorm1, aitr_wnorm, aup2_rnorm;
    enum ARPACK_ido ido;    
    enum ARPACK_which which, bmat, info, iter, maxiter;            
    int mode, n, nconv, ncv, nev, np, numop, numpb, numreo, shift, getv0_first, getv0_iter, getv0_itry, getv0_orth, aitr_iter, aitr_j, aitr_orth1, aitr_orth2, aitr_restart, aitr_step3, aitr_step4, aitr_ierr, aup2_initv, aup2_iter, aup2_getv0, aup2_cnorm, aup2_kplusp, aup2_nev0, aup2_np0, aup2_numcnv, aup2_update, aup2_ushift;
};
```

You can see from the prefixes which function they are `SAVE`d. These are the ones that are kept on the reverse communication layer to keep the state intact, a basic common trick that game devs use all the time for characters. So it's not really anything that has changed from ARPACK but the way we interact with it is changed. Whether this is justified or not is a different story.

**Comment by yixuan** [comment]
Thanks for the discussions! Now I understand the current status better, and it seems that several things can be done in parallel. This PR for SciPy looks to be in a good shape, and I will also try to use my spare time to draft a LAPACK-based version of Spectra. It is always nice to have more options in open source projects. 😁

When I get something that is more concrete, I'll let you know.

**Comment by szhorvat** [comment]
@ilayn What values are you using for `bmat` instead of characters `I` and `G`? Which is true and which is false, out of `I` and `G`?

Given that you are treating this as a boolean, is there any reason you're not using the C99 `bool` type? Also, sice this is treated as a boolean, it is perhaps better not to validate the value and strictly enforce a `0` or `1` when I read "boolean", I assume that values will only be tested using conditionals, not `==`, and any nonzero is treated as "true".

File: scipy/sparse/linalg/_eigen/arpack/ARPACK/_arpack.h [hunk 2]
```diff
@@ -0,0 +1,197 @@
+#ifndef _ARPACK_H
+#define _ARPACK_H
+
+#ifdef __cplusplus
+extern "C"
+{
+#endif /* __cplusplus */
```
Comment (szhorvat) [inline scipy/sparse/linalg/_eigen/arpack/ARPACK/_arpack.h]: This bit of code is often added through a macro called `__BEGIN_DECLS`, which is defined based on whether the file is compiled as C or C++.

More importantly, system headers _must_ be included outside of the `extern "C"` block. This is a bug here that prevents compilation when the header is included in a C++ file. The right approach is to include _all_ headers outside of this block, whether it's a system header or your own header.  Each header should be individually responsible for adding the `extern "C"` to the functions it declares.

Comment (ilayn) [reply scipy/sparse/linalg/_eigen/arpack/ARPACK/_arpack.h]: I didn't know that. Thanks for that. 

And come to think of it I think this is not even needed as probably nobody will compile it in C++. Let me just remove it instead of pretending that I have proper guards for C++.

**Comment by ilayn** [comment]
`bmat=1` signify that there is a B matrix involved. `bmat=0` is the standard problem.

That's mostly due to avoid strange portability issues around bool type of C which is one byte. Say, you want to use Python or Fortran wrapper, CPython one is more than a byte and in Fortran it is 4 bytes (I think). So making it an integer sounds safer to me. I'll document the options once things are stabilized, currently it's still moving around for bug fixes and so on. 

Note that the C integer `int` is just a place holder for now. I'll batch replace it with an integer type macro that you can choose to accomodate for ILP64 BLAS/LAPACK via 64bit ints or regular 32bit ints from `stdint.h`.

File: scipy/sparse/linalg/_eigen/arpack/ARPACK/_arpack.h (hunk 2 above)
Comment (szhorvat) [reply scipy/sparse/linalg/_eigen/arpack/ARPACK/_arpack.h]: C++ support would actually be very good to have ... But we don't currently need it in igraph. Perhaps this is something to come back to later.

What I'm unsure about is how easy it is to handle the C99 complex type in C++. I think this is not directly supported by the C++ standard, and is only an extension, but I'm really not sure.

**Comment by szhorvat** [comment]
OK, that makes sense. Would you be okay with avoiding `if (bmat == 1)` tests and replacing all these by `if (bmat)` instead?

**Comment by ilayn** [comment]
Yes that's fair. I was being lazy.

**Comment by szhorvat** [comment]
Some more comments:

----

To make porting from classic ARPACK easier:

 - Would it be possible to annotate the entries of the `ARPACK_arnoldi_update_vars` struct with whether they are used for input, output or both? A comment in the header would do. For example, `ido` is for both input and output. `ncv` is input only. I don't remember if there are output-only ones. Of course this can be mostly looked up in the original ARPACK docs.
 - Similarly, it'd be nice to make notes about which struct members the caller is supposed to set vs which are private to ARPACK's internal operations.
 - It'd be nice to have some notes on how to port from classic ARPACK, in particular for function parameters that appear to have disappeared at first glance (I still haven't figured all of them out). Examples are IPNTR, IPARAM (broken down into pieces, which is good), LWORKL.

----

What do you think about prefixing most public symbols with `ARPACK`, similar to how `ARPACK_which` is prefixed? I am primarily thinking of enum values, such as `which_LM` -> `ARPACK_which_LM`. This is to guarantee no conflict with other packages.

To be clear, this is NOT a problem for igraph.

----

~~What are the `ARPACK_cplx` macros for? They seem to be unused.~~ These are actually used but not in the `_arpack.h` header. They should probably be removed from there.

----

As I recall, there were some issues related to specific Fortran calling conventions and string parameters. GFortran would require extra parameters to indicate the length of string (`character`) parameters. Unfortunately I don't have a full understanding of this issue. Is this not going to be a problem when calling LAPACK routines that have string parameters?

----

From a maintainability perspective, would it make sense to use some macro magic and share code between the double-precision and single-precision variants?

**Comment by ilayn** [comment]
Thanks @szhorvat good points overall. 

> Would it be possible to annotate the entries of the ARPACK_arnoldi_update_vars struct with whether they are used for input, output or both?

Yes, that's a good idea. 

> Similarly, it'd be nice to make notes about which struct members the caller is supposed to set

It's in my notes for the docs, I'll get to it once this symmetric bug is done.

> What do you think about prefixing most public symbols with ARPACK, similar to how ARPACK_which is prefixed?

Yeah, probably we should do that, we need a name for this first though. 

> These are actually used but not in the _arpack.h header.

Must be a relic from earlier commits. I'll remove it. 

> As I recall, there were some issues related to specific Fortran calling conventions and string parameters. 

I'm also not very involved in that one but we are linking to the BLAS/LAPACK libraries and not compiling together with ARPACK. So that problem lives in BLAS/LAPACK vendors in case they have it, we are just exposing the symbols.

> From a maintainability perspective, would it make sense to use some macro magic and share code between the double-precision and single-precision variants?

This is actually what I am doing though not in C. I have some simple regex file that I run through the copy of the double version to generate single versions. Preprocessors are text replacement ops anyways hence I think they are pretty arcane text processing tools. I have better ones so I don't use such macros in general. Instead of making the code unreadable I typically do it externally. But it should be possible indeed with macro magic. 

<hr>

I have one last symmetric bug somewhere. I roughly know where it is but I ran out of time that I'll be busy for a few days. If I can find it by staring, I'll fix that one otherwise I'll need to find more time to sit down for a fix. Then we can start the cosmetics and other changes.

**Comment by ilayn** [comment]
Apart from those the Array API rng related errors, this is all passing. I should buy a lottery ticket. I thought I'd never see the day.

The basic functionality is working. I'll put some documentation so we can start throwing segfaulty problems to it. None of the examples above are segfaulting on my machine unfortunately.

**Comment by ilayn** [comment]
cc @haampie @cournape now that things are stabilized a bit, a gentle ping in case you are interested.

**Comment by ilayn** [comment]
Among the remaining items, #6827 and related https://github.com/opencollab/arpack-ng/issues/51 look like a genuine ARPACK shortcoming instead of a code problem. Not sure how to prevent it yet but I can also force eigenvector unity or more restarts if we fall into that trap. I know @haampie has done some stabilization work on this matter in ArnoldiMethod.jl.

**Comment by ilayn** [comment]
Folks should we kick this in and potentially get some angry feedback from the nightlies? I would really appreciate some feedback from the downstream libraries in the coming 6 months before 1.17 rolls out. The other F77 translations so far, still very disgusting, were kinda-sorta easier to test but this thing is a bit of a beast and bugs pop up in, say, iteration 23 or whatever that is very disheartening work to figure out. I found and fixed some of the low hanging fruits but who knows what's up there. 

As I mentioned there are a few things left to address; I am a bit blinded by all the changes here but I'd like to implement an integer switch for ILP64 LAPACK by using int32 and int64 definition inside on a clean PR so that it can be reviewed. Also, as @szhorvat expects, we need to put these into proper `include` and `src` folders like a modern C project in case others want to use it. Right now it's a bit all over the place.

Then maybe, emphasis on **maybe**, work on ARPACK's own issues especially when it comes to clustered eigenvalues hence attempt to implement Krylov-Schur method instead. There might also be some eventual bugs left but now that I know where to look it started to become easier to find them quickly. 

What do you think?

**Comment by ilayn** [comment]
If there are no comments, I'd like to click the button this evening for the items I mentioned above.

**Comment by szhorvat** [comment]
> If there are no comments

Please correct me if I misunderstood, you are at this stage waiting for SciPy-specific feedback, right?

I'm still overwhelmed and it takes quite some effort to integrate this into igraph in the current raw state (I gave it a quick try earlier). So that will take some time, and I might bombard you with some questions during the process.

**Comment by ilayn** [comment]
> Please correct me if I misunderstood, you are at this stage waiting for SciPy-specific feedback, right?

Yes indeed. Then I'll start the cosmetics and document the API for external usage. 

> I might bombard you with some questions during the process.

No worries, that's good exercise anyways to improve ARPACK outside SciPy.

**Comment by rgommers** [comment]
Great to see this land, thanks for the huge effort you poured into this @ilayn!

I managed to completely miss the discussion over the last weeks, so some post-merge comments:

1. Licensing: we should keep the ARPACK license file, since this rewrite is a derivative work and the original license and attribution  it still applies. We need a separate file, rather than it being in `_arpack.h`.
2. Build config: `.h` files don't go in the list of sources. Building a separate static library instead of adding the `.c` sources to the extension module is fine if you anticipate separating this rewrite out into its own package eventually, but it isn't necessary.
3. Code structure: (nit) underscores at the start at all filenames isn't necessary and looks a bit unusual. (more important) it looks like the difference between `single` and `double` is only types, so the code size can probably be halved by a minor amount of templating if it's moved to C++. That's probably worth doing as a follow-up?

**Comment by ilayn** [comment]
Ah yes, I basically forgot to add the readme and the license files. I'll add in the new PR I'll send out soon for restructuring. Since we decided to rename this lib anyways, due to API changes; ARPACKX, ARPAX or something like that. Everything else has been taken over the decades it seems.

For 2, that's a bit of a contested area, everybody has their own opinion about them because there is no structure dictated about the build discipline by the language. h files only go out of source directory if they are the public exposed symbols under an `include` directory and the internal header files are typically kept private. Depending on the size of the project either they are bundled with the src files or have an internal directory for .h files. But again these are all artificial conventions. If the project is small enough it does not matter. I converted it into `include`/`src` distinction and added a makefile in the upcoming PR. 

For 3, this is everyone's favorite item and I have been trying C++ workflow in the last few weeks with PROPACK. I can't say it gives me the "coding once, works twice" feeling. To be honest, tempita feels superior to template programming with C++. Because there is no continuous questioning of what will happen if I write constexpr or static const or whatever, am I falling into a UB, is this C++17 or newer etc. And debugging with C++ is more challenging. Instead coding once for double and running a regex over the file (converting `dgemm` to `sgemm` or `hypot` to `hypotf` etc.) is much much faster for me and diff'ble. 

I would not object to if someone else wants to combine the C sources and make a C++ lib with it but translating directly into C++ is really not my thing. Or let me say it differently, after I convert it to C, I don't have any opinion what happens to the code as it happened to `xsf`. I have no dog in that race :)

**Comment by rgommers** [comment]
> h files only go out of source directory if

That's not what I meant - I agree that source tree layout is an opinion. What I meant to say is: `.h` files should be removed from the `arpack_sources` list in `meson.build`. Header files are handled automatically via depfiles.

**Comment by ilayn** [comment]
Ah OK,  I didn't know that. What a strange automation choice. But probably exists for a reason.

**Comment by rgommers** [comment]
> What a strange automation choice. But probably exists for a reason.

Good reasons: it is necessary to handle it automatically both for correctness (e.g., conditional includes) and to ensure that rebuilds do happen if and only if header files get updated. Since that mechanism also works for system headers and headers in build-time dependencies, using it for internal headers/dependencies as well is natural.

**Comment by szhorvat** [comment]
Regarding underscores, using `arpack.h` would be problematic because this is not compatible with ARPACK. Using `_arpack.h` is one of multiple possibilities to get around that.

File: scipy/sparse/linalg/_eigen/arpack/_arpackmodule.c [hunk 3]
```diff
@@ -0,0 +1,1078 @@
...
+// The following macros are used to define the field names in the ARPACK struct.
+#define STRUCT_INEXACT_FIELD_NAMES X(tol) X(getv0_rnorm0) X(aitr_betaj) X(aitr_rnorm1) X(aitr_wnorm) X(aup2_rnorm)
+#define STRUCT_INT_FIELD_NAMES X(ido) X(which) X(bmat) X(info) X(iter) X(maxiter) X(mode) \
+                               X(n) X(nconv) X(ncv) X(nev) X(np) \
+                               X(shift) X(getv0_first) X(getv0_iter) X(getv0_itry) X(getv0_orth) \
+                               X(aitr_iter) X(aitr_j) X(aitr_orth1) X(aitr_orth2) X(aitr_restart) \
+                               X(aitr_step3) X(aitr_step4) X(aitr_ierr) X(aup2_initv) X(aup2_iter) \
+                               X(aup2_getv0) X(aup2_cnorm) X(aup2_kplusp) X(aup2_nev0) X(aup2_np0) \
+                               X(aup2_numcnv) X(aup2_update) X(aup2_ushift)
+#define STRUCT_FIELD_NAMES STRUCT_INT_FIELD_NAMES STRUCT_INEXACT_FIELD_NAMES
```
Comment (h-vetinari) [inline scipy/sparse/linalg/_eigen/arpack/_arpackmodule.c:30]: Can't say I'm a fan of the macro games being played here. `X` here isn't defined yet, and in fact gets redefined constantly further down. That might be easy to read for a veteran C programmer like yourself, but I think it's hard to grok and fragile.

Comment (h-vetinari) [reply scipy/sparse/linalg/_eigen/arpack/_arpackmodule.c:30]: I've tried playing around with putting this on a more solid footing, but gah. The difference between `ARPACK_arnoldi_update_vars_s` and `ARPACK_arnoldi_update_vars_d` is pointless on 64bit platforms, but of course, the types appear in the function signatures and thus the API/ABI, and \*of course\* the only fields of potentially differing size are at the _beginning_ of the struct, which completely messes up any offset-based computations between the two structs. 😑

**Review by h-vetinari — COMMENTED** [review]
Great work as always, though there are some implementation details that I find not ideal.

File: scipy/sparse/linalg/_eigen/arpack/_arpackmodule.c (hunk 3 above)
Comment (ilayn) [reply scipy/sparse/linalg/_eigen/arpack/_arpackmodule.c:30]: I commented on your PR for the reasoning on my part

File: scipy/sparse/linalg/_eigen/arpack/arpack.py [hunk 4]
```diff
@@ -1528,6 +1599,11 @@ def eigsh(A, k=6, M=None, sigma=None, which='LM', v0=None,
         The choice of mode will affect which eigenvalues are selected by
         the keyword 'which', and can also impact the stability of
         convergence (see [2] for a discussion).
+    rng : `numpy.random.Generator`, optional
+        Pseudorandom number generator state. When `rng` is None, a new
+        `numpy.random.Generator` is created using entropy from the
+        operating system. Types other than `numpy.random.Generator` are
+        passed to `numpy.random.default_rng` to instantiate a ``Generator``.
```
Comment (flying-sheep) [inline scipy/sparse/linalg/_eigen/arpack/arpack.py:1606]: Hi, would be dope if you could document when you add parameters in the future!

Comment (ilayn) [reply scipy/sparse/linalg/_eigen/arpack/arpack.py:1606]: Hi @flying-sheep do you mean the rubrics like `added version 1.160..` ?

Comment (flying-sheep) [reply scipy/sparse/linalg/_eigen/arpack/arpack.py:1606]: In our docs we have `.. version-added:: x.y` directives so people can see at a glance if they can use a parameter without bumping their minimum required version of our library.
