### PR TITLE
BUG: special: fix algorithmic error in `ratevl` in `cephes/polevl.h`

### LINKED ISSUE #20697: BUG: special: algorithmic Error in `ratevl` in `cephes/polevl.h`
I am a PhD candidate in Applied Math from the University of Waterloo. I was investigating some numerical issues in my research when I found an algorithmic error for the function `ratevl` in `scipy / scipy / special / cephes / polevl.h`. It appears on `line 158`, which should be `i = M - N;` instead of `i = N - M;`. Here I give a brief explanation of what the function does and why there is a bug.
The function `ratevl` on `line 118` evaluates a rational function $\cfrac{P(x)}{Q(x)}$, where $P(x)$ and $Q(x)$ are polynomials of order $M$ and $N$ respectively. For $|x| > 1$, $P(x)$ and $Q(x)$ are evaluated by $\cfrac{1}{x}$ instead of $x$, using Horner's method as referenced on `line 55`.
Here I give a simple example to illustrate. Let $f_2(x) = a_2 x^2 + a_1 x + a_0$ be a second order polynomial. If $|x| > 1$, then the polynomial is evaluated in reverse order as polynomial in $\cfrac{1}{x}$.
That is, $\cfrac{f_2(x)}{x^2} = a_2 + a_1 \cdot\cfrac{1}{x} + a_0 \cdot\cfrac{1}{x^2} = (a_0 \cdot\cfrac{1}{x} + a_1)\cdot \cfrac{1}{x} + a_2$, thus $f_2(x) = ((a_0\cdot \cfrac{1}{x} + a_1)\cdot\cfrac{1}{x} + a_2) \cdot x^2$. In the code, $P(x) = num\textunderscore ans \cdot x^M$, $Q(x) = denom\textunderscore ans \cdot x^N$, thus $\cfrac{P(x)}{Q(x)} = \cfrac{num\textunderscore ans}{denom\textunderscore ans}\cdot x^{M - N}$, and $i$ on `line 158` should be $M - N$, not $N - M$.
In the boost implementation as referenced on `line 55`, it pre-processed to require $P(x)$ and $Q(x)$ to have the same order so that it's not an issue there. As on `line 60`, I believe the piece of code for the function `ratevl` is rewritten instead of copying from the reference directly, which is likely to be a reason for this error.

### PR DESCRIPTION
**Pull request by ZhibingSun**
#### Reference issue

Closes #20697.
#### What does this implement/fix?

It fixed an algorithmic error in `ratevl` in `cephes/polevl.h`.

### CODE REVIEW

**Review by tupui — APPROVED** [review]
Thanks @ZhibingSun

**Comment by lucascolley** [comment]
and congrats on your first contribution to SciPy!

File: scipy/special/special/cephes/polevl.h [hunk 1]
```diff
@@ -115,6 +116,7 @@ namespace cephes {
 
     /* Evaluate a rational function. See [1]. */
 
+    /* The function ratevl is only used once in cephes/lanczos.h. */
```
Comment (steppi) [inline scipy/special/special/cephes/polevl.h:119]: I think it's fine to keep this comment here, but just want to point out that this may change in the future, especially as we work on unifying the `cephes`, `amos`, `specfun`, `cdflib`, `faddeeva`, etc. codebases.

Comment (ZhibingSun) [reply scipy/special/special/cephes/polevl.h:119]: Sure. I just checked the code for $erf(x)$ and $erfc(x)$ in `special/Faddeeva.cc`, which I think have better performance than the ones in `cephes/ndtr.h`, so is it possible to improve the performance of the functions in `cephes/ndtr.h` in the future, i.e., $erf(x)$, $erfc(x)$, and $ndtr(x)$?.

Comment (steppi) [reply scipy/special/special/cephes/polevl.h:119]: We actually found that `cephes` has better accuracy for real valued `ndtr`, `erf`, and `erfc`. See https://github.com/scipy/scipy/pull/19492#issuecomment-1802330899.

I just meant that it's not unlikely that `ratevl` will end up being used again in another function, and I want to make sure to keep in mind that if so, this comment will need to be updated.
