### PR TITLE
MAINT: make bdt{r,rc,ri}() functions accept double n,k args + tests

### LINKED ISSUE #7058: Errors in special.bdtri and special.bdtr for non-integer k values
Assuming the incomplete beta function and its inverse are correct, the functions bdtri(n,k,y) and bdtr(k,n,p) give the wrong values for non-integer k (```scipy.__version__ == 0.18.1```)
Test code:
```
from scipy.special import bdtrik, bdtri, bdtr, betainc, betaincinv
import numpy as np
for n in range(2,9):    
    p = 0.05
    y = 0.95
    k = bdtrik(y, n, p)
    print n, k, bdtr(k,n,p), betainc(n-k,k+1,1-p), bdtri(k,n,y), 1 - betaincinv(n-k,k+1,y)
    k = np.ceil(k)
    print n, k, bdtr(k,n,p), betainc(n-k,k+1,1-p), bdtri(k,n,y), 1 - betaincinv(n-k,k+1,y) 
```
Outputs:

| n | k | y = bdtr(k,n,p) | y = betainc(n-k,k+1,1-p) | p = bdtri(k,n,y) | p = 1 - betaincinv(n-k,k+1,y) | 
| - | - | ----------- | -------------------- | ------------ | ------------------------- | 
 | 2.0 | 0.2142 | 0.9025 | 0.95 | 0.0253 | 0.05 | 
 | 2.0 | 1.0 | 0.9975 | 0.9975 | 0.2236 | 0.2236 | 
 | 3.0 | 0.3902 | 0.8574 | 0.95 | 0.017 | 0.05 | 
 | 3.0 | 1.0 | 0.9928 | 0.9928 | 0.1354 | 0.1354 | 
 | 4.0 | 0.5456 | 0.8145 | 0.95 | 0.0127 | 0.05 | 
 | 4.0 | 1.0 | 0.986 | 0.986 | 0.0976 | 0.0976 | 
 | 5.0 | 0.6876 | 0.7738 | 0.95 | 0.0102 | 0.05 | 
 | 5.0 | 1.0 | 0.9774 | 0.9774 | 0.0764 | 0.0764 | 
 | 6.0 | 0.8202 | 0.7351 | 0.95 | 0.0085 | 0.05 | 
 | 6.0 | 1.0 | 0.9672 | 0.9672 | 0.0628 | 0.0628 | 
 | 7.0 | 0.9457 | 0.6983 | 0.95 | 0.0073 | 0.05 | 
 | 7.0 | 1.0 | 0.9556 | 0.9556 | 0.0534 | 0.0534 | 
 | 8.0 | 1.0655 | 0.9428 | 0.95 | 0.0464 | 0.05 | 
 | 8.0 | 2.0 | 0.9942 | 0.9942 | 0.1111 | 0.1111 |

### PR DESCRIPTION
**Pull request by rlucas7**
#### Reference issue
Closes gh-7058

#### What does this implement/fix?
This PR changes the signature for the `bdtr()`, `bdtrc()`, and `bdtri()` functions to accept all arguments as doubles (with appropriate floor/rounding). 

#### Additional information
I'm not clear about the `bdtri()` function. In 1 or 2 cases the unit tests I've written return `np.nan` and I'm unsure if that this the desired behavior for the `bdtri()` function. Would specifically like feedback on that function. Of course feedback on the other 2 functions is also welcome.

### CODE REVIEW

File: scipy/special/cephes/bdtr.c [hunk 1]
```diff
@@ -148,103 +148,89 @@
 
 #include "mconf.h"
 
-double bdtrc(k, n, p)
-int k, n;
-double p;
+double bdtrc(double k, double n, double p)
```
Comment (person142) [inline scipy/special/cephes/bdtr.c]: Hm I'm not sure that rounding makes sense for `n`; it seems like if `n != floor(n)` then we should return NaN.

OTOH that's now going to be a back compatibility break, so if we want to change it we will need to go through a deprecation cycle.

File: scipy/special/cephes/bdtr.c [hunk 2]
```diff
@@ -148,103 +148,89 @@
...
 	return 1.0;
     }
-
-    if (n < k) {
-      domerr:
-	sf_error("bdtrc", SF_ERROR_DOMAIN, NULL);
-	return NPY_NAN;
-    }
-
-    if (k == n)
```
Comment (person142) [inline scipy/special/cephes/bdtr.c]: I assume this path was dropped because `incbet` is doing to handle it correctly below anyway?

File: scipy/special/cephes/bdtr.c [hunk 3]
```diff
@@ -148,103 +148,89 @@
...
+        sf_error("bdtr", SF_ERROR_DOMAIN, NULL);
+        return NPY_NAN;
     }
 
     if (k == n)
-	return (1.0);
+	return 1.0;
 
-    dn = n - k;
+    dn = floor(n) - floor(k);
```
Comment (person142) [inline scipy/special/cephes/bdtr.c]: As above about rounding `n`.

**Review by person142 — COMMENTED** [review]
Looks good, but we need to think about what the right behavior for nonintegral `n` is I think.

I mentioned using `pytest.mark.parametrize` in a comment on one of the tests, but there are other tests where it is also applicable, so please consider that too.

File: scipy/special/add_newdocs.py [hunk 4]
```diff
@@ -382,9 +382,9 @@ def add_newdoc(name, doc):
     Parameters
     ----------
     k : array_like
-        Number of successes (int).
+        Number of successes (int or double).
```
[the remark this answers is not in the document]
Comment (rlucas7) [reply scipy/special/add_newdocs.py]: ok. Changes made for `bdtr` and `bdtrc`

File: scipy/special/tests/test_bdtr.py [hunk 5]
```diff
@@ -0,0 +1,99 @@
...
+        val = sc.bdtr([0, 1, 2], 2, 0.5)
+        assert_array_equal(val, [0.25, 0.75, 1.0])
+
+    def test_rounding(self):
+        double_val = sc.bdtr([0.1, 1.1, 2.1], 2.1, 0.5)
+        int_val = sc.bdtr([0, 1, 2], 2, 0.5)
+        assert_array_equal(double_val, int_val)
+
+    def test_inf(self):
+        val = sc.bdtr(np.inf, 2.0, 0.5)
```
[the remark this answers is not in the document]
Comment (rlucas7) [reply scipy/special/tests/test_bdtr.py]: done.

File: scipy/special/tests/test_bdtr.py [hunk 6]
```diff
@@ -0,0 +1,99 @@
...
+        val2 = sc.bdtr(1.0, np.inf, 0.5)
+        val3 = sc.bdtr(1.0, 2.0, np.inf)
+        assert np.isnan(val)
+        assert np.isnan(val2)
+        assert np.isnan(val3)
+
+    def test_domain(self):
+        val = sc.bdtr(-1.1, 1.0, 0.5)
+        assert np.isnan(val)
+
```
[the remark this answers is not in the document]
Comment (rlucas7) [reply scipy/special/tests/test_bdtr.py]: done

File: scipy/special/tests/test_bdtr.py [hunk 7]
```diff
@@ -0,0 +1,99 @@
...
+    def test_domain(self):
+        val = sc.bdtri(-1.1, 1.0, 0.5)
+        val2 = sc.bdtri(2.1, 1.0, 0.5)
+        assert np.isnan(val)
+        assert np.isnan(val2)
+
+    def test_bdtr_bdtri_roundtrip(self):
+        bdtr_vals = sc.bdtr([0, 1, 2], 2, 0.5)
+        roundtrip_vals = sc.bdtri([0, 1, 2], 2, bdtr_vals)
+        assert_almost_equal(roundtrip_vals, [0.5, 0.5, np.nan])
```
[the remark this answers is not in the document]
Comment (rlucas7) [reply scipy/special/tests/test_bdtr.py]: done

File: scipy/special/cephes/bdtr.c (hunk 1 above)
Comment (rlucas7) [reply scipy/special/cephes/bdtr.c]: >OTOH that's now going to be a back compatibility break, so if we want to change it we will need to go through a deprecation cycle.

I'm not sure I follow. Currently, the `bdtr()` throws a runtime warning. Are you suggesting to depracate the current behavior and the `floor()` behavior proposed here for a `double n` argument where 
```
if (n != floor(n)) {
    sf_error("bdtrc", SF_ERROR_DOMAIN, NULL);
    return NPY_NAN;
}
```
If I understand correctly please let me know. I haven't done any depracations in SciPy before but I think I've seen one or two annotations for them. I'm guessing the typical process is add the depracated annotation for `X` release cycles then change the behavior. Please let me know what we'd like to do here, e.g. if my understanding is correct.

File: scipy/special/tests/test_bdtr.py [hunk 8]
```diff
@@ -0,0 +1,99 @@
...
+
+    def test_domain(self):
+        val = sc.bdtrc(-1.1, 1.0, 0.5)
+        val2 = sc.bdtrc(2.1, 1.0, 0.5)
+        assert np.isnan(val2)
+        assert_almost_equal(val, 1.0)
+
+    def test_bdtr_bdtrc_sum_to_one(self):
+        bdtr_vals = sc.bdtr([0, 1, 2], 2, 0.5)
+        bdtrc_vals = np.nan_to_num(sc.bdtrc([0, 1, 2], 2, 0.5))
```
[the remark this answers is not in the document]
Comment (rlucas7) [reply scipy/special/tests/test_bdtr.py]: I think the `2,2,0.5` argument was giving a `nan` which was caused by my dropping (accidentally) of the `if (n==k) {` case above.  Fixed now.

File: scipy/special/cephes/bdtr.c (hunk 2 above)
Comment (rlucas7) [reply scipy/special/cephes/bdtr.c]: I don't think `incbet` was handling correctly. See comment above about `2,2,0.5` going to a `nan`

File: scipy/special/cephes/bdtr.c (hunk 3 above)
Comment (rlucas7) [reply scipy/special/cephes/bdtr.c]: see my question above. I'm not clear what you mean by the depracation comment.

File: scipy/special/cephes/bdtr.c (hunk 1 above)
Comment (person142) [reply scipy/special/cephes/bdtr.c]: > Are you suggesting to depracate the current behavior and the floor() behavior proposed here

Yes, that’s what I’m proposing. Before getting into the details of deprecating, however, do we agree that nonintegral `n` doesn’t seem like a reasonable input? We should think through this one carefully.

**Comment by rlucas7** [comment]
@person142 could you clarify on the `nan` throwing/depraction comment? I addressed other comments in the latest push-changes related to `n` argument were not done as not clear.

**Comment by rlucas7** [comment]
> Yes, that’s what I’m proposing. Before getting into the details of deprecating, however, do we agree that nonintegral n doesn’t seem like a reasonable input? We should think through this one carefully.
> 
From a math perspective I don’t think n needs to be integral. The binomial distribution makes us think n should be an int because of the n choose k term. The relationship between a combination and a beta function allows one to extend the k,n arguments to all valid real (complex really but let’s not go there) n,k. Here the sf_error checks in bdtr are getting the valid real argument checks for the binomial. 

However these if this is being used in
Other routines, or we want to keep that option available, perhaps the rounding should appear in the source for the binomial functions in stats? 
I’m thinking that doing rounding on k,n forces some behavior that is sensible for the binomial but not for other uses. 

Are these functions (bdtr, bdtrc,etc) intended for use outside of the binomial?

**Comment by person142** [comment]
> Are these functions (bdtr, bdtrc,etc) intended for use outside of the binomial?

This is the crux I think. If we _weren’t_ dealing with a CDF then the rounding in `k` would be incorrect too; we should just interpolate using the incomplete beta function, and similarly for `n`. But I have been approaching from a “this is just a CDF” perspective, with the assumption that if you want the interpolated behavior you go and use the incomplete beta function directly.

**Comment by rlucas7** [comment]
> > I’m thinking that doing rounding on k,n forces some behavior that is sensible for the binomial but not for other uses. Are these functions (bdtr, bdtrc,etc) intended for use outside of the binomial?
> 
> This is the crux I think. If we _weren’t_ dealing with a CDF then the rounding in `k` would be incorrect too; we should just interpolate using the incomplete beta function, and similarly for `n`. But I have been approaching from a “this is just a CDF” perspective, with the assumption that if you want the interpolated behavior you go and use the incomplete beta function directly.

Ok, from the CDF perspective we agree that `double k` is ok. I'm not sure that we ***need*** an integral valued `n` (whether type is `double` or not). At least from a mathematical perspective: 
https://en.wikipedia.org/wiki/Binomial_distribution#Beta_distribution
`double n` without rounding is fine. However, there seems to be enough surprise from users that I'd say following [PLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) the input for `n` should be an integral value. I think it is fine for type `double` and we can check if `floor(n) !=n`
and throw an error if not equal. In other words, I think your proposal is reasonably for the `n` argument on the `floor(n) !=n` side but if we keep `int n` I'm not sure why we would need to check `floor(n) != n`? 

If you mean ***for  now*** keep `int n` and add depracation, then in  two release cycles, convert to `double n` and  return `nan` if `floor(n)!=n` that sounds fine to me. 

Either way, the `bdtr()` (and others in this PR) already take floating point arguments currently. Right now they emit a runtime warning if `floor(n)!=n`. The change in this PR makes the runtime warning go away completely. Your proposal (which also sounds reasonable) is to convert the runtime warning to an exception. The only thing I disagree on is that the `n` argument needs to be an `int` type, maybe I misunderstood? 

Is what I understand what you mean?

**Comment by rlucas7** [comment]
@person142
I've considered this a bit more, I think there should be an error thrown if `floor(n)!=n`. My reasoning is that the `binom` distribution class should have a consistent interface to the user. I tested the various methods with `n=1.1` to see what happens: 
```
>>> ss.binom(1, 0.5)
<scipy.stats._distn_infrastructure.rv_frozen object at 0x107710a20>
>>> ss.binom(1, 0.5).rvs(1)
array([0])
>>> ss.binom(1.1, 0.5).rvs(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rlucas/scipy-dev/scipy/scipy/stats/_distn_infrastructure.py", line 463, in rvs
    return self.dist.rvs(*self.args, **kwds)
  File "/Users/rlucas/scipy-dev/scipy/scipy/stats/_distn_infrastructure.py", line 2964, in rvs
    return super(rv_discrete, self).rvs(*args, **kwargs)
  File "/Users/rlucas/scipy-dev/scipy/scipy/stats/_distn_infrastructure.py", line 980, in rvs
    vals = self._rvs(*args)
  File "/Users/rlucas/scipy-dev/scipy/scipy/stats/_discrete_distns.py", line 43, in _rvs
    return self._random_state.binomial(n, p, self._size)
  File "mtrand.pyx", line 3795, in mtrand.RandomState.binomial
TypeError: Cannot cast array data from dtype('float64') to dtype('int64') according to the rule 'safe'
>>> ss.binom(1.1, 0.5).pmf(1)
0.5131681453452441
>>> ss.binom(1.1, 0.5).cdf(1)
/Users/rlucas/scipy-dev/scipy/scipy/stats/_discrete_distns.py:62: RuntimeWarning: floating point number truncated to an integer
  vals = special.bdtr(k, n, p)
1.0
>>> ss.binom(1.1, 0.5).stats()
(array(0.55), array(0.275))
>>> ss.binom(1.1, 0.5).stats('mvsk')
(array(0.55), array(0.275), array(0.), array(-1.81818182))
>>> ss.binom(1.1, 0.5).ppf(.25)
/Users/rlucas/scipy-dev/scipy/scipy/stats/_discrete_distns.py:72: RuntimeWarning: floating point number truncated to an integer
  temp = special.bdtr(vals1, n, p)
0.0
>>> ss.binom(1.1, 0.5).cdf(1)
1.0
>>> ss.binom(1.1, 0.5).sf(1)
/Users/rlucas/scipy-dev/scipy/scipy/stats/_discrete_distns.py:67: RuntimeWarning: floating point number truncated to an integer
  return special.bdtrc(k, n, p)
0.0
>>> ss.binom(1.1, 0.5).logsf(1)
-inf
>>> ss.binom(1.1, 0.5).isf(1)
-1.0
>>> ss.binom(1.1, 0.5).entropy()
array(0.79204583)
>>> ss.binom(1.1, 0.5).expect()
0.5644849598797687
>>> ss.binom(1.1, 0.5).median()
0.0
>>> ss.binom(1.1, 0.5).mean()
0.55
>>> ss.binom(1.1, 0.5).var()
0.275
>>> ss.binom(1.1, 0.5).std()
0.5244044240850758
>>> ss.binom(1.1, 0.5).interval(.05)
(0.0, 1.0)
>>> 
```
The `rvs()` method throws an error. The other functions in the class who are calling `bdtr` functions are emitting a runtime warning. So I think all the methods should throw an error. 
Also, this follows the Principle of Least astonishment-2 good reasons for `floor(n)==n` and throw an error if not.

**Comment by person142** [comment]
So throwing an exception from a ufunc is pretty much a no-go. It’s generally not done because one bad input can destroy a large computation. It also goes against the special API. Instead of exceptions we return NaNs.

**Comment by person142** [comment]
You could always add the check on the stats side though-just not on the special side.

**Comment by rlucas7** [comment]
> You could always add the check on the stats side though-just not on the special side.
> 
Yes that sounds like the way to go.
Bottom line I agree with you on the nan return if floor(n)==n. And that would be a change from the current bdtr api. 

Given returning NaN in this case would break backwards compatibility, How would you recommend to proceed in this PR?

**Comment by person142** [comment]
Ok, my proposed concrete solution:

- The end goal is to just have the signature `bdtr(double k, long n, double p)`. If `n` only makes sense for integers, let's just leave it an integer and only allow `k` to be a double. We update the Cephes signature and also update the docs to make it really clear what's happening.
- Since we have to go through a deprecation cycle, we change the `_legacy.pxd` signature so that it emits a deprecation warning saying that calling with `n` a double is deprecated as of 1.4 and will be removed in the future.
- In 1.6 we remove the legacy signature.

(And similar things for `bdtrc`.)

**Comment by rlucas7** [comment]
> Ok, my proposed concrete solution:
> 
>     * The end goal is to just have the signature `bdtr(double k, long n, double p)`. If `n` only makes sense for integers, let's just leave it an integer and only allow `k` to be a double. We update the Cephes signature and also update the docs to make it really clear what's happening.
> 
>     * Since we have to go through a deprecation cycle, we change the `_legacy.pxd` signature so that it emits a deprecation warning saying that calling with `n` a double is deprecated as of 1.4 and will be removed in the future.
> 
>     * In 1.6 we remove the legacy signature.
> 
> 
> (And similar things for `bdtrc`.)

This aligns with what I was expecting. 
It is clear to me what to do for the functions in this PR, except possibly the deprecation in the `_legacy.pxd` file. 
Specifically, I've only seen the deprecation annotation used in pure python files in SciPy. I'm not sure if the same annotation can be used in Cython but I'll give it a go and see if it breaks. 

I should be able to get this done over this weekend so we can (hopefully) get this into the 1.4.0 release.

**Comment by person142** [comment]
> Specifically, I've only seen the deprecation annotation used in pure python files in SciPy. I'm not sure if the same annotation can be used in Cython but I'll give it a go and see if it breaks.

Right, so I would not use the decorator here. Instead use what `_legacy_cast_check` does as a model:

https://github.com/scipy/scipy/blob/d88f3ab77606d98ee72416c5e0abdbe1e1102aa5/scipy/special/_legacy.pxd#L30

and make it a `DeprecationWarning` with an appropriate message instead.

**Comment by rlucas7** [comment]
> Right, so I would not use the decorator here. Instead use what `_legacy_cast_check` does as a model:
> 
> https://github.com/scipy/scipy/blob/d88f3ab77606d98ee72416c5e0abdbe1e1102aa5/scipy/special/_legacy.pxd#L30
> 
> and make it a `DeprecationWarning` with an appropriate message instead.

@person142 I put something in here that emits the deprecation warning, these changes exposed a couple of items in the unit tests and the `np.inf` input for `n` that I also needed to change. I was able to confirm that the functions emit a `DeprecationWarning` if `floor(n)!=n`.

**Comment by rlucas7** [comment]
This is interesting: 
```
_________________________ TestBdtr.test_deprecation ___________________________

[gw2] linux -- Python 3.7.1 /home/travis/virtualenv/python3.7.1/bin/python

self = <scipy.special.tests.test_bdtr.TestBdtr object at 0x7f3d5f8dea20>

    def test_deprecation(self):

>       pytest.warns(DeprecationWarning,"sc.bdtr(1.1, 1.2, 0.5)")

E       TypeError: 'sc.bdtr(1.1, 1.2, 0.5)' object (type: <class 'str'>) must be callable

self       = <scipy.special.tests.test_bdtr.TestBdtr object at 0x7f3d5f8dea20>

/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/scipy/special/tests/test_bdtr.py:35: TypeError
```
but these tests pass on my local setup? 
Either we have an old pytest version that doesn't support those types of arguments into 
`pytest.warns` or there is something else going on I'm not aware of in the builds. I'll check if I can switch to the function and argument approach and see if that builds. 

Ah I see now, based on:
https://docs.scipy.org/doc/scipy/reference/dev/index.html
we don't want unit tests for the deprecation warnings. In particular where it states:
`When introducing the warning, also ensure that those warnings are filtered out when running the test suite so they don’t pollute the output.`
I'll remove these tests and the build should pass.

File: scipy/special/_legacy.pxd [hunk 9]
```diff
@@ -35,6 +36,13 @@ cdef inline void _legacy_cast_check(char *func_name, double x, double y) nogil:
                                "floating point number truncated to an integer",
                                1)
 
+cdef inline void _legacy_deprecation(char *func_name, double x, double y) nogil:
+    if <int>y != y:
+        with gil:
+            PyErr_WarnEx_noerr(DeprecationWarning,
+                               "non-integer arg is deprecated, removed in SciPy 1.6.x",
```
Comment (person142) [inline scipy/special/_legacy.pxd]: You're going to want to warn whenever the `double`, `double`, `double` signature is hit, since in the future just passing a double for `n` will fail, not just a double that doesn't happen to be an integer.

File: scipy/special/_legacy.pxd [hunk 10]
```diff
@@ -50,23 +58,23 @@ cdef inline double ellip_harmonic_unsafe(double h2, double k2, double n,
     _legacy_cast_check("_ellip_harm", n, p)
     return ellip_harmonic(h2, k2, <int>n, <int>p, l, signm, signn)
 
-cdef inline double bdtrc_unsafe(double k, double n, double p) nogil:
-    if npy_isnan(k) or npy_isnan(n):
+cdef inline double bdtr_unsafe(double k, double n, double p) nogil:
+    if npy_isnan(k) or npy_isnan(n) or npy_isinf(n):
```
Comment (person142) [inline scipy/special/_legacy.pxd]: The warning should occur before this line-you should always get a warning for hitting this signature.

File: scipy/special/add_newdocs.py [hunk 11]
```diff
@@ -374,15 +374,15 @@ def add_newdoc(name, doc):
 
     Binomial distribution cumulative distribution function.
 
-    Sum of the terms 0 through `k` of the Binomial probability density.
+    Sum of the terms 0 through `floor(k)` of the Binomial probability density.
 
     .. math::
-        \mathrm{bdtr}(k, n, p) = \sum_{j=0}^k {{n}\choose{j}} p^j (1-p)^{n-j}
+        \mathrm{bdtr}(k, n, p) = \sum_{j=0}^floor(k) {{n}\choose{j}} p^j (1-p)^{n-j}
```
Comment (person142) [inline scipy/special/add_newdocs.py]: Use LaTeX here, i.e. `\lfloor` and `\rfloor`.

File: scipy/special/add_newdocs.py [hunk 12]
```diff
@@ -374,15 +374,15 @@ def add_newdoc(name, doc):
...
 
     Parameters
     ----------
     k : array_like
-        Number of successes (int).
+        Number of successes (double).
```
Comment (person142) [inline scipy/special/add_newdocs.py]: Similarly the rounding needs to be mentioned.

File: scipy/special/cephes/bdtr.c [hunk 13]
```diff
@@ -148,103 +148,92 @@
 
 #include "mconf.h"
 
-double bdtrc(k, n, p)
-int k, n;
-double p;
+double bdtrc(double k, int n, double p)
```
Comment (person142) [inline scipy/special/cephes/bdtr.c]: Looks like you should compute `floor(k)` somewhere at the beginning of the function and use it throughout.

File: scipy/special/cephes/bdtr.c [hunk 14]
```diff
@@ -148,103 +148,92 @@
...
 {
     double dk, dn;
 
     if (npy_isnan(p)) {
```
Comment (person142) [inline scipy/special/cephes/bdtr.c]: Now we will also need a NaN check for `k`.

File: scipy/special/cephes/bdtr.c [hunk 15]
```diff
@@ -148,103 +148,92 @@
...
 	return NPY_NAN;
     }
-    if ((p < 0.0) || (p > 1.0)) {
-	goto domerr;
+    if (p < 0.0 || p > 1.0 || n < floor(k)) {
```
Comment (person142) [inline scipy/special/cephes/bdtr.c]: Hm the `n < floor(k)` feels weird (versus `n < k`).

For the future (i.e. not this PR) we could think about extending the domain of the CDF for `-oo < k < oo`, and similarly with the other survival functions/CDFs.

File: scipy/special/tests/test_basic.py [hunk 16]
```diff
@@ -3271,9 +3271,9 @@ def test_legacy():
     # Legacy behavior: truncating arguments to integers
     with suppress_warnings() as sup:
         sup.filter(RuntimeWarning, "floating point number truncated to an integer")
-        assert_equal(special.bdtrc(1, 2, 0.3), special.bdtrc(1.8, 2.8, 0.3))
-        assert_equal(special.bdtr(1, 2, 0.3), special.bdtr(1.8, 2.8, 0.3))
-        assert_equal(special.bdtri(1, 2, 0.3), special.bdtri(1.8, 2.8, 0.3))
+        # assert_equal(special.bdtrc(1, 2, 0.3), special.bdtrc(1.8, 2.8, 0.3))
+        # assert_equal(special.bdtr(1, 2, 0.3), special.bdtr(1.8, 2.8, 0.3))
+        # assert_equal(special.bdtri(1, 2, 0.3), special.bdtri(1.8, 2.8, 0.3))
```
Comment (person142) [inline scipy/special/tests/test_basic.py]: Just delete these?

**Review by person142 — COMMENTED** [review]
There were a few things I only commented on once (e.g. using LaTeX for floor) that were applicable in other parts of the PR, so please take that into consideration.

**Comment by rlucas7** [comment]
Thanks for the comments, these are some good, helpful, points. I'm pretty busy over the next couple weeks so I won't be able to get back to this for 2-3 weekends. This means it isn't getting into 1.4.0 release which I think is fine. I'll chime in on the thread when I pick this back up.

File: scipy/special/tests/test_basic.py (hunk 16 above)
Comment (rlucas7) [reply scipy/special/tests/test_basic.py]: yeah, those should've been deleted in last commit.

File: scipy/special/cephes/bdtr.c (hunk 15 above)
Comment (rlucas7) [reply scipy/special/cephes/bdtr.c]: I'll infer from your comment here that for now I'll leave this as it is currently written. 

If we continue to proceed with interpretation as a cdf then the values for `k` can be `0` for `k<0` and `1` for `k>n`.

File: scipy/special/cephes/bdtr.c (hunk 14 above)
Comment (rlucas7) [reply scipy/special/cephes/bdtr.c]: ok, I've got that changed, do we need a NaN check for `n` too? 
I'm assuming we are drop the if-check block in `scipy/special/_legacy.pxd` entirely, let me know if you think otherwise.

File: scipy/special/cephes/bdtr.c (hunk 13 above)
Comment (rlucas7) [reply scipy/special/cephes/bdtr.c]: good idea, changed throughout to have a single `fk = floor(k)` call in each function w/subsequent calculations using `fk`.

File: scipy/special/add_newdocs.py (hunk 12 above)
Comment (rlucas7) [reply scipy/special/add_newdocs.py]: done. added a note that `k` is rounded down to nearest integer.

File: scipy/special/add_newdocs.py (hunk 11 above)
Comment (rlucas7) [reply scipy/special/add_newdocs.py]: ok.

File: scipy/special/_legacy.pxd (hunk 9 above)
Comment (rlucas7) [reply scipy/special/_legacy.pxd]: Not sure I follow how you'd like line 40 to read, are you suggesting something like: 
`if isinstance(x, double) and isinstance(y, double) and  isinstance(z, double):`
not sure if the syntax is fully correct, I'm less familiar w/Cython than I am with C or Python.

File: scipy/special/_legacy.pxd (hunk 10 above)
Comment (rlucas7) [reply scipy/special/_legacy.pxd]: I'm assuming what you mean here is to remove the `if npy_isnan(k) or npy_isnan(n) or npy_isinf(n):` line entirely and adjust indent etc. 
when I do that the `nan`s pass through and b/c they are floats they trigger the deprecation which causes the tests in `scipy/special/tests/test_nan_inputs.py` to fail. 
Maybe I am not understanding what you are suggesting?

File: scipy/special/add_newdocs.py (hunk 11 above)
Comment (rlucas7) [reply scipy/special/add_newdocs.py]: when I add the \lfloor \rfloor that causes the doc build and therefore the entire build to fail, something like this:" 
```
scipy/signal/_spectral.pyx has not changed
scipy/signal/_sosfilt.pyx has not changed
scipy/stats/_stats.pyx has not changed

Error compiling Cython file:
------------------------------------------------------------
...
    "    events).\n"
    "\n"
    "Returns\n"
    "-------\n"
    "p : ndarray\n"
    "    The event probability such that `bdtr(\\lfloor k 
                                                         ^
------------------------------------------------------------

_ufuncs.pyx:3045:58: Unclosed string literal
Traceback (most recent call last):
  File "/Users/rlucas/scipy-dev/scipy/tools/cythonize.py", line 307, in <module>
    main()
  File "/Users/rlucas/scipy-dev/scipy/tools/cythonize.py", line 303, in main
    find_process_files(root_dir)
  File "/Users/rlucas/scipy-dev/scipy/tools/cythonize.py", line 292, in find_process_files
    for result in pool.imap_unordered(lambda args: process(*args), jobs):
  File "/Users/rlucas/anaconda3/envs/scipy-dev/lib/python3.6/multiprocessing/pool.py", line 761, in next
    raise value
  File "/Users/rlucas/anaconda3/envs/scipy-dev/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/Users/rlucas/scipy-dev/scipy/tools/cythonize.py", line 292, in <lambda>
    for result in pool.imap_unordered(lambda args: process(*args), jobs):
  File "/Users/rlucas/scipy-dev/scipy/tools/cythonize.py", line 231, in process
    processor_function(fromfile, tofile, cwd=path)
  File "/Users/rlucas/scipy-dev/scipy/tools/cythonize.py", line 96, in process_pyx
    raise Exception('Cython failed')
Exception: Cython failed
Cythonizing sources
Traceback (most recent call last):
  File "setup.py", line 540, in <module>
    setup_package()
  File "setup.py", line 524, in setup_package
    generate_cython()
  File "setup.py", line 292, in generate_cython
    raise RuntimeError("Running cythonize failed!")
RuntimeError: Running cythonize failed!

Build failed! (0:00:03.020187 elapsed)
(scipy-dev) Lucass-MacBook:scipy rlucas$ 
```
I only have a single `\` in the docstring in ` scipy/special/add_newdocs.py` but for some reason the doc build is inserting a second `\` into the docstring failing the build.

Comment (person142) [reply scipy/special/add_newdocs.py]: Ah, so that's because the `bdtri` docstring isn't a raw string-make the start of the string `r"""`.

File: scipy/special/_legacy.pxd (hunk 9 above)
Comment (person142) [reply scipy/special/_legacy.pxd]: Right, so the ufunc itself will handle dispatching to this signature, which means that by the time we hit this code we know that we are already in the case where `n` is a float, and that means we want to warn. So we don't need the conditional.

File: scipy/special/_legacy.pxd (hunk 10 above)
Comment (person142) [reply scipy/special/_legacy.pxd]: > which causes the tests in scipy/special/tests/test_nan_inputs.py to fail.

Ah yeah, that. I'd add an extra filter for deprecation warnings in that test, similar to what is done for `RuntimeWarning`. When I wrote those tests this situation hadn't arisen, so I didn't filter for it.

Comment (rlucas7) [reply scipy/special/_legacy.pxd]: Yeah, I'm just seeing your response to these now, I guess I might check ***before*** I do a push. I added an explicit
```
        with warnings.catch_warnings():
            warnings.simplefilter("ignore", DeprecationWarning)
```
in each of the spots where the deprecations are failing tests. Let me know if you have a better way of doing it, I couldn't seem to get the pytest context manager to suppress DeprecationWarnings but the warnings approach worked.

File: scipy/special/_legacy.pxd (hunk 9 above)
Comment (rlucas7) [reply scipy/special/_legacy.pxd]: Ok, sounds like were on the same page then, thanks.

**Comment by rlucas7** [comment]
ugh, I forgot to add the header
`#include <numpy/npy_math.h>`
for `npy_isnan()` in the `bdtr.c` causing the builds to fail. Pushing again even though not everything is finished, all the builds will fail without the header.

**Comment by rlucas7** [comment]
So I'm a bit unclear on if the header include is still needed in the bdtr.c file. It looks like the source of the error is that we're keeping `int n` and `npy_isnan(x)` expects `x` to be a `double`. So I removed the `npy_isnan(n)` in the if block but kept the others; `npy_isnan(k) || npy_isnan(p)`, see if that fixes the builds. 

What is weird is I am able to build locally across all these changes...

File: scipy/special/add_newdocs.py (hunk 11 above)
Comment (rlucas7) [reply scipy/special/add_newdocs.py]: ah. that fixed it, thanks! I recall reading about the distinction awhile back but I'll need to re-read the distinction here for sphinx.

**Comment by rlucas7** [comment]
> So I'm a bit unclear on if the header include is still needed in the bdtr.c file. 

This one still not clear to me but I've left the include in the file.
I made `bdtri()` docstring 'raw' and I've removed the warnings import and filters in favor of context managers for the specific deprecation warnings within the tests using `suppress_warnings()` context managers similar to how the rest of the project uses these. Hoping this will enable builds (and unit tests) to pass.

**Comment by rlucas7** [comment]
>Hoping this will enable builds (and unit tests) to pass.

Looks like everything except 3 tests when `n` is `NaN` are passing in the builds and tests.
These tests are failing now because the `n` is `int` type in the signature and `npy_isnan()` only takes `double`s. The workaround-I think-is to put a check for `NaN` type into the Cython code similar to how it was previously except now we throw the `DeprecationWarning` and then check if `n` is `nan` and return `nan`. We'll see if that fixes, everything passes locally for me, so it is a bit difficult to determine these failures without pushing and running CI.

**Comment by rlucas7** [comment]
So looks like everything passes except the np.nan input for n argument in the nan tests. I tried a couple things last night that I thought would work, they don’t appear to fix. After looking over this again today, still I’m not clear why the nan for n argument is not being caught and handled here.

 @person142 would you be able to take a look?

 I’m thinking you’d be able to pick up the root cause here, I’m out of ideas.

**Comment by rlucas7** [comment]
The only fail here is travis. The two travis builds that fail are for issues unrelated to the changes. 

One fail is a networking issue, travis is unable to connect to instantiate containers, or at least that is what it seems like from this log:
https://travis-ci.org/scipy/scipy/jobs/627547516#L488
other failure occured when generating the build script, seems like also an inability to connect to container registry but hard to say because the log is 1 line and very cryptic message:
https://travis-ci.org/scipy/scipy/jobs/627547524#L1

At this point I think this PR is good, @person142 if you could take another look when you've got time would be very helpful. 
I haven't made any changes in terms of warnings/errors being thrown in `stats.binom` I'd assume those would go in a separate PR. 
This PR contains changes isolated to `special.bdtr`, `special.bdtri`, and  `special.bdtrc`.

**Review by person142 — APPROVED** [review]
LGTM. I restarted Travis to see if it works this time; ping me if its green and I'll merge.

**Comment by rlucas7** [comment]
> LGTM. I restarted Travis to see if it works this time; ping me if its green and I'll merge.

@person142 thanks for taking another look. 
The travis builds finished, all green ***except*** the second build which fails on bootstrap:
https://travis-ci.org/scipy/scipy/jobs/627547516#L488
nothing to do w/the changes in this PR. 
I think the previous build failures were the same reason but on a different build of the 7 so not sure if you're ok with merging as is or want to retry the build once more? 

These travis fails on setup seem to be somewhat regular in my last few PRs.

**Comment by person142** [comment]
Hm this failure actually seems real:

https://travis-ci.org/scipy/scipy/jobs/627547516?utm_medium=notification&utm_source=github_status

**Comment by rlucas7** [comment]
> Hm this failure actually seems real:
> 
> https://travis-ci.org/scipy/scipy/jobs/627547516?utm_medium=notification&utm_source=github_status

Hmm, you're right. Looks like the `bdtr` test fail is from a recent commit from Warren:
https://github.com/scipy/scipy/commit/6dbfe3406e7542ef6b497d6dcafbd72aa4647d19#diff-9456f9c319b4b0c2dc0e9218fffe8c76
is Warren's commit and that causes both travis failures:
https://travis-ci.org/scipy/scipy/jobs/627547516#L18276
https://travis-ci.org/scipy/scipy/jobs/627547516#L18283
a rebase off master should fix these. I'll do that and see if that fixes the travis builds.

**Comment by rlucas7** [comment]
A few more failures which are spurious:

https://dev.azure.com/scipy-org/SciPy/_build/results?buildId=4427&view=logs&j=dca3794b-c3dc-52e6-709a-3545ea017448&t=42f16a10-8379-5482-623d-4749ae3e519a&l=1467

these all appear to come from the linear program routines tests that fail (or krylov) from a change in behavior of acceptable precision in `assert_array_almost_equal`, not sure if this is a config change we made or a result of swapping out the numpy campatibility stuff for a direct use of numpy. Either way the aren't related to my changes. The 1 travis build that failed (the last one) is:

https://travis-ci.org/scipy/scipy/jobs/630660383?utm_medium=notification&utm_source=github_status
there isn't much to go on there, the build script wasn't generated it seems so the build failed automatically. I'll close and reopen the PR to trigger another build and see if the travis builds all pass (fingers crossed).

**Comment by rlucas7** [comment]
After the restart from close and reopen the (last) travis build still fails:

https://travis-ci.org/scipy/scipy/jobs/630689560?utm_medium=notification&utm_source=github_status

The good news is the failure is reproducible, the bad news is because the build failure script fails to generate-and there is only a 1 line entry in the log-I don't really have any idea what the issue is, if it has anything to do with my changes or something else, e.g. perhaps travis setup/configuration related.

**Comment by tylerjereddy** [comment]
Yeah, just ignore that `ppc64le` Travis failure---it is affecting NumPy & SciPy now & not related to your changes.

**Comment by person142** [comment]
Since failures are unrelated, let's merge this.

**Comment by person142** [comment]
Thanks for sticking with this @rlucas7.

**Comment by rlucas7** [comment]
Thanks @person142 for merge and @tylerjereddy for clarifying status of `ppc64le` build fail.
I wrote a note in the wiki for 1.5.0 release on the deprecation for integer `n` in `bdtr` etc:
https://github.com/scipy/scipy/wiki/*Release-note-entries-for-SciPy-1.5.0*#scipyspecial-changes

**Comment by mdhaber** [comment]
Thanks @rlucas7! If you'd like your name added to [THANKS.txt](https://github.com/scipy/scipy/blob/master/THANKS.txt), please make an entry [here](https://github.com/scipy/scipy/wiki/*THANKS.txt-additions-modifications-for-1.5.0*).

**Comment by rlucas7** [comment]
@mdhaber thanks for reminding me
