### PR TITLE
MAINT: Update vendored pypocketfft version

### LINKED ISSUE #11322: scipy build fails in AIX
Scipy 1.3.X used to compile and work in AIX. 
The recent version 1.4.X fails to compile. The compilation error occurs within the newly added code (pocketfft).

Below are the logs. 
```
  g++: scipy/fft/_pocketfft/pypocketfft.cxx
  In file included from scipy/fft/_pocketfft/pypocketfft.cxx:19:0:
  scipy/fft/_pocketfft/pocketfft_hdronly.h: In static member function 'static size_t pocketfft::detail::util::thread_count(size_t, const shape_t&, size_t, size_t)':
  scipy/fft/_pocketfft/pocketfft_hdronly.h:712:7: **error: reference to 'thread' is ambiguous**
         thread::hardware_concurrency() : nthreads;
         ^~~~~~
  In file included from /usr/include/sys/ptrace.h:28:0,
                   from /usr/include/sys/proc.h:42,
                   from /usr/include/sys/pri.h:43,
                   from /usr/include/sys/sched.h:38,
                   from /usr/include/sched.h:51,
                   from /usr/include/pthread.h:63,
                   from /opt/freeware/include/python3.7m/pythread.h:114,
                   from /opt/freeware/include/python3.7m/pystate.h:11,
                   from /opt/freeware/include/python3.7m/traceback.h:8,
                   from /opt/freeware/include/python3.7m/Python.h:119,
                   from /opt/freeware/include/python3.7m/pybind11/detail/common.h:112,
                   from /opt/freeware/include/python3.7m/pybind11/pytypes.h:12,
                   from /opt/freeware/include/python3.7m/pybind11/cast.h:13,
                   from /opt/freeware/include/python3.7m/pybind11/attr.h:13,
                   from /opt/freeware/include/python3.7m/pybind11/pybind11.h:44,
                   from scipy/fft/_pocketfft/pypocketfft.cxx:15:
  **/usr/include/sys/thread.h:105:8: note: candidates are: struct thread**
   struct thread {
          ^~~~~~
  In file included from scipy/fft/_pocketfft/pocketfft_hdronly.h:69:0,
                   from scipy/fft/_pocketfft/pypocketfft.cxx:19:
  **/opt/freeware/lib/gcc/powerpc-ibm-aix7.1.0.0/6.3.0/include/c++/thread:61:9: note:                 class std::thread**
     class thread
           ^~~~~~
  In file included from scipy/fft/_pocketfft/pypocketfft.cxx:19:0:
  scipy/fft/_pocketfft/pocketfft_hdronly.h: At global scope:
  scipy/fft/_pocketfft/pocketfft_hdronly.h:734:43: error: reference to 'thread' is ambiguous
   static const size_t max_threads = max(1u, thread::hardware_concurrency());
```

Seems like there is a collision with the "thread" keyword.

### PR DESCRIPTION
**Pull request by peterbell10**
#### Reference issue
Closes gh-11322

#### What does this implement/fix?
This updates the `pypocketfft` version to include [pypocketfft!31](https://gitlab.mpcdf.mpg.de/mtr/pypocketfft/merge_requests/31) which fixes the `thread` name collisions on AIX and hopefully all future collisions by removing uses of
```cpp
using namespace std;
```
from Martin's code.

#### Additional information
~I believe this update also includes a reduction of the FFT twiddle factor array size from O(N) to O(sqrt(N)) which should reduce the transform cache's memory footprint.~

### CODE REVIEW

**Review by larsoner — APPROVED** [review]

**Comment by larsoner** [comment]
Looks good except the Travis error, which appears legitimate
```
scipy/fft/_pocketfft/pocketfft_hdronly.h:3202:45: error: non-const reference cannot bind to vector element
7670                in[it.iofs(j,ii)].SplitConj(tdatav[i][j], tdatav[i+1][j]);
7671                                            ^~~~~~~~~~~~
```

https://travis-ci.org/scipy/scipy/jobs/634260582#L7669

File: scipy/fft/_pocketfft/pocketfft_hdronly.h [hunk 1]
```diff
@@ -105,7 +110,7 @@ constexpr bool FORWARD  = true,
 #if defined(__INTEL_COMPILER)
 // do nothing. This is necessary because this compiler also sets __GNUC__.
 #elif defined(__clang__)
-#if __clang__>=5
+#if __clang_major__>=5
```
Comment (peterbell10) [inline scipy/fft/_pocketfft/pocketfft_hdronly.h]: cc @mreineck this is broken on AppleClang since it gives the XCode version here instead of the base clang version.

Comment (mreineck) [reply scipy/fft/_pocketfft/pocketfft_hdronly.h]: This is a problem, because I noticed that the original version was broken everywhere else ...
On Linux with clang++ 9, `__clang__` is defined as 1 and `__clang_major__` is 9.
Do we need another level of `#ifdef`s here?

Comment (peterbell10) [reply scipy/fft/_pocketfft/pocketfft_hdronly.h]: I think you can just guard it with `#ifdef __APPLE__`. 

According to [wikipedia](https://en.wikipedia.org/wiki/Xcode#Toolchain_versions) clang 5 corresponds to Xcode 9.3 and above. So, it would be 
```cpp
#ifdef __APPLE__
#  if (__clang_major__ > 9) || (__clang_major__ == 9 && __clang_minor__ >= 3) 
#     undef POCKETFFT_NO_VECTORS
#  endif
#elif __clang_major__ >= 5
#  undef POCKETFFT_NO_VECTORS
#endif
```

**Comment by mreineck** [comment]
> I believe this update also includes a reduction of the FFT twiddle factor array size from O(N) to O(sqrt(N)) which should reduce the transform cache's memory footprint.

Unfortunately no. The change only affects the plan building stage itself, not the final plan size. Reducing the plan object itself to O(sqrt(n)) size would reduce performance noticeably, so I was reluctant to do that.

File: scipy/fft/_pocketfft/pocketfft_hdronly.h (hunk 1 above)
Comment (mreineck) [reply scipy/fft/_pocketfft/pocketfft_hdronly.h]: This is fine! I'll apply this patch upstream, once CI passes.

**Comment by peterbell10** [comment]
Ah okay, I missed that distinction.

**Comment by pv** [comment]
The remaining issue addressed, so merging, thanks.
