### PR TITLE
BUG: Include `int64_t` declaration to `rectangular_lsap.cpp`

### LINKED ISSUE #11319: Missing `int64_t` declaration in rectangular_lsap.cpp
I was trying to install scipy for several hours in `python:3.7-alpine` image. Unfortunately it doesn't build for me. Thought it was a problem with dependencies, tried multiple configurations, but then checked the code that's actually failing and found an issue.

#### Steps to reproduce:

Create `dummy.dockerfile` with following content:

```
FROM python:3.7-alpine
RUN apk add --no-cache build-base openblas-dev lapack-dev
RUN pip install scipy==1.4.1
```

and run:

```
docker build -t dummy -f dummy.dockerfile .
```

#### Error message:

```
creating build/temp.linux-x86_64-3.7/scipy/optimize/rectangular_lsap
  compile options: '-I/tmp/pip-build-env-psdpbyuc/overlay/lib/python3.7/site-packages/numpy/core/include -c'
  g++: scipy/optimize/rectangular_lsap/rectangular_lsap.cpp
  Running from scipy source directory.
  /tmp/pip-build-env-psdpbyuc/overlay/lib/python3.7/site-packages/numpy/distutils/system_info.py:716: UserWarning: Specified path /usr/include/python3.7m is invalid.
    return self.get_paths(self.section, key)
  scipy/optimize/rectangular_lsap/rectangular_lsap.cpp:117:43: error: 'int64_t' has not been declared
    117 | solve(int nr, int nc, double* input_cost, int64_t* output_col4row)
        |                                           ^~~~~~~
  scipy/optimize/rectangular_lsap/rectangular_lsap.cpp:186:41: error: 'int64_t' has not been declared
    186 |                                         int64_t* col4row)
        |                                         ^~~~~~~
  scipy/optimize/rectangular_lsap/rectangular_lsap.cpp:117:43: error: 'int64_t' has not been declared
    117 | solve(int nr, int nc, double* input_cost, int64_t* output_col4row)
        |                                           ^~~~~~~
  scipy/optimize/rectangular_lsap/rectangular_lsap.cpp:186:41: error: 'int64_t' has not been declared
    186 |                                         int64_t* col4row)
        |                                         ^~~~~~~
  error: Command "g++ -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/tmp/pip-build-env-psdpbyuc/overlay/lib/python3.7/site-packages/numpy/core/include -c scipy/optimize/rectangular_lsap/rectangular_lsap.cpp -o build/temp.linux-x86_64-3.7/scipy/optimize/rectangular_lsap/rectangular_lsap.o -MMD -MF build/temp.linux-x86_64-3.7/scipy/optimize/rectangular_lsap/rectangular_lsap.o.d" failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for scipy
```

#### Scipy/Numpy/Python version information:

```
scipy==1.4.1
```

#### My findings:

I was digging a bit through the code and found that `int64_t` declaration is truly missing in the [`rectangular_lsap.cpp`](https://github.com/scipy/scipy/blob/master/scipy/optimize/rectangular_lsap/rectangular_lsap.cpp) file. A line with

```
#include <cstdint>
```

should be added.

EDIT: @peterbell10 suggested that it may be better to

```
#include "rectangular_lsap.h"
```

### PR DESCRIPTION
**Pull request by gmrukwa**
There was missing declaration of `int64_t` in the file,
causing the extension build failure.

#### Reference issue
Closes #11319

#### What does this implement/fix?
Missing declaration of `int64_t` in `rectangular_lsap.cpp`.

### CODE REVIEW

File: scipy/optimize/rectangular_lsap/rectangular_lsap.cpp [hunk 1]
```diff
@@ -42,6 +42,7 @@ Author: PM Larsen
 
 #include <algorithm>
 #include <cmath>
+#include <cstdint>
```
Comment (peterbell10) [inline scipy/optimize/rectangular_lsap/rectangular_lsap.cpp]: Looks like `<cstdint>` is failing the build as it's C++11 only. You could change the config to build with C++11 but it's probably easier to just change the include. 
```suggestion
#include "rectangular_lsap.h"
```

Comment (gmrukwa) [reply scipy/optimize/rectangular_lsap/rectangular_lsap.cpp]: Good point, thanks! :)

**Comment by pv** [comment]
thanks, merged

**Comment by pensapav** [comment]
This prevents 1.4.1 from building on Alpine (for lightweight docker images).  Any possibility of getting it fixed in a 1.4.X release sooner than a minor version bump to 1.5?

**Comment by tylerjereddy** [comment]
I've labelled it as a backport-candidate. The release process is volunteer-driven so it may still be a while, but I suspect a `1.4.2` will happen before `1.5.0` as things accumulate. I'll see what I can do :)

**Comment by rwolst** [comment]
I have the same issue trying to build in Alpine. Note however that they have a prebuilt package for 1.4.1 [here](https://pkgs.alpinelinux.org/packages?name=py3-scipy&branch=edge). I will use this for the moment until the next release.

**Comment by philgoetz** [comment]
> thanks, merged

I may be doing something dumb, but I still see no declaration of int64_t in rectangular_lsap.cpp (https://github.com/scipy/scipy/blob/master/scipy/optimize/rectangular_lsap/rectangular_lsap.cpp)

**Comment by ewmoore** [comment]
@philgoetz, stdint.h is included in rectangular_lsap.h.

**Comment by frol** [comment]
Would you consider backporting the patch to 1.4.x?

**Comment by tylerjereddy** [comment]
> Would you consider backporting the patch to 1.4.x?

There's a backport label on the PR. Our release infrastructure is in a bit of a state of flux because we're migrating from rackspace to anaconda.org for some hosting. That's my current excuse anyway.

If I have to backport the migration stuff to 1.4.x so that I avoid using rackspace resources that could lead to more entropy/maintenance burden.

I probably should finish up the migration as soon as I can..
