### PR TITLE
BUG: special: fix `stdtr` and `stdtrit` for infinite df

### LINKED ISSUE #14777: BUG: Wrong limit and no warning in stats.t for df=np.inf
### Describe your issue.

Scipy's stats module for Student's t distribution does not have the correct limit of a Gaussian distribution if the degree-of-freedom (`df`) parameter is set to `np.inf`. Most importantly, Scipy does not print a warning nor does it raise an error, instead it simply yields a completely wrong result.

While I think it would make sense to branch for `df=np.inf`, it certainly does not make sense to let the user plug in values that produce bogus results.

### Reproducing Code Example

```python
In [1]: import numpy as np

In [2]: from scipy.stats import norm as stats_norm

In [3]: from scipy.stats import t as stats_t

In [4]: stats_t.sf(loc=3., df=99999., x=2., scale=1.)
Out[4]: 0.8413435362058463

In [5]: stats_t.sf(loc=3., df=np.inf, x=2., scale=1.)
Out[5]: 0.5
```

### Error message

```shell
None
```

### SciPy/NumPy/Python version information

1.7.1 1.21.2 sys.version_info(major=3, minor=9, micro=7, releaselevel='final', serial=0)

### PR DESCRIPTION
**Pull request by tirthasheshpatel**
#### Reference issue

Partially addresses gh-14777
Supersedes gh-14781

#### What does this implement/fix?

`stdtr` and `stdtrit` returned wrong results when infinite df was given.
This behavior has been fixed by branching to `ndtr` and `ndtri` respectively.
Tests comparing the result with R's `pt` and `qt` have also been added.

#### Additional information

This should fix the `cdf`, `ppf`, and `isf` methods of the t distribution. In a follow-up, I will fix `pdf`, `stats`, and `moment` which should close gh-14777

### CODE REVIEW

**Review by mdhaber — APPROVED** [review]
Tests look good and code changes look reasonable, although I'm not familiar with the C code. Just going to confirm the output of R myself and test the `t` distribution functions. Maybe someone from `special` should take a quick look to make sure the C looks good. Also, do we need a new file for just these tests?
Test failures look like they're in master (see gh-15251, too).

File: scipy/special/cdf_wrappers.c [hunk 1]
```diff
@@ -8,6 +8,7 @@
  */
 
 #include "cdf_wrappers.h"
+#include "cephes.h"
```
Comment (tirthasheshpatel) [inline scipy/special/cdf_wrappers.c:11]: `cdflib` also has a `stdtr` and `stdtri` implementation but SciPy uses the cephes `implementation` so prefer it instead.

Comment (rgommers) [reply scipy/special/cdf_wrappers.c:11]: Cephes is already linked for the extensions where `cdf_wrappers.c` is used in `setup.py`, so this seems fine to me.

Comment (tirthasheshpatel) [reply scipy/special/cdf_wrappers.c:11]: Thanks for taking a look. I think this PR is ready from my side!

Comment (rgommers) [reply scipy/special/cdf_wrappers.c:11]: CI is very unhappy, can you rebase so we pick up the fixes in master?

Comment (tirthasheshpatel) [reply scipy/special/cdf_wrappers.c:11]: Done.

**Comment by rgommers** [comment]
Hmm, this is now failing on 32-bit Linux with clear problems due to `setuptools >= 60.0` and the changes in gh-15268

```
...
Remainder of file ignored
Error processing line 1 of /usr/local/lib/python3.8/dist-packages/distutils-precedence.pth:

  Traceback (most recent call last):
    File "/usr/lib/python3.8/site.py", line 175, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  AttributeError: module '_distutils_hack' has no attribute 'ensure_shim'

Remainder of file ignored
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
RuntimeErrorRuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
: module compiled against API version 0xe but this version of numpy is 0xd
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
...
```
You can ignore that here. Other CI results look fine.

**Comment by rgommers** [comment]
> Just going to confirm the output of R myself and test the `t` distribution functions.

Did you still want to do this @mdhaber?

File: scipy/special/tests/test_cdft_asymptotic.py [hunk 2]
```diff
@@ -0,0 +1,49 @@
...
+    t = 1.
+    res = stdtr(df, t)
+    # R Code:
+    #   options(digits=20)
+    #   pt(1., c(1e10, 1e12, 1e120, Inf))
+    res_R = [0.84134474605644460343,
+             0.84134474606842180044,
+             0.84134474606854281475,
+             0.84134474606854292578]
+    assert_allclose(res, res_R, rtol=1e-15)
```
Comment (mdhaber) [inline scipy/special/tests/test_cdft_asymptotic.py:20]:
```suggestion
    assert_allclose(res, res_R, rtol=2e-15)
```
As Ralf mentioned, on 32-bit Ubuntu CI:
```
___________________________ test_stdtr_vs_R_large_df ___________________________
[gw1] linux -- Python 3.8.0 /usr/bin/python3.8
scipy/special/tests/test_cdft_asymptotic.py:20: in test_stdtr_vs_R_large_df
    assert_allclose(res, res_R, rtol=1e-15)
E   AssertionError: 
E   Not equal to tolerance rtol=1e-15, atol=0
E   
E   Mismatch: 25%
E   Max absolute difference: 8.8817842e-16
E   Max relative difference: 1.05566526e-15
E    x: array([0.841345, 0.841345, 0.841345, 0.841345])
E    y: array([0.841345, 0.841345, 0.841345, 0.841345])
        df         = [10000000000.0, 1000000000000.0, 1e+120, inf]
        res        = array([0.84134475, 0.84134475, 0.84134475, 0.84134475])
        res_R      = [0.8413447460564446, 0.8413447460684218, 0.8413447460685428, 0.8413447460685429]
        t          = 1.0
- generated xml file: /scipy/build/testenv/lib/python3.8/site-packages/junit/test-results.xml -
=========================== short test summary info ============================
```

**Comment by mdhaber** [comment]
Confirmed the output of R and tested `scipy.stats.t`. All looks good!
Just need to adjust the tolerance for the 32-bit build, and hopefully the refguide failure is intermittent and will fix itself.
@tirthasheshpatel LMK when it's all passing and I'll merge.

File: scipy/special/tests/test_cdft_asymptotic.py (hunk 2 above)
Comment (tirthasheshpatel) [reply scipy/special/tests/test_cdft_asymptotic.py]: Thanks!

**Comment by mdhaber** [comment]
Just the usual timeout. Thanks @tirthasheshpatel @rgommers!
