### PR TITLE
BUG: special: Fix formula for division of dual numbers in xsf

### LINKED ISSUE #21665: BUG: special: autodifferentiation of division operator
### Describe your issue.

In gh-21568, we found that the implementation of `dual &operator/=(const dual &other)` may not be quite right. I thought we should open this so it's not forgotten. 
@izaid can you fix this, and @steppi can review?
In any case, we should add a test and a reference so it doesn't come up again.

### PR DESCRIPTION
**Pull request by steppi**
#### Reference issue

Closes #21665 

#### What does this implement/fix?

This PR fixes the definition of division of dual numbers in xsf. There were some typos in this definition in #21483 that weren't caught because division of dual numbers is not used in that PR.

@izaid took the definition from the 2023 master's thesis of Songchen Tan, [Higher-Order Automatic Differentiation and its Applications](https://dspace.mit.edu/bitstream/handle/1721.1/151501/tan-songchen-csesm-ccse-2023-thesis%20Songchen%20Tan.pdf?sequence=1&isAllowed=y). The relevant formula is in item (2.9) in section 2.3.2 and is pasted below:

image

In #21483, this implemented as

```C++
dual &operator/=(const dual &other) {
        for (size_t i = 0; i <= Order; ++i) {
            T coef = 1; // binomial coefficient
            for (size_t j = 1; j <= i; ++j) {
                data[i] -= coef * other.data[j] * data[i - j];
                coef *= T(i - j) / T(j + 1);
            }

            data[i] /= other.data[0];
        }
```

One can see that: 

* In iteration $(i, j)$:`coef` contains the value ${i - 1 \choose j}$
* The outer loop is over $1 \leq i \leq \mathrm{Order}$
* For each `i` the inner loop is over $1 \leq j \leq i$.
*  The case `i = 0` is skipped because `j` starts at 1, so the loop condition `j <= i` never holds. 
* `other.data[j]` contains the value of $g^{(j)}$ for each $j$
* `data[i]` initially contains the value of $f^{(i)}$ for each `i`,and the intention is that `data[i]` is updated to contain the value of $\left(\frac{f}{g}\right)^{(i)}$ as we step through the loop.

Putting this all together, we see that the formula which has actually been implemented is

$$\left(\frac{f}{g}\right)^{(n)} = \frac{1}{g}\left[f^{(n)} - \sum_{k=1}^{n}{n - 1 \choose k} g^{(k)}\left(\frac{f}{g}\right)^{\left(n - k\right)}\right]$$

Comparing to the formula above, we see that `other.data` and `data` have been switched, and there's an off by one in the indices. 

In #21568, I replaced the `coef` which is computed on the fly directly with `binom(i, j)`, which itself was incorrect, due to not fixing the off by one error in the indices. I also didn't notice that `data` and `other.data` were swapped.

I've updated things here so that the formula matches the reference.

#### Additional information

I haven't added a test case because it would require creating a new ufunc just for testing purposes. I think it's fine to test this when we get around to adding derivatives for a special function which uses division internally.

cc @mdhaber

### CODE REVIEW

**Comment by izaid** [comment]
Ok, so let me state what I actually did. I didn't take the definition from Tan, but I did use that as a reference later.

I first started with what Boost uses, as per [here](https://live.boost.org/doc/libs/1_83_0/libs/math/doc/differentiation/autodiff.pdf). That doesn't have the binomial-type coefficient we have, you still need to multiply by a value when you extract the derivatives. It DOES have f and g, also known as `data` and `other.data`, as I originally had them.

Screenshot 2024-10-15 at 4 42 56 PM

At some point, before the original PR went in, I think I traced through things to work out what the coefficients were. At that point I saw the Tan definition above.

Note I'm not saying I didn't make a mistake, and if you can find one please correct it! But we need to be a bit careful with things.

**Comment by steppi** [comment]
@izaid, OK I think it's plausible that Tan's formula and the one you've given are equivalent then. I don't really have time to investigate. Do you think Tan's formula might be incorrect though? I'm pretty sure what I have here accurately implements Tan's formula. If you don't want to look into it now, we can just revisit when dual division is actually used.

**Comment by izaid** [comment]
> @izaid, OK I think it's plausible that Tan's formula and the one you've given are equivalent then. I don't really have time to investigate. Do you think Tan's formula might be incorrect though? I'm pretty sure what I have here accurately implements Tan's formula. If you don't want to look into it now, we can just revisit when dual division is actually used.

Honestly I could go either way. I think I was just concerned because the dual stuff was quite hard to get right and we weren't changing it carefully.

I think we should it revert it to what I had originally and revisit this with proper testing. No one has actually shown it was wrong in the first place. If someone can show that, of course we should fix it!

**Comment by steppi** [comment]
> Honestly I could go either way. I think I was just concerned because the dual stuff was quite hard to get right and we weren't changing it carefully.
> 
> I think we should it revert it to what I had originally and revisit this with proper testing. No one has actually shown it was wrong in the first place. If someone can show that, of course we should fix it!

OK, the minimal diff in this case is to change

```C++
    dual &operator/=(const dual &other) {
        for (size_t i = 0; i <= Order; ++i) {
            // General Leibniz Rule
            for (size_t j = 1; j <= i; ++j) {
                data[i] -= detail::fast_binom<T>(i, j) * other.data[j] * data[i - j];
            }
```

to

```C++
 dual &operator/=(const dual &other) {
        for (size_t i = 0; i <= Order; ++i) {
            // General Leibniz Rule
            for (size_t j = 1; j <= i; ++j) {
                data[i] -= detail::fast_binom<T>(i - 1, j) * other.data[j] * data[i - j];
            }
```

I'd rather not go back to computing binomial coefficients on the fly. If you want to make this change, I'll approve it and merge.

**Comment by izaid** [comment]
> > Honestly I could go either way. I think I was just concerned because the dual stuff was quite hard to get right and we weren't changing it carefully.
> > I think we should it revert it to what I had originally and revisit this with proper testing. No one has actually shown it was wrong in the first place. If someone can show that, of course we should fix it!
> 
> OK, the minimal diff in this case is to change
> 
> ```c++
>     dual &operator/=(const dual &other) {
>         for (size_t i = 0; i <= Order; ++i) {
>             // General Leibniz Rule
>             for (size_t j = 1; j <= i; ++j) {
>                 data[i] -= detail::fast_binom<T>(i, j) * other.data[j] * data[i - j];
>             }
> ```
> 
> to
> 
> ```c++
>  dual &operator/=(const dual &other) {
>         for (size_t i = 0; i <= Order; ++i) {
>             // General Leibniz Rule
>             for (size_t j = 1; j <= i; ++j) {
>                 data[i] -= detail::fast_binom<T>(i - 1, j) * other.data[j] * data[i - j];
>             }
> ```
> 
> I'd rather not go back to computing binomial coefficients on the fly. If you want to make this change, I'll approve it and merge.

Happy with this, or if you think something else is better also happy with that.

File: scipy/special/xsf/dual.h [hunk 1]
```diff
@@ -120,9 +120,8 @@ class dual<T, Order> {
 
     dual &operator/=(const dual &other) {
         for (size_t i = 0; i <= Order; ++i) {
-            // General Leibniz Rule
-            for (size_t j = 1; j <= i; ++j) {
-                data[i] -= detail::fast_binom<T>(i, j) * other.data[j] * data[i - j];
+            for (size_t j = 0; j < i; ++j) {
+                data[i] -= detail::fast_binom<T>(i, j) * data[j] * other.data[i - j];
```
Comment (mdhaber) [inline scipy/special/xsf/dual.h:124]:
```suggestion
            for (size_t j = 1; j <= i; ++j) {
                data[i] -= detail::fast_binom<T>(i - 1, j) * other.data[j] * data[i - j];
```

File: scipy/special/xsf/dual.h [hunk 2]
```diff
@@ -250,9 +249,8 @@ class dual<T, Order0, Order1, Orders...> {
 
     dual &operator/=(const dual &other) {
         for (size_t i = 0; i <= Order0; ++i) {
-            // General Leibniz Rule
-            for (size_t j = 1; j <= i; ++j) {
-                data[i] -= detail::fast_binom<T>(i, j) * other.data[j] * data[i - j];
+            for (size_t j = 0; j < i; ++j) {
+                data[i] -= detail::fast_binom<T>(i, j) * data[j] * other.data[i - j];
```
Comment (mdhaber) [inline scipy/special/xsf/dual.h:253]:
```suggestion
            for (size_t j = 1; j <= i; ++j) {
                data[i] -= detail::fast_binom<T>(i - 1, j) * other.data[j] * data[i - j];
```

**Comment by steppi** [comment]
Thanks @mdhaber. Feel free to merge if there are no CI issues.
