### PR TITLE
ENH: Translate complex valued hyp2f1 to C++ and make improvements

### LINKED ISSUE #8083: special.hyp2f1 returns the wrong values when c-a-b is an integer (for 0.9<|z|<1.0)
The hypergeometric function hyp2f1(a,b,c,z) gets the wrong values when c-a-b=integer and z is in the region of the complex plane given by:

0.9<|z|<1.0 and real(z)>0

The source code for hyp2f1 can definitely handle the case of integer differences between the a,b,c parameters, but in this case the code doesn't correctly calculate the integer corresponding to c-a-b.
Specifically, this bug is caused by a couple of lines in specfun.f in which the integer is determined by the expression
```
M=INT(C-A-B)
```
For some values of a,b,c this might be 3.9999 which gets cast to the integer *3* instead of *4*.  Using a conversion of the form 
```
M=INT(C-A-B+EPS*DSIGN(1.0D0,C-A-B))
```
where EPS is a small value like 1e-8 or 1e-15 should fix this issue (this is at least what specfun.f does elsewhere in HYGFZ when determining an integer from real values). 

### Reproducing code example:
```
>>> import numpy as np
>>> from scipy.special import hyp2f1 
>>> import mpmath
>>> a=1.45
>>> b=0.6
>>> c=6.05
>>> c-a-b
3.9999999999999996
>>> z=0.9*np.exp(1.j*(-0.2*np.pi))
>>> hyp2f1(a,b,c,z)
(5.670408102465732-0.76807186486958579j)
>>> mpmath.hyp2f1(a,b,c,z)
mpc(real='1.1053555735636691', imag='-0.11840327506397474')
```
In the above test case, HYGFZ is using *3* instead of *4* for c-a-b which is why it gets the wrong answer as compared with mpmath.

### Scipy/Numpy/Python version information:
```
>>> print scipy.__version__,np.__version__,sys.version_info
1.0.0.dev0+b579459 1.13.1 sys.version_info(major=2, minor=7, micro=12, releaselevel='final', serial=0)
```

### PR DESCRIPTION
**Pull request by steppi**
#### Reference issue

Closes #8083

#### What does this implement/fix?

This PR translates `hyp2f1` into CUDA compatible C++, including both the parts from written in Cython in `hyp2f1.pxd` and the parts written in Fortran in `specfun.f`. Improvements have been made by 

- Choosing better domains for using the different linear transformations as suggested by @FormerPhysicist in #8151 (though I've not used the same domains he used).
- Using tolerance `EPS = 1e-15 throughout` and increasing the maximum number of iterations. (Zhang and Jin used a lower tolerance of `EPS = 1e-8` for cases their implementation could not handle well. The improvements made here make this unnecessary.
- Fix the case where `a - b` is an integer and the smaller of `c - a` or `c - b` is a positive integer. A different limiting formula is needed in this case due to a singularity in a digamma function appearing in the terms of a series.

#### Additional information

Here is a table comparing percentiles for relative error in this PR and main over 3,003,855 test cases generated by the script https://github.com/scipy/scipy/blob/main/scipy/special/_precompute/hyp2f1_data.py, using default arguments, with the exception that parameter group 9 is excluded, and excluding cases where the true result is $\infty$ which both `main` and this PR branch get right in all cases. These tests were run with gcc 11.4 on Linux.

The improvement is substantial, although note that there are still some cases where the new implementation fails. Fixing these cases will require implementing argument reduction of `a`, `b`, and `c` using [Miller's Recurrence Algorithm](https://en.wikipedia.org/wiki/Miller%27s_recurrence_algorithm). 

| -         |        30% |         40% |          50%|         60% |         70% |         80% |         90% |        max |
|---------|--------------|--------------|--------------|--------------|--------------|--------------|--------------|--------------|
| main | 1.06e-15  | 3.70e-15 | 9.02e-13 | 8.02e-11 | 8.69e-10 | 5.20e-09 | 3.99e-08 | inf         |
| PR      | 5.25e-16 | 8.06e-16 | 1.27e-15 | 2.25e-15 | 5.19e-15 | 2.73e-14  | 2.81e-12  |2.02+44 |

Here's a breakdown of the highest percentiles.

| -|         91% |         92% |         93% |         94% |         95% |         96% |         97% |         98% |       99% |
|------------|-------------|-------------|-------------|-------------|-------------|-------------|-------------|-------------|-----------|
| main       | 5.94e-08 | 9.49e-08 | 1.72e-07 | 3.66e-07 | 9.61e-07 | 3.74e-06 | 3.27e-05 | 0.0016  | 15.74   |
| PR | 6.75e-12 | 1.83e-11 | 5.77e-11 | 2.23e-10  | 1.16e-09 | 9.40e-09 | 1.85e-07  | 2.47e-05 |  0.22 |

**Update**: I've rounded to two significant figures and cut out some of the percentiles in order to get the tables to fit properly. The results for the 10th and 20th percentiles are comparable between main and this PR. (slightly better for this PR).

The example `hyp2f1(1, 1, 4, 3 + 4j)` from https://github.com/scipy/scipy/issues/1561 is now computed accurately.

```python
from mpmath import mp
from scipy.special import hyp2f1

hyp2f1(1, 1, 4, 3 + 4j)
# (0.49234384000963594+0.6051340616612398j)

mp.hyp2f1(1, 1, 4, 3 + 4j)
# mpc(real='0.49234384000963544', imag='0.60513406166123973')
```
and has been added to the tests. This case was broken in Zhang and Jin because they did not account for the need to use a a different limiting formula in the case where both `a - b` is an integer and the smaller of `c - a` and `c - b` is a positive integer. The need for this was noted by @gertingold in https://github.com/scipy/scipy/issues/1561. I don't think this this is enough to close that issue, since other inaccuracies are mentioned there. Closing that will have to wait until argument reduction is implemented.

I have implemented series evaluators in `scipy/special/special/tools.h` which are used in this implementation. These evaluators take generators for the terms of a series as input, and using them has streamlined the implementation. I've confirmed that everything I've done here works on CuPy.

I'm pretty confident in the mathematical correctness due to the large set of test cases in https://github.com/scipy/scipy/blob/main/scipy/special/_precompute/hyp2f1_data.py, and the extreme care I've taken.

cc @izaid

### CODE REVIEW

**Comment by steppi** [comment]
Huh, those tables looked nice in the preview, but are unreadable in the actual post.

**Comment by lucascolley** [comment]
closing the 4th oldest issue - not bad 😉

**Comment by ilayn** [comment]
Things are finally coming together 😃

**Comment by steppi** [comment]
The failing test case is new to this PR and just needs a tolerance bump. It’s not a regression.

**Comment by steppi** [comment]
I've also translated the real valued `hyp2f1` from cephes into C++, which I can either add here, or do in a follow-up. I think that will need to go in before we can add `hyp2f1` to CuPy.

https://github.com/steppi/scipy/blob/hyp2f1_cephes/scipy/special/special/cephes/hyp2f1.h

File: scipy/special/special/tools.h [hunk 1]
```diff
@@ -0,0 +1,70 @@
...
+#pragma once
+
+#include "config.h"
+#include "error.h"
+
+namespace special {
+namespace detail {
+
+    // Series evaluators.
+    template <typename Generator, typename Number>
```
Comment (izaid) [inline scipy/special/special/tools.h:12]: Do we really need to worry about Number being non-floating point? I see you have this constexpr if below. Is there a use case for this?

File: scipy/special/special/tools.h [hunk 2]
```diff
@@ -0,0 +1,70 @@
...
+        for (std::uint64_t i = 0; i < max_terms; ++i) {
+            term = g();
+            result += term;
+            if (std::abs(term) < std::abs(result) * tol) {
+                return result;
+            }
+        }
+        // Exceeded max terms without converging. Return NaN.
+        set_error(func_name, SF_ERROR_NO_RESULT, NULL);
+        if constexpr (std::is_floating_point<Number>::value) {
```
Comment (izaid) [inline scipy/special/special/tools.h:42]: See above, I'm not sure why we need this.

File: scipy/special/special/tools.h (hunk 1 above)
Comment (izaid) [inline scipy/special/special/tools.h:12]: Instead of "Number", the typical template parameter here would be called "T"

File: scipy/special/special/tools.h (hunk 2 above)
Comment (steppi) [reply scipy/special/special/tools.h:42]: without this, this won't work for both real and complex values. We need to return $\text{NAN}$ in the first case and $\text{NAN} + \text{NAN}i$ in the latter.

File: scipy/special/special/tools.h [hunk 3]
```diff
@@ -0,0 +1,70 @@
...
+            return std::numeric_limits<Number>::quiet_NaN();
+        }
+        // If result type is not a floating point type, assume it is complex.
+        using FloatingType = typename Number::value_type;
+        return Number(std::numeric_limits<FloatingType>::quiet_NaN(), std::numeric_limits<FloatingType>::quiet_NaN());
```
Comment (izaid) [inline scipy/special/special/tools.h:47]: Ah, ok, so this is all to assign NaN to both the real and imaginary parts in the case of complex? In that case, I'd add a dummy function in `detail` called:
```
template <typename T>
std::enable_if_t<std::is_floating_point_v<T>, T> maybe_complex_NaN() { return quiet_NaN(); }

template <typename T>
std::enable_if_t<!std::is_floating_point_v<T>, T> maybe_complex_NaN() { return {quiet_NaN(), quiet_NaN()}; }
```

and call it like `maybe_complex_NaN<T>()`.

File: scipy/special/special/tools.h (hunk 1 above)
Comment (steppi) [reply scipy/special/special/tools.h:12]: We want this generic over both regular `floating point` and `complex`. The `constexpr` thing is just a cookbook recipe I found online for checking if its a real type or a complex type

Comment (izaid) [reply scipy/special/special/tools.h:12]: Yep! I think that make sense.

File: scipy/special/special/tools.h (hunk 2 above)
Comment (izaid) [reply scipy/special/special/tools.h:42]: Got it, see below.

**Comment by steppi** [comment]
@izaid, I think I've addressed everything. Thanks for the suggestions!

**Review by izaid — APPROVED** [review]

**Comment by izaid** [comment]
Thanks @steppi! Looks good to me.

**Comment by steppi** [comment]
> Thanks @steppi! Looks good to me.

Thanks @izaid!

File: scipy/special/special/hyp2f1.h [hunk 4]
```diff
@@ -0,0 +1,675 @@
...
+     * implementation [1] although there is very likely a better heuristic
+     * to determine when this transformation should be applied. As it
+     * stands, this hurts precision in some cases. */
+    if (z_abs < 0.9 && z.real() >= 0) {
+        if (c - a < a && c - b < b) {
+            result = std::pow(1.0 - z, c - a - b);
+            // Maximum number of terms 1500 comes from Zhang and Jin.
+            auto series_generator = detail::HypergeometricSeriesGenerator(c - a, c - b, c, z);
+            result *= detail::series_eval(series_generator, std::complex<double>{0.0, 0.0}, detail::hyp2f1_EPS,
+                                          detail::hyp2f1_MAXITER, "hyp2f1");
```
Comment (rlucas7) [inline scipy/special/special/hyp2f1.h:613]: @steppi IIUC the comment says `1500` is the max terms here but `detail::hyp2f1_MAXITER` is `3000`, did I miss something, or is one of the comment of the `max_iter` argument value misstated?

File: scipy/special/special/hyp2f1.h [hunk 5]
```diff
@@ -0,0 +1,675 @@
...
+#include "binom.h"
+#include "cephes/gamma.h"
+#include "cephes/lanczos.h"
+#include "cephes/poch.h"
+#include "digamma.h"
+
+namespace special {
+namespace detail {
+    constexpr double hyp2f1_EPS = 1e-15;
+    constexpr std::uint64_t hyp2f1_MAXITER = 3000;
```
Comment (rlucas7) [inline scipy/special/special/hyp2f1.h:55]: related to comment beneath here `detail::hyp2f1_MAXITER` is set to 3000

**Review by rlucas7 — COMMENTED** [review]
left one question b/c I'm not clear on if I'm interpreting the comment correctly

File: scipy/special/special/hyp2f1.h [hunk 6]
```diff
@@ -0,0 +1,675 @@
...
+     * -----------------------------------------------------------------------
+     * Apply Euler Hypergeometric Transformation (DLMF 15.8.1) to reduce
+     * size of a and b if possible. We follow Zhang and Jin's
+     * implementation [1] although there is very likely a better heuristic
+     * to determine when this transformation should be applied. As it
+     * stands, this hurts precision in some cases. */
+    if (z_abs < 0.9 && z.real() >= 0) {
+        if (c - a < a && c - b < b) {
+            result = std::pow(1.0 - z, c - a - b);
+            // Maximum number of terms 1500 comes from Zhang and Jin.
```
Comment (rlucas7) [inline scipy/special/special/hyp2f1.h:610]:
```suggestion
            // Maximum number of terms 1500 comes from Zhang and Jin. 
            // This wasn't enough for convergence in some test cases so 
            // we're using 3000 instead which seems to converge. 
```

Comment (rlucas7) [reply scipy/special/special/hyp2f1.h:610]: @steppi maybe this is a bit clearer comment? It's based on what I understood from our slack conversation so feel free to use

**Comment by steppi** [comment]
Thanks @rlucas7. Good catch. I'll update the comments.

File: scipy/special/special/hyp2f1.h (hunk 4 above)
Comment (rlucas7) [reply scipy/special/special/hyp2f1.h:619]: spoke on slack the comment was simply out of date from findings on refactor. Some cases weren't converging at 1500 even though the book indicated 1500 max_iter.

**Review by rlucas7 — APPROVED** [review]

**Comment by rlucas7** [comment]
@steppi it looks like there's one failing test. To me it seems unrelated, something to do with array_api compatibility. Can you confirm that's unrelated? If so I can merge. I'm not super familiar with the tests in that module though:

https://github.com/scipy/scipy/actions/runs/8616963915/job/23615829427?pr=20089#step:3:2989

**Comment by steppi** [comment]
@rlucas7. It’s unrelated. It’s failing everywhere.

**Comment by rlucas7** [comment]
> @rlucas7. It’s unrelated. It’s failing everywhere.

Ah yeah I see one now over here in an unrelated PR with a much smaller change surface. 

https://github.com/scipy/scipy/actions/runs/8623028347/job/23636209805?pr=20432#step:3:2986

I'll cancel the job and merge this PR. No sense wasting the resources to let the job run when we expect it to fail.

**Comment by rlucas7** [comment]
@steppi merged. Keep them coming

**Comment by steppi** [comment]
Awesome! Thanks @rlucas7!

**Comment by fancidev** [comment]
A small comment about `series_eval` for @steppi : instead of accepting a `Generator`,  have you considered accepting an `Iterator`? I come across this when writing the continued fraction evaluator for `iv_ratio`. 

Both Generator and Iterator will do the job, but Iterator has some benefits:
- Runs faster if the first term of the series is computed differently from the rest (though a strong enough compiler might unroll the first Generate call to achieve the same effect).
- Offers the possibility to visit the series in backward or random order (if needed).
- More flexible; e.g. readily works with a plain array of input.
- More C++ style and works more smoothly with the rest C++ infrastructure.

For the caller, making an Iterator requires about two more lines of code than making a Generator.

I’ll make a PR for `iv_ratio` with an example of an Iterator-based continued fraction evaluator as a proof of concept.

**Comment by steppi** [comment]
Thanks for the suggestions @fancidev.

> A small comment about `series_eval` for @steppi : instead of accepting a `Generator`, have you considered accepting an `Iterator`? I come across this when writing the continued fraction evaluator for `iv_ratio`.

That means iterating over a chunk of memory right? I wrote some like that in early drafts, but since we want these functions to be usable as CUDA kernels, we want to avoid memory allocations. Generating the terms in a lazy way when possible is helpful for this. We're actually hoping to be able to cut down on existing memory allocations in [specfun](https://github.com/scipy/scipy/blob/main/scipy/special/special/specfun/specfun.h) for this reason.

> * Runs faster if the first term of the series is computed differently from the rest (though a strong enough compiler might unroll the first Generate call to achieve the same effect).

I've written these so that the first term is an argument of the series evaluator, not something that comes out the generator.

> * Offers the possibility to visit the series in backward or random order (if needed).

Funnily enough, the next thing I'm planning to do for `hyp2f1` is write a series evaluator which sums the terms forwards until convergence, and then re-sums them backwards from smallest to largest. This approach was suggested to me by Cephes author Stephen Moshier. I'm doing this by accepting generators which allow moving forwards and backwards. I want to try something like this for continued fractions too, using forward evaluation to assess the number of iterations needed, and then re-evaluating with more numerically stable backwards evaluation.

> I’ll make a PR for `iv_ratio` with an example of an Iterator-based continued fraction evaluator as a proof of concept.

I'd be happy to see the PR. Also, I've been planning to follow up on your work with `iv_ratio` and have just been a bit delayed due to feeling sick over the past week.

**Comment by fancidev** [comment]
Thanks for the quick response @steppi .

The Iterator way is also “lazy”, and no memory allocation is incurred. Basically, instead of calling `g()` to get the current element and (implicitly) advance to the next item, call `*g` to get the current item and `++g` to advance to the next item.

By the “first term” I mean `(a[1], b[1])`. While it’s possible to manually “unroll” the continued fraction so that `(a[2], b[2])` becomes the “first term”, it alters the convergence condition (based on relative tolerance) and therefore may complicate things.

The forward-backward approach is a good idea! For the Iterator way, it’s as simple as calling `--g`.

I’ll make the `iv_ratio` (draft) PR tomorrow!

**Comment by steppi** [comment]
@fancidev. Ah, I see what you mean. That does sound like a good idea. Thanks.

**Comment by fancidev** [comment]
I come across [this line](https://github.com/scipy/scipy/blob/09769690f65cfc078c860f960f084aa3689df5b4/scipy/special/special/hyp2f1.h#L200); wonder if it’s a typo? The comment wants u > v, but that lines makes u < v.

**Comment by steppi** [comment]
> Actually I mean the code appears to have a typo. Because u, v, w, x are passed to four_gamma_lanczos; but in that function it is expected that u > v and w > x, and makes this assumption to do some scaling (so to speak).

Ah, you're absolutely right. I didn't check carefully just now.

Somehow I'd flipped the sign when translating to C++, and I think any loss of accuracy due to this went unnoticed because there were many other changes which improved accuracy.

https://github.com/scipy/scipy/blob/f133c27843a36c8fe1c2979b3a072ac4f5a00624/scipy/special/_hyp2f1.pxd#L322-L326

Do you want to submit a PR with the fix?
