### PR TITLE
BUG: signal: Fix calculation of extended image indices in convolve2d.

### LINKED ISSUE #8684: signal.convolve2d performs unexpectedly with boundary='wrap'
The signal.convolve2d(sig_1, sig_2, boundary='wrap') function behaves unexpectedly when the input signals match a certain criteria. Let's call the shape of sig_1 AxB and the shape of sig_2 CxD. If C > A+1 or D > B+1, then the output of signal.convolve2d tends to take on absurd values at certain points. 

Notes: After a bit of experimentation, these absurd values are still linearly related to the input. See the reproducing code example below:

### Reproducing code example:
```
>>> sig_1 = np.array([[1, 2], [-2, 0]])
>>> sig_2 = np.array([[1, 2, 3, 1], [0, 0, 1, 2]])
>>> convolve2d(sig_1, sig_2, boundary='wrap')
array([[-1878980598,           7,           8,           7,           5],
       [  537006075,          -2,          -3,          -2,          48],
       [-1878980598,           7,           8,           7,           5]])
>>> sig_2[0,3] -= 1
>>> convolve2d(sig_1, sig_2, boundary='wrap')
array([[       10,         6,         6,         6,         3],
       [537006073,         0,        -3,         0,        48],
       [       10,         6,         6,         6,         3]])
>>> # The absurd values in the first and third row increased by 1878980608
>>> # The absurd value in the second row decreased by 2
>>> sig_2[0,3] -= 1
>>> convolve2d(sig_1, sig_2, boundary='wrap')
array([[1878980618,          5,          4,          5,          1],
       [ 537006071,          2,         -3,          2,         48],
       [1878980618,          5,          4,          5,          1]])
>>> # The absurd values in the first and third row increased by 1878980608
>>> # The absurd value in the second row decreased by 2
>>> # There is linear consistency in changing sig_2[0,3]
```

My presumption is that, internally, the algorithm is only tiling sig_1 twice and then performing convolution. I believe that this insufficient tiling is leading to a buffer over-read, or something of the sort. For example, based on the above, I expect the internal algorithm is really only calculating the non-wrapped convolution of the following:

sig_1 (tiled):
```
1878980608 | 1   2 | 1   2
?          |-2   0 |-2   0
--------------------------
1878980608 | 1   2 | 1   2
?          |-2   0 |-2   0
```

sig_2:
```
1   2   3   1
0   0   1   2
```
Or something to this effect. When experimented with further, I'm not sure this is truly the case.

### Scipy/Numpy/Python version information:
```
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.0.0 1.14.0 sys.version_info(major=3, minor=6, micro=4, releaselevel='final', serial=0)
```

I've attached some code that I used to gain insight on the issue.
```
import numpy as np
from scipy.signal import convolve2d

# How I believe the algorithm should behave
def my_conv2d_wrap(sig_1, sig_2):
    A, B = sig_1.shape
    C, D = sig_2.shape
    sig_out = np.zeros((A + C - 1, B + D - 1))
    # For the sig_out domain
    for t_m in range(A + C - 1):
        for t_n in range(B + D - 1):
            conv_sum = 0
            # For the convolution summation domain
            for tau_m in range(C):
                for tau_n in range(D):
                    # Using the flipping orientation that scipy uses
                    conv_sum += sig_2[tau_m, tau_n] * \
                                sig_1[(t_m - tau_m) % A, (t_n - tau_n) % B]
            sig_out[t_m, t_n] = conv_sum
    return sig_out

for i in range(10000):
    if 0 == i % 100:
        print('Done with:', i, 'runs')
    # Make random signals up to 5x5 large
    A = 1 + np.random.randint(5)
    B = 1 + np.random.randint(5)
    C = 1 + np.random.randint(5)
    D = 1 + np.random.randint(5)
    sig_1 = np.random.randint(10, size=(A, B)) - 5
    sig_2 = np.random.randint(10, size=(C, D)) - 5
    # Generate the outputs
    conv_scipy = convolve2d(sig_1, sig_2, boundary='wrap')
    conv_mine = my_conv2d_wrap(sig_1, sig_2)
    # Ensure no sizing errors ever occur
    assert conv_mine.shape[0] == conv_scipy.shape[0] and conv_mine.shape[1] \
           == conv_scipy.shape[1]
    if np.any(conv_mine != conv_scipy):
        # Assume either C > A+1 or D > B+1 for inconsistencies to occur
        if not ((C > A+1) or (D > B+1)):
            print("The C > A+1 or D > B+1 assumption is wrong!")
```

### LINKED ISSUE #8814: convolve2d mode='same' crash on bad input
When passing in certain bad inputs to scipy.signal.convolve2d, it crashes. In particular it crashes hard, not just throwing a python exception, making it potentially quite time consuming for someone to track down the source of the problem.

While trying to reproduce it simply I found it hard to find the exact conditions under which it occurs but it seems to at least include mode='same', boundary='symm', in2 being large, and in particular in2 being larger than in1.

The sample below crashes consistently on my machine. Smaller numbers I tried did not crash. However the original issue in my code (that I can't send sorry) was with smaller values - a 1482x1200 image and a filter of shape 3359x1

### Reproducing code example:
```
import numpy
from scipy import signal

image = numpy.zeros((300, 300))
filter = numpy.zeros((1, 700000))

signal.convolve2d(image, filter, mode='same', boundary='symm')
```
### Error message:

There's no exception thrown, I just get Windows popping up a box saying a problem has occurred and would I like to send them information. It does say this though on the console in Pycharm:
```
Process finished with exit code -1073741819 (0xC0000005)
```
### Scipy/Numpy/Python version information:
```
1.1.0 1.14.3 sys.version_info(major=3, minor=6, micro=2, releaselevel='final', serial=0)
```

### LINKED ISSUE #12686: convolve2d and correlate2d read memory outside of inputs in some cases
When calling `scipy.signal.convolve2d` and `correlate2d` with an `in1.shape` that has a value that is less than half of the corresponding value in `in2.shape` then `boundary!="constant"` and `mode!='valid'` will read outside of the array. This can be see in https://github.com/scipy/scipy/blob/4e3d82268eae3c89e94ff5f3c3774bb12c12982a/scipy/signal/firfilter.c#L166-L175. In those lines it is possible that `ind0 < 2*NS[0]` or `ind0 > 2*NS[0]` when `in1.shape` has a value that is less than half of the corresponding value in `in2.shape` resulting in an `ind0` that is still out-of-bounds after those `if` statements. The circular conditions (or wrap) need a `%` operation while the reflect conditions (or symm) need at least a `%` and `min` operations.

There are a similar set of lines later for `ind1` and `NS[1]`.

As a quick check that garbage is not being read, the following should be `True`:

```python
import numpy as np, scipy.signal as sig, scipy.ndimage as ndi
a = np.arange(1, 10*3+1, dtype=float).reshape(10, 3)                                                                                  
b = np.arange(1, 10*10+1, dtype=float).reshape(10, 10)                                                                                
print((sig.convolve2d(a, b, mode='same', boundary='wrap') == ndi.convolve(a, b, mode='wrap', origin=(-1, -1))).all())
```

### PR DESCRIPTION
**Pull request by WarrenWeckesser**
To handle the `boundary` arguments "wrap" and "symm", the `convolve2d`
code computes indices into the first argument that might be negative or
larger than the size of the image.  The code adjusts negative or big
values so that the adjusted index refers to the correct data element
within the array.  The problem was that this adjustment code assumed
that it would only require that the data be extended *once*. E.g. if
an axis had length 100, it assumed that the extended index would be
in [-100, 200].  This is not true in general; the kernel (i.e. the
second argument of `convolve2d`) can be any size, and so the required
extension could be any size.  If the kernel was too big, the adjusted
indices might still be negative or too big, resulting in attempts to
access memory outside of input array's data.  That could result in
reading garbage, or a segmentation fault.

The fix is to use a couple helper functions that can handle arbitrarily
large kernel dimensions when computing the extended data.

Closes gh-8684.
Closes gh-8814.
Closes gh-12686.

### CODE REVIEW

**Comment by WarrenWeckesser** [comment]
This also closes gh-12686.  I pushed another commit containing a couple more tests based on the examples in @coderforlife's comments in that issue.

**Review by larsoner — APPROVED** [review]
Looks pretty straghtforward to me, +1 for merge from my end.

@WarrenWeckesser anyone else you think we should ping before merge? If not, feel free to merge in a couple of days if nobody else says anything

**Comment by WarrenWeckesser** [comment]
Thanks @larsoner.

> anyone else you think we should ping...

@endolith is involved with `scipy.signal`, though admittedly `convolve2d` is more of an image processing function than a DSP function.
 
@coderforlife, you did a deep dive into the C code and correctly analyzed the problem in https://github.com/scipy/scipy/issues/12686 (back in 2020!), so you might be interested in taking a look now that the problem is finally being fixed.

File: scipy/signal/_firfilter.c [hunk 1]
```diff
@@ -185,13 +198,13 @@ int pylab_convolve_2d (char  *in,        /* Input data Ns[0] x Ns[1] */
 	  for (int64_t k=0; k < Nwin[1]; k++) {
 	    int64_t ind1 = convolve ? (new_n-k) : (new_n+k);
 	    if (ind1 < 0) {
-	      if (boundary == REFLECT) ind1 = -1-ind1;
-	      else if (boundary == CIRCULAR) ind1 = Ns[1] + ind1;
+	      if (boundary == REFLECT) ind1 = reflect_symm_index(ind1, Ns[1]);
+	      else if (boundary == CIRCULAR) ind1 = circular_wrap_index(ind1, Ns[1]);
 	      else bounds_pad_flag = true;
 	    }
 	    else if (ind1 >= Ns[1]) {
```
Comment (endolith) [inline scipy/signal/_firfilter.c:205]: and this removed too

File: scipy/signal/_firfilter.c [hunk 2]
```diff
@@ -164,13 +177,13 @@ int pylab_convolve_2d (char  *in,        /* Input data Ns[0] x Ns[1] */
...
+	  else if (boundary == CIRCULAR) ind0 = circular_wrap_index(ind0, Ns[0]);
 	  else bounds_pad_flag = true;
 	}
 	else if (ind0 >= Ns[0]) {
-	  if (boundary == REFLECT) ind0 = Ns[0]+Ns[0]-1-ind0;
-	  else if (boundary == CIRCULAR) ind0 = ind0 - Ns[0];
+	  if (boundary == REFLECT) ind0 = reflect_symm_index(ind0, Ns[0]);
+	  else if (boundary == CIRCULAR) ind0 = circular_wrap_index(ind0, Ns[0]);
 	  else bounds_pad_flag = true;
 	}
```
Comment (endolith) [inline scipy/signal/_firfilter.c:188]:
```suggestion
	if ((ind0 < 0) || (ind0 >= Ns[0])) {
	  if (boundary == REFLECT) ind0 = reflect_symm_index(ind0, Ns[0]);
	  else if (boundary == CIRCULAR) ind0 = circular_wrap_index(ind0, Ns[0]);
	  else bounds_pad_flag = true;
	}
```

Comment (endolith) [reply scipy/signal/_firfilter.c:188]: Suggestion feature doesn't seem to be working

**Review by endolith — CHANGES_REQUESTED** [review]
Looks good otherwise

**Comment by coderforlife** [comment]
I did look it over and it looked good. Sorry, I couldn't make a PR myself, I discovered the problem while working on cupy's implementation of these functions.

File: scipy/signal/_firfilter.c [hunk 3]
```diff
@@ -99,6 +99,19 @@ static OneMultAddFunction *OneMultAdd[]={NULL,
 					 CLONGDOUBLE_onemultadd,
                                          NULL, NULL, NULL, NULL};
 
+static int64_t
+reflect_symm_index(int64_t j, int64_t m)
+{
```
[the remark this answers is not in the document]
Comment (WarrenWeckesser) [reply scipy/signal/_firfilter.c:122]: Done.

File: scipy/signal/_firfilter.c [hunk 4]
```diff
@@ -164,13 +177,13 @@ int pylab_convolve_2d (char  *in,        /* Input data Ns[0] x Ns[1] */
 	bool bounds_pad_flag = false;
 
 	if (ind0 < 0) {
-	  if (boundary == REFLECT) ind0 = -1-ind0;
-	  else if (boundary == CIRCULAR) ind0 = Ns[0] + ind0;
+	  if (boundary == REFLECT) ind0 = reflect_symm_index(ind0, Ns[0]);
+	  else if (boundary == CIRCULAR) ind0 = circular_wrap_index(ind0, Ns[0]);
 	  else bounds_pad_flag = true;
 	}
 	else if (ind0 >= Ns[0]) {
```
[the remark this answers is not in the document]
Comment (WarrenWeckesser) [reply scipy/signal/_firfilter.c]: Done.  I made the suggested changes locally instead of using the github "suggested changes" UI.

File: scipy/signal/_firfilter.c (hunk 1 above)
Comment (WarrenWeckesser) [reply scipy/signal/_firfilter.c]: Done.

**Comment by WarrenWeckesser** [comment]
Thanks @endolith, all good suggestions that I've implemented.

And thanks for taking a look, @coderforlife.  No need to apologize for not submitting a PR.  Reporting and analyzing a problem does not obligate you to fix it!

**Comment by WarrenWeckesser** [comment]
By the way, the horrible code alignment and mix of tabs and spaces in `_firfilter.c` makes reading that code more challenging than necessary.  I don't want to mix a big reformatting job with this PR, but perhaps in a separate maintenance PR this file (and several other C files here and in scipy.special) can be cleaned up with clang-format or some other formatter.

**Comment by ilayn** [comment]
If you deem necessary, then we can review it by hiding whitespace changes. Usually I agree it is a mess to have these changes but C files don't see too much change over time hence I think we can do it for this one occasion.

**Review by endolith — APPROVED** [review]
Code all looks good to me now, comments are great.  Not sure about the test failures

**Comment by WarrenWeckesser** [comment]
The test failures are not related to this PR.  They are result of changes in NumPy; see https://github.com/scipy/scipy/pull/16152.

**Comment by WarrenWeckesser** [comment]
@ilayn, I won't reformat the file in this PR.  That can be done in a separate PR, after we've decided the extent to which we want to clean up our C and C++ files, and which style to use when we do it.

**Comment by larsoner** [comment]
> @ilayn, I won't reformat the file in this PR. That can be done in a separate PR, after we've decided the extent to which we want to clean up our C and C++ files, and which style to use when we do it.

Agreed this should be a separate PR, and that we should probably do it. @WarrenWeckesser want to get the ball rolling maybe with a post suggesting your preferred solution/formatter to the scipy-dev list? If nobody objects we can do it and add the commit to `.git-blame-ignore-revs` like we're looking at doing for NumpyDoc: https://github.com/numpy/numpydoc/pull/391#issue-1228777252

As noted by @WarrenWeckesser the failures are unrelated and it looks like all comments have been addressed, so I'll merge in a couple of days unless others ask for more changes or time to look!

**Review by stefanv — APPROVED** [review]

**Comment by ilayn** [comment]
> after we've decided the extent to which we want to clean up our C and C++ files, and which style to use when we do it.

That shed would not be painted very soon, hence my comment 😃 But no problem, I don't see it as a blocker anyways. +1 from me too.

**Comment by larsoner** [comment]
Thanks @WarrenWeckesser !
