### PR TITLE
BUG: Use uint16 for cost in NI_WatershedElement

### LINKED ISSUE #10069: scipy.ndimage.watershed_ift regression in 1.0.0
The following line
```
_nd_image.watershed_ift(input, markers, structure, output)
```
in `scipy/ndimage/measurements.py` (`watershed_ift`) produces different result before and after `scipy=1.0.0` with the input attached. I guess this might just be an example of a corner case using bad inputs, but it would be nice to know why the results differ.

### Reproducing code example:
```python
import numpy as np
from scipy.ndimage import watershed_ift

image = np.loadtxt('image.txt', dtype=np.uint16)

markers = np.zeros(image.shape, dtype=np.int16)
markers[0, 0] = 1
markers[image.shape[0] / 2, image.shape[1] / 2] = 2

print("Same input:")
print(hash(image.tostring()))
print(hash(markers.tostring()))

output = watershed_ift(image, markers)

print("Different output:")
print(hash(output.tostring()))

import matplotlib.pyplot as plt
plt.imshow(output, cmap='jet')
plt.show()
```
Inputs:
[image.txt](https://github.com/scipy/scipy/files/3085325/image.txt)

### Scipy/Numpy/Python version information:
Example of "good" output:
```
'0.15.1', '1.15.1', sys.version_info(major=2, minor=7, micro=10, releaselevel='final', serial=0)
```
```
Same input:
2134465424452735359
3894358299218458450
Different output:
-3225594274849803831
```
output-0 15 1

Example of "bad" output:
```
'1.1.0', '1.12.1', sys.version_info(major=2, minor=7, micro=13, releaselevel='final', serial=0)
```
```
Same input:
2134465424452735359
3894358299218458450
Different output:
6558824525946414866
```
output-1 1 0

The breaking change seems to have occurred in `scipy=1.0.0`. The result looks just as bad for:
```
1.2.1 1.16.2 sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)
```

### PR DESCRIPTION
**Pull request by SimonSegerblomRex**
#### Reference issue
Fixes gh-10069.

#### What does this implement/fix?
`uint8` was not enough for `uint16` input. It caused strange output containing zeros in some cases.

#### Additional information
This was regressed in v1.0.0

### CODE REVIEW

**Comment by SimonSegerblomRex** [comment]
The type for done used to be uint8 instead of uint16:
https://github.com/scipy/scipy/commit/b3a66bfdfd8b7af92405d5c8419a2333abdaaa7c

Maybe that should also be reverted.

File: scipy/ndimage/src/ni_measure.c [hunk 1]
```diff
@@ -205,7 +205,7 @@ typedef struct {
     npy_intp index;
     void *next, *prev;
     npy_uint16 done;
```
Comment (SimonSegerblomRex) [inline scipy/ndimage/src/ni_measure.c:207]: The type for done used to be `uint8` instead of `uint16`:
b3a66bf#diff-23265bac697090bca24e16cd0e08f306L663

Maybe this should also be reverted.

File: scipy/ndimage/src/ni_measure.c [hunk 2]
```diff
@@ -205,7 +205,7 @@ typedef struct {
...
-    npy_uint8 cost;
+    npy_uint16 cost;
```
Comment (tylerjereddy) [inline scipy/ndimage/src/ni_measure.c:208]: It looks like a simple enough fix, but I will reiterate the concerns in the matching issue about providing a concise unit/regression test to go along with it if possible.

It seems there were some recent improvements to the reproducing examples there so maybe they could be converted to a test?

Comment (SimonSegerblomRex) [reply scipy/ndimage/src/ni_measure.c:208]: > It seems there were some recent improvements to the reproducing examples there so maybe they could be converted to a test?

Yes, I can add a regression test with a 2x2 matrix tomorrow.

Comment (SimonSegerblomRex) [reply scipy/ndimage/src/ni_measure.c:207]: I added a simple regression test.

File: scipy/ndimage/src/ni_measure.c (hunk 1 above)
Comment (SimonSegerblomRex) [reply scipy/ndimage/src/ni_measure.c]: I reverted the type for `done` (while keeping the order of the fields sorted by decreasing size).

**Comment by SimonSegerblomRex** [comment]
The build failure is unrelated to this change. Can you retrigger the build (after fixing the issue)?

**Comment by SimonSegerblomRex** [comment]
I don't understand why the build is failing. Is Travis CI unstable?

**Review by peterbell10 — APPROVED** [review]
Tracked this down to [this commit](https://github.com/scipy/scipy/commit/b3a66bfdfd8b7af92405d5c8419a2333abdaaa7c#diff-23265bac697090bca24e16cd0e08f306L663-L672). `done` is a boolean flag so there's no reason for it to be `uint16`.

Unfortunately the ARM Travis can be a bit flaky. The failure is unrelated.

**Comment by peterbell10** [comment]
Thanks @SimonSegerblomRex.

**Comment by johanjeppsson** [comment]
Would it be possible to backport this fix to the 1.2 maint-branch?

**Comment by tylerjereddy** [comment]
@johanjeppsson That's a pretty old maintenance branch--are you stuck with Python 2.7 or something? I think technically our support window for that branch is closed except for pretty major bugs/security issues.

**Comment by johanjeppsson** [comment]
Yes, we still have some old python 2.7 code running. We are working on updating it to python 3, but as a stepping stone, the idea was to update all packages to the latest python 2 versions. For that to work, this is the last issue we've found.

But I totally get it if you don't want to backport stuff to branches that are that old. We can probably work around it.
