### PR TITLE
BUG: fix ortho mode in DST type 2/3

### LINKED ISSUE #18452: BUG: DST 2 and 3 with `norm="ortho"` are not orthogonal
### Describe your issue.

Hi,

It seems that even with the option `norm="ortho"`, the DST is not properly orthogonalized. It seems that the wrong element gets rescaled (the last element should be rescaled, instead of the first). Rescaling the last element is coherent with [wikipedia's definition](https://en.wikipedia.org/wiki/Discrete_sine_transform#DST-II). 

It is only an issue with the DST, the DCT works properly.

I've attached a snippet that shows that the DST is not orthogonal, manually reproduces scipy's orthogonalization strategy, and shows that the alternative strategy does yield an orthogonal transform. I've only tested it with version 1.10, but rescaling the first element instead of the last is documented as far back as [version 1.4](https://docs.scipy.org/doc/scipy-1.4.0/reference/generated/scipy.fft.dst.html#scipy.fft.dst).

I am surprised that this question has not come up before, so I may be missing something.

### Reproducing Code Example

```python
import numpy as np
from scipy.fft import dst


def make_mat_dst_scipy(n, type=2):
    """
    Build coefficients matrix
    """
    x = np.eye(n)
    y = dst(x, type=type, norm="ortho", axis=-1).T
    return y


def make_mat_dst_scipy_reproduce(n, type=2):
    """
    Reproduce Scipy's "ortho" normalization
    """
    x = np.eye(n)
    x /= (2 * n) ** 0.5
    if type == 3:
        x[:, 0] *= 2**0.5
    y = dst(x, type=type, norm=None, axis=-1).T
    if type == 2:
        y[0, :] /= 2**0.5
    return y


def make_mat_dst_scipy_fixed(n, type=2):
    """
    Fix it by normalizing the last element instead of the first
    """
    x = np.eye(n)
    x /= (2 * n) ** 0.5
    if type == 3:
        x[:, -1] *= 2**0.5
    y = dst(x, type=type, norm=None, axis=-1).T
    if type == 2:
        y[-1, :] /= 2**0.5
    return y


print('Scipy')
DST2 = make_mat_dst_scipy(4, type=2)
print(np.round((DST2 @ DST2.T), 3))
DST3 = make_mat_dst_scipy(4, type=3)
print(np.round((DST3 @ DST3.T), 3))


print('Scipy (reproduce)')
DST2 = make_mat_dst_scipy_reproduce(4, type=2)
print(np.round((DST2 @ DST2.T), 3))
DST3 = make_mat_dst_scipy_reproduce(4, type=3)
print(np.round((DST3 @ DST3.T), 3))


print('Fix')
DST2 = make_mat_dst_scipy_fixed(4, type=2)
print(np.round((DST2 @ DST2.T), 3))
DST3 = make_mat_dst_scipy_fixed(4, type=3)
print(np.round((DST3 @ DST3.T), 3))
```

### Error message

```shell
# This shows the result from the snippet

Scipy
[[ 0.5  0.  -0.   0. ]
 [ 0.   1.   0.   0. ]
 [-0.   0.   1.  -0. ]
 [ 0.   0.  -0.   2. ]]
[[0.948 0.302 0.052 0.198]
 [0.302 1.302 0.552 0.052]
 [0.052 0.552 1.302 0.302]
 [0.198 0.052 0.302 0.948]]

Scipy (reproduce)
[[ 0.5  0.  -0.  -0. ]
 [ 0.   1.   0.   0. ]
 [-0.   0.   1.  -0. ]
 [-0.   0.  -0.   2. ]]
[[0.948 0.302 0.052 0.198]
 [0.302 1.302 0.552 0.052]
 [0.052 0.552 1.302 0.302]
 [0.198 0.052 0.302 0.948]]

Fix
[[ 1.  0.  0. -0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1. -0.]
 [-0.  0. -0.  1.]]
[[ 1. -0.  0. -0.]
 [-0.  1. -0.  0.]
 [ 0. -0.  1. -0.]
 [-0.  0. -0.  1.]]
```

### SciPy/NumPy/Python version and system information

```shell
1.10.1 1.24.2 sys.version_info(major=3, minor=8, micro=16, releaselevel='final', serial=0)
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
  NOT AVAILABLE
openblas_clapack_info:
  NOT AVAILABLE
flame_info:
  NOT AVAILABLE
atlas_3_10_threads_info:
  NOT AVAILABLE
atlas_3_10_info:
  NOT AVAILABLE
atlas_threads_info:
  NOT AVAILABLE
atlas_info:
  NOT AVAILABLE
lapack_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas']
    library_dirs = ['/opt/miniconda3/envs/jitfields/lib']
    language = f77
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
  NOT AVAILABLE
atlas_3_10_blas_threads_info:
  NOT AVAILABLE
atlas_3_10_blas_info:
  NOT AVAILABLE
atlas_blas_threads_info:
  NOT AVAILABLE
atlas_blas_info:
  NOT AVAILABLE
blas_info:
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/opt/miniconda3/envs/jitfields/lib']
    include_dirs = ['/opt/miniconda3/envs/jitfields/include']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/opt/miniconda3/envs/jitfields/lib']
    include_dirs = ['/opt/miniconda3/envs/jitfields/include']
    language = c
lapack_opt_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/opt/miniconda3/envs/jitfields/lib']
    language = c
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/miniconda3/envs/jitfields/include']
```

### PR DESCRIPTION
**Pull request by mreineck**
#### Reference issue
Closes #18452 

#### What does this implement/fix?
Fixes orthonormalization in DSTs type 2 and 3

@peterbell10 what do you think?

### CODE REVIEW

**Comment by mreineck** [comment]
OK, it seems that the unit tests actually try to make sure that we get the "wrong" behaviour. I can update them, but I'd like to have independent confirmation that the tests are indeed buggy.

**Comment by mreineck** [comment]
Ping :-)

File: scipy/fft/_pocketfft/pocketfft_hdronly.h [hunk 1]
```diff
@@ -2630,11 +2630,13 @@ template<typename T0> class T_dcst23
...
             std::swap(c[k], c[kc]);
-        if (ortho) c[0]*=sqrt2*T0(0.5);
+        if (ortho)
+          cosine ? c[0]*=sqrt2*T0(0.5) : c[N-1]*=sqrt2*T0(0.5);
         }
       else
         {
-        if (ortho) c[0]*=sqrt2;
+        if (ortho)
+          cosine ? c[0]*=sqrt2 : c[N-1]*=sqrt2;
```
Comment (peterbell10) [inline scipy/fft/_pocketfft/pocketfft_hdronly.h:2639]: It would be good to fix these on the upstream repo as well, then we can sync all the other changes in the last few years.

**Review by peterbell10 — APPROVED** [review]

File: scipy/fft/_pocketfft/pocketfft_hdronly.h (hunk 1 above)
Comment (mreineck) [reply scipy/fft/_pocketfft/pocketfft_hdronly.h:2639]: Sure, the PR there is already prepared! I just wanted to get positive feedback first.
