### PR TITLE
BUG: fix scipy.special.voigt_profile

### LINKED ISSUE #11598: output of special.voigt_profile when sigma=0
Hey!

scipy.special.voigt_profile(x, sigma, gamma, out=None) returns NA when sigma=0.
However, I would have expected/it would be useful if in that case it returns a Lorentzian profile, as e.g. described here:
http://apps.jcns.fz-juelich.de/man/voigt.html
Best,
Alex

### PR DESCRIPTION
**Pull request by ruslanye**
#### Reference issue
Closes #11598

#### What does this implement/fix?
Fixed scipy.special.voigt_profile to handle cases when either of parameters is 0 as suggested in #11598.

### CODE REVIEW

**Comment by ruslanye** [comment]
@tylerjereddy, Can I ask for a review?

**Comment by person142** [comment]
I will review this weekend.

File: scipy/special/_faddeeva.cxx [hunk 1]
```diff
@@ -128,6 +128,18 @@ double faddeeva_voigt_profile(double x, double sigma, double gamma)
...
+    if(sigma == 0){
+        if (gamma == 0){
+            if (x == 0)
+                return NPY_INFINITY;
+            return 0;
+        }
+        return gamma / NPY_PI / (x*x + gamma*gamma);
+    }
+    if (gamma == 0){
+        return 1 / SQRT_2PI / sigma * exp(-x*x / 2 / (sigma*sigma));
```
Comment (ilayn) [inline scipy/special/_faddeeva.cxx]: squaring `x/sigma` might be a bit more numerically stable

Comment (ruslanye) [reply scipy/special/_faddeeva.cxx]: @ilayn, changed it

File: scipy/special/add_newdocs.py [hunk 2]
```diff
@@ -112,6 +112,10 @@ def add_newdoc(name, doc):
     standard deviation ``sigma`` and a 1-D Cauchy distribution with half-width at
     half-maximum ``gamma``.
 
+    If ``sigma`` = 0, PDF of Cauchy distribution is returned.
```
Comment (person142) [inline scipy/special/add_newdocs.py]: Put the `= 0 ` part inside the backticks too. (And similarly below.)

File: scipy/special/_faddeeva.cxx [hunk 3]
```diff
@@ -128,6 +128,18 @@ double faddeeva_voigt_profile(double x, double sigma, double gamma)
     const double INV_SQRT_2 = 0.707106781186547524401;
     const double SQRT_2PI = 2.5066282746310002416123552393401042;
 
+    if(sigma == 0){
+        if (gamma == 0){
+            if (x == 0)
+                return NPY_INFINITY;
+            return 0;
```
Comment (person142) [inline scipy/special/_faddeeva.cxx]: This branch won't propagate NaNs.

File: scipy/special/tests/test_faddeeva.py [hunk 4]
```diff
@@ -57,3 +57,21 @@ def test_symmetry(self):
             rtol=1e-15,
             atol=0
         )
+    
+    def test_corner_cases(self):
+        points = np.array([
```
Comment (person142) [inline scipy/special/tests/test_faddeeva.py]: So the trick with this test data is that it doesn't appear to have a canonical source. That makes sense, since the implementation for these edge cases is simple, but it makes it unclear if the test is correct. I would suggest instead testing for some edge cases with exact outputs (like the `np.inf` entry below). You can do that inside a

```python
@pytest.mark.parametrize('x, sigma, gamma, desired', [
    (0, 0, 0, inf),
    (1, 0, 0, 0),
    ....
])
def test_corner_cases(self, x, sigma, gamma, desired):
    assert sc.voigt_profile(x, sigma, gamma) == desired
```

Then I would add tests that check the _continuity_ as `gamma -> 0` e.g. So compare the result at `gamma = 1e-16` (say) with the result at `gamma = 0` with all other inputs held constant. (And do similar checks for the other limits.)

Comment (person142) [reply scipy/special/tests/test_faddeeva.py]: And add tests for `NaN` inputs.

**Comment by ruslanye** [comment]
@person142, I've addressed your comments. Could you please review again?

**Comment by person142** [comment]
Looks good now. Will merge once the CI passes.

**Comment by ruslanye** [comment]
@person142, seems something is wrong with scipy.scipy (Windows Python36-32bit-full) tests. It's been in progress for two days already.

**Comment by person142** [comment]
Hm... I'm sure there is a restart button in there somewhere, but for the life of me I cannot find it. @tylerjereddy you know how to restart in Azure?

**Comment by tylerjereddy** [comment]
ok, restarted

**Comment by person142** [comment]
Maybe the problem is that I don't belong to the SciPy org in Azure?

**Comment by tylerjereddy** [comment]
ok, let me know the relevant username/email info and I'll see what I can do

**Comment by person142** [comment]
@tylerjereddy emailed you. Thanks!

**Comment by person142** [comment]
Merged, thanks @ruslanye.
