### PR TITLE
ENH:interpolate: Rewrite FITPACK in C

### LINKED ISSUE #18566: META: FORTRAN Code inventory
This issue is meant for a central place for our Fortran (almost exclusively F77) codebase to track per module and if possible remove depending on availability of contributor affinity of the subject matter and fortran-fu. 

List has projected effort required just based on code length hence involves prejudice.

- [ ] scipy.integrate:
  -  [ ] dop Convert: Easy
  - [ ] mach Convert: Easy
  - [ ] odepack : Convert : Hard
  - [ ] quadpack : Convert : Moderate-Hard
- [ ] scipy.interpolate
  - [ ] fitpack : Convert : Moderate-Hard
- [ ] scipy.io
  - [ ] Test Fortran : ? 
- [x] scipy.linalg
  - [x] lu/det : Replaced in #18225, #18358
  - [x] id_dist : Convert: Moderate (replacement in progress)
- [ ] scipy.odr
  - [ ] odrpack : Convert : Moderate
- [ ] scipy.optimize
  - [ ] nnls: Convert : Easy/Moderate
  - [ ] cobyla : Convert : Hard (The new implementation PRIMA is going to replace cobyla)
  - [ ] L-BFGS-B: Convert : Hard
  - [ ] minpack: Convert : Hard (reimplemented by LFortran team)
  - [ ] minpack2: Convert : Easy
  - [ ] slsqp : Convert: Hard
- [ ] scipy.sparse.linalg
  - [ ] ARPACK Convert : Hard
  - [x] iterative Replaced : #18488
  - [ ] PROPACK : Convert : Hard
- [ ] scipy.special
  - [ ] AMOS: Convert : Hard
  - [ ] cdflib: Convert : Hard
  - [ ] mach: Convert : Easy
  - [ ] specfun : Convert: Very Hard

### LINKED ISSUE #24084: BUG: `RectBivariateSpline.partial_derivative` rejects valid x-derivative orders when `kx > ky`
### Describe your issue.

`RectBivariateSpline.partial_derivative(dx, dy)` should accept any derivative orders with `0 ≤ dx < kx` and `0 ≤ dy < ky`. However, when `kx > ky`, requesting a valid x-derivative with `dx ≥ ky` but `dx < kx` raises `_dfitpack.error`. The fix should be simple, the Fitpack routine (`pardtc`) currently appears to compare the x-derivative order (`nux`) against `ky` instead of `kx`. 

### Reproducing Code Example

```python
import numpy as np
from scipy.interpolate import RectBivariateSpline

x = np.array([-2.0, -1.0, 0.0, 1.0, 2.0])
y = np.array([-2.0, -1.0, 0.0, 1.0])
z = np.exp(-x[:, None]**2 - y[None, :]**2)

spline = RectBivariateSpline(x, y, z, kx=3, ky=2)

spline.partial_derivative(2, 0)
```

### Error message

```shell
Traceback (most recent call last):
  File "/data/src/test.py", line 12, in <module>
    spline.partial_derivative(2, 0)
  File "/home/hdd/miniconda3/envs/py312/lib/python3.12/site-packages/scipy/interpolate/_fitpack2.py", line 1131, in partial_derivative
    newc, ier = dfitpack.pardtc(tx, ty, c, kx, ky, dx, dy)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_dfitpack.error: ((0 <= nuy) && (nux < ky)) failed for 7th argument nuy: pardtc:nuy=0
```

### SciPy/NumPy/Python version and system information

```shell
1.16.3 2.3.4 sys.version_info(major=3, minor=12, micro=12, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.11/lib/python3.12/site-packages/scipy_openblas32/include
    lib directory: /opt/_internal/cpython-3.12.11/lib/python3.12/site-packages/scipy_openblas32/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.29.dev DYNAMIC_ARCH NO_AFFINITY Haswell MAX_THREADS=64
    pc file directory: /project
    version: 0.3.29.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.11/lib/python3.12/site-packages/scipy_openblas32/include
    lib directory: /opt/_internal/cpython-3.12.11/lib/python3.12/site-packages/scipy_openblas32/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.29.dev DYNAMIC_ARCH NO_AFFINITY Haswell MAX_THREADS=64
    pc file directory: /project
    version: 0.3.29.dev
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 3.0.1
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.1.6
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  pythran:
    include directory: ../../tmp/build-env-99e64tom/lib/python3.12/site-packages/pythran
    version: 0.18.0
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /tmp/build-env-99e64tom/bin/python
  version: '3.12'
```

### PR DESCRIPTION
**Pull request by ilayn**
#### Reference issue
Closes #18566 (don't jinx it)
Closes #24084

### CODE REVIEW

**Comment by ilayn** [comment]
@ev-br I have some questions, I'll also reply your mail later. So this `_fitpackmodule.c` imports three functions from FITPACK and exposes a module `_fitpack`. But at the same time `dfitpack.pyf` also exposes another module `_dfitpack`.

Do you know which one is used where? It's a bit more involved that LSODA where it also had two separate interfaces but this time I don't have any idea what these functions do.

**Comment by ev-br** [comment]
This looks like a great start @ilayn! Apologies it took me a while to get to it.

A couple of high-level comments first:

- `surfit.f` is exposed to python in two places: `bisprep` (via the `_fitpack.surfit` ), and `SmoothBivariateSpline` (via `dfitpack.surfit_smth`)  and `LSQBivariateSpline` (via `dfitpack.surfit_lsq`)
- python-level binding can go through `src/_dierckxmodule.cc` -- obviously if you prefer a separate extension, fine.
- for evaluations (`bisplev` and `__call__` methods of `*Spline` classes) I think it's easiest to go through `NdBSpline`. https://github.com/scipy/scipy/pull/23962 has a couple of trampolines between the 2D and NdBSpline formats. Either subclass NdBSpline or route via `self._spline` (I'd probably go for the latter because the `*Spline` interface is a bit unusual).

Checking the test suite, our test coverage of this is _very_ thin. So probably the only way we can pull it off is to make the change and watch out of bug reports. Not sure how much real-world usage `*BivariateSpline` has. We've been [recommending other routines](https://docs.scipy.org/doc/scipy/tutorial/interpolate/interp_transition_guide.html#scattered-2d-linear-interpolation-prefer-linearndinterpolator-to-smoothbivariatespline-or-bisplrep) for a couple of years now.

Happy to help out, please do let me know how.

File: scipy/interpolate/src/dfitpack.c [hunk 1]
```diff
@@ -0,0 +1,1772 @@
...
+
+
+void
+fprota(double c, double s, double *a, double *b)
+{
+    // fprota applies a givens rotation to the pair (a,b).
+    double temp = c * (*a) - s * (*b);
+    *b          = c * (*b) + s * (*a);
+    *a          = temp;
+}
```
Comment (ev-br) [inline scipy/interpolate/src/dfitpack.c:144]: https://github.com/scipy/scipy/blob/main/scipy/interpolate/src/__fitpack.h#L31 (C++ though)

File: scipy/interpolate/src/dfitpack.c [hunk 2]
```diff
@@ -0,0 +1,1772 @@
...
+
+
+void
+fpbspl(const double* t, const int n, const int k, const double x, const int l, double* h)
```
Comment (ev-br) [inline scipy/interpolate/src/dfitpack.c]: https://github.com/scipy/scipy/blob/main/scipy/interpolate/src/__fitpack.cc#L12

File: scipy/interpolate/src/dfitpack.c [hunk 3]
```diff
@@ -0,0 +1,1772 @@
...
+            else {
+                h[i + 1] = 0.0;
+            }
+        }
+    }
+}
+
+
+void
+fpback(double* a, double* z, const int n, const int k, double* c, const int nest)
```
Comment (ev-br) [inline scipy/interpolate/src/dfitpack.c:434]: https://github.com/scipy/scipy/blob/main/scipy/interpolate/src/__fitpack.cc#L897

File: scipy/interpolate/src/dfitpack.c [hunk 4]
```diff
@@ -0,0 +1,1772 @@
...
+            }
+            z[m] = sp;
+            m++;
+        }
+    }
+}
+
+
+void
+fpgivs(const double piv, double* ww, double* cos, double* sin)
```
Comment (ev-br) [inline scipy/interpolate/src/dfitpack.c]: this is `dlartg`, basically.

File: scipy/interpolate/src/dfitpack.c [hunk 5]
```diff
@@ -0,0 +1,1772 @@
...
+    }
+
+    *cos = *ww / dd;
+    *sin = piv / dd;
+    *ww = dd;
+}
+
+
+void
+fpdisc(const double* t, const int n, const int k2, double* b, const int nest)
```
Comment (ev-br) [inline scipy/interpolate/src/dfitpack.c]: Elsewhere, we moved it to python https://github.com/scipy/scipy/blob/main/scipy/interpolate/_fitpack_repro.py#L439

File: scipy/interpolate/src/dfitpack.c [hunk 6]
```diff
@@ -0,0 +1,1772 @@
...
+            }
+        }
+        stor3 += (a[i - 1] * c[i - 1]) * ((a[i - 1] * c[i - 1]) - store - store);
+    }
+    *sq += stor3;
+}
+
+
+double
+fprati(double* p1, double* f1, double* p2, double* f2, double* p3, double* f3)
```
Comment (ev-br) [inline scipy/interpolate/src/dfitpack.c]: This we moved to python, too: https://github.com/scipy/scipy/blob/main/scipy/interpolate/_fitpack_repro.py#L825

**Review by ev-br — COMMENTED** [review]
A couple of links to things we moved from fortran to python or C for other routines. All optional.

**Comment by ilayn** [comment]
Ah nice thanks. It makes it clearer. 

I took a look at the existing functions but the ones that I am translating has dependency on them anyways. So I was not sure if I would be able to dissect in that plane (it does not like if I link to cpp headers from C code). 

But anyways, is it ok that I translate what I find in the dependency tree and then we salvage what needs to be salvaged? I am a bit lost in what is needed and what is not in the fortran code alone because there is some high scaffolding in the C++ and Python code.

**Comment by ev-br** [comment]
> But anyways, is it ok that I translate what I find in the dependency tree and then we salvage what needs to be salvaged?

Absolutely, yes.
We'll be able to deduplicate at leisure.

> am a bit lost in what is needed and what is not in the fortran code alone because there is some high scaffolding in the C++ and Python code.

This is a bit sad---the "scaffolding" was made with an explicit goal to make it easier to work with than the original Fortran monolith [1]. Clearly your experience does not support that.  Anyhow, please don't let my not making it easier stop you doing what you find easier!





---------------

[1] And as an aside, it's c++ mostly because I can handle `print*, ` debugging, in fortran, `std::cout <<` debugging,  but `printf` defies me. There is hardly anything c++ specific in `__fitpack.cc`.

**Comment by ilayn** [comment]
Sure that part is clear. What I mean is that it is not very obvious which function becomes which public API without going through the entire library. That's why I did not want to get into it. The compiled parts are easy to grep anyways, the mermaid diagram already shows the code duplication so it is not a tall call stack unfortunately but a very wide one.

**Comment by ilayn** [comment]
Is it easier to mark which ones I can skip in the mermaid here 

image


I am a bit more confused because there is `_fitpack` module coming from `_fitpackmodule.c`, there is `_dfitpack` module coming from the `dfitpack.pyf` file, and there is also `_diercx` module coming from `_dierckxmodule.cc`. So we have three of them, and they kind of wrap it in a hybrid way. Is this intentional or just historical luggage? I don't think we can pick and choose in this setting but translate all :face_with_diagonal_mouth:

**Comment by ev-br** [comment]
`_fitpack` / `dfitpack` duplication is historical [1], cf https://github.com/scipy/scipy/issues/16729. The goal is to have both of them gone together with the Fortran code they wrap.

`_dierckxmodule` is new in scipy 1.15, and is a python fronted for C/C++ Fortran replacements (_dierckxmodule.cc is the python glue, implementations are in `__fitpack.cc`). This one we want to keep when the Fortran is gone. 
There is no requirement that all FITPACK replacements are exposed through this single extension though.

> in the mermaid here

I tried clicking on the mermaid to enlarge it but it responds with "This private-user-images.githubusercontent.com page can’t be found", <s>could you fix it so that I can try saying something useful?</s> EDIT: found a way; give me a bit to cross out definitely not needed routines.


>  it is not very obvious which function becomes which public API without going through the entire library. 

Yeah. I don't know about mermaids, so I just grep it like this:

- python `bisplrep` function calls `_fitpack._surfit` which wraps `sufit.f.
- `surfit.f` quickly calls `fpsurf` (seems typical for FITPACK), and has a helpful comment, 

> c  other subroutines required:
> c    fpback,fpbspl,fpsurf,fpdisc,fpgivs,fprank,fprati,fprota,fporde

> it does not like if I link to cpp headers from C code

What I'd do, I'd compile your translations as c++ (no code changes needed), and from this point on you can include/link whatever. Anyway, I think we covered this at some point, and you mentioned some reasons not to, so it's up to you really.

---------------

[1] At a guess, one of them predates f2py and the other is contemporaneous with its development?

**Comment by ilayn** [comment]
Image should be fixed now, basically the same as in #18566.

**Comment by ev-br** [comment]
Thanks @ilayn. On that mermaid, we need the following top-level routines and their dependencies:

- surfit
- sphere
- spgrid (unless @czgdp1807 has already found a way to add it to his translation of `regrid` -- hence a question mark in the picture below)
- dblint

If for some reason we cannot make evaluations work with NdBSpline (I honestly don't see big blockers though; if there's an issue with these, please do ping me before spending significant effort), we will also need
- parder
- pardeu
- bispev
- bispeu
- pardtc

merm

The rest of the mermaid is either already covered (1D routines) or has never been wrapped in scipy (pogrid, concon etc; some of these give fairly unique functionality --- spline fits with convexity constraints, anyone --- but we never had it, so these are really optional and only if you're feeling _very_ ambitious Ilhan)

**Comment by ilayn** [comment]
<strike>Currently missing functions, but still wrapped

coming from `_fitpackmodule.c`
 - `clocur` -> `fpclos` (*)

coming from `dfitpack.pyf`
- `splev`
- `splder`
- `sproot` -> `fpcuro`
- `curfit` -> `fpcurfit` (*)
- `spalde` -> `fpader`
- `percur` -> `fpperi` (*)
- `parcur` -> `fppara` (*)
- `fpcurf0` -> `fpcurf`
- `fpcurf1` -> `fpcurf`
- `fpcurfm1` -> `fpcurf`
- `regrid_smth` -> Still needed? 
- `regrid_smth_spher` -> Still needed? </strike>

 (*) marked ones are disgusting. If these are still used, then my feeling is not relevant; it's already quite a big chunk of it. 

I don't quite see what is wrapped (or if anything used) directly from `_dierckxmodule.c`. But seems like nothing is used from F77 code.

**Comment by ev-br** [comment]
> I don't quite see what is wrapped (or if anything used) directly from _dierckxmodule.c. But seems like nothing is used from F77 code.

Not sure what you mean? 

These all are Fortran-free:

```
$ git grep "_dierckx\." scipy/interpolate/
scipy/interpolate/_bsplines.py:        data, offsets, _ = _dierckx.data_matrix(x, t, k, np.ones_like(x), extrapolate)
scipy/interpolate/_bsplines.py:        out = _dierckx.evaluate_spline(self._t, cc, self.k, x, nu, extrapolate)
scipy/interpolate/_bsplines.py:                out = _dierckx.evaluate_spline(ta, ca.reshape(ca.shape[0], -1),
scipy/interpolate/_bsplines.py:                out = _dierckx.evaluate_spline(ta, ca.reshape(ca.shape[0], -1),
scipy/interpolate/_bsplines.py:                out = _dierckx.evaluate_spline(ta, ca.reshape(ca.shape[0], -1),
scipy/interpolate/_bsplines.py:                out = _dierckx.evaluate_spline(ta, ca.reshape(ca.shape[0], -1),
scipy/interpolate/_bsplines.py:            out = _dierckx.evaluate_spline(ta, ca.reshape(ca.shape[0], -1),
scipy/interpolate/_bsplines.py:    interval = _dierckx.find_interval(t, k, float(xval), k, False)
scipy/interpolate/_bsplines.py:        bb = _dierckx.evaluate_all_bspl(t, k, x[0], k, i + 1)
scipy/interpolate/_bsplines.py:        bb = _dierckx.evaluate_all_bspl(t, k, x[-1], n + k - 1, i + 1)[:-1]
scipy/interpolate/_bsplines.py:        bb = _dierckx.evaluate_all_bspl(t, k, xval, left)
scipy/interpolate/_bsplines.py:    left = _dierckx.find_interval(t, k, float(xval), k, False)
scipy/interpolate/_bsplines.py:        wrk = _dierckx.evaluate_all_bspl(t, k, xval, left, nu)
scipy/interpolate/_bsplines.py:    _dierckx._coloc(x[:-1], t, k, ab.T, k)
scipy/interpolate/_bsplines.py:    _dierckx._coloc(x, t, k, ab.T, nleft)
scipy/interpolate/_bsplines.py:        _dierckx._norm_eq_lsq(x, t, k,
scipy/interpolate/_bsplines.py:    R, H1, H2, offset, nc = _dierckx.data_matrix_periodic(x, t, k, w, False)
scipy/interpolate/_bsplines.py:    A1, A2, Z, p, _ = _dierckx.qr_reduce_periodic(
scipy/interpolate/_bsplines.py:    c, residuals, _ = _dierckx.fpbacp(A1, A2, Z, k, k, x, y, t, w)
scipy/interpolate/_bsplines.py:        A, offset, nc = _dierckx.data_matrix(x, t, k, w)
scipy/interpolate/_bsplines.py:        _dierckx.qr_reduce(A, offset, nc, y_w)         # modifies arguments in-place
scipy/interpolate/_bsplines.py:        c, residuals, fp = _dierckx.fpback(A, nc, x, y, t, k, w, y_w)
scipy/interpolate/_bsplines.py:        R, H1, H2, offset, nc = _dierckx.data_matrix_periodic(x, t, k, w, False)
scipy/interpolate/_bsplines.py:        A1, A2, Z, fp = _dierckx.qr_reduce_periodic(
scipy/interpolate/_bsplines.py:        c, residuals, _ = _dierckx.fpbacp(A1, A2, Z, k, k, x, y, t, w)
scipy/interpolate/_fitpack_repro.py:    new_knot = _dierckx.fpknot(x, t, k, residuals)
scipy/interpolate/_fitpack_repro.py:        _dierckx.qr_reduce(AB, offset, nc, QY, startrow=nc)
scipy/interpolate/_fitpack_repro.py:        c, _, fp = _dierckx.fpback(AB, nc, self.x, self.y, self.t, self.k, self.w, QY)
scipy/interpolate/_fitpack_repro.py:        G1, G2, H1, H2, offset = _dierckx.init_augmented_matrices(A1, A2, b, len(t), k)
scipy/interpolate/_fitpack_repro.py:        _dierckx.qr_reduce_augmented_matrices(
scipy/interpolate/_fitpack_repro.py:        c, _, fp = _dierckx.fpbacp(
scipy/interpolate/_ndbspline.py:        out = _dierckx.evaluate_ndbspline(xi,
scipy/interpolate/_ndbspline.py:        data, indices, indptr = _dierckx._coloc_nd(xvals,
scipy/interpolate/tests/test_bsplines.py:        bb = _dierckx.evaluate_all_bspl(t, k, xval, left)
scipy/interpolate/tests/test_bsplines.py:        bb = _dierckx.evaluate_all_bspl(t, k, xval, left)
scipy/interpolate/tests/test_bsplines.py:        _dierckx.qr_reduce(A, offset, nc, y_)      # modifies arguments in-place
scipy/interpolate/tests/test_bsplines.py:        c_banded, _, _ = _dierckx.fpback(R.a, R.nc, x, y_, t, k, np.ones_like(y), y_)
scipy/interpolate/tests/test_bsplines.py:        _dierckx.qr_reduce(A, offset, nc , y_)   # in-place
scipy/interpolate/tests/test_bsplines.py:        A, offset, nc = _dierckx.data_matrix(x, t, k, w)
scipy/interpolate/tests/test_bsplines.py:        A, offset, nc = _dierckx.data_matrix(x, t, k, np.ones_like(x))
scipy/interpolate/tests/test_bsplines.py:        _dierckx.qr_reduce(A, offset, nc, y)
scipy/interpolate/tests/test_bsplines.py:        cc, _, _ = _dierckx.fpback(A, nc, x, y, t, k, np.ones_like(x), y)
```

I'd really recommend that we add python wrappers for `surfit` and see what else is missing in `_fitpack.py` and  `_fitpack2.py`. In particular, there's absolutely no need to touch `*UnivariateSpline` and `spl*` functions: these have been taken care of previously.

**Comment by ilayn** [comment]
I mean the functions I listed are currently exposed by the wrappers. I already said the rest looks fortran free. Not sure what I miscommunicated

**Comment by ev-br** [comment]
> I mean the functions I listed are currently exposed by the wrappers. I already said the rest looks fortran free. Not sure what I miscommunicated

Superb, sorry for the noise then. (goes off to get more coffee)

**Comment by czgdp1807** [comment]
> * spgrid (unless @czgdp1807 has already found a way to add it to his translation of `regrid` -- hence a question mark in the picture below)

Should we target `spgrid` after `regrid`? Our previous plan was to go for `surfit` after we complete `regrid`. Let me know if we need to change that. If `spgrid` is quicker than `surfit`, then making `spgrid` Fortran free can be prioritised.

**Comment by ev-br** [comment]
> Our previous plan

That plan was drafted before Ilhan joined the fun. `surfit` is done in this PR already, and it looks like `spgrid` is on Ilhan's chopping block. If you already have it in the framework of your `regrid` rewrite, please say so. If not, let's keep it for after the Fortran is gone and we can rewrite the algorithms "at leisure".

**Comment by ilayn** [comment]
Added the `spgrid` yesterday, in case relevant. All that is currently missing are the list above. `splev` and `splder` is also done, will push them soon.

Rewrapping all these up will be the annoying bit, Cython or otherwise.

**Comment by ilayn** [comment]
Am I understanding correctly that `regrid` is not needed to be translated now?

**Comment by ev-br** [comment]
> All that is currently missing are the list above

Out of https://github.com/scipy/scipy/pull/24022#issuecomment-3584054524 I believe we have everything apart from `sproot` (which solves for zeros of a cubic parabola via a Cardano formula IIUC).

**Comment by ilayn** [comment]
Oops, CircleCI still has Python 3.11 but 1.18 minimum Python version is 3.12. Should we defer that restriction to a later stage until CircleCI catch up?

**Comment by ilayn** [comment]
I must say, out of all the JurassicPACK code, this is the first time Python side was more difficult than the Fortran side.  I'm quite confident with the C code. There can be minor typos bugs still but I don't expect anything major. 

However Python side and the way we are wrapping these functions is concerning. This is the first time I used C code testing directly from C, instead of our regular machinery because I could not make things work for a long time. 

In particular, 

- we have 5 implementation files, two of them are the new overhaul work of Gagandeep and Evgeni, while underlying machinery is separate, it's quite some mental gymnastics to find the old API. The other three `_fitpack`, `_fitpack2` and `_fitpack_impl` are entangled. 
- These three files wrap same Fortran functions multiple times, `surfit` is once wrapped from the C extension module but it is also wrapped by the f2py with `surfit_lsq` and `surfit_smth`. Same confusion involves `regrid` and `curfit` and some more.
- The old interface is also stateful in case certain drivers are called with `iopt=1`. This makes interpolate module thread unsafe. You can see the `_curfit_cache`, `_surfit_cache` global dictionaries. However there were multiple typos in the cache naming so I think we can conclude that nobody is using these. 

I am not sure what to do but if the old interface is going to be kept then either we need to make iopt=1 usage illegal and remove the caching. Or we need to deprecate the old interfaces. I can't comment on the remaining class as I couldn't figure out what is importing which one yet.

**Comment by ev-br** [comment]
Of `_fitpack_py`, `_fitpack_impl` and `_fitpack2` files:
- `_fitpack2` implements `*UnivariateSpline` and `*BivariateSpline` families
- `_fitpack_impl` implements the "functional" interface, `spl*` and `bispl*` functions.
- `_fitpack_py` is a collections of trampolines which decide between `_fitpack_impl` or `BSpline` (teh latter is Fortran free).

So for Fortran removal you only need to look into `_fitpack2` and `_fitpack_impl`. 

How did we end up with this kind of a mess :-). In short, and omitting several cleanup passes multiple people (Pauli, Andreas Hillboll, Atsushi Sakai, Jake Bowhay, myself and many others) did over time
- two interfaces, "OOP" with f2py wrapping vs "functional" with manual wrapping are from multipack era.
- `iopt = 1` and `_curfit_cache` never worked, full stop. It's from the same multipack era. Never worked AFAICT. Somebody tried fixing them but that had to be reverted. Already a decade ago. Thus, I suspect nobody is using them, since they are just broken and always were. So, either rewrite from scratch or don't touch :-).
- `curfit_smth` vs `curfit_lsq` wraps around the same `iopt=1` functionality; the python-side mapping is `InterpolateUnivariateSpline` vs `LSQUnivariateSpline` etc. Also either rewrite from scratch or don't touch :-).

My opinionated approach was on the "rewrite" side: work on providing sane equivalents (hence BSpline, make_splrep), declare the old stuff _legacy_ and don't touch it with a barge pole.
Deprecating `UnivariateSpline` --- sure let's try it if you're serious about it; previous attempts at even floating this idea were meeting mighty pushbacks from even among the core devs, let alone users.

**Comment by ev-br** [comment]
> can't comment on the remaining class as I couldn't figure out what is importing which one yet

which class is it?

**Comment by ilayn** [comment]
> My opinionated approach was on the "rewrite" side: work on providing sane equivalents (hence BSpline, make_splrep), declare the old stuff legacy and don't touch it with a barge pole.

If your work is slowly rewriting the existing things in a piecemeal fashion that's great. I think that is the way to go.

> Deprecating UnivariateSpline --- sure let's try it if you're serious about it; previous attempts at even floating this idea were meeting mighty pushbacks from even among the core devs, let alone users.

I don't know if we need to deprecate or rewrite the inner parts of it. Also I don't have any capacity to teach myself about the necessary theory. But as an outside persepective, maybe swap the underlying machinery of those classes with your rewrite?

Currently it is layers of classes; so you get an instance by calling corresponding lsq or smth with very strangely named variables and name-swapped over the wire and then `__call__` methods go into bispev, bispeu, parder etc. I don't know if it is my views on DRY principle forming my opinion, but this inheritance pyramid makes things really complicated to analyze the code. A standalone class is much cleaner to maintain in my opinion so that we don't need to fill a generic class with edge cases. The main point is that we can't maintain this, and probably why multiple people poured enourmous effort including yourself, to keep it going. 

> which class is it?

The base class `_BivariateSplineBase` things seem to inherit from it if inheriting classes don't inject their own.

In general, my overall understanding is that we formed the Python API following the Fortran library and that is probably why it smells funny. We should not be needing to do that. So if we are doing something new, let's not follow the legacy API at all and focus on the functionality we are providing. That's the part I don't have much experience in terms of how this is used.

**Comment by ilayn** [comment]
I guess CircleCI Python issue is not going to be resolved soon so should we put this in?

**Comment by ilayn** [comment]
OK fingers crossed then. Thanks Evgeni for the review.

**Comment by lucascolley** [comment]
congratulations @ilayn 🎉

**Comment by dschmitz89** [comment]
Hat tip @ilayn !

**Comment by dschmitz89** [comment]
The refguide check failure in main looks related: https://app.circleci.com/jobs/github/scipy/scipy/130594

CC @ilayn @ev-br 
```
2407 >>> lut = LSQSphereBivariateSpline(lats.ravel(), lons.ravel(),
UNEXPECTED EXCEPTION: ValueError('ier=3156')
Traceback (most recent call last):
  File "/home/circleci/.pyenv/versions/3.13.10/lib/python3.13/doctest.py", line 1398, in __run
    exec(compile(example.source, filename, "single",
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                 compileflags, True), test.globs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<doctest scipy.interpolate.LSQSphereBivariateSpline[19]>", line 1, in <module>
  File "/home/circleci/repo/build-install/usr/lib/python3.13/site-packages/scipy/interpolate/_fitpack2.py", line 2450, in __init__
    raise ValueError(message)
ValueError: ier=3156
/home/circleci/repo/build-install/usr/lib/python3.13/site-packages/scipy/interpolate/_fitpack2.py:2407: UnexpectedException
=========================== short test summary info ============================
FAILED scipy/interpolate/__init__.py::scipy.interpolate.LSQSphereBivariateSpline
================== 1 failed, 1790 passed in 230.70s (0:03:50) ==================
```

**Comment by ilayn** [comment]
Ah OK, it wasn't working in the PR. I'll take a look. I could not replicate this locally though.
