### PR TITLE
BUG: immortalize uarray global strings in order to prevent negative refcounts

### LINKED ISSUE #21214: BUG: _lib: crash in uarray on interpreter exit with a free-threaded interpreter
_From @albanD's report in https://github.com/scipy/scipy/issues/20669#issuecomment-2234284526:_

Running with pydebug build as of two weeks ago and using ua_function, 1.15.0dev0 crashes on exit with
```
(null):0: _Py_NegativeRefcount: Assertion failed: object has negative ref count
<object at 0x2000e12e2b0 is freed>
Fatal Python error: _PyObject_AssertFailed: _PyObject_AssertFailed
Python runtime state: finalizing (tstate=0x00000000009bab80)
```

From @colesbury comment that 3.13t sets all module as being immortal, the explanation is that https://github.com/scipy/scipy/blob/941d5b08614841a213019990b6ceee83a05d6dcc/scipy/_lib/_uarray/_uarray_dispatch.cxx#L1774 never gets called and so the static string from https://github.com/scipy/scipy/blob/941d5b08614841a213019990b6ceee83a05d6dcc/scipy/_lib/_uarray/_uarray_dispatch.cxx#L145 outlives the python runtime while still having a strong reference.
When we get to static variable de-alloc, we end up calling the py_ref destructor https://github.com/scipy/scipy/blob/941d5b08614841a213019990b6ceee83a05d6dcc/scipy/_lib/_uarray/_uarray_dispatch.cxx#L38 (without taking the gil btw) while the python runtime is already dead (and in this case the string already properly de-allocated by the runtime) and thus we detect it to have negative refcount.
Since the m_free not being called is not going to be fixed, I guess the right fix is to have the static variable have an owning reference to the py_obj but explicitly leak it (never call decref on it).

This would be the same treatment being applied to PyTorch's static variables in https://github.com/pytorch/pytorch/pull/130341 and other places like https://github.com/pytorch/pytorch/blob/0b134c15cdf8cb4c2c7ffed1c2b6518de44382bf/torch/csrc/autograd/python_hook.cpp#L105

### PR DESCRIPTION
**Pull request by andfoy**
#### Reference issue

Fixes https://github.com/scipy/scipy/issues/21214
Closes https://github.com/scipy/scipy/pull/21218

#### What does this implement/fix?

This is an alternative PR based off @peterbell10 comment https://github.com/scipy/scipy/pull/21218#pullrequestreview-2466103157 on the original PR that was opened to fix some segfaults that appeared when global `uarray` strings were being released when the Python interpreter was no longer existent.

### CODE REVIEW

File: scipy/_lib/_uarray/_uarray_dispatch.cxx [hunk 1]
```diff
@@ -15,13 +15,43 @@
...
 /** Handle to a python object that automatically DECREFs */
 class py_ref {
-  explicit py_ref(PyObject * object): obj_(object) {}
+  // explicit py_ref(PyObject * object): obj_(object) {}
 
 public:
   py_ref() noexcept: obj_(nullptr) {}
+  py_ref(PyObject * object): obj_(object) {}
   py_ref(std::nullptr_t) noexcept: py_ref() {}
+  py_ref(immortal<py_ref> other): obj_(other->get()) { Py_XINCREF(obj_); }
```
Comment (peterbell10) [inline scipy/_lib/_uarray/_uarray_dispatch.cxx:54]: These should not be necessary. `py_ref` should only ever be created via `steal` or `ref`.

File: scipy/_lib/_uarray/_uarray_dispatch.cxx [hunk 2]
```diff
@@ -114,9 +144,26 @@ struct backend_options {
...
+
+  bool operator!=(const global_backend_options & other) const {
+    return !(*this == other);
+  }
+};
+
 struct global_backends {
-  backend_options global;
-  std::vector<py_ref> registered;
+  global_backend_options global;
```
Comment (peterbell10) [inline scipy/_lib/_uarray/_uarray_dispatch.cxx:165]: Don't make the members `immortal`, make the global variable itself immortal. 
```cpp
static immortal<global_state_t> global_domain_map;
```

File: scipy/_lib/_uarray/_uarray_dispatch.cxx [hunk 3]
```diff
@@ -15,13 +15,43 @@
...
+    const T* get() const { return reinterpret_cast<const T*>(&storage); }
+    const T* get_const() const { return reinterpret_cast<const T*>(&storage); }
+
+
+    const T* operator ->() const { return get(); }
+    // T* operator ->() const { return get(); }
+
+    friend bool operator==(const immortal<T> & lhs, const immortal<T> & rhs) {
+      return lhs.get() == rhs.get();
+    }
```
Comment (peterbell10) [inline scipy/_lib/_uarray/_uarray_dispatch.cxx:42]: Sorry, I missed a few things in my earlier comment. I think this should be more complete
```suggestion
    T* get() { return reinterpret_cast<T*>(&storage); }
    const T* get() const { return reinterpret_cast<const T*>(&storage); }
    const T* get_const() const { return reinterpret_cast<const T*>(&storage); }

    const T* operator ->() const { return get(); }
    T* operator ->() { return get(); }

    T& operator*() { return *get(); }
    const T& operator*() const { return *get(); }
```

File: scipy/_lib/_uarray/_uarray_dispatch.cxx [hunk 4]
```diff
@@ -140,30 +187,30 @@ Using these with PyObject_GetAttr is faster than PyObject_GetAttrString which
...
-  py_ref ua_domain;
-  py_ref ua_function;
+  immortal<py_ref> ua_convert;
+  immortal<py_ref> ua_domain;
+  immortal<py_ref> ua_function;
 
   bool init() {
-    ua_convert = py_ref::steal(PyUnicode_InternFromString("__ua_convert__"));
-    if (!ua_convert)
+    ua_convert = immortal<py_ref>(PyUnicode_InternFromString("__ua_convert__"));
```
Comment (peterbell10) [inline scipy/_lib/_uarray/_uarray_dispatch.cxx:195]: With the `operator*` above, you should be able to do
```suggestion
    *ua_convert = py_ref::steal(PyUnicode_InternFromString("__ua_convert__"));
```

**Review by peterbell10 — CHANGES_REQUESTED** [review]
Should be able to revert most of this PR and change a few `.` to `->` and maybe add a few `*`s.

File: scipy/_lib/_uarray/_uarray_dispatch.cxx [hunk 5]
```diff
@@ -1522,8 +1548,14 @@ PyObject * set_state(PyObject * /* self */, PyObject * args) {
...
-  current_global_state =
-      use_thread_local_globals ? &thread_local_domain_map : &global_domain_map;
+
+  if(use_thread_local_globals) {
+    static immortal<global_state_t> thread_local_copy = immortal<global_state_t>(
+      thread_local_domain_map);
+    current_global_state = &thread_local_copy;
+  } else {
+    current_global_state = &global_domain_map;
+  }
```
Comment (peterbell10) [inline scipy/_lib/_uarray/_uarray_dispatch.cxx:1558]:
```suggestion
  current_global_state =
      use_thread_local_globals ? &thread_local_domain_map : global_domain_map.get();
```

File: scipy/_lib/_uarray/_uarray_dispatch.cxx [hunk 6]
```diff
@@ -129,8 +155,8 @@ using global_state_t = std::unordered_map<std::string, global_backends>;
 using local_state_t = std::unordered_map<std::string, local_backends>;
 
 static py_ref BackendNotImplementedError;
-static global_state_t global_domain_map;
-thread_local global_state_t * current_global_state = &global_domain_map;
+static immortal<global_state_t> global_domain_map;
+thread_local immortal<global_state_t> * current_global_state = &global_domain_map;
```
Comment (peterbell10) [inline scipy/_lib/_uarray/_uarray_dispatch.cxx:159]:
```suggestion
thread_local global_state_t * current_global_state = &global_domain_map;
```

**Review by peterbell10 — COMMENTED** [review]
Looking much better now! Just one issue left.

File: scipy/_lib/_uarray/_uarray_dispatch.cxx [hunk 7]
```diff
@@ -129,8 +155,8 @@ using global_state_t = std::unordered_map<std::string, global_backends>;
 using local_state_t = std::unordered_map<std::string, local_backends>;
 
 static py_ref BackendNotImplementedError;
-static global_state_t global_domain_map;
-thread_local global_state_t * current_global_state = &global_domain_map;
+static immortal<global_state_t> global_domain_map;
+thread_local global_state_t * current_global_state = &*global_domain_map;
```
Comment (peterbell10) [inline scipy/_lib/_uarray/_uarray_dispatch.cxx:159]: Sorry, I meant this
```suggestion
thread_local global_state_t * current_global_state = global_domain_map.get();
```

File: scipy/_lib/_uarray/_uarray_dispatch.cxx [hunk 8]
```diff
@@ -1499,7 +1525,7 @@ PyObject * get_state(PyObject * /* self */, PyObject * /* args */) {
 
   output->locals = local_domain_map;
   output->use_thread_local_globals =
-      (current_global_state != &global_domain_map);
+      (current_global_state != &*global_domain_map);
```
Comment (peterbell10) [inline scipy/_lib/_uarray/_uarray_dispatch.cxx:1528]:
```suggestion
      (current_global_state != global_domain_map.get());
```

**Review by peterbell10 — APPROVED** [review]
LGTM, just a NIT

**Comment by rgommers** [comment]
Can we do both in parallel please? This needs to be backported to 1.15.x still, ideally soon.

**Comment by rgommers** [comment]
Great, thanks a lot @andfoy and @peterbell10, and @hameerabbasi for already taking care of syncing it to Uarray!
