### PR TITLE
BUG: linalg.expm: Fix noncompliant compiler branch typos in C code

### LINKED ISSUE #22558: BUG: linalg.expm: bug on Windows / conda
### Describe your issue.

I am able to reproduce the issue reported in [the forum post "Intrinsic calculation error exists in scipy.linalg.expm"](https://discuss.scientific-python.org/t/intrinsic-calculation-error-exists-in-scipy-linalg-expm/1733) in a fresh conda environment on Windows. The test passes in my development environment on the same machine.

### Reproducing Code Example

```python
from scipy.linalg import expm, logm
import numpy as np

A2 = np.asarray([[ 0.   +0.j   ,  0.087-0.05j ,  0.   +0.j   ,  0.   +0.j   , 0.   +0.j   ],
                 [-0.087-0.05j ,  0.   +0.j   ,  0.122-0.071j,  0.   +0.j   , 0.   +0.j   ],
                 [ 0.   +0.j   , -0.122-0.071j,  0.   +0.j   ,  0.15 -0.087j, 0.   +0.j   ],
                 [ 0.   +0.j   ,  0.   +0.j   , -0.15 -0.087j,  0.   +0.j   , 0.173-0.1j  ], 
                 [ 0.   +0.j   ,  0.   +0.j   ,  0.   +0.j   , -0.173-0.1j  , 0.   +0.j   ]])

np.testing.assert_allclose(logm(expm(A2)), A2, atol=1e-8)
```

Same problem with SciPy 1.15.0, 1.15.1, and 1.15.2, but not 1.14.1.

### Error message

```shell
Mismatched elements: 12 / 25 (48%)
Max absolute difference among violations: 0.20304702
Max relative difference among violations: 1.02072959
 ACTUAL: array([[-4.261118e-16-1.336821e-16j, -6.018066e-04+3.458659e-04j,
         1.723339e-16-7.010722e-17j, -1.958826e-06-5.660793e-04j,
         3.941346e-16-1.434399e-16j],...
 DESIRED: array([[ 0.   +0.j   ,  0.087-0.05j ,  0.   +0.j   ,  0.   +0.j   ,
         0.   +0.j   ],
       [-0.087-0.05j ,  0.   +0.j   ,  0.122-0.071j,  0.   +0.j   ,...

# I also got this warning

>>> from scipy.linalg import expm
<frozen importlib._bootstrap>:488: RuntimeWarning: The global interpreter lock (GIL) has been enabled to load module 'scipy.linalg._linalg_pythran', which has not declared that it can run safely without the GIL. To override this behavior and keep the GIL disabled (at your own risk), run with PYTHON_GIL=0 or -Xgil=0.
```

### SciPy/NumPy/Python version and system information

<details>

```shell
1.15.1 2.2.3 sys.version_info(major=3, minor=13, micro=2, releaselevel='final', serial=0)
C:\Users\matth\miniforge3\envs\scipy_1_15_1\Lib\site-packages\scipy\__config__.py:154: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)
{
  "Compilers": {
    "c": {
      "name": "clang-cl",
      "linker": "lld-link",
      "version": "19.1.6",
      "commands": "clang-cl",
      "linker args": "-Wl,-defaultlib:C:/bld/scipy-split_1736617311302/_build_env/lib/clang/19/lib/windows/clang_rt.builtins-x86_64.lib"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.1.0",
      "commands": "cython"
    },
    "c++": {
      "name": "clang-cl",
      "linker": "lld-link",
      "version": "19.1.6",
      "commands": "clang-cl",
      "linker args": "-Wl,-defaultlib:C:/bld/scipy-split_1736617311302/_build_env/lib/clang/19/lib/windows/clang_rt.builtins-x86_64.lib"
    },
    "fortran": {
      "name": "llvm-flang",
      "linker": "lld-link",
      "version": "19.1.6",
      "commands": "flang-new",
      "args": "-D_CRT_SECURE_NO_WARNINGS, -fms-runtime-lib=dll, -fuse-ld=lld, -IC:\\bld\\scipy-split_1736617311302\\_h_env\\Library\\include",
      "linker args": "-Wl,-defaultlib:C:/bld/scipy-split_1736617311302/_build_env/lib/clang/19/lib/windows/clang_rt.builtins-x86_64.lib, -D_CRT_SECURE_NO_WARNINGS, -fms-runtime-lib=dll, -fuse-ld=lld, -IC:\\bld\\scipy-split_1736617311302\\_h_env\\Library\\include"
    },
    "pythran": {
      "version": "0.17.0",
      "include directory": "..\\..\\_h_env\\Lib\\site-packages\\pythran"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "cross-compiled": false
  },
  "Build Dependencies": {
    "blas": {
      "name": "blas",
      "found": true,
      "version": "3.9.0",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/matth/miniforge3/envs/scipy_1_15_1/Library/include",
      "lib directory": "C:/Users/matth/miniforge3/envs/scipy_1_15_1/Library/lib",
      "openblas configuration": "unknown",
      "pc file directory": "C:\\bld\\scipy-split_1736617311302\\_h_env\\Library\\lib\\pkgconfig"
    },
    "lapack": {
      "name": "lapack",
      "found": true,
      "version": "3.9.0",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/matth/miniforge3/envs/scipy_1_15_1/Library/include",
      "lib directory": "C:/Users/matth/miniforge3/envs/scipy_1_15_1/Library/lib",
      "openblas configuration": "unknown",
      "pc file directory": "C:\\bld\\scipy-split_1736617311302\\_h_env\\Library\\lib\\pkgconfig"
    },
    "pybind11": {
      "name": "pybind11",
      "version": "2.13.6",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/matth/miniforge3/envs/scipy_1_15_1/Library/include"
    }
  },
  "Python Information": {
    "path": "C:\\bld\\scipy-split_1736617311302\\_h_env\\python.exe",
    "version": "3.13"
  }
}
```

</details>

### PR DESCRIPTION
**Pull request by ilayn**
The typos that were being hit by the non-C99-compliant compiler branches are fixed.

#### Reference issue
Closes #22558 

For future reference, the only conda build command I used that succeeded to build on Windows was 

```pwsh
$env:CC="clang";$env:CXX="clang++";$env:FC="flang-new";$env:CXX_LD="lld-link";$env:CC_LD="lld-link";$env:FC_LD="lld-link";python dev.py build
```

that painted a lot with all kinds of warnings. If the linkers are omitted, meson picks up MSVC linker instead.

### CODE REVIEW

File: scipy/linalg/_matfuncs_expm.c [hunk 1]
```diff
@@ -2179,8 +2179,8 @@ pade_UV_calc_z(EXPM_Z* Am, const Py_ssize_t size_n, const int m, int* info)
                 inter1 = _Cmulcr(Am[n2 + n*i + j], b[2]);
                 inter2 = _Cmulcr(Am[2*n2 + n*i + j], b[4]);
                 inter3 = _Cmulcr(Am[3*n2 + n*i + j], b[6]);
-                Am[4*n2 + n*i + j] = CPLX_Z(creal(inter1) + creal(inter2) + creal(inter3),
-                                            cimag(inter1) + cimag(inter2) + cimag(inter3));
+                Am[n2 + n*i + j] = CPLX_Z(creal(inter1) + creal(inter2) + creal(inter3),
```
Comment (ev-br) [inline scipy/linalg/_matfuncs_expm.c:2182]: Can't help wondering if there's a generic solution for these kinds of index/pointer typos. 

(idle wonderings, nothing blocking the PR itself)

Comment (ilayn) [reply scipy/linalg/_matfuncs_expm.c:2182]: A better language would be really nice, or dropping support for non-compliant compilers. I should have tested on Conda but wasn't able to for quite a while. Now with flang-new I managed to reproduce the issue.

**Comment by ilayn** [comment]
Since we don't test SciPy with Clang/cl, I'll go ahead and merge this to get things in order over the non-C99 land. The fail is about the timing of a `stats` test.

@tylerjereddy if possible could we backport this to 1.15? I'll tentatively add the label but feel free to override please.

**Comment by tylerjereddy** [comment]
Understood, we're at 8 merged backport-labeled PRs at the moment, and I believe some of them are for substantial regressions like 40x performance decreases, etc. I suspect if/when I go through and manually label other merged "defect" PRs that number would go up a fair bit.

I'm not sure that I was planning on a `1.15.3`, but could make sense perhaps.

I believe ~April 25th is when I'd sent out the proposed schedule for the `1.16.x` process, but the final release of that is still a way off.
