### PR TITLE
BUG: wrap median_filter stability

### LINKED ISSUE #22250: BUG: median_filter on 1D array crashes with memory corruption using SciPy 1.15.0
### Describe your issue.

When I run `median_filter` on a 1D array, Python crashes. The crash occurs in SciPy 1.15.0. It runs fine in SciPy 1.14.1.

### Reproducing Code Example

```python
import numpy as np
from scipy.ndimage import median_filter

# Create a demo image
np.random.seed(42)  # For reproducibility
image = np.zeros((9044, ))

# Add random noise
noisy_image = image + 0.4 * np.random.random(image.shape)

# Apply median filtering
filtered_image = median_filter(noisy_image, size=10, mode='wrap')
```

### Error message

```shell
$ python3 median.py
corrupted size vs. prev_size
Aborted (core dumped)
```

### SciPy/NumPy/Python version and system information

```shell
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info); scipy.show_config()
1.15.0 1.26.4 sys.version_info(major=3, minor=12, micro=3, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.7/lib/python3.12/site-packages/scipy_openblas32/include
    lib directory: /opt/_internal/cpython-3.12.7/lib/python3.12/site-packages/scipy_openblas32/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.28 DYNAMIC_ARCH NO_AFFINITY Haswell MAX_THREADS=64
    pc file directory: /project
    version: 0.3.28
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.7/lib/python3.12/site-packages/scipy_openblas32/include
    lib directory: /opt/_internal/cpython-3.12.7/lib/python3.12/site-packages/scipy_openblas32/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.28 DYNAMIC_ARCH NO_AFFINITY Haswell MAX_THREADS=64
    pc file directory: /project
    version: 0.3.28
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.13.6
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.11
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  pythran:
    include directory: ../../tmp/pip-build-env-4fhy_u4k/overlay/lib/python3.12/site-packages/pythran
    version: 0.17.0
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /opt/python/cp312-cp312/bin/python
  version: '3.12'
```

### LINKED ISSUE #22325: BUG: ndimage.median_filter: Heap corruption with scipy 1.15
### Describe your issue.

I get a heap corruption on scipy 1.15.0 and 1.15.1 but not on earlier versions (I now use 1.14.1)

I tried python 3.10 , 3.12 and 3.13

I think the code crashes when using scipy.ndimage.median_filter with mode « mirror » bit I haven’t invested that much 

With faulthandler I get:
Windows fatal exception: code 0xc0000374

### Reproducing Code Example

```python
Sorry no reproducing example, seems to only crash when the data is large enough
```

### Error message

```shell
Windows fatal exception: code 0xc0000374

The trace back shows the line where median filter is used
```

### SciPy/NumPy/Python version and system information

```shell
Numpy: 2.0.2
Scipy: 1.15.1
Python: 3.10.8
```

### LINKED ISSUE #22333: BUG: signal.medfilt and ndimage.median_filter not returning correct output
### Describe your issue.

After investigating a regression with some of the tests at work after upgrading from Scipy 1.14.1 to 1.15.1 I noticed some odd behavior in Scipy 1.15.1.

For certain inputs, scipy.signal.medfilt and scipy.ndimage.median_filter will not always return the correct input (kinda random).

For example, if I try to median filter the following sequence with a kernel size 9 and zero padding: `[272, 58, 67, 163, 463, 608, 87, 108, 1378]`
I sometimes get this wrong result `[58, 67, 87, 108,  *272*, 108, 108, 108, 87]`
instead of this correct result: `[ 58, 67, 87, 108, *163*, 108, 108, 108,  87]`
This example can take multiple runs to reproduce.

I have another example though that can somewhat reliably reproduce this issue. See the reproducing code example below

### Reproducing Code Example

```python
import numpy as np
from scipy.signal import medfilt
from scipy.ndimage import median_filter


# An input that can somewhat reliably reproduce the bug in a short amount of iterations
# I also managed to replicate this issue for x = [272, 58, 67, 163, 463, 608, 87, 108, 1378] with kernel size 9 though
# I had to rerun the script multiple times for the wrong result to appear. In all cases of wrong results, I got
# [58, 67, 87, 108,  *272*, 108, 108, 108, 87] instead of [58, 67, 87, 108, *163*, 108, 108, 108, 87]
x = [272, 58, 67, 163, 463, 608, 87, 108, 1378, 72, 136, 566, 747, 122, 249, 302, 48, 181, 60, 104, 119, 206, 349, 223, 58, 105, 116, 136, 114, 386, 108, 112, 127, 91, 120, 110, 117, 117, 63, 65, 128, 97, 96, 99, 124, 107, 105, 122, 121, 129, 77, 104, 141, 132, 216, 301, 130, 113, 92, 89, 99, 311, 405, 41, 89, 103, 5044, 116, 71, 96, 92, 123, 4561, 84]

# Expected result after median filtering with kernel size 9 (zero-padded edges), computed using Scipy 1.14.1
# Especially note that the result from Scipy 1.15.1 is often wrong in the fifth element (y[4] != expected[4]),
# with value 272 instead of 163
expected = [58, 67, 87, 108, 163, 108, 136, 163, 463, 136, 136, 249, 249, 181, 181, 181, 122, 122, 181, 181, 119, 119, 116, 119, 119, 136, 116, 114, 114, 114, 116, 114, 114, 117, 112, 112, 117, 110, 110, 99, 99, 99, 99, 105, 107, 107, 107, 107, 121, 121, 122, 129, 130, 130, 130, 130, 130, 130, 130, 113, 99, 99, 99, 103, 103, 103, 96, 96, 103, 103, 96, 92, 84, 84]


for idx in range(1_000):
    np.testing.assert_array_equal(medfilt(x, 9), expected)

    # uncomment this line and comment line above to test scipy.ndimage.median_filter
    #np.testing.assert_array_equal(median_filter(x, 9, mode="constant"), expected)
```

### Error message

```shell
For medfilt:

Traceback (most recent call last):
  File "/home/kristofer/worktrees/develop/bug_demo.py", line 19, in <module>
    np.testing.assert_array_equal(medfilt(x, 9), expected)
  File "/home/kristofer/worktrees/develop/dist/export/python/virtualenvs/python-default/3.12.3/lib/python3.12/site-packages/numpy/_utils/__init__.py", line 85, in wrapper
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/kristofer/worktrees/develop/dist/export/python/virtualenvs/python-default/3.12.3/lib/python3.12/site-packages/numpy/testing/_private/utils.py", line 1020, in assert_array_equal
    assert_array_compare(operator.__eq__, actual, desired, err_msg=err_msg,
  File "/home/kristofer/worktrees/develop/dist/export/python/virtualenvs/python-default/3.12.3/lib/python3.12/site-packages/numpy/testing/_private/utils.py", line 884, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

Mismatched elements: 1 / 74 (1.35%)
Max absolute difference among violations: 109
Max relative difference among violations: 0.66871166
 ACTUAL: array([ 58,  67,  87, 108, 272, 108, 136, 163, 463, 136, 136, 249, 249,
       181, 181, 181, 122, 122, 181, 181, 119, 119, 116, 119, 119, 136,
       116, 114, 114, 114, 116, 114, 114, 117, 112, 112, 117, 110, 110,...
 DESIRED: array([ 58,  67,  87, 108, 163, 108, 136, 163, 463, 136, 136, 249, 249,
       181, 181, 181, 122, 122, 181, 181, 119, 119, 116, 119, 119, 136,
       116, 114, 114, 114, 116, 114, 114, 117, 112, 112, 117, 110, 110,...


For median_filter:
Traceback (most recent call last):
  File "/home/kristofer/worktrees/develop/bug_demo.py", line 22, in <module>
    np.testing.assert_array_equal(median_filter(x, 9, mode="constant"), expected)
  File "/home/kristofer/worktrees/develop/dist/export/python/virtualenvs/python-default/3.12.3/lib/python3.12/site-packages/numpy/_utils/__init__.py", line 85, in wrapper
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/kristofer/worktrees/develop/dist/export/python/virtualenvs/python-default/3.12.3/lib/python3.12/site-packages/numpy/testing/_private/utils.py", line 1020, in assert_array_equal
    assert_array_compare(operator.__eq__, actual, desired, err_msg=err_msg,
  File "/home/kristofer/worktrees/develop/dist/export/python/virtualenvs/python-default/3.12.3/lib/python3.12/site-packages/numpy/testing/_private/utils.py", line 884, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

Mismatched elements: 1 / 74 (1.35%)
Max absolute difference among violations: 109
Max relative difference among violations: 0.66871166
 ACTUAL: array([ 58,  67,  87, 108, 272, 108, 136, 163, 463, 136, 136, 249, 249,
       181, 181, 181, 122, 122, 181, 181, 119, 119, 116, 119, 119, 136,
       116, 114, 114, 114, 116, 114, 114, 117, 112, 112, 117, 110, 110,...
 DESIRED: array([ 58,  67,  87, 108, 163, 108, 136, 163, 463, 136, 136, 249, 249,
       181, 181, 181, 122, 122, 181, 181, 119, 119, 116, 119, 119, 136,
       116, 114, 114, 114, 116, 114, 114, 117, 112, 112, 117, 110, 110,...
```

### SciPy/NumPy/Python version and system information

```shell
I managed to reproduce this issue on Windows 11 (not WSL) using Python 3.13, Scipy 15.1, and Numpy 2.21.

I also managed to reproduce this issue using Python 3.12 on Ubuntu 24.04 running in WSL:
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info); scipy.show_config()
1.15.1 2.2.1 sys.version_info(major=3, minor=12, micro=3, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.7/lib/python3.12/site-packages/scipy_openblas32/include
    lib directory: /opt/_internal/cpython-3.12.7/lib/python3.12/site-packages/scipy_openblas32/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.28 DYNAMIC_ARCH NO_AFFINITY Haswell MAX_THREADS=64
    pc file directory: /project
    version: 0.3.28
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.7/lib/python3.12/site-packages/scipy_openblas32/include
    lib directory: /opt/_internal/cpython-3.12.7/lib/python3.12/site-packages/scipy_openblas32/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.28 DYNAMIC_ARCH NO_AFFINITY Haswell MAX_THREADS=64
    pc file directory: /project
    version: 0.3.28
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.13.6
    name: gcc
    version: 10.2.1
  pythran:
    include directory: ../../tmp/pip-build-env-p8gqjxwf/overlay/lib/python3.12/site-packages/pythran
    version: 0.17.0
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /opt/python/cp312-cp312/bin/python
  version: '3.12'
```

### PR DESCRIPTION
**Pull request by tylerjereddy**
* Fixes gh-22250
* Fixes gh-22325
* Fixes gh-22333

* The shims in this branch ~seem to substantially improve the probability of the new~ allow `test_gh_22250` to pass under high repeat counts with `pytest-repeat` on Linux. ~There still seems to be a memory instability that leads to stochastically incorrect results between test incantations though.~

* ~I wonder if any of the memory issues Warren mentions at gh-22365 might be related to the instability (Warren suggests the *crashes* are not related, but I'm no longer seeing crashes on Linux on this branch).~ (kind of, Warren mentioned unchecked memory for `data`, but it was specifically the lack of *initialization*/zeroing out that was causing algorithmic problems on Linux, separate from the index segfault).

~[ci skip] [skip cirrus]~

### CODE REVIEW

File: scipy/ndimage/src/_rank_filter_1d.cpp [hunk 1]
```diff
@@ -180,7 +181,13 @@ void _rank_filter(T *in_arr, int rank, int arr_len, int win_len, T *out_arr,
     }
     break;
   case WRAP:
-    for (i = arr_len - lim - 1 - 2 * origin; i < arr_len; i++) {
+    if (win_len % 2 == 0) {
+        offset = 2;
+    }
+    else {
+        offset = 0;
+    }
```
Comment (tylerjereddy) [inline scipy/ndimage/src/_rank_filter_1d.cpp:189]: this block is based on an analysis of the indices visited by `median_filter` in the default `reflect` mode because of the patterning similarities between the two approaches from the docs:

> ‘reflect’ d c b a | a b c d | d c b a
> ‘wrap’  a b c d | a b c d | a b c d

kind of a "flipped" order to boundary handling.

This is a bit of a fishing expedition though.

**Comment by tylerjereddy** [comment]
On ARM Mac, `python dev.py test -t scipy/ndimage/tests/test_filters.py::test_gh_22250 -- --count=1000` passes on this branch, while on Linux it variably produced 382 failures (all for a filter size of `20` that matches the image itself) and 397 failures (mostly size `20` failures, but 1 filter size `15` failure) over two incantations.

Reverting the patch on MacOS ARM results in segfaults.

That might be a decent clue that memory shenanigans and/or something different compilers can optimize differently might be to blame on this branch rather than a fundamental algorithmic misunderstanding (though I probably should add even more `1.14.1`-based test cases given that I'm not operating from a place of deep expertise).

**Comment by tylerjereddy** [comment]
Switching to `clang` compiler toolchain (`FC=gfortran-11 CC=clang-15 CXX=clang++-15`) for a clean build on Linux doesn't resolve the test failures. Hmm, so fundamental memory management issue rather than compiler-specific behavior perhaps?

**Comment by tylerjereddy** [comment]
If I link against address sanitizer on Linux and `LD_PRELOAD` `libasan.so`, the tests pass reliably on Linux over thousands of repeat incantations. The actual output from the sanitizer seems completely unhelpful though, and it also detects leaks in other completely unrelated test modules.

Nonetheless, IIUC, the preload intercepts and overrides `malloc`, so that is probably evidence that memory allocation is indeed the remaining issue.

**Comment by ev-br** [comment]
> it also detects leaks in other completely unrelated test modules.

Quoting from Tyler in an unrelated thread: Open separate issues for separate issues? :-)

File: scipy/ndimage/src/_rank_filter_1d.cpp [hunk 2]
```diff
@@ -155,8 +155,13 @@ void _rank_filter(T *in_arr, int rank, int arr_len, int win_len, T *out_arr,
                   int mode, T cval, int origin) {
   int i, arr_len_thresh, lim = (win_len - 1) / 2 - origin;
   int lim2 = arr_len - lim;
+  int offset;
   Mediator *m = MediatorNew(win_len, rank);
   T *data = new T[win_len];
+  for (int i = 0; i < win_len; ++i) {
+    data[i] = 0;
+  }
```
Comment (tylerjereddy) [inline scipy/ndimage/src/_rank_filter_1d.cpp:163]: After *many* more hours of debugging, and static analyzers proving useless, this block of code seems to do the trick. `data` is uninitialized memory, and the treatment of such memory apparently differs on many Linux platforms vs. MacOS, explaining why `pytest-repeat` was stochastically exhibiting algorithmic failures.

With this addition shim, `test_gh_22250` passes with thousands of repeat incantations on my Linux box vs. failing before.

I'll open this PR for review now and see if the CI agrees with me (there are two unrelated `test_batch.py` failures I see locally on `main` as well).

There are many open issues about this machinery, so if there is interest in this patch, I'd appreciate suggestions for which additional test(s) you'd like me to add in (from specific issues, multi-dimensional cases as well? etc.).

File: scipy/ndimage/src/_rank_filter_1d.cpp (hunk 1 above)
Comment (tylerjereddy) [reply scipy/ndimage/src/_rank_filter_1d.cpp:193]: One point of caution--with the memory initialization issue repaired, I no longer need this patch, though the patch is also not harmful with the current suite of tests that we have.

Objectively that probably means that we should remove this part of the shim. That said, it may also be sensible to expand the testing to include non-zero `origin` values vs. `1.14.1` and n-dims vs. `1.14.1` because the lack of sensitivity on the indexing here makes me a bit suspicious.

**Review by ev-br — APPROVED** [review]
Wow, that was a hard catch!

Confirmed that locally this PR avoids the segfault from gh-22250. The CI seems to agree, modulo an unrelated failure which is safe to ignore. 

FWIW, I don't think `ndim > 1` tests are essential here, given that the problematic addition of scipy 1.5.1 is specifically a 1D shortcut.

Looking through related issues: 
- https://github.com/scipy/scipy/issues/22325 does not have a reproducible example, and is quite likely to be the same, so IMO it's OK to add `closes gh-22325` on this PR unless there's evidence to the contrary
- Warren's MWE at https://github.com/scipy/scipy/issues/22333#issuecomment-2603037534 seems to be fixed by this PR
- https://github.com/scipy/scipy/issues/22365 highlights several issues which, as Warren notes, are unlikely to be related; I'd agree addressing these in this PR is optional.

All in all, I'd be +1 for landing this as is for 1.5.2, and addressing  https://github.com/scipy/scipy/issues/22365 in a less hectic pace in the 1.6.0 timeframe.

**Comment by j-bowhay** [comment]
Also possibly closes #22368 and #22333

**Comment by tylerjereddy** [comment]
@WarrenWeckesser opinion?

**Comment by tylerjereddy** [comment]
> Also possibly closes https://github.com/scipy/scipy/issues/22368 and https://github.com/scipy/scipy/issues/22333

For gh-22368, I found no evidence that my patch is helpful per analysis at https://github.com/scipy/scipy/issues/22368#issuecomment-2657888558

For gh-22333, the patch here indeed resolves the problem on x86_64 Linux per analysis at https://github.com/scipy/scipy/issues/22333#issuecomment-2657923377. I've added adjusted the original comment above accordingly and added the additional regression test for that issue.

I'm somewhat-tempted to consider self-merging this for the `1.15.2` release if this remains free of objections. The biggest objection is my own at https://github.com/scipy/scipy/pull/22402#discussion_r1929887109, I hate having code changes that are poorly understood and not even changing the test results like that. If we backed that out, would need to be careful to `pytest-repeat`-based probe the new regression tests to be sure it wasn't helping.

**Comment by WarrenWeckesser** [comment]
@tylerjereddy, I probably won't be able to get back to this until sometime next week, so don't wait for me if you need to wrap this up sooner.

**Comment by dschmitz89** [comment]
I can't review but this bug is hitting a lot of people and this seems to resolve it based on the tests. I am +1 for back porting into 1.15.2.

**Comment by tylerjereddy** [comment]
The CI failures are unrelated and covered by the issue Matt opened recently at gh-22534. Given the swath of issues this fixes, the two core developer "approvals," and seriousness of the bugs fixed (segfaults possible on Linux), I think I'll go ahead and squash merge for backporting despite this being a sub-optimal self-merge activity.

I suspect what is going to happen is that the lack of understanding around https://github.com/scipy/scipy/pull/22402#discussion_r1929887109 will come back to bite us someday, but I think this at least has support as an incremental improvement we could get more feedback on while preventing some bad results/segfaults.
