### PR TITLE
BUG: special: Use Boost for ncfdtr, fixing accuracy issues

### LINKED ISSUE #15582: BUG: `special.ncfdtr(dfn, dfd, nc, f)`  and `stats.ncf.cdf(x, dfn, dfd, nc)` results are different from R and Matlab results.
### Describe your issue.

Calculated results are not equal to that of R and Matlab

`stats.ncf.cdf(20, 6,33,30.4) = '
0.998868`

but in R
`pf(20, df1 = 6, df2 = 33, ncp = 30.4) = 
0.998921`

In Matlab
`ncfcdf(20,  6, 33, 30.4) =
0.998921`

### Reproducing Code Example

```python
No
```

### Error message

```shell
No
```

### SciPy/NumPy/Python version information

scipy.__version__ '1.6.2'

### PR DESCRIPTION
**Pull request by steppi**
#### Reference issue

Closes #15582, ticks a box for #20223 

#### What does this implement/fix?

This PR changes the scalar kernel for `ncfdtr` to use a wrapper of the more accurate Boost implementation which was already being used in stats for `ncf.cdf`. Previously there were two ufuncs a public `ncfdtr` using cdflib, and a private `_ncf_cdf` using Boost. I've changed it so there is no only one ufunc, `ncfdtr` which uses Boost. I had to change the argument order for `_ncf_cdf`, which differed from that of `ncfdtr`, but this was not difficult because `_ncf_cdf` is only used in one place in stats. I also had to add `NAN` handling in the Boost wrapper.

I had to `xfail` round trip tests for `ncfdtri`, `ncfdtridfn`, `ncfdtridfn`, and `ncfdtrinc`, because these functions invert the less accurate `cdflib` implementation of `ncfdtr`, and therefore now fail. We can fix this after https://github.com/scipy/scipy/pull/21454 lands and we are able to have these functions invert the Boost implementation now being used.

I added some tests comparing `ncfdtr` against an `mpmath` reference. 11 of the 12 test cases I added fail on main. Locally I tested a larger range consisting of 625 cases. On `main` the deciles for relative error over these cases are

```
array([0.00000000e+00, 1.15300845e-14, 4.37093510e-13, 5.72470839e-10,
       1.48813582e-08, 7.50889455e-08, 2.50213950e-07, 1.19707132e-06,
       1.48768369e-05, 3.80639979e-05, 2.12464729e-04])
```

using Boost, the deciles for relative error are

```
array([0.00000000e+00, 0.00000000e+00, 1.40500993e-16, 2.52732515e-16,
       4.34020841e-16, 6.33097261e-16, 1.09243091e-15, 1.53843495e-15,
       2.34037246e-15, 6.13809455e-15, 8.41339873e-14])
```

The max relative error for Boost is better than the 20th percentile for cdflib.

The script generating the test cases is in the comments for the test I added to `special/tests/test_cdflib.py`.
#### Additional information
As suggested by @dschmitz89 here, https://github.com/scipy/scipy/issues/15582#issuecomment-2177581310, we should follow up by using the Boost implementations instead of cdflib when stats is already using Boost, and investigate Boost or other alternatives to cdflib for other functions.)

### CODE REVIEW

File: scipy/special/boost_special_functions.h [hunk 1]
```diff
@@ -760,18 +760,22 @@ ncf_pdf_double(double x, double v1, double v2, double l)
 
 template<typename Real>
 Real
-ncf_cdf_wrap(const Real x, const Real v1, const Real v2, const Real l)
+ncf_cdf_wrap(const Real v1, const Real v2, const Real l, const Real x)
```
Comment (mdhaber) [inline scipy/special/boost_special_functions.h:763]: Could you explain what is going on here? `ncf_cdf_float` and `ncf_cdf_double` are calling this function with arguments like `ncf_cdf_wrap(x, v1, v2, l)`, but it looks like these are ordered differently. Also, the arguments accepted by `ncf_cdf_float` and `ncf_cdf_double` appear to be in a different order.

File: scipy/special/cython_special.pxd [hunk 2]
```diff
@@ -190,7 +190,7 @@ cpdef double nbdtrc(dlp_number_t x0, dlp_number_t x1, double x2) noexcept nogil
 cpdef double nbdtri(dlp_number_t x0, dlp_number_t x1, double x2) noexcept nogil
 cpdef double nbdtrik(double x0, double x1, double x2) noexcept nogil
 cpdef double nbdtrin(double x0, double x1, double x2) noexcept nogil
-cpdef double ncfdtr(double x0, double x1, double x2, double x3) noexcept nogil
+cpdef df_number_t ncfdtr(df_number_t x0, df_number_t x1, df_number_t x2, df_number_t x3) noexcept nogil
```
Comment (mdhaber) [inline scipy/special/cython_special.pxd:193]: I don't know what this means, but I'm happy to assume it is the right thing.

File: scipy/special/tests/test_basic.py [hunk 3]
```diff
@@ -716,22 +716,46 @@ def test_nbdtrin(self):
...
+    @pytest.mark.xfail(
+        reason=(
+            "ncfdtr uses a Boost math implementation but ncfdtri"
+            "inverts the less accurate cdflib implementation of ncfdtr."
+        )
+    )
     def test_ncfdtri(self):
         assert_equal(cephes.ncfdtri(1, 1, 1, 0), 0.0)
         f = [0.5, 1, 1.5]
         p = cephes.ncfdtr(2, 3, 1.5, f)
```
Comment (mdhaber) [inline scipy/special/tests/test_basic.py:728]: Can we make it a little more obvious that this is not actually using Cephes by (importing and) using ufuncs by the usual name? 
```suggestion
        p = scu.ncfdtr(2, 3, 1.5, f)
```

File: scipy/special/tests/test_cdflib.py [hunk 4]
```diff
@@ -525,3 +524,64 @@ def test_bdtrik_nbdtrik_inf():
...
+    #
+    # import numpy as np
+    #
+    # from mpmath import mp
+    # from scipy.special import ncfdtr
+    #
+    # mp.dps = 100
+    #
+    # def mp_ncfdtr(dfn, dfd, nc, f):
+    #     # Uses formula 26.2.20 from Abramowitz and Stegun.
```
Comment (mdhaber) [inline scipy/special/tests/test_cdflib.py:555]: Could you share that formula?

File: scipy/special/tests/test_cdflib.py [hunk 5]
```diff
@@ -525,3 +524,64 @@ def test_bdtrik_nbdtrik_inf():
...
+    # cases = []
+    # re = []
+    # for x0, x1, x2, x3 in zip(*(dfn, dfd, nc, f)):
+    #     observed = ncfdtr(x0, x1, x2, x3)
+    #     expected = mp_ncfdtr(x0, x1, x2, x3)
+    #     cases.append((x0, x1, x2, x3, expected))
+    #     re.append((abs(expected - observed)/abs(expected)))
+    #
+    # assert np.max(re) < 1e-13
+    #
```
Comment (mdhaber) [inline scipy/special/tests/test_cdflib.py:583]: So this is just verifying many more cases, and you pick a few to keep at random?

File: scipy/special/boost_special_functions.h (hunk 1 above)
Comment (steppi) [reply scipy/special/boost_special_functions.h:763]: Looks like a mistake on my part. Because they were worked on separately, `ncfdtr` and the boost wrapping ufunc `_ncf_cdf` take a different order for the arguments, and I messed up trying to standardize on the `ncfdtr‘ order, but I guess in such a way that my mistakes cancelled out and the tests still pass. Not at a computer now, but I’ll fix this.

File: scipy/special/cython_special.pxd (hunk 2 above)
Comment (steppi) [reply scipy/special/cython_special.pxd:193]: Fused type in Cython. Let’s the function take both double or float and dispatch to the right one. It’s like a bootleg way of handling what templates can do in C++.

File: scipy/special/tests/test_basic.py (hunk 3 above)
Comment (steppi) [reply scipy/special/tests/test_basic.py:728]: Yeah, but I think it should be in a separate PR for all of them. This is a historical remnant from when Travis first did special and it only wrapped cephes. I guess no one wanted to change all of the cephes to special or something, so this has been like this for 20+ years.

File: scipy/special/tests/test_cdflib.py (hunk 4 above)
Comment (steppi) [reply scipy/special/tests/test_cdflib.py:555]: Sure. It’s in the docstring for ncfdtr. I can put a link to it in the comment. The only reason I didn’t is because it makes the line very long, but I can noqa it.

File: scipy/special/tests/test_cdflib.py (hunk 5 above)
Comment (steppi) [reply scipy/special/tests/test_cdflib.py:583]: Yes. That’s right

File: scipy/special/tests/test_basic.py (hunk 3 above)
Comment (mdhaber) [reply scipy/special/tests/test_basic.py:728]: I don't mean for all occurences in the file, just this one, since the comment specifically says "ncfdtr uses a Boost math implementation" whereas it looks like it's using `cephes`.

File: scipy/special/tests/test_cdflib.py (hunk 4 above)
Comment (mdhaber) [reply scipy/special/tests/test_cdflib.py:555]: I just mean here on GitHub, like screenshot?

Comment (steppi) [reply scipy/special/tests/test_cdflib.py:555]: Ah, got you. 

image

File: scipy/special/tests/test_basic.py (hunk 3 above)
Comment (steppi) [reply scipy/special/tests/test_basic.py:728]: I know, I mean I’d rather fix it for all of them at once in a different PR. This didn’t come from cephes before this PR either. I think most of these things don’t come from cephes. Someone just decided to make cephes an alias for special to avoid having to do a find and replace. What we have now is at least consistent with the mad logic of this file. I can follow up with a PR fixing it for everything after this one goes in if you’d be willing to review.

Comment (steppi) [reply scipy/special/tests/test_basic.py:728]: At my computer now, (but hopefully you're asleep). The reason I'd rather keep this as `cephes` until their all fixed instead of making just `ncfdtr` say `special`  is because then in this block it will make it look doubly so that all of the functions except `ncfdtr` listed here come from `cephes`, when out of the seven of them, only `nbdtr` does.

```python
    def test_nbdtr(self):
        assert_equal(cephes.nbdtr(1,1,1),1.0)

    def test_nbdtrc(self):
        assert_equal(cephes.nbdtrc(1,1,1),0.0)

    def test_nbdtri(self):
        assert_equal(cephes.nbdtri(1,1,1),1.0)

    def test_nbdtrik(self):
        cephes.nbdtrik(1,.4,.5)

    def test_nbdtrin(self):
        assert_equal(cephes.nbdtrin(1,0,0),5.0)

    def test_ncfdtr(self):
        assert_equal(special.ncfdtr(1,1,1,0),0.0)

    @pytest.mark.xfail(
        reason=(
            "ncfdtr uses a Boost math implementation but ncfdtri"
            "inverts the less accurate cdflib implementation of ncfdtr."
        )
    )
    def test_ncfdtri(self):
        assert_equal(cephes.ncfdtri(1, 1, 1, 0), 0.0)
        f = [0.5, 1, 1.5]
        p = cephes.ncfdtr(2, 3, 1.5, f)
        assert_allclose(cephes.ncfdtri(2, 3, 1.5, p), f)
```

Comment (mdhaber) [reply scipy/special/tests/test_basic.py:728]: K. 
I'd be willing to review the PR if it's just fine and replace.

**Comment by mdhaber** [comment]
> I had to xfail round trip tests for ncfdtri, ncfdtridfn, ncfdtridfn, and ncfdtrinc, because these functions invert the less accurate cdflib implementation of ncfdtr, and therefore now fail.

Just thought I'd mentioned that `ncfdtri` could be replaced with Boost's NCF `quantile`, though, if desired.

File: scipy/special/tests/test_cdflib.py (hunk 4 above)
Comment (mdhaber) [reply scipy/special/tests/test_cdflib.py:555]: Implementation LGTM

**Comment by steppi** [comment]
> Just thought I'd mentioned that `ncfdtri` could be replaced with Boost's NCF `quantile`, though, if desired.

Great suggestion.

**Review by mdhaber — APPROVED** [review]
I'm not an expert for the compiled stuff, but it looks good AFAICT, and the things I'm not able to assess at all look formulaic, so I think they are safe if the code compiles and runs. The xfails seem appropriate unless you want to use the distribution's `quantile` method for `ncfdtri`. I checked that `mpmath` produces the values listed in the test, and I checked the reference implementation of the NCF CDF. LGTM!

File: scipy/special/boost_special_functions.h (hunk 1 above)
Comment (dschmitz89) [reply scipy/special/boost_special_functions.h:763]: @steppi : could you add a short sentence about the discrepancy in the argument order between `stats.nct.cdf` and `special.nctdtr`? Such things are for sure a constant source of confusion for users if maintainers already are confused themselves.

**Comment by dschmitz89** [comment]
The docstring still mentions that `nc<1e-4`. I think boost handles large `nc` correct though.

**Comment by steppi** [comment]
> The docstring still mentions that `nc<1e4`. I think boost handles large `nc` correct though.

Good catch.

**Comment by steppi** [comment]
> Last note: might be worth pinging the statsmodels maintainers who faced most of the fallout of rewriting these cdflib functions.

Thanks, that's important. I'll also test if there are any regressions in their test suite locally.

**Comment by steppi** [comment]
OK, after looking into `ncfdtri`, for which Boost can throw errors even when valid input are given (overflow etc.) I found that the differences in error handling between the private `stats` scalar kernels and the `special` scalar kernels is significant enough, that I don't think it's OK to unify `ncfdtr` and `_ncf_cdf` in this PR. I suspect the error handling is different in `stats` just because the Boost functions in stats were originally in separate extension module which was worked on independently from `special`, and `special`'s error handling would be sufficient. I don't want to touch that here though, so I guess the best thing to do is just maintain duplicate versions like we do for `betainc`, and circle back later to unify the Boost policies and make everything work.

**Comment by steppi** [comment]
I got around to running the `statsmodels` tests. If we don't do both `ncfdtr` and `ncfdtri` this will make some `statsmodels` tests to fail for the same reason it made some our tests fail, inaccurate roundtrip comparison.

Alright, I'm just going to go for it. Also, I  was wrong about us maintaining two `betaincs` anyway. We just use `special.betainc` for `stats.beta.cdf`, so I guess it's fine for error handling to work like it does in `special` and we don't need to maintain the behavior of the current stats Boost wrappers. (In `special` in general you can warn, print, or ignore various error types using `special.seterr` or the `special.errstate` context manager and the default is `ignore`. In the private Boost wrappers we've been using in stats, you get a runtime warning that can't be silenced as far as I can tell.)

https://github.com/scipy/scipy/blob/4dcde22c8ddb41ed11d6324aeb87170a23d70de4/scipy/stats/_continuous_distns.py#L747-L748

File: scipy/special/boost_special_functions.h [hunk 6]
```diff
@@ -760,46 +760,94 @@ ncf_pdf_double(double x, double v1, double v2, double l)
...
+	 * error, but domain errors are already handled earlier in the wrapper. If
+	 * this try-catch block catches something, that would be unexpected, but it
+	 * feels wrong to call to Boost directly without a try-catch block when
+	 * SpecialPolicy is being used.
+	 */
+	y = boost::math::cdf(
+                boost::math::non_central_f_distribution<Real, SpecialPolicy>(v1, v2, l), x);
+    } catch (...) {
+        sf_error("ncfdtr", SF_ERROR_OTHER, NULL);
+        y = NAN;
```
Comment (steppi) [inline scipy/special/boost_special_functions.h:793]: I've discovered there are some cases that the cdflib implementation can kind of handle that the new one cannot. They are extreme cases though, one is

```
ncfdtr(1e-100, 3, 1.5, 1e100)
# on main: np.float64(0.611813014416088)
# on this branch: np.float64(nan)

# mpmath reference implementation discussed earlier
mp_ncfdtr(1e-100, 3, 1.5, 1e100)
# 0.611815287345399
```

With a boost math evaluation error getting caught in this catch-all here. Ideally what we could do is fall back to the cdflib implementation here (and in the similar catch-all in `ncfdtri`) and set `SF_ERROR_LOSS` signaling reduced precision. Right now the cdflib implementation is defined in ` .pxd` file and I think it would be difficult to make this work. The good news is that I've already translated most of cdflib into C++ headers, but just haven't PR'd any of that work, and then we could just include the relevant header here, or restructure things in some other way. I think I might be OK with temporarily return NAN for such extreme cases until enough of my cdflib translation work lands.

**Review by steppi — COMMENTED** [review]
I've confirmed that the `statsmodels` tests now all pass when `ncfdtr` and `ncfdtri` are both changed to use Boost implementations. @josef-pkt, we want to make sure aware of this PR and have no objections before this goes in. We're looking to update `ncfdtr` and `ncfdtri` to use implementations from Boost Math instead of cdflib. Relative error improves dramatically, as can be seen in a comment above, but there are some extreme cases where cdflib can get at least a few digits of precision that Boost cannot handle at all. There's a path to adding a fallback to cdflib for such extreme cases though. The extreme cases correspond to having vanishingly small degrees of freedom in the numerator or denominator, and looking very far in the tail.  

For anyone interested, any thoughts on whether it's Ok if `ncfdtr` is temporarily unable to handle such extreme cases, or if it should be considered a blocker? Implementing a `cdflib` fallback with the state of things now seems like it would be messy.

**Comment by steppi** [comment]
Of the test failures that appeared one was simple to fix, I had accidentally made the range of the `nc` parameter `(0, inf)` instead of `[0, inf)`. The other is more interesting. Currently there is a check for a runtime warning for `ncf.ppf` in `scipy.stats.test_distributions` https://github.com/scipy/scipy/blob/608b05eb9f88a7300f6fcd935375bbcb6bb9a90c/scipy/stats/tests/test_distributions.py#L9160-L9170

the runtime warning looks like this

```
In [7]: q = ncf.ppf(x, *par)
/home/birbir/scipy/build-install/lib/python3.12/site-packages/scipy/stats/_continuous_distns.py:7725: RuntimeWarning: Error in function quantile(non_central_beta_distribution<d>, %1%): Unable to locate solution in a reasonable time: either there is no answer to quantile of the non central beta distribution or the answer is infinite.  Current best guess is %1%
  return scu._ncf_ppf(q, dfn, dfd, nc)
```

how important is it to keep this? I can put the calls to `ncfdtr` and `ncfdtri` in `stats.ncf` in the `errstate` context manager like this:

```python
with sc.seterr(all="warn"):
    return sc.ncfdtr(dfn, dfd, nc, x)
```

and make the calls to `sf_error` in `ncf_cdf_wrap` pass on the Boost error message like above, and then change the warning type in the test from `RuntimeWarning` to `special.SpecialFunctionWarning` if that would be desirable. I guess could also pass the buck and maintain separate versions for `stats` and `special` for a little longer.

**Comment by steppi** [comment]
More failures. Ok, separate wrappers for `stats` and `special` it is. Kicking the can down the road.

**Comment by steppi** [comment]
OK, I've made it so that `ncfdtr` and `ncfdtri` are separate `ufuncs` from `_ncf_cdf` and `_ncf_ppf` again. I don't want to touch the difference in warning behavior right now, and think it probably needs an RFC or something to settle on how to unify the `special` and `stats` Boost based ufuncs.

I've also implemented a fallback to `cdflib` for the cases Boost can't handle. Doing this required writing a `ncfdtr.cpp` file which includes the relevant headers from Boost and has the Boost wrappers in it, and a corresponding header `ncfdtr.`. Things are set up in the build system in a similar way as they are for `xsf_wrappers.cpp` and its header `xsf_wrappers.h`. Where what we ultimately provide are wrappers which can be called from C. This is because adding `ncfdtr.cpp` to the `_ufuncs_cxx` extension module would require linking `_ufuncs_cxx` with the `cdflib` static library, which causes a dramatic bloat in binary sizes. Making the wrappers callable from C means we can include them in the `_ufuncs` extension module which is already linked with the `cdflib` static library. We need to add Boost to the include path for the `_ufuncs` extension module. I've put them in the `_ufuncs` extension module using the old ufunc creation infrastructure instead of `_special_ufuncs` which uses the new infrastructure just out of convenience, because it's faster to get something out, but I'd be happy to change it to use the new infrastructure.

I've verified once again that all `statsmodels` tests pass when using the scipy from this branch.

**Comment by steppi** [comment]
The windows failures look like they are probably relevant.

File: scipy/special/boost_special_functions.h (hunk 6 above)
Comment (mdhaber) [reply scipy/special/boost_special_functions.h]: I think the NaNs are preferable to inaccurate results here.

**Comment by mdhaber** [comment]
Reading through the old issue report and PR, I don't think that relaying Boost's warning message was the important part. I think the main thing was to avoid a segfault and return a NaN. As long as we can still do that - and it sounds like we can even get *a* warning with `special.seterr` - I think it's fine.

File: scipy/special/boost_special_functions.h (hunk 6 above)
Comment (mdhaber) [reply scipy/special/boost_special_functions.h]: At least for this case, we should submit a bug report for Boost. For small values of the noncentrality parameter, there should be no trouble getting accurate results by directly evaluating the CDF from the definition unless `betainc` is inaccurate, and it's not in this case here.

**Comment by steppi** [comment]
Thanks @mdhaber.  I misunderstood the purpose of `test_ncf_ppf_issue_17026` because I didn't read the issue. The point wasn't to check that the warning appears, just that running those lines doesn't cause a segfault. This PR once again unifies the `stats` and `special` ufuncs for the ncf cdf and ppf.

I've also removed the fallback to `cdflib`. You're right, it's too much complexity to add just to get low quality results in some extreme cases where Boost returns `NaN`.

**Comment by dschmitz89** [comment]
I'd be happy to submit an issue about tiny df values in the boost repo when I am back from vacation next week.

File: scipy/special/_add_newdocs.py [hunk 7]
```diff
@@ -6854,16 +6856,13 @@ def add_newdoc(name, doc):
     where :math:`I` is the regularized incomplete beta function, and
     :math:`x = f d_n/(f d_n + d_d)`.
 
-    The computation time required for this routine is proportional to the
-    noncentrality parameter `nc`.  Very large values of this parameter can
-    consume immense computer resources.  This is why the search range is
-    bounded by 10,000.
+    Note that argument order of `ncfdtr` is different from that
+    of `scipy.stats.ncf.cdf`. `f` is the last parameter of `ncfdtr`
```
Comment (mdhaber) [inline scipy/special/_add_newdocs.py:6860]: I don't remember the right way to do this, but I think this is the cause of the CI failure. Probably need to specify the role?

File: scipy/special/tests/test_cdflib.py [hunk 8]
```diff
@@ -3,7 +3,6 @@
 
 The following functions still need tests:
 
-- ncfdtr
 - ncfdtri
```
Comment (mdhaber) [inline scipy/special/tests/test_cdflib.py:6]:
```suggestion
```

File: scipy/special/_add_newdocs.py (hunk 7 above)
Comment (dschmitz89) [reply scipy/special/_add_newdocs.py:6860]: Had a similar issue lately. I bet that sphinx tries to find a reference to `f`, changing too ``f`` should fix it.

Comment (lucascolley) [reply scipy/special/_add_newdocs.py:6860]: Yeah, there is no docs page for `scipy.stats.ncf.cdf`. You can either refer to ``cdf`` of `scipy.stats.ncf` (with double backticks around 'cdf') or just put the whole thing in double backticks.

Comment (steppi) [reply scipy/special/_add_newdocs.py]: Thanks everyone. Fixed now.

**Comment by steppi** [comment]
> I'd be happy to submit an issue about tiny df values in the boost repo when I am back from vacation next week.

Thanks @dschmitz89. That would be great

File: scipy/special/_add_newdocs.py [hunk 9]
```diff
@@ -6854,16 +6856,13 @@ def add_newdoc(name, doc):
     where :math:`I` is the regularized incomplete beta function, and
     :math:`x = f d_n/(f d_n + d_d)`.
 
-    The computation time required for this routine is proportional to the
-    noncentrality parameter `nc`.  Very large values of this parameter can
-    consume immense computer resources.  This is why the search range is
-    bounded by 10,000.
+    Note that argument order of `ncfdtr` is different from that of the
+    otherwise equivalent ``cdf`` method of `scipy.stats.ncf`. `f` is the last
```
Comment (dschmitz89) [inline scipy/special/_add_newdocs.py:6860]:
```suggestion
    otherwise equivalent ``cdf`` method of `scipy.stats.ncf`. ``f`` is the last
```

Double back ticks once more, otherwise this will link to the f distribution.

**Review by dschmitz89 — DISMISSED** [review]

File: scipy/special/_add_newdocs.py [hunk 10]
```diff
@@ -6839,10 +6839,12 @@ def add_newdoc(name, doc):
...
     ncfdtrinc : Inverse of `ncfdtr` with respect to `nc`.
+    scipy.stats.ncf : Non-central F distribution.
 
     Notes
     -----
-    Wrapper for the CDFLIB [1]_ Fortran routine `cdffnc`.
+    This function calculates the CDF of the non-central f distribution using
+    the Boost Math C++ library [1]_.
 
     The cumulative distribution function is computed using Formula 26.6.20 of
```
Comment (mdhaber) [inline scipy/special/_add_newdocs.py:6849]: Strictly speaking, this probably isn't true, right?

image

This is fine fine as is, but I point it out because presumably Boost has a more efficient way of performing the computation for large values of the noncentrality parameter.

File: scipy/special/_add_newdocs.py (hunk 9 above)
Comment (mdhaber) [reply scipy/special/_add_newdocs.py:6860]: I don't think this should be changed.

image

`f` refers to the parameter of this function, and it does not currently link to `scipy.stats.f`.

Comment (mdhaber) [reply scipy/special/_add_newdocs.py:6860]:
```suggestion
    similar ``cdf`` method of `scipy.stats.ncf`: `f` is the last
```
or "comparable".
There are other differences, like `ncf.cdf` evaluated outside of the support is zero or one whereas the `ncfdtr` function returns NaN.

File: scipy/special/boost_special_functions.h [hunk 11]
```diff
@@ -760,46 +760,86 @@ ncf_pdf_double(double x, double v1, double v2, double l)
...
+	return NAN;
     }
-    // -inf => 0, inf => 1
-    return 1.0 - std::signbit(x);
+    if ((v1 <= 0) || (v2 <= 0) || (l < 0)) {
+	sf_error("ncfdtr", SF_ERROR_DOMAIN, NULL);
+	return NAN;
+    }
+    if (std::isinf(x)) {
+	// -inf => 0, inf => 1
```
Comment (mdhaber) [inline scipy/special/boost_special_functions.h:773]: To be self-consistent and consistent with previous behavior, this should return NaN for all `x < 0`, right?

**Review by mdhaber — COMMENTED** [review]
Please extrapolate as appropriate to `ncfdtri`.

File: scipy/special/boost_special_functions.h (hunk 11 above)
Comment (steppi) [reply scipy/special/boost_special_functions.h:773]: Ah, good point. That trips me up too. I'll change it. I think I understand the rationale at least. For example, ifwe defined `betainc` to be the CDF of the Beta distribution, then it's natural to say `betainc(2, 2, -0.2)` is zero, since if $X \sim B(2, 2)$, then $P(X < -0.2) = 0$. Treating it just as a special function though, the natural way to extend things is by analytic continuation, and if we haven't implemented the analytic continuation (or if we're looking at the real valued version and the analytic continuation on the real axis but outside of the usual domain for the distribution function returns complex values, then it makes sense to return `NAN`.

Comment (mdhaber) [reply scipy/special/boost_special_functions.h:773]: > For example, if we defined betainc to be the CDF of the Beta distribution

I think that's my point, though: `betainc` *isn't* the CDF of the beta distribution; `btdtr` is / was. So I would have extended `betainc`'s domain or returned NaN, whereas I would think `btdtr` would only be for reals and would return 0 or 1 outside the distribution's domain.

Comment (steppi) [reply scipy/special/boost_special_functions.h:773]: Yeah, I agree it's weird that we have different versions of the some functions, one a CDF, the other not, but the CDF doesn't behave as one would expect. I would imagine it's just an historical thing. It seems like the consistent principle being followed may be "whether something says it's a CDF or not, we don't treat it as a CDF, and the only valid way to extend a domain is by analytic continuation"?

Would you support maintaining CDF and non-CDF versions of the same functions with the only difference being how they treat arguments outside of the usual domain? It seems like a reasonable thing to do.

**Comment by steppi** [comment]
I just found this comment, https://github.com/scipy/scipy/pull/17697#issuecomment-1453781732, from @josef-pkt.

> How good are these boost functions?
> 
> In statsmodels,, I just switched away from using the boost function for the noncentral distributions (ncf, nct) in scipy.stats to use the original scipy.special functions.
> 
> I guess it will take several years to fix boost for some cases that worked without problems in scipy.special.
> 
> AFAIR, the incomplete beta functions are quite heavily used.

File: scipy/special/_add_newdocs.py (hunk 10 above)
Comment (steppi) [reply scipy/special/_add_newdocs.py:6849]: I noticed this too. It wasn't even true for cdflib. It could be changed to "is defined" or "can be computed", but I'll leave it for now.

File: scipy/special/boost_special_functions.h (hunk 11 above)
Comment (mdhaber) [reply scipy/special/boost_special_functions.h:773]: > It seems like the consistent principle being followed may be "whether something says it's a CDF or not, we don't treat it as a CDF, and the only valid way to extend a domain is by analytic continuation"?

I think that describes what is happening. And with that in mind, yes, I imagine the reason for the apparent duplication is just historical.

> Would you support maintaining CDF and non-CDF versions of the same functions with the only difference being how they treat arguments outside of the usual domain?

Personally, I wouldn't want to work toward it because I think the random variable infrastructure can serve the need for functions to be treated as CDFs. On one hand, it would be great if the infrastructure could just call the special function and it would behave as a CDF, etc. There is lower overhead if this behavior happens at the compiled level. But if there is a need for this sort of behavior to be added by the distribution infrastructure (e.g. user-defined distributions) it might as well be applied consistently to all distributions, and then there is not much need to duplicate it in `special`.

**Comment by mdhaber** [comment]
The comment doesn't identify what the problem is with the Boost versions, so I don't think it provides actionable information. In this case, you've tested the Boost version, and it is almost always better than the original implementation, so I think it's preferable to use it. Also, Boost is maintained, but CEPHES doesn't seem to be. So if there are specific problems, we report them to Boost, and we help them fix them.

**Comment by josef-pkt** [comment]
> I think the NaNs are preferable to inaccurate results here.

In our practice, 5 or 6 decimal accuracy is still better than nan when getting close to boundaries.

I don't know any direct usecase for very small degrees of freedom in nct, ncf. 
(very large df are important. I don't remember about the range of the noncentrality parameter in examples or test cases)

However, in statsmodels power functions, those functions are used for root finding, implemented mainly generically and not distribution specific. For near extreme cases the root finding might require to evaluate close to boundaries, and I guess that's what triggered the initial test failure with nct, ncf in statsmodels.
(AFAIR, the scipy root finders broke down when encountering a nan.)

**Comment by mdhaber** [comment]
OK. But the existing implementation is not accurate to 5-6 digits, even for moderate values of the noncentrality parameter, hence the motivation to upgrade.

Note that it's not just the Boost version that produces NaNs. 
```python3
special.ncfdtr(1e20, 1e20, 1, 1)
# NaN on main locally, 1.0235204882650641 on Colab 1.13.1
```
is problematic for both versions. (@steppi, Boost produces a negative result for this example. Probably want to output NaN if a numerical result is out of bounds.)

But since Boost tends to be much more accurate for a wide range of parameters, let's use it and work with them to improve the usable domain. For instance, in the example @steppi gave above, direct summation would have worked very well. When both the degrees of freedom are very large and both implementations give bogus results or NaNs, there are approximations, e.g. [this](https://www.jstor.org/stable/2333311).

```python3
def ncfdtr_approx(v1, v2, lam, f):
    t1 = ((v1 * f) / (v1 + lam)) ** (1 / 3)
    t2 = 1 - 2 / (9 * v2)
    t3 = 1 - (2 * (v1 + 2 * lam) / (9 * (v1 + lam) ** 2))
    t4 = (2 * (v1 + 2 * lam)) / (9 * (v1 + lam) ** 2)
    t5 = 2 / (9 * v2) * ((v1 * f) / (v1 + lam)) ** (2 / 3)
    x = (t1 * t2 - t3) / (t4 + t5) ** (1 / 2)
    return special.ndtr(x)
```

Although the relative error in the deep left tail isn't great, the absolute error is quite good for moderately large numbers of degrees of freedom. Presumably it gets better as the degrees of freedom get too large for the Boost implementation.

**Comment by josef-pkt** [comment]
If there are other approximations, then why are they not in boost/scipy.special.
I"m not a "special" guy and have no idea what approximations work or what they are.

The use case that is relative important is when t/nct approach normal for large samples, and F/ncf approach the chisquare versions.

We don't have to cover the entire range given that 0 and inf are difficult boundaries. 
However, the initial test failures in statsmodels are most likely not "weird" cases that never show up in real life.

**Comment by mdhaber** [comment]
What test failures? @steppi wrote that there were failures only when Boost was used for `ncfdtr` but not `ncfdtri`. Twice since then he has confirmed that the statsmodels cases are passing.

**Comment by steppi** [comment]
> I don't think there are any failures now. @steppi wrote that there were failures only when Boost was used for `ncfdtr` but not `ncfdtri` because the old `ncfdtri` was inverting the less accurate implementation. Twice since then he has confirmed that the statsmodels cases are passing. Am I missing a post?

@josef-pkt was seeing test failures when statsmodels was using Boost for `ncf` distribution functions in the past. I think one of two things might be happening

1. Boost has since fixed the issues that lead to those test failures.
2. statsmodels was using the default Boost policies, whereas SciPy increases the value of `max_root_iterations` from 200 to 400. Using the default value might have been leading to failure of convergence in more cases for `ncfdtri`.

@josef-pkt, if statsmodels tests are passing against this branch, do you think this is safe to merge?

**Comment by josef-pkt** [comment]
> if statsmodels tests are passing against this branch, do you think this is safe to merge?

Yes, that's fine. It means the old problem cases are fixed.

If new problems show up in future, then I will have to investigate more, and maybe add more checks in statsmodels that users don't try to compute for "weird" (too close to boundaries) cases.
(A df of 1e20 should not happen in any real life dataset)

I also agree with returning nans for clearly wrong returns.
5 or 6 digits precision is still useful, but while trying out a few examples mentioned in this PR in my old scipy version, I get cdf values > 1 with ncfdtr which are clearly wrong.
(cases like `special.ncfdtr(5, 1e7, 1, 1)` at 5 decimals agreement with mpmath in my scipy version still look ok for our use cases)

(my current scipy is still 1.7.3, an older version I use with old fashioned jupyter notebooks)

**Comment by steppi** [comment]
> Note that it's not just the Boost version that produces NaNs.
> 
> ```python
> special.ncfdtr(1e20, 1e20, 1, 1)
> # NaN on main locally, 1.0235204882650641 on Colab 1.13.1
> ```

The `mpmath` implementation I wrote can't even handle this case. I'm getting

```
File <string>:31, in hypsum_2_1_ZZ_Z_R(coeffs, z, prec, wp, epsshift, magnitude_check, **kwargs)

NoConvergence: Hypergeometric series converges too slowly. Try increasing maxterms.
```

and `maxterms` is already very high. That's interesting that this used to not return NAN though. Maybe something happened during the Fortran to C translations.


> (cases like `special.ncfdtr(5, 1e7, 1, 1)` at 5 decimals agreement with mpmath in my scipy version still look ok for our use cases)

I've found that Boost is only off by 1ulp here.

> Yes, that's fine. It means the old problem cases are fixed.

OK,  cool. That seems to be the case.

**Comment by steppi** [comment]
> is problematic for both versions. (@steppi, Boost produces a negative result for this example. Probably want to output NaN if a numerical result is out of bounds.)

I wonder if it should output NAN or clip the result.

**Comment by mdhaber** [comment]
I think I got it when I knew what the result should be and clipping to 0 or 1 would not have been right. But I'll play with it a bit.

**Comment by mdhaber** [comment]
Should we add the statsmodels cases to our suite?

**Comment by steppi** [comment]
OK, yikes. This looks like a normal approximation run amok.

```
ncfdtr(1e20, 1e20, 1, 1) == np.float64(-124.40303872682864)
```

**Comment by josef-pkt** [comment]
> special.ncfdtr(1e20, 1e20, 1, 1)

I had tried wolfram alpha and it also bailed out. "Standard computation time exceeded...", and I don't have "Pro computation time"

**Comment by mdhaber** [comment]
I had tried real Mathematica earlier, and it wouldn't produce a numerical result either.

File: scipy/special/_add_newdocs.py (hunk 9 above)
Comment (steppi) [reply scipy/special/_add_newdocs.py]: @dschmitz89, can you approve or take back the request so this can be merged without having "requested changes".

Comment (mdhaber) [reply scipy/special/_add_newdocs.py]: I can dismiss the review. Looks like everything was addressed.

File: scipy/special/boost_special_functions.h [hunk 12]
```diff
@@ -760,46 +760,93 @@ ncf_pdf_double(double x, double v1, double v2, double l)
...
     }
-    // -inf => 0, inf => 1
-    return 1.0 - std::signbit(x);
+    if ((v1 <= 0) || (v2 <= 0) || (l < 0) || (x < 0)) {
+	sf_error("ncfdtr", SF_ERROR_DOMAIN, NULL);
+	return NAN;
+    }
+    if (std::isinf(x)) {
+	// -inf => 0, inf => 1
+	return 1.0 - std::signbit(x);
```
Comment (mdhaber) [inline scipy/special/boost_special_functions.h:774]: We've already returned if `x < 0`, so all that's left is ` x == inf`, right?

Comment (steppi) [reply scipy/special/boost_special_functions.h:774]: Yes. Good catch.  A holdover from this once having the natural cdf behavior because it was copied from the scalar kernel for `_ncf_cdf`.

File: scipy/special/cython_special.pyx [hunk 13]
```diff
@@ -3175,13 +3167,29 @@ cpdef double nbdtrin(double x0, double x1, double x2) noexcept nogil:
...
-    return _func_ncfdtr(x0, x1, x2, x3)
+    if df_number_t is float:
+        return (<float(*)(float, float, float, float) noexcept nogil>scipy.special._ufuncs_cxx._export_ncf_cdf_float)(x0, x1, x2, x3)
+    elif df_number_t is double:
+        return (<double(*)(double, double, double, double) noexcept nogil>scipy.special._ufuncs_cxx._export_ncf_cdf_double)(x0, x1, x2, x3)
+    else:
+        if df_number_t is double:
+            return NAN
+        else:
+            return NAN
```
Comment (mdhaber) [inline scipy/special/cython_special.pyx:3180]:
```suggestion
        return NAN
```
This is copied from elsewhere, but it looks really redundant. If the rest looks good, I'll merge as-is, but consider consolidating or adding a comment.

**Comment by mdhaber** [comment]
> Me: This is super easy, right? 
Albert: yep, it's extremely simple.

73 comments and 26 commits later, this looks great!

**Comment by mdhaber** [comment]
@dschmitz89 Thanks for offering to file the issue with Boost. The cases we ran into were for tiny degrees of freedom (https://github.com/scipy/scipy/pull/21505#discussion_r1743782008) and very large degrees of freedom (e.g. https://github.com/scipy/scipy/pull/21505#issuecomment-2334793846; I think there might be separate problems when only `dfd` is large VS when both are large). For moderate values of the noncentrality parameter, it might be worthwhile to have a code path directly evaluates the typical expression of the CDF (https://github.com/scipy/scipy/pull/21505#discussion_r1744882349). Approximations might be useful for large `dfn`/`dfd` (https://github.com/scipy/scipy/pull/21505#issuecomment-2334793846).
