### PR TITLE
MAINT: Fix convergence message for remez

### LINKED ISSUE #4569: remez: "ValueError: Failure to converge after 25 iterations.       Design may still be correct."
This error message doesn't make sense, as no design is returned.  Either change to a warning and return the possibly correct result, or remove "Design may still be correct" from the error message.

### PR DESCRIPTION
**Pull request by maniteja123**
Correctly print the error message so as to describe the failure of convergence. Removes the "Design may still be correct" from the error message. Fixes #4569.

### CODE REVIEW

File: scipy/signal/sigtoolsmodule.c [hunk 1]
```diff
@@ -1242,9 +1242,7 @@ static PyObject *sigtools_remez(PyObject *NPY_UNUSED(dummy), PyObject *args) {
                       type, maxiter, grid_density);
         if (err < 0) {
 	  if (err == -1) {
-            sprintf(mystr, "Failure to converge after %d iterations.\n      " \
-                           "Design may still be correct.",
-                    maxiter);
+            printf(mystr, "Failure to converge after %d iterations.\n", maxiter);
```
Comment (rgommers) [inline scipy/signal/sigtoolsmodule.c]: the change from ``sprintf`` to ``printf`` isn't right. the message isn't printed to stdout but stored in ``mystr`` and used in the line below

**Comment by maniteja123** [comment]
Sorry, I had accidentally changed sprintf to printf. Fixed it now. Thanks @rgommers .

**Comment by rgommers** [comment]
Can you squash the two commits and remove ``[ci skip]`` from the commit message? This is executable code, so the tests should be run. ``[ci skip]`` is really for when you touch docstrings or ``.txt`` files.

**Comment by maniteja123** [comment]
Oops, I didn't think about that since it was just a change in error message, sorry about that. I squashed the two commits and removed ``[skip ci]`` from the commit message. I also renamed the message to ``MAINT:...`` instead of ``DOC:...``.

**Comment by rgommers** [comment]
Thanks, looks good now. ``MAINT`` is right. This can be merged when the testrun has completed.

**Comment by rgommers** [comment]
Merged, thanks @maniteja123
