### PR TITLE
ENH: sparse: Add 64-bit integer to sparsetools

### LINKED ISSUE #7230: Sparse COO.toarray fails if nnz > 2**31
While handling of sparse arrays with more that 2**31 non zero elements was enabled in #442, it looks like the conversion from CSR to a dense array still fails in this case with an error in `coo_todense` .

```py
In [1]: import scipy.sparse
     .. import numpy as np
     .. X = scipy.sparse.csr_matrix(np.ones((2**16, 1)))
     .. X
Out[1]:
# <65536x1 sparse matrix of type '<class 'numpy.float64'>'
#        with 65536 stored elements in Compressed Sparse Row format>

In [2]: (X*X[:2**15-1].T).toarray()
Out[2]:
array([[ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       ...,
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.]])

In [3]: (X*X[:2**15].T).toarray()
ValueError                                Traceback (most recent call last)
<ipython-input-6-ee8192b524ea> in <module>()
----> 1 (X*X[:2**15].T).toarray()

/home/ec2-user/miniconda3/envs/test-env/lib/python3.6/site-packages/scipy/sparse/compressed.py in toarray(self, order, out)
    918     def toarray(self, order=None, out=None):
    919         """See the docstring for `spmatrix.toarray`."""
--> 920         return self.tocoo(copy=False).toarray(order=order, out=out)
    921
    922     ##############################################################

/home/ec2-user/miniconda3/envs/test-env/lib/python3.6/site-packages/scipy/sparse/coo.py in toarray(self, order, out)
    256         M,N = self.shape
    257         coo_todense(M, N, self.nnz, self.row, self.col, self.data,
--> 258                     B.ravel('A'), fortran)
    259         return B
    260

ValueError: could not convert integer scalar
```
**Note:** approximately 64 GB RAM is necessary to run this example.
 
Using numpy 1.12.1 and scipy 0.18.1 on Linux.

What would be the advised workaround in this case to convert a CSR array to a dense array? something along the lines of the function below? 

```py 
def csr_to_array_fallback(X):
    if X.format != 'csr':
        raise ValueError
    row_indices = np.zeros(len(X.indices), dtype='int32')
    indptr = X.indptr 
    for idx in range(len(indptr) - 1):
        row_indices[indptr[idx]:indptr[idx+1]] = idx
    Y = np.zeros(X.shape, dtype=X.dtype)
    Y[row_indices, X.indices] = X.data 
    return Y 
```

I believe this is, in particular, causing the following issues in scikit-learn,
  - http://stackoverflow.com/questions/42543125/could-not-convert-integer-scalar-error-when-using-dbscan
  - https://github.com/FreeDiscovery/FreeDiscovery/issues/126

cc @eugene-yang

### PR DESCRIPTION
**Pull request by perimosocordiae**
This supersedes gh-7435 and fixes gh-7230, by allowing sparsetools functions to accept 64-bit integers even when the index dtype is 32-bit.

It's a little tricky to verify that this works without gobs of RAM, but here's one way to do it:
```python
import numpy as np
import scipy.sparse
from scipy.sparse._sparsetools import coo_todense

a = scipy.sparse.rand(5, 4, density=0.5)  # produces coo_matrix with index dtype = int32
out = np.zeros_like(a.toarray())
nnz = 2**32
coo_todense(5, 4, nnz, a.row, a.col, a.data, out.ravel('A'), 0)
```

Without this PR, the sparsetools machinery tries to cast `nnz` to int32, fails, and raises an error.

With this PR, we are able to pass `nnz` as a 64-bit integer and `coo_todense` promptly segfaults (as expected).

### CODE REVIEW

File: scipy/sparse/sparsetools/sparsetools.cxx [hunk 1]
```diff
@@ -280,7 +281,7 @@ call_thunk(char ret_spec, const char *spec, thunk_t *thunk, PyObject *args)
                 goto fail;
             }
 
-            if (PyArray_EquivTypenums(I_typenum, NPY_INT64)
+            if ((*p == 'l' || PyArray_EquivTypenums(I_typenum, NPY_INT64))
                     && value == (npy_int64)value) {
                 arg_list[j] = std::malloc(sizeof(npy_int64));
                 *(npy_int64*)arg_list[j] = (npy_int64)value;
```
Comment (pv) [inline scipy/sparse/sparsetools/sparsetools.cxx]: The `else if` clause following this should start with `else if (*p == 'i' && PyArray_EquivTypenums(I_typenum, NPY_INT32) ...`

**Review by pv — CHANGES_REQUESTED** [review]
Probably also need to add `case 'l':` to the `switch (ret_spec)` on line 376?

Also, `'l'` needs to be handled in the cleanup around line 449.

**Comment by perimosocordiae** [comment]
Comments addressed. I'm not positive that I've used the right API call for converting an int64 to a Python int, though. I know that some platforms don't satisfy `long == int64`, but I didn't see a more explicit conversion function.

**Comment by pv** [comment]
Can you add a test? Try to golf it down to minimum memory requirement, then estimate how much is needed, and then do as here:
https://github.com/scipy/scipy/blob/676da8f65d38cd62c89799aec7444df227424e04/scipy/sparse/tests/test_sparsetools.py#L251

File: scipy/sparse/sparsetools/sparsetools.cxx [hunk 2]
```diff
@@ -376,6 +378,9 @@ call_thunk(char ret_spec, const char *spec, thunk_t *thunk, PyObject *args)
     case 'i':
         return_value = PyInt_FromSsize_t(ret);
         break;
+    case 'l':
+        return_value = PyInt_FromLong(ret);
```
Comment (pv) [inline scipy/sparse/sparsetools/sparsetools.cxx]: This is not the right one I think, will fail on windows.
FromLongLong is safe, since that's always at least 64-bit.

Comment (pv) [reply scipy/sparse/sparsetools/sparsetools.cxx]: TBH, also the call above it should be FromLongLong because `'i'` can be 64-bit. Can you fix that at the same time?

**Comment by perimosocordiae** [comment]
I changed `ret` to be a `long long`, which means that the `'l'` and `'i'` cases are now the same for the return value conversion code.

The test will come next, but first: why is the `test_csr_matmat_int64_overflow` test unconditionally skipped? I know it's unlikely that any machine will have 155GB of available RAM, but the skip message seems wrong.

**Comment by perimosocordiae** [comment]
I added the test, but I don't have a machine with the 20GB available to actually run it.

**Comment by person142** [comment]
@perimosocordiae ran the test on a machine with 32GB; it passed.

**Comment by perimosocordiae** [comment]
@person142 thanks! Could you try running the same test against master to make sure it fails?

**Comment by person142** [comment]
On master I get:
```
============================================ FAILURES =============================================
________________________________________ test_nnz_overflow ________________________________________

    def test_nnz_overflow():
        # Regression test for gh-7230 / gh-7871, checking that coo_todense
        # with nnz > int32max doesn't overflow.
        nnz = np.iinfo(np.int32).max + 1
        # Ensure ~20 GB of RAM is free to run this test.
        check_free_memory((4 + 4 + 1) * nnz / 1e6 + 0.5)

        # Use nnz duplicate entries to keep the dense version small.
        row = np.zeros(nnz, dtype=np.int32)
        col = np.zeros(nnz, dtype=np.int32)
        data = np.zeros(nnz, dtype=np.int8)
        data[-1] = 4
        s = coo_matrix((data, (row, col)), shape=(1, 1), copy=False)
        # Sums nnz duplicates to produce a 1x1 array containing 4.
>       d = s.toarray()

../test_sparsetools.py:79:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <1x1 sparse matrix of type '<class 'numpy.int8'>'
	with 2147483648 stored elements in COOrdinate format>
order = None, out = None

    def toarray(self, order=None, out=None):
        """See the docstring for `spmatrix.toarray`."""
        B = self._process_toarray_args(order, out)
        fortran = int(B.flags.f_contiguous)
        if not fortran and not B.flags.c_contiguous:
            raise ValueError("Output array must be C or F contiguous")
        M,N = self.shape
        coo_todense(M, N, self.nnz, self.row, self.col, self.data,
>                   B.ravel('A'), fortran)
E       ValueError: could not convert integer scalar
```

**Comment by pv** [comment]
I don't recally why that one test is unconditionally skipped.
It may be it was added in some early stage of the 64-bit support and was not fixed up later on.

**Comment by pasudyan** [comment]
Hello, 

I am still having this exact same problem even after including the trick above. Any thoughts?
Here is the error:
ValueError                                Traceback (most recent call last)
<ipython-input-98-128ba715d74a> in <module>()
----> 1 coo_todense(5, 4, nnz, a.row, a.col, a.data, out.ravel('A'), 0)

ValueError: could not convert integer scalar
