### PR TITLE
ENH: linalg: Rewrite `sqrtm` in C with low-level nD support

### LINKED ISSUE #12994: Expose "_sqrtm_triu" as a function
I've encountered a problem where I'd like to find the square root of an upper triangular matrix. (I can provide more specifics if helpful, but this seems like a relatively generic problem users might encounter.)

I was pleasantly surprised to find that `scipy.linalg.sqrtm` calls a helper function [`_sqrtm_triu`](https://github.com/scipy/scipy/blob/v1.5.3/scipy/linalg/_matfuncs_sqrtm.py#L24) which I think accomplishes exactly what I want! I think it would be great to expose this as a function for users -- maybe call it something like `sqrtm_triangular(...)`. This would save the computation time of an unecessary Schur decomposition.

### LINKED ISSUE #19415: BUG: linalg.sqrtm results different between version 1.11.1 and 1.11.2/1.11.3
### Describe your issue.

There is a difference in the result of `scipy.linalg.sqrtm` between version 1.11.1 and the following versions (to date: 1.11.2 and 1.11.3) for specific matrices. In the following code example, the error when calculating the square root of the matrix is infinitesimal in 1.11.1, but gigantic in 1.11.2 and 1.11.3. It seems that `sqrtm` either produced a wrong result in earlier versions, or newer versions fail to calculate the square root correctly.

I could not create an example with a random matrix, which is why I made a repository with some data that produces the error: https://github.com/akug/mwe_scipy_sqrtm_bug

Thank you for your time and effort maintaining scipy, it's a great library!

### Reproducing Code Example

```python
# See the repository at https://github.com/akug/mwe_scipy_sqrtm_bug for sample data
import numpy as np
from scipy.linalg import sqrtm

data = np.load("./sample_sqrtm_fails.npz")["array"]
out, error = sqrtm(data, disp=False)
print(error)  # error in 1.11.2 and 1.11.3 is about 2.3e+24, but in 1.11.1 is 2.1e-28
```

### Error message

```shell
# There is no error message, it just produces different results between versions
```

### SciPy/NumPy/Python version and system information

```shell
1.11.3 1.26.0 sys.version_info(major=3, minor=11, micro=5, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.21.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.21.dev
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.11.0
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 0.29.36
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  pythran:
    include directory: ../../tmp/pip-build-env-358nkn7q/overlay/lib/python3.11/site-packages/pythran
    version: 0.14.0
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /opt/python/cp311-cp311/bin/python
  version: '3.11'
```

### LINKED ISSUE #20219: BUG: failing `sqrtm` regression test
Caused by gh-20212. Marked as xfail in gh-20218. Failing with both OpenBLAS 0.3.21 and new Accelerate - see https://github.com/scipy/scipy/pull/19816#issuecomment-1985656794.

From [this CI log](https://github.com/scipy/scipy/actions/runs/8201161926/job/22429344365):

```
____________________________ TestSqrtM.test_gh17918 ____________________________
  ../venv-test/lib/python3.12/site-packages/scipy/linalg/tests/test_matfuncs.py:423: in test_gh17918
      assert np.isrealobj(sqrtm(M))
  E   assert False
  E    +  where False = <function isrealobj at 0x114d80e30>(array([[0.45485703-1.38777878e-17j, 0.20990806+3.46944695e-17j,\n        0.20990806-1.08420217e-18j, 0.20990806-1.30104...+1.08420217e-19j,\n        0.20990806+1.08420217e-19j, 0.20990806+1.08420217e-19j,\n        0.45485703+1.08420217e-19j]]))
  E    +    where <function isrealobj at 0x114d80e30> = np.isrealobj
  E    +    and   array([[0.45485703-1.38777878e-17j, 0.20990806+3.46944695e-17j,\n        0.20990806-1.08420217e-18j, 0.20990806-1.30104...+1.08420217e-19j,\n        0.20990806+1.08420217e-19j, 0.20990806+1.08420217e-19j,\n        0.45485703+1.08420217e-19j]]) = sqrtm(array([[1.  , 0.94, 0.94, 0.94, 0.94, 0.94, 0.94, 0.94, 0.94, 0.94, 0.94,\n        0.94, 0.94, 0.94, 0.94, 0.94, 0.94, ..., 0.94, 0.94, 0.94, 0.94, 0.94, 0.94, 0.94, 0.94, 0.94, 0.94,\n        0.94, 0.94, 0.94, 0.94, 0.94, 0.94, 0.94, 1.  ]]))
          M          = array([[1.  , 0.94, 0.94, 0.94, 0.94, 0.94, 0.94, 0.94, 0.94, 0.94, 0.94,
          0.94, 0.94, 0.94, 0.94, 0.94, 0.94, ..., 0.94, 0.94, 0.94, 0.94, 0.94, 0.94, 0.94, 0.94, 0.94, 0.94,
          0.94, 0.94, 0.94, 0.94, 0.94, 0.94, 0.94, 1.  ]])
          self       = <scipy.linalg.tests.test_matfuncs.TestSqrtM object at 0x12b4b79b0>

FAILED linalg/tests/test_matfuncs.py::TestSqrtM::test_gh17918 - assert False
```

Cc @ev-br

### PR DESCRIPTION
**Pull request by ilayn**
This PR rewrites the `linalg.sqrtm` matrix function in C to remedy a few long-standing shortcomings; 

 - most importantly, returning real valued square roots for real valued input data where available (with an explicit check for negative real eigenvalues).
 - recursive square root algorithm instead of the current block size dependent blocked algorithm
 - includes a fast real to complex Schur form conversion
 - looping batch input at the lower level, independent of the memory layout, instead of slow python copies.
 - works on a single allocated memory area to avoid unnecessary malloc/free calls.
 - now works with complex64 and float32 datatypes
 - substantial speed up for small arrays

Closes #12994 (since now checking for Schur form is built-in and the check cost is marginal to the actual algorithm)
Closes #19415
Closes #20219

### CODE REVIEW

**Comment by ilayn** [comment]
The low-level code is pretty much done but we have some issues with the `linalg.sqrtm` function. Namely, 

 - `blocksize` keyword is now unused. So that becomes a regular deprecation period item. @j-bowhay Do we need a `_NoValue` here? Or you prefer something else?
 - The second is a bit more annoying since the return signature changes depending on the keyword `disp`. Now that sqrtm has a more accurate check of the possible failures, as we track eigenvalues and other details, we can print proper warnings. However, it is also computing a costly and, personal opinion!, not so useful information if the disp is false. 

This is ancient signature so things were different back then, but I propose to remove the current disp behavior and the error estimate completely to make it more consistent with the remaining catalogue of matrix functions. That will break code if not modified though so probably we can give it four+ versions for deprecation. 

Any objections, remarks?

File: scipy/linalg/_matfuncs_sqrtm.c [hunk 1]
```diff
@@ -0,0 +1,995 @@
...
+        for (int i = 0; i < n; i++) {
+            for (int j = 0; j < n; j++) {
+                data2[i * n + j] = *(slice_ptr + (i*strides[ndim - 2]/sizeof(float)) + (j*strides[ndim - 1]/sizeof(float)));
+            }
+        }
+        swap_cf_s(data2, data, n, n, n);
+
+        isComplex = 0;
+        // ------------------------------------------------------------------------
+        // Check if array is (quasi)upper triangular.
```
Comment (j-bowhay) [inline scipy/linalg/_matfuncs_sqrtm.c:102]: Should we handle the lower triangular case?

Comment (ilayn) [reply scipy/linalg/_matfuncs_sqrtm.c:102]: The algorithm expects upper (quasi) triangular case in general. So lower (quasi) triangular Schur form will be a quite corner case. Not impossible but not sure if it's worth it, especially converting it to complex schur form if needed in the real case.

**Comment by j-bowhay** [comment]
> * `blocksize` keyword is now unused. So that becomes a regular deprecation period item. @j-bowhay Do we need a `_NoValue` here? Or you prefer something else?

Setting the default to `_NoValue` and using that to check if it's set sounds good.

> * The second is a bit more annoying since the return signature changes depending on the keyword `disp`. Now that sqrtm has a more accurate check of the possible failures, as we track eigenvalues and other details, we can print proper warnings. However, it is also computing a costly and, personal opinion!, not so useful information if the disp is false.
> 
> This is ancient signature so things were different back then, but I propose to remove the current disp behavior and the error estimate completely to make it more consistent with the remaining catalogue of matrix functions. That will break code if not modified though so probably we can give it four+ versions for deprecation.
> 
> Any objections, remarks?

+1 to deprecate `disp`, would be nice to send that to the history books

Removing the error estimate seems harder because we're changing the return type which could be a pain for downstream libraries. Off the top of my head I can't think of an especially nice way to do it but maybe someone else can

**Comment by mdhaber** [comment]
> Off the top of my head I can't think of an especially nice way to do it but maybe someone else can

I'd love to see it added as an attribute to the array. (If necessary, creating a very light subclass of array that just adds the attribute.) This sort of thing would be useful all over the place as a way of returning extra information to those who are interested but not disruptive otherwise.

**Comment by ilayn** [comment]
We used to do that with `Bunch` class in the past but in this case the output is changing output argument number so it is quite out of place to have it. But breaking things is never fun so not sure if we have any other choice.

**Comment by mdhaber** [comment]
> We used to do that with Bunch class in the past but in this case the output is changing output argument number so it is quite out of place to have it.

Are you referring to stdlib `Bunch` or [`make_tuple_bunch`](https://github.com/scipy/scipy/blob/main/scipy/_lib/_bunch.py)? The later only works without breaking things when you already return a tuple but want to add new attributes to it (and maybe give the existing ones names).

**Comment by ilayn** [comment]
Like the one in scikit-learn [`sklearn.utils.Bunch`](https://scikit-learn.org/stable/modules/generated/sklearn.utils.Bunch.html) but it has to be a `Bunch` object in the first place indeed.

But these info are not essential to the algorithm so I don't think it is worth tacking it to the array. Even worse, the error is an estimate and a one-liner (even then it is in a try block)

https://github.com/scipy/scipy/blob/33746fc8385b99efccfc5ab2845d2284caefca53/scipy/linalg/_matfuncs_sqrtm.py#L199-L205

**Comment by ilayn** [comment]
I get that. But here we are trying to remove a second argument and this is not going to remedy that immediately. But in the future for other places, I'm all for it similar like the `Bunch` stuff. That actually would make the output arguments much neater. We should indeed do that more often.

A very typical use case of this is using these functions inside expressions such as `A @ sqrtm(B) * C` etc. So these extras are just getting in the way of doing chain operations. If necessary, that estimate is a one liner and the user can get it themselves in my opinion.

**Comment by mdhaber** [comment]
I don't think that's necessary because it is not returned by default. All you need to do is follow the normal deprecation policy for `disp`, right?

**Comment by j-bowhay** [comment]
You're right that's a nice surprise, for some reason I thought it was currently returned by default

So yep we can just deprecate `disp` and be done

**Comment by ilayn** [comment]
Sigh, seems like `logm`, `signm`, and `funm` has also the same fate.

**Comment by j-bowhay** [comment]
> Sigh, seems like `logm`, `signm`, and `funm` has also the same fate.

I'm happy to open a pr deprecating `disp` for these functions if you want?

**Comment by mdhaber** [comment]
Yeah, I was thinking it would be nice for that to be separate. I can review that one unless @ilayn really wants it here : )

**Comment by ilayn** [comment]
Let me push the code I have so far that is working with a few tests failing because now `sqrtm` is emitting warnings. Then you can see the deprecation in action.

**Comment by ilayn** [comment]
Ah dang it, I thought the tests don't run in draft mode. In the meantime, let's see what sort of C silliness it has in store for me.

**Comment by j-bowhay** [comment]
I opened #22427 to send `disp` to the history books and hopefully keep the diff here down a tiny bit

**Comment by ilayn** [comment]
I change the location of sqrtm in this PR but there is work happening on #22427. How should we coordinate it ?

**Comment by j-bowhay** [comment]
Oops I didn't notice the file move, let's land this first otherwise the merge conflict will be annoying. Maybe it would be easiest not to add any deprecations in this pr since the diff is already massive then land them in #22427?

**Comment by ilayn** [comment]
Ah OK, I can do that. Let me reverse the deprecation decorators then.

**Comment by ilayn** [comment]
I just found a memory issue that I will fix right away but here are some crude benchmarks using `timeit` on an ipython terminal, 

```python
import scipy.linalg as la
import numpy as np
rng = np.random.default_rng(12334523452345)
for n in [2,3,4,5,10,15,20,30,50,100,150,200,500,1000,1500,2000]:
    A = rng.integers(-3,7,size=[n,n]) + n/2*np.eye(n)
    %timeit la.sqrtm(A)
```

gives

```
   n        v1.15.1                this PR
-------------------------------------------------
   2 |  43.5 μs ± 162 ns    |  1.68 μs ± 3.87 ns 
   3 |  48.2 μs ± 262 ns    |  3.93 μs ± 8.46 ns 
   4 |  95.3 μs ± 141 ns    |  5.38 μs ± 10.2 ns 
   5 |  130 μs ± 266 ns     |  6.52 μs ± 14.4 ns 
  10 |  179 μs ± 200 ns     |  18.3 μs ± 31.5 ns 
  15 |  295 μs ± 1.12 μs    |  38.9 μs ± 20.9 ns 
  20 |  364 μs ± 1.69 μs    |  79.5 μs ± 75.6 ns 
  30 |  637 μs ± 1.28 μs    |  174 μs ± 126 ns 
  50 |  1.34 ms ± 12.1 μs   |  563 μs ± 282 ns 
 100 |  143 ms ± 8.33 ms    |  9.21 ms ± 180 μs 
 150 |  200 ms ± 4.99 ms    |  19 ms ± 488 μs 
 200 |  209 ms ± 15.1 ms    |  33 ms ± 289 μs 
 500 |  419 ms ± 6.13 ms    |  240 ms ± 4.8 ms 
1000 |  1.09 s ± 28 ms      |  978 ms ± 10.8 ms 
1500 |  2.12 s ± 34.9 ms    |  2.07 s ± 10.6 ms 
2000 |  4.41 s ± 175 ms     |  4.14 s ± 50.2 ms 
```

So quite a bit of performance increase until n=500-1000 for real inputs returning reals. Then blocking and recursion catches up as the data movement dominates. 

The results are similar if we remove the extra ` n/2*np.eye(n)` part (hence making complex returns more often). Then v1.15.1 catches earlier and starts doing better sometimes. However small array performance stays substantial

```
   n        v1.15.1                this PR
-------------------------------------------------
   2 |  43.1 μs ± 150 ns   |  1.97 μs ± 15.3 ns 
   3 |  47.5 μs ± 63.2 ns  |  4.54 μs ± 27.7 ns 
   4 |  93.2 μs ± 81.1 ns  |  5.94 μs ± 24.7 ns 
   5 |  127 μs ± 1.24 μs   |  7.09 μs ± 14.4 ns 
  10 |  180 μs ± 281 ns    |  22.3 μs ± 24 ns 
  15 |  296 μs ± 2.35 μs   |  41.1 μs ± 1.38 μs 
  20 |  362 μs ± 1.96 μs   |  81.7 μs ± 409 ns 
  30 |  637 μs ± 3.59 μs   |  206 μs ± 1.38 μs 
  50 |  1.33 ms ± 9.06 μs  |  777 μs ± 11.2 μs 
 100 |  142 ms ± 11.9 ms   |  9.83 ms ± 268 μs 
 150 |  193 ms ± 13.2 ms   |  20.1 ms ± 415 μs 
 200 |  232 ms ± 7.15 ms   |  35.6 ms ± 516 μs 
 500 |  424 ms ± 6.49 ms   |  277 ms ± 35.3 ms 
1000 |  1.13 s ± 40.4 ms   |  1.3 s ± 52.8 ms 
1500 |  2.3 s ± 98.2 ms    |  3.2 s ± 135 ms 
2000 |  3.89 s ± 115 ms    |  6.53 s ± 320 ms 
```

**Comment by ilayn** [comment]
Same machine but Win10 instead of Linux Mint.

```
n        v1.15.1(with eye)    this PR(with eye)       v1.15.1(no eye)    this PR(no eye)
-------------------------------------------------------------------------------------------
   2 |  94.7 μs ± 1.43 μs  | 2.92 μs ± 8.54 ns  |  92.2 μs ± 292 ns   |  3.19 μs ± 11.8 ns        
   3 |  100 μs ± 235 ns    | 4.16 μs ± 224 ns   |  97.4 μs ± 2.37 μs  |  4.06 μs ± 21 ns    
   4 |  107 μs ± 422 ns    | 5.66 μs ± 105 ns   |  106 μs ± 1.46 μs   |  6.39 μs ± 7.74 ns   
   5 |  56.7 μs ± 164 ns   | 8.05 μs ± 16.7 ns  |  56.6 μs ± 1.53 μs  |  8.12 μs ± 127 ns      
  10 |  231 μs ± 6.57 μs   | 20.5 μs ± 81.6 ns  |  234 μs ± 11.1 μs   |  20.5 μs ± 46.5 ns     
  15 |  374 μs ± 29.4 μs   | 47 μs ± 392 ns     |  321 μs ± 10.2 μs   |  46.4 μs ± 995 ns         
  20 |  741 μs ± 292 μs    | 79.6 μs ± 1.76 μs  |  394 μs ± 10.6 μs   |  77 μs ± 111 ns    
  30 |  1.04 ms ± 268 μs   | 220 μs ± 16.9 μs   |  744 μs ± 10.1 μs   |  215 μs ± 180 ns    
  50 |  1.8 ms ± 15.2 μs   | 760 μs ± 99.8 μs   |  1.79 ms ± 14.4 μs  |  924 μs ± 4.51 μs     
 100 |  12 ms ± 2.01 ms    | 6.2 ms ± 94.4 μs   |  9.06 ms ± 441 μs   |  6.67 ms ± 34 μs    
 150 |  22.6 ms ± 901 μs   | 16.6 ms ± 235 μs   |  23.5 ms ± 986 μs   |  17.4 ms ± 296 μs     
 200 |  36.1 ms ± 880 μs   | 26.3 ms ± 645 μs   |  34 ms ± 417 μs     |  28.7 ms ± 1.1 ms     
1000 |  860 ms ± 7.4 ms    | 733 ms ± 10.7 ms   |  859 ms ± 73.9 ms   |  1.03 s ± 23.9 ms    
1500 |  2.02 s ± 102 ms    | 1.55 s ± 58.6 ms   |  2.09 s ± 68.6 ms   |  2.73 s ± 142 ms    
2000 |  4.4 s ± 542 ms     | 3.14 s ± 93.5 ms   |  4.77 s ± 397 ms    |  5.75 s ± 183 ms  
```

**Comment by ilayn** [comment]
The fail is unrelated and tracked in #22395

**Comment by dschmitz89** [comment]
Does this also close https://github.com/scipy/scipy/issues/20219 ?

**Comment by ilayn** [comment]
Indeed, the matrix is well-conditioned so it won't fail for a real valued solution (famous last-words). I'll add it to the list.

**Comment by ilayn** [comment]
This is done from my side. Hence, I'd appreciate any feedback. 

I just noticed the DOIs are duplicated, I'll fix that as a final "no CI" run when we are ready to merge.

File: scipy/linalg/_matfuncs_sqrtm.h [hunk 2]
```diff
@@ -0,0 +1,186 @@
...
+    {
+        PYERR(sqrtm_error, "Last two dimensions of the input must be the same.");
+    }
+
+    // Create the output array with the same shape as the input with twice the
+    // number of entries to accomodate for potential complex-valued data from
+    // real data which will be cast to complex e.g., "ret.asview(complex128)"
+    // Example, (3, 3) -> (18), (4, 5, 5) -> (4, 50)
+    npy_intp ret_dims = 1;
+    for (int i = 0; i < ndim; i++) { ret_dims *= shape[i]; }
```
Comment (ev-br) [inline scipy/linalg/_matfuncs_sqrtm.h:68]: This is `PyArray_SIZE(ap_Am)`, correct?

File: scipy/linalg/_matfuncs_sqrtm.h [hunk 3]
```diff
@@ -0,0 +1,186 @@
...
+
+    if (!isComplex)
+    {
+        // Input and output is real, truncate the extra space at the end
+        npy_intp new_size = (ret_dims/2)*(input_type == NPY_FLOAT32 ? sizeof(float) : sizeof(double));
+        void* mem_ret_half = realloc(mem_ret, new_size);
+        // Quite unlikely but still allowed to fail
+        if (!mem_ret_half) { PYERR(sqrtm_error, "Memory reallocation failed."); }
+        PyArrayObject* ap_ret = (PyArrayObject*)PyArray_SimpleNewFromData(ndim, shape, input_type, mem_ret_half);
+        return Py_BuildValue("Niii",PyArray_Return(ap_ret), isIllconditioned, isSingular, info);
```
Comment (ev-br) [inline scipy/linalg/_matfuncs_sqrtm.h:116]: `PyArray_Return` is documented as "This function checks to see if arr is a 0-dimensional array and, if so, returns the appropriate array scalar. It should be used whenever 0-dimensional arrays could be returned to Python."

So the return value can be either
- a python scalar `None` on a LAPACK internal error
- a numpy scalar if ndim==0 (is this even reasonable?)
- an array otherwise

Would be nice to either return an array of predictable shape or raise IMO

File: scipy/linalg/_matfuncs_sqrtm.h [hunk 4]
```diff
@@ -0,0 +1,186 @@
...
+        PYERR(sqrtm_error, "Unsupported input data type to sqrtm C function.");
+    }
+
+    if (info < 0)
+    {
+        // Internal failure memory or LAPACK error, fail and return the error code in info
+        free(mem_ret);
+        Py_INCREF(Py_None);
+        return Py_BuildValue("Niii", Py_None, isIllconditioned, isSingular, info);
+    }
```
Comment (ev-br) [inline scipy/linalg/_matfuncs_sqrtm.h:106]: Please consider either raising an informative exception or returning an array full of nans on failure.

File: scipy/linalg/_matfuncs_sqrtm.h [hunk 5]
```diff
@@ -0,0 +1,186 @@
...
+
+    if (!isComplex)
+    {
+        // Input and output is real, truncate the extra space at the end
+        npy_intp new_size = (ret_dims/2)*(input_type == NPY_FLOAT32 ? sizeof(float) : sizeof(double));
+        void* mem_ret_half = realloc(mem_ret, new_size);
+        // Quite unlikely but still allowed to fail
+        if (!mem_ret_half) { PYERR(sqrtm_error, "Memory reallocation failed."); }
```
Comment (ev-br) [inline scipy/linalg/_matfuncs_sqrtm.h:114]: need to `free` the original `mem_ret` here?

File: scipy/linalg/_common_array_utils.h [hunk 6]
```diff
@@ -0,0 +1,314 @@
...
+void zgetrs_(char* trans, int* n, int* nrhs, SCIPY_Z* a, int* lda, int* ipiv, SCIPY_Z* b, int* ldb, int* info);
+void zlacn2_(int* n, SCIPY_Z* v, SCIPY_Z* x, double* est, int* kase, int* isave);
+void zrot_(int* n, SCIPY_Z* cx, int* incx, SCIPY_Z* cy, int* incy, double* c, SCIPY_Z* s);
+void zdscal_(int* n, double* sa, SCIPY_Z* sx, int* incx);
+void ztrsyl_(char* trana, char* tranb, int* isgn, int* m, int* n, SCIPY_Z* a, int* lda, SCIPY_Z* b, int* ldb, SCIPY_Z* c, int* ldc, double* scale, int* info);
+// void ztrsyl3_(char* trana, char* tranb, int* isgn, int* m, int* n, SCIPY_Z* a, int* lda, SCIPY_Z* b, int* ldb, SCIPY_Z* c, int* ldc, double* scale, double* swork, int* ldswork, int* info);
+
+
+static inline void
+swap_cf_s(float* restrict a, float* restrict b, const Py_ssize_t r, const Py_ssize_t c, const Py_ssize_t n)
```
Comment (ev-br) [inline scipy/linalg/_common_array_utils.h:78]: At call sites, these `Py_ssize_t` arguments are all `npy_intp`. I'm never sure if these two types are interchangeable or not on some weird platforms (surely it's OK on x86 linux, not so sure on Windows on x86 already, what happens on windows arm who knows). 
Is there a deep reason to not use `npy_intp` here so that we don't even need to FUD?

File: scipy/linalg/tests/test_matfuncs.py [hunk 7]
```diff
@@ -321,72 +326,76 @@ def test_sqrtm_type_preservation_and_conversion(self):
...
+
+                A_sqrtm = sqrtm(A)
+                assert_allclose(np.tril(A_sqrtm), np.zeros((4, 4)))
+                assert np.isnan(A_sqrtm).any()
+                assert np.isinf(A_sqrtm).any()
+
+    # Future edit: This squareroot is not possible to find algorithmically
+    # with the current methods. Now sqrtm docstring has another example of
+    # such matrix whose squareroot is not a polynomial in it. Hence no need
+    # to test it here.
```
Comment (ev-br) [inline scipy/linalg/tests/test_matfuncs.py:397]: Is it possible to actually add a test , if only to fix the behavior on this algorithmic corner case? Whatever the current behavior is

**Review by ev-br — COMMENTED** [review]
A cursory review, focusing mainly on technicalities and python interface.
Pretty much all comments are optional.  
A more in-depth review would take me potentially much longer, will try to take a closer look at the algorithmic internals, but there's no need to block anything on my account.

File: scipy/linalg/_common_array_utils.h [hunk 8]
```diff
@@ -0,0 +1,314 @@
...
+void zcopy_(int* n, SCIPY_Z* dx, int* incx, SCIPY_Z* dy, int* incy);
+void zgees_(char* jobvs, char* sort, int (*select)(SCIPY_Z), int* n, SCIPY_Z* a, int* lda, int* sdim, SCIPY_Z* w, SCIPY_Z* vs, int* ldvs, SCIPY_Z* work, int* lwork, double* rwork, int* bwork, int* info);
+void zgemm_(char* transa, char* transb, int* m, int* n, int* k, SCIPY_Z* alpha, SCIPY_Z* a, int* lda, SCIPY_Z* b, int* ldb, SCIPY_Z* beta, SCIPY_Z* c, int* ldc);
+void zgemv_(char* trans, int* m, int* n, SCIPY_Z* alpha, SCIPY_Z* a, int* lda, SCIPY_Z* x, int* incx, SCIPY_Z* beta, SCIPY_Z* y, int* incy);
+void zgetrf_(int* m, int* n, SCIPY_Z* a, int* lda, int* ipiv, int* info);
+void zgetrs_(char* trans, int* n, int* nrhs, SCIPY_Z* a, int* lda, int* ipiv, SCIPY_Z* b, int* ldb, int* info);
+void zlacn2_(int* n, SCIPY_Z* v, SCIPY_Z* x, double* est, int* kase, int* isave);
+void zrot_(int* n, SCIPY_Z* cx, int* incx, SCIPY_Z* cy, int* incy, double* c, SCIPY_Z* s);
+void zdscal_(int* n, double* sa, SCIPY_Z* sx, int* incx);
+void ztrsyl_(char* trana, char* tranb, int* isgn, int* m, int* n, SCIPY_Z* a, int* lda, SCIPY_Z* b, int* ldb, SCIPY_Z* c, int* ldc, double* scale, int* info);
```
[the remark this answers is not in the document]
Comment (ilayn) [reply scipy/linalg/_common_array_utils.h:73]: Good catch. Will fix it.

File: scipy/linalg/_common_array_utils.h [hunk 9]
```diff
@@ -0,0 +1,314 @@
...
+            c2 = c/2;
+            swap_cf_c(a, b, r, c2, n);
+            swap_cf_c(a+(c2)*n, b+c2, r, c-c2, n);
+        }
+    }
+}
+
+
+static inline void
+swap_cf_z(SCIPY_Z* restrict a, SCIPY_Z* restrict b, const Py_ssize_t r, const Py_ssize_t c, const Py_ssize_t n)
```
[the remark this answers is not in the document]
Comment (ilayn) [reply scipy/linalg/_common_array_utils.h:177]: See above.

File: scipy/linalg/_matfuncs.py [hunk 10]
```diff
@@ -395,6 +396,136 @@ def _exp_sinch(x):
     return lexp_diff
 
 
+def sqrtm(A, disp=_NoValue, blocksize=_NoValue):
+    """
+    Compute, if exists, the matrix square root.
```
[the remark this answers is not in the document]
Comment (ilayn) [reply scipy/linalg/_matfuncs.py:401]: Returns partially filled NaNs and Infs.

File: scipy/linalg/_matfuncs.py [hunk 11]
```diff
@@ -395,6 +396,136 @@ def _exp_sinch(x):
...
+        return np.emath.sqrt(a)
+
+    if not np.issubdtype(a.dtype, np.inexact):
+        a = a.astype(np.float64)
+    elif a.dtype == np.float16:
+        a = a.astype(np.float32)
+    elif a.dtype.char in 'G':
+        a = a.astype(np.complex128)
+    elif a.dtype.char in 'g':
+        a = a.astype(np.float64)
```
[the remark this answers is not in the document]
Comment (ilayn) [reply scipy/linalg/_matfuncs.py:499]: It's float128, and I have no idea what to do with it or which platform supports it. Just wanted to take it out of the way.

File: scipy/linalg/_matfuncs_sqrtm.py [hunk 12]
```diff
@@ -4,24 +4,16 @@
 This module exists to avoid cyclic imports.
 
 """
-__all__ = ['sqrtm']
+__all__ = []
```
[the remark this answers is not in the document]
Comment (ilayn) [reply scipy/linalg/_matfuncs_sqrtm.py:7]: We are not using this module but the C module. But this is still used by `logm` and other funcs. So I left the previous helper functions in but took the public API function out. I'll clean this mess when I implement `logm`. It is all over the place.

File: scipy/linalg/_matfuncs_sqrtm.h [hunk 13]
```diff
@@ -0,0 +1,186 @@
...
+This function does not test for 0-dimensional, or nD arrays where some dimensions
+are 0. It is expected to have this case caught by the caller.
+*/
+static PyObject*
+recursive_schur_sqrtm(PyObject *dummy, PyObject *args) {
+    int isComplex = 0, isIllconditioned = 0, isSingular = 0, info = 0;
+    PyArrayObject *ap_Am=NULL;
+    void* mem_ret = NULL;
+    // Get the input array
+    if (!PyArg_ParseTuple(args, ("O!"), &PyArray_Type, (PyObject **)&ap_Am))
```
[the remark this answers is not in the document]
Comment (ilayn) [reply scipy/linalg/_matfuncs_sqrtm.h:37]: You don't want to know how much time I wasted on these and NumPy C-API. PRL analogy is spot on. It's like talking to Dennis Ritchie with an Oija board. I just can't decode what they are saying.

File: scipy/linalg/_matfuncs_sqrtm.h [hunk 14]
```diff
@@ -0,0 +1,186 @@
...
+    npy_intp ret_dims = 1;
+    for (int i = 0; i < ndim; i++) { ret_dims *= shape[i]; }
+    if ((input_type == NPY_FLOAT32) || (input_type == NPY_FLOAT64))
+    {
+        ret_dims *= 2;
+    }
+
+    if (PyArray_TYPE(ap_Am) == NPY_FLOAT32)
+    {
+        mem_ret = malloc(ret_dims*sizeof(float));
```
[the remark this answers is not in the document]
Comment (ilayn) [reply scipy/linalg/_matfuncs_sqrtm.h:76]: Dangit, I thought I had all of it.

File: scipy/linalg/_matfuncs_sqrtm.h (hunk 2 above)
Comment (ilayn) [reply scipy/linalg/_matfuncs_sqrtm.h:68]: Yes it is in line 54 now.

File: scipy/linalg/_matfuncs_sqrtm.h (hunk 3 above)
Comment (ilayn) [reply scipy/linalg/_matfuncs_sqrtm.h:116]: The first and the third is indeed true. The second we don't let the Python func to call with zero size. 

I can return an empty array for the first one indeed. Let me get to that.

File: scipy/linalg/_matfuncs_sqrtm.h (hunk 4 above)
Comment (ilayn) [reply scipy/linalg/_matfuncs_sqrtm.h:106]: This is something that came sometime ago but I can't find the relevant issue. If it is singular the results are not correct but it could be correct for a part of the array. I checked matlab/octave and other places and they don't fill in the array rather let the partially correct parts stay intact and return whatever has happened internally.

File: scipy/linalg/_matfuncs_sqrtm.h (hunk 5 above)
Comment (ilayn) [reply scipy/linalg/_matfuncs_sqrtm.h:114]: I am not sure. I was under the impression that we are quitting the program so it will return `mem_ret` but let me free it explicitly anyways. Good catch nevertheless.

File: scipy/linalg/tests/test_matfuncs.py (hunk 7 above)
Comment (ilayn) [reply scipy/linalg/tests/test_matfuncs.py:397]: The test can be added but the return value will be changing depending on which math library is used (because we are not filling NaNs anymore as mentioned above).

File: scipy/linalg/_matfuncs.py (hunk 11 above)
[the remark this answers is not in the document]
Comment (ev-br) [reply scipy/linalg/_matfuncs.py:499]: Which is `np.float96` on some platforms, `float128` by name 96-bit in reality in some others. 
Bottom line: it's not guaranteed to exist, and even it exists, the bit width is not.
I'd seriously suggest to burn it with fire (maybe across scipy.linalg even). Here it's simple:  raise a deprecation warning and replace with a hard error after two releases.

File: scipy/linalg/_matfuncs.py [hunk 15]
```diff
@@ -395,6 +396,136 @@ def _exp_sinch(x):
...
+
+    if a.dtype.char not in 'fdFD':
+        raise TypeError("scipy.linalg.sqrtm is not supported for the data type"
+                        f" {a.dtype}")
+
+    res, isIllconditioned, isSingular, info = recursive_schur_sqrtm(a)
```
[the remark this answers is not in the document]
Comment (ev-br) [reply scipy/linalg/_matfuncs.py:505]: oookay. Hopefully we have a test with strided inputs, like `a = np.ones((2*n, 2*n)); sqrtm(a[::2, ::2])` or some such.

File: scipy/linalg/_matfuncs_sqrtm.h (hunk 13 above)
[the remark this answers is not in the document]
Comment (ev-br) [reply scipy/linalg/_matfuncs_sqrtm.h:37]: You're right,  I don't. Am pretty sure though that between you and me, the sum is about twice of the amount I don't want to know :-).

More seriously though, the pattern I sorta converged on (after you don't want to know how much wasted time) is

```
PyObject *py_a;

if(!PyArg_ParseTuple(args, "O", &py_a):
   return NULL;
}

if (!PyArray_Check(py_a) {
   // raise an error
}

PyArrayObject *a = (PyArrayObject *)py_a;

// work with an array as usual
```

I'm not saying your pattern is bad though. All I'm saying it feels a bit more explicit and easier to read. 
Also, does your version allow array subclasses (masked arrays, np.memmaps)? It's kinda straightforward to control if you call `PyArray_Check` manually, cf https://github.com/scipy/scipy/pull/22158

File: scipy/linalg/_matfuncs_sqrtm.h (hunk 4 above)
Comment (ev-br) [reply scipy/linalg/_matfuncs_sqrtm.h:106]: Whoa. So you're talking about a situation where in a batch of size 25 (`sqrtm(a)` with `a.shape = (25, n, n)`), 24 elements are OK but the 25-th is bad, and you want to make these 24 computed elements available to the user?

Would be nice to establish an invariant from the get-go (for otherwise we'll never get to it). And document it, too.

File: scipy/linalg/_matfuncs_sqrtm.h (hunk 3 above)
Comment (ev-br) [reply scipy/linalg/_matfuncs_sqrtm.h:116]: > empty array for the first one indeed.

Array of nans, probably?

File: scipy/linalg/_matfuncs_sqrtm.h (hunk 13 above)
[the remark this answers is not in the document]
Comment (ilayn) [reply scipy/linalg/_matfuncs_sqrtm.h:37]: I am counting on the fact that subtypes are proper (in the type theory sense). According to my research™, the `PyArg_ParseTuple` does that implicitly. Meaning that subtypes are accepted if they are proper, hence subclasses are `PyArray_Object`s internally, otherwise they lead to `TypeError` as that cryptic thing above says. 

If a masked array comes in your guess as is as good as mine about what would happen. So if you want to go that way probably we have to check [`PyArray_CheckExact`](https://numpy.org/doc/stable/reference/c-api/array.html#c.PyArray_CheckExact) and reject anything else. Otherwise I don't know how to handle anything else.

File: scipy/linalg/_matfuncs_sqrtm.h (hunk 4 above)
Comment (ilayn) [reply scipy/linalg/_matfuncs_sqrtm.h:106]: Yes not only that but also within the same slice like so in matlab

image

File: scipy/linalg/_common_array_utils.h [hunk 16]
```diff
@@ -0,0 +1,314 @@
...
+    #define SCIPY_C _Fcomplex
+    #define CPLX_Z(real, imag) (_Cbuild(real, imag))
+    #define CPLX_C(real, imag) (_FCbuild(real, imag))
+#else
+    #include <complex.h>
+    #define SCIPY_Z double complex
+    #define SCIPY_C float complex
+    #define CPLX_Z(real, imag) (real + imag*I)
+    #define CPLX_C(real, imag) (real + imag*I)
+#endif
```
[the remark this answers is not in the document]
Comment (ev-br) [reply scipy/linalg/_common_array_utils.h:21]: > add C generics here to use it similar to C templates

https://en.cppreference.com/w/c/language/generic ? Good grace please no. 


FTR, I believe it's possible to deduplicate these type-templated repetition with only minimal C++ shenaghians. But let's drop it now, this can can be kicked down the road easily.

File: scipy/linalg/tests/test_matfuncs.py (hunk 7 above)
Comment (ev-br) [reply scipy/linalg/tests/test_matfuncs.py:397]: I'd then add a test that it does not segfault and returns something.

File: scipy/linalg/_matfuncs_sqrtm.h (hunk 13 above)
[the remark this answers is not in the document]
Comment (ev-br) [reply scipy/linalg/_matfuncs_sqrtm.h:37]: Well then, maybe worth reinstating `asarray_validated` on the python side.

File: scipy/linalg/_matfuncs_sqrtm.c [hunk 17]
```diff
@@ -0,0 +1,1006 @@
...
+        The output is always a C contiguous array hence we visit slices in
+        C-order for easy insertion to the output array; by just offsetting
+        idx*n*n * sizeof(dtype). For this reason, we  start the offset
+        calculation from the inner-most outer dimension.
+        ------------------------------------------------------------------*/
+        npy_intp offset = 0;
+        npy_intp temp_idx = idx;
+        for (int i = ndim - 3; i >= 0; i--) {
+            offset += (temp_idx % shape[i]) * strides[i];
+            temp_idx /= shape[i];
```
Comment (ev-br) [inline scipy/linalg/_matfuncs_sqrtm.c:88]: Hopefully there's a check for zero-sized arrays at the call site. Probably in python. Needs a test.

File: scipy/linalg/_matfuncs_sqrtm.c [hunk 18]
```diff
@@ -0,0 +1,1006 @@
...
+    // lwork for work
+    size_t buffer_size = 4*n*n + 2*n + lwork;
+    float* restrict buffer = malloc(buffer_size*sizeof(float));
+    if (buffer == NULL) { *sq_info = -101; return; }
+
+    // --------------------------------------------------------------------
+    // Pointers to the variables inside the buffer for easy access
+    // --------------------------------------------------------------------
+    float* restrict data = &buffer[0];
+    float* restrict data2 = &buffer[n*n];
```
Comment (ev-br) [inline scipy/linalg/_matfuncs_sqrtm.c:59]: So you have a single buffer and partition it for various arrays and copies of the "inner" arrays.
What do you store at `data` and `data2`?

File: scipy/linalg/_matfuncs_sqrtm.c [hunk 19]
```diff
@@ -0,0 +1,1006 @@
...
+            sgees_("V", "N", NULL, &intn, data, &intn, &sdim, wr, wi, vs, &intn, work, &lwork, NULL, &info);
+            if (info != 0)
+            {
+                free(buffer);
+                *sq_info = -102;
+                return;
+            }
+        } else {
+            // Manually get the eigenvalues with possible 2x2 blocks on the diagonal
+            for (Py_ssize_t col = 0; col < n; col++)
```
Comment (ev-br) [inline scipy/linalg/_matfuncs_sqrtm.c:116]: this should probably be `npy_intp` even if (assumingly) these types are the same (?). In other places indexing uses npy_intp.

File: scipy/linalg/_matfuncs_sqrtm.c [hunk 20]
```diff
@@ -0,0 +1,1006 @@
...
+            temp_idx /= shape[i];
+        }
+        float* restrict slice_ptr = (float*)(Am_data + (offset/sizeof(float)));
+
+        for (int i = 0; i < n; i++) {
+            for (int j = 0; j < n; j++) {
+                data2[i * n + j] = *(slice_ptr + (i*strides[ndim - 2]/sizeof(float)) + (j*strides[ndim - 1]/sizeof(float)));
+            }
+        }
+        swap_cf_s(data2, data, n, n, n);
```
Comment (ev-br) [inline scipy/linalg/_matfuncs_sqrtm.c:97]: This looks to be the key part for the batching. Let me check my understanding: on a high level, you iterate over the `n*n` parts ("slices" of the batched input array), copy each part, make sure it's F ordered, and then feed the copied-and-transposed part to a LAPACK function---is this correct?

What's hard to figure out (and later, debug, I suppose) is some code comments on the data movement, in which parts of `buffer` you store what.

File: scipy/linalg/_common_array_utils.h (hunk 6 above)
Comment (ev-br) [inline scipy/linalg/_common_array_utils.h:78]: Would be _really_ helpful to either add an explanatory comment on whether this copies `a` to `b` or the other way around. Or even rename the arguments to `src`, `dst` to parrot `memcpy`.

**Review by ev-br — COMMENTED** [review]
Went through the "data management" part of this with an eye towards treating it a blueprint for a uniform batching across scipy.linalg, as a discussion in  https://github.com/scipy/scipy/pull/21935 suggests.

Most of the comments below are small and technical.

Two larger comments:

- This seems to do something rather clever with allocating once and partitioning the buffer. Would be great to have some explanatory code comments on what goes where (`data`, `data2` etc).
- This essentially reinvents numpy.linalg and/or f2py; Or, rather, takes the best of them without the rest of them. Great. Then this needs a battery of tests with weird arrays sizes, shapes and strides. Broadcasted arrays (some strides are zero --- both for inner and batch dimensions), arrays with negative strides etc. Most likely most of these are handled correctly, just needs tests confirming this :-).

File: scipy/linalg/_common_array_utils.h (hunk 9 above)
[the remark this answers is not in the document]
Comment (ev-br) [reply scipy/linalg/_common_array_utils.h:177]: I still think that having four copies of an essentially identical function with frankly rather error-prone logic is suboptimal. How about this:

In a single header file:

```
template<typename T> 
static inline void swap_cf(T* restrict a, T* restrict b, const Py_ssize_t r, const Py_ssize_t c, const Py_ssize_t n) {
  T *bb = b;
  T *aa = a;
  ... the rest is intact ...
}
```

In this file, 

```
extern "C"  {
    static inline void swap_cf_f(float * restrict a, float * restict b, const Py_ssize_t r, const Py_ssize_t c, const Py_ssize_t n)  {return swap_cf(a, b, r, c, n); }
    static inline void swap_cf_d(double * restrict a, double * restrict b, const Py_ssize_t r, const Py_ssize_t c, const Py_ssize_t n) {return swap_cf(a, b, r, c, n); };
}
```
and the rest of the code needs no changes.

This way you still write whatever style you prefer but have only a single source of the `swap` function.

Same for `isschur` and the part where you're computing the offset. 

If you prefer, I'm ready to send a PR to you branch :-).

**Comment by ilayn** [comment]
So much good stuff in this review, thanks a lot @ev-br . I will come back to this as soon as I can and address each one.

File: scipy/linalg/_matfuncs_sqrtm.c (hunk 20 above)
Comment (ilayn) [reply scipy/linalg/_matfuncs_sqrtm.c:97]: > ---is this correct? 

Spot on. So we have 4 options C contiguous, F contiguous, C noncontiguous and F noncontiguous. All of them map to F contiguous eventually by using the stride jumping at the input. The annoying part is the ndarrays since then we have to jump either by the leftmost or the rightmost index to jump n*n strides and it gets annoying when it comes to ever ndarrays with n > 3. You are definitely right that I should include all the steps for ease of maintenance.

Basically you start with the ndim (3, 4, 5, 5). And starting from inside out you start moving with the strides to get to the next n*n slice. In C layout these are next to each other. In F order the elements are not next to each other and you have to follow on the left most index hence the strange loop that covers all these cases. 

Once the input is normalized then it goes into the actual sqrtm code as if an `n*n` contiguous array is given.

File: scipy/linalg/_common_array_utils.h (hunk 6 above)
Comment (ilayn) [reply scipy/linalg/_common_array_utils.h:78]: `src`, `dst` terminology is a really good idea.

File: scipy/linalg/_matfuncs.py (hunk 11 above)
[the remark this answers is not in the document]
Comment (ilayn) [reply scipy/linalg/_matfuncs.py:499]: Across linalg is probably a better option but probably not good to tackle it here.

File: scipy/linalg/_matfuncs_sqrtm.h (hunk 3 above)
Comment (ilayn) [reply scipy/linalg/_matfuncs_sqrtm.h:123]: The first one actually is an exception so nothing is returned. So we are back to consistent.

File: scipy/linalg/_matfuncs_sqrtm.c (hunk 18 above)
Comment (ilayn) [reply scipy/linalg/_matfuncs_sqrtm.c:62]: I've added some comments above this.

File: scipy/linalg/_matfuncs_sqrtm.c (hunk 19 above)
Comment (ilayn) [reply scipy/linalg/_matfuncs_sqrtm.c:119]: We don't need to use npy_intp for non NumPy entities such as malloc'd buffers etc. In fact we don't need to use npy_intp anywhere but I did to visually separate when I'm touching NumPy array stuff.

File: scipy/linalg/_common_array_utils.h (hunk 9 above)
[the remark this answers is not in the document]
Comment (ev-br) [reply scipy/linalg/_common_array_utils.h]: Agreed, let's mark it for a follow-up. I'm planning to play a bit with batching of LAPACK wrappers, and  reuse bits and pieces from this PR. Then we'll see how much of this needs generalizing and how much of this can be reused across all of scipy.linalg.

**Review by ev-br — APPROVED** [review]
While I did not check the math, I'm ready to trust Ilhan on this :-).
The data management part looks reasonable if scary. I'm pretty sure there's a runaway pointer bomb or two, but we won't smoke them out without some real-world usage anyway.
The added testing or weird-strided arrays looks comprehensive. 

So all in all here's a +1 from me.

**Comment by ilayn** [comment]
Math part is the only part I'm confident with to be honest :) 

But we don't have to rush if there is any concerns left about this one. We can wait until someone else wants to have a go at it. Random matrices and some cases where I thought were edge cases are passing hence I am out of ideas how else we should stress this code.

Anyone on Apple Silicon with conda+MKL might be a good testing ground too because that's the only platform I don't have access to.

**Comment by lucascolley** [comment]
> Anyone on Apple Silicon with conda+MKL might be a good testing ground too because that's the only major platform I don't have access to.

Happy to help with this if you have suggestions of what to test?

**Comment by ilayn** [comment]
Ah missed your comment, thanks @lucascolley 

If you have any capacity to build this pr, and compare with main, something like https://github.com/scipy/scipy/pull/22406#issuecomment-2622506142 would be really nice to see if the performance is taking a hit or not on macOS.

**Comment by lucascolley** [comment]
> Apple Silicon with conda+MKL

To clarify, you are looking for someone to test with accelerate, when you said MKL? The two build options for [osx-arm64 libblas packages on conda-forge](https://prefix.dev/channels/conda-forge/packages/libblas) are openblas and accelerate.

**Comment by ilayn** [comment]
All are fine, the more the merrier on macOS to be honest. The issues on these platforms come much after we release when it hits personal systems and not CI envs. Hence I don't mind replicating the CI envs. But only if you have capacity, otherwise no problem at all.

**Comment by lucascolley** [comment]
How to reproduce: https://github.com/lucascolley/pixi-dev-scipystack/tree/accelerate

```bash
pixi run --environment=accelerate build && pixi run --environment=accelerate ipython
```

```python
import scipy.linalg as la
import numpy as np
rng = np.random.default_rng(12334523452345)
for n in [2,3,4,5,10,15,20,30,50,100,150,200,500,1000,1500,2000]:
    A = rng.integers(-3,7,size=[n,n]) + n/2*np.eye(n)
    %timeit la.sqrtm(A)
```

---

```
   n        main                  this PR
-------------------------------------------------
   2 |  30.2 μs ± 89.7 ns   |  1.85 μs ± 42.5 ns
   3 |  34.1 μs ± 285 ns    |  4.74 μs ± 12.8 ns
   4 |  69.5 μs ± 6.77 μs   |  5.69 μs ± 33.5 ns
   5 |  94.1 μs ± 1.04 μs   |  7.87 μs ± 25.6 ns
  10 |  148 μs ± 4.18 μs    |  25.3 μs ± 59.4 ns
  15 |  227 μs ± 365 ns     |  48.9 μs ± 208 ns
  20 |  279 μs ± 484 ns     |  71.9 μs ± 126 ns
  30 |  500 μs ± 3.23 μs    |  194 μs ± 2.32 μs
  50 |  1.02 ms ± 40 μs     |  595 μs ± 26 μs
 100 |  5.72 ms ± 352 μs    |  4.34 ms ± 23.9 μs
 150 |  10.6 ms ± 148 μs    |  8.32 ms ± 17.3 μs
 200 |  18.8 ms ± 204 μs    |  14.8 ms ± 245 μs
 500 |  115 ms ± 718 μs     |  96.1 ms ± 3.84 ms
1000 |  560 ms ± 28.2 ms    |  472 ms ± 26.1 ms
1500 |  1.6 s ± 45.2 ms     |  1.37 s ± 64 ms 
2000 |  3.45 s ± 69.8 ms    |  3.22 s ± 65.9 ms
```

Removing `n/2*np.eye(n)`:

```
   n        main                  this PR
-------------------------------------------------
   2 |  32.7 μs ± 183 ns   |  3.31 μs ± 27.4 ns
   3 |  67.1 μs ± 416 ns   |  5.85 μs ± 14.2 ns
   4 |  68.3 μs ± 337 ns   |  6.37 μs ± 76.5 ns
   5 |  94.9 μs ± 1.45 μs  |  7.85 μs ± 119 ns
  10 |  175 μs ± 1.46 μs   |  24.1 μs ± 185 ns
  15 |  241 μs ± 9.94 μs   |  50 μs ± 87.5 ns
  20 |  313 μs ± 6.71 μs   |  98.1 μs ± 1.6 μs
  30 |  504 μs ± 3.09 μs   |  172 μs ± 737 ns
  50 |  1.23 ms ± 29.5 μs  |  527 μs ± 1.49 μs 
 100 |  6.21 ms ± 203 μs   |  4.62 ms ± 50.8 μs
 150 |  10.8 ms ± 195 μs   |  8.21 ms ± 20.7 μs
 200 |  20.7 ms ± 671 μs   |  15.8 ms ± 26 μs
 500 |  123 ms ± 2.95 ms   |  114 ms ± 143 μs
1000 |  592 ms ± 17.6 ms   |  661 ms ± 2.44 ms
1500 |  1.66 s ± 87.5 ms   |  1.96 s ± 9.14 ms
2000 |  3.48 s ± 119 ms    |  4.51 s ± 33.2 ms 
```

**Comment by ilayn** [comment]
Looks like we are not losing the improvements. Accelerate sometimes hides some nice surprises but apparently not this time. Thank you for the exercise.

File: scipy/linalg/_matfuncs_sqrtm.c [hunk 21]
```diff
@@ -0,0 +1,1009 @@
...
+        ------------------------------------------------------------------*/
+        npy_intp offset = 0;
+        npy_intp temp_idx = idx;
+        for (int i = ndim - 3; i >= 0; i--) {
+            offset += (temp_idx % shape[i]) * strides[i];
+            temp_idx /= shape[i];
+        }
+        float* restrict slice_ptr = (float*)(Am_data + (offset/sizeof(float)));
+
+        for (int i = 0; i < n; i++) {
```
Comment (ev-br) [inline scipy/linalg/_matfuncs_sqrtm.c:95]: On re-reading this to actually make sure I understand the iteration over slices: internal loop variable `i` is used twice:  line 89 above and this line 95. Even if it is actually legal in C (is it?), consider not reusing the same name for the loop variable in nested loops.

This is of course minor, can be pushed to a follow-up. Would be great to have this PR in regardless.

Comment (ilayn) [reply scipy/linalg/_matfuncs_sqrtm.c:95]: This is something I used to wonder earlier and essentially you are asking what is the difference between 

```C
int i;
for (i = 0; ...) { ...}
```

and 

```C
for (int i = 0; ...) { ... }
```

In the first one, `i` lives in the scope of the definition after the loop, so you can use again without defining, the second one has `i` only defined in the loop and is not defined outside that particular loop. You can try 

```C
#include <stdio.h>

int main() {
    for (int i = 0; i < 5; i++) { printf("i = %d\n", i); }
    printf("i = %d\n", i);
    return 0;
}
```

to get a compiler error. Is this a clarification or am I just writing past you?

Comment (ev-br) [reply scipy/linalg/_matfuncs_sqrtm.c:95]: A bit past, sadly.

Your example

```
int i;
for(i=0, ....
```

shows that it is probably legal to write

```
for (int i=0; i < 10; i++) {
   for(int i=0; i < 10; i++){
     printf("%d\n", i);
   }
}
```

OK, it's something we _can_ do; is this something we should do though?

Comment (ev-br) [reply scipy/linalg/_matfuncs_sqrtm.c:95]: Ok, rereading this again. Lines 89 and 93 are not nested. 
The loops are one after the other.
Case closed.
Sorry for the noise.

**Comment by ilayn** [comment]
@ev-br I think we need to yank out this slice iterator for common use in case we port more (logm is in the pipeline since it is connected to it). We probably need to do this outside this PR just to plant a virus in your head too

**Comment by ev-br** [comment]
> I think we need to yank out this slice iterator for common use in case we port more (logm is in the pipeline since it is connected to it). We probably need to do this outside this PR but just to plant a virus in your head too.

Exactly. Plus one, twice (on "yank" and "in a separate PR").
In fact, my noise earlier today was from exactly this kind of work to reuse this on a gh-21935 counterpart.

**Comment by ilayn** [comment]
Checked the conda branch and all looks good, also there is significantly less difference compared to `expm`. So I think this is good to go.

**Comment by ev-br** [comment]
Agreed, let's land this. Thanks @ilayn, this is an impressive bit of work! (as always.)

**Comment by ilayn** [comment]
Thanks @ev-br for the review. Much appreciated

**Comment by ev-br** [comment]
> work to reuse this on a gh-21935 counterpart.

https://github.com/scipy/scipy/pull/22838
