### PR TITLE
BUG: modify optimize.bisect to achieve desired tolerance

### LINKED ISSUE #5555: optimize.bisect does not acheive desired tolerance
The function `optimize.bisect` has a parameter for absolute tolerance `xtol` and a parameter for relative tolerance `rtol`. I would expect the computed root `res` and the exact root `r` to satisfy `abs(res - r) <= xtol + rtol*res`, but this is not the case:

```python
from scipy.optimize import bisect
from numpy import finfo

root = 0.1
def f(x):
    return x - root

xtol = 1e-12
rtol = 2*finfo(float).eps
res = bisect(f, -1e8, 1e8, xtol=xtol, rtol=rtol)
tol = xtol + rtol*res

print abs(res - root) <= tol
```
returns `False`. If in the above `bisect` is replaced by `brentq`, `brenth`, or `ridder` we get `True`. The issue is that the tolerance is set to be `tol = xtol + rtol*(fabs(xa) + fabs(xb))` for `xa`, `xb` the endpoints of the initial interval and then never changed throughout the routine, where it should be updated at each step with the current interval (as is done in the other methods). This means that if the endpoints of the initial interval are much larger than the root we lose accuracy.

Will submit a pull request soon with a proposed fix.

### PR DESCRIPTION
**Pull request by person142**
The functions optimize.{brentq, brenth, ridder} all achieve a tolerance of `xtol + rtol*res`, where xtol is the absolute tolerance, rtol is the relative tolerance, and res is the computed root. The function optimize.bisect, on the other hand, does not achieve this tolerance because the routine fixes the tolerance to be `xtol + rtol*(|a| + |b|)`, where [a, b] is the initial interval. This pull request modifies optimize.bisect to update the tolerance along with improved guesses for res so that it achieves the same tolerance as optimize.{brentq, brenth, ridder}. Closes gh-5555.

### CODE REVIEW

**Comment by person142** [comment]
Realized that I forgot to change the documentation; will fix this later today.

File: scipy/optimize/Zeros/bisect.c [hunk 1]
```diff
@@ -3,14 +3,14 @@
 #include <math.h>
 #include "zeros.h"
 
+#define MIN(a, b) ((a) < (b) ? (a) : (b))
```
Comment (charris) [inline scipy/optimize/Zeros/bisect.c]: Is this used?

File: scipy/optimize/Zeros/bisect.c [hunk 2]
```diff
@@ -36,8 +36,8 @@ bisect(callback_type f, double xa, double xb, double xtol, double rtol,
         if (fm*fa >= 0) {
             xa = xm;
         }
-        if (fm == 0 || fabs(dm) < tol) {
-            return xm;
+	if (fm == 0 || fabs(dm) < xtol + rtol*fabs(xm)) {
+	  return xm;
```
Comment (charris) [inline scipy/optimize/Zeros/bisect.c]: Indentation is four spaces, no hard tabs.

**Comment by charris** [comment]
Should mention the change in the 0.18 release notes.

**Comment by person142** [comment]
I made some changes which made the initial commit message inaccurate, so I forced an update. The new commit message explains the changes made.

**Comment by person142** [comment]
@charris: it looks like the 0.18 release notes haven't been created yet. Is there someone I should ask about creating them? (It seems like the sort of thing I shouldn't do myself.)

**Comment by ev-br** [comment]
@person142 here you are: https://github.com/scipy/scipy/blob/master/doc/release/0.18.0-notes.rst
