### PR TITLE
FIX: optimize: use npy_intp to store array dims for lsap

### LINKED ISSUE #13421: linear_sum_assignment - support for matrices with more than 2^31 elements
The `linear_sum_assignment` function is super useful and really fast! Thank you!
Unfortunately I'm encountering a crash with matrices that have more than 2^31 elements, and I've tried on MacOS and Linux.
Is this a surmountable problem? Is there a way to support big matrices like this one? Really appreciate it!

#### Code that works (40k * 40k)
```python
from scipy.sparse import random
from scipy.optimize import linear_sum_assignment

m = random(40000, 40000, density=0.05).toarray()
print("array ready")
solution = linear_sum_assignment(m)
print("LSA solved")
```

#### Code that breaks (50k * 50k)
```python
from scipy.sparse import random
from scipy.optimize import linear_sum_assignment

m = random(50000, 50000, density=0.05).toarray()
print("array ready")
solution = linear_sum_assignment(m)
print("LSA solved")
```

#### Error message:
```
libc++abi.dylib: terminating with uncaught exception of type std::length_error: vector
```

#### Scipy/Numpy/Python version information:
```
1.6.0 1.19.5 sys.version_info(major=3, minor=8, micro=7, releaselevel='final', serial=0)
```

### PR DESCRIPTION
**Pull request by mckib2**
#### Reference issue

- closes gh-13421

#### What does this implement/fix?

- avoids unsafe downcast from `npy_intp` to `int`
- allows for any size 2d array (up to max allowed by numpy)
- requires use of `intptr_t` instead of `int` for index comparisons; potentially larger memory footprint

#### Additional information

- needs to be verified that this fixes the issue's reproducer (I don't have a machine with enough memory in front of me right now and I didn't think it would be fair to the CI to allocate a 20GiB array...) _EDIT: confirmed fix_
- Effect on memory consumption and performance should be examined due to change from `int` to `intptr_t`

### CODE REVIEW

**Review by tylerjereddy — COMMENTED** [review]
@mckib2 I confirmed that your feature here does fix the issue compared to `master` on a machine with sufficient memory.

On `master` with reproducer code presented in the issue:

```
array ready
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```

This feature branch:

```
array ready
LSA solved
```

Runtime was just under 5 minutes on a windows subsystem for linux 1 setup. I could also test on native linux if needed.

If there's a straightforward asv benchmark command you want me to run I could probably do that.

**Comment by tylerjereddy** [comment]
The Azure ilp64 failure looks like a fluke so restarting

File: scipy/optimize/rectangular_lsap/rectangular_lsap.cpp [hunk 1]
```diff
@@ -116,55 +116,55 @@ augmenting_path(int nc, std::vector<double>& cost, std::vector<double>& u,
     return sink;
 }
 
-static int
-solve(int nr, int nc, double* input_cost, int64_t* output_col4row)
+static intptr_t
```
Comment (pmla) [inline scipy/optimize/rectangular_lsap/rectangular_lsap.cpp:119]: This `int` is fine as-is.
The return code is either 0 for success or -1 for failure.

Comment (mckib2) [reply scipy/optimize/rectangular_lsap/rectangular_lsap.cpp]: Fixed in latest push

**Comment by mckib2** [comment]
@tylerjereddy I'm having trouble getting `asv` to play nicely with `venv`, but if you have a minute you could try running this branch against master, i.e. `python runtests.py --bench-compare master optimize_lap`

**Comment by tylerjereddy** [comment]
Yes, I get the same result, no effect on performance:

<details>

```
· Creating environments..........
· Discovering benchmarks....................
·· Uninstalling from virtualenv-py3.8-Cython0.29.21-numpy-pybind11-pytest
·· Building 14a1dfdb <lsap-fix-unsafe-downcast> for virtualenv-py3.8-Cython0.29.21-numpy-pybind11-pytest.......................................................................................................................................................................................................................
·· Installing 14a1dfdb <lsap-fix-unsafe-downcast> into virtualenv-py3.8-Cython0.29.21-numpy-pybind11-pytest.
· Running 2 total benchmarks (2 commits * 1 environments * 1 benchmarks)
[  0.00%] · For scipy commit 4fd523c6 <master> (round 1/2):
[  0.00%] ·· Building for virtualenv-py3.8-Cython0.29.21-numpy-pybind11-pytest.................................................................................................................................................................................................................................
[  0.00%] ·· Benchmarking virtualenv-py3.8-Cython0.29.21-numpy-pybind11-pytest
[ 25.00%] ··· Running (optimize_lap.LinearAssignment.time_evaluation--).
[ 25.00%] · For scipy commit 14a1dfdb <lsap-fix-unsafe-downcast> (round 1/2):
[ 25.00%] ·· Building for virtualenv-py3.8-Cython0.29.21-numpy-pybind11-pytest......
[ 25.00%] ·· Benchmarking virtualenv-py3.8-Cython0.29.21-numpy-pybind11-pytest
[ 50.00%] ··· Running (optimize_lap.LinearAssignment.time_evaluation--).
[ 50.00%] · For scipy commit 14a1dfdb <lsap-fix-unsafe-downcast> (round 2/2):
[ 50.00%] ·· Benchmarking virtualenv-py3.8-Cython0.29.21-numpy-pybind11-pytest
[ 75.00%] ··· optimize_lap.LinearAssignment.time_evaluation                                                                                                                                                                                               ok
[ 75.00%] ··· ============ ============= ============ ============= ============= ============
              --                                        cost_type
              ------------ -------------------------------------------------------------------
                 shapes       uniform      spatial     logarithmic     integer       binary
              ============ ============= ============ ============= ============= ============
               (100, 100)     286±30μs     362±60μs      310±20μs      266±10μs     138±1μs
               (200, 200)   1.19±0.03ms   1.81±0.2ms   1.27±0.07ms   1.12±0.06ms    527±1μs
               (300, 300)    4.59±0.6ms   5.67±0.3ms    2.89±0.1ms    4.23±0.6ms   2.67±0.7ms
               (400, 400)    8.13±0.8ms   11.5±0.8ms    5.65±0.3ms    7.57±0.9ms    4.92±1ms
               (100, 200)     209±9μs      205±20μs      212±7μs       198±9μs     254±0.6μs
               (200, 400)    2.12±0.6ms   2.09±0.6ms     777±30μs     2.12±0.7ms   2.35±0.6ms
               (300, 600)     4.90±1ms     4.95±1ms    1.70±0.03ms     4.91±1ms     5.50±1ms
               (400, 800)     8.88±2ms     9.11±2ms     3.31±0.2ms     8.91±2ms     10.0±2ms
              ============ ============= ============ ============= ============= ============

[ 75.00%] · For scipy commit 4fd523c6 <master> (round 2/2):
[ 75.00%] ·· Building for virtualenv-py3.8-Cython0.29.21-numpy-pybind11-pytest.....
[ 75.00%] ·· Benchmarking virtualenv-py3.8-Cython0.29.21-numpy-pybind11-pytest
[100.00%] ··· optimize_lap.LinearAssignment.time_evaluation                                                                                                                                                                                               ok
[100.00%] ··· ============ ============= ============ ============= ============= ============
              --                                        cost_type
              ------------ -------------------------------------------------------------------
                 shapes       uniform      spatial     logarithmic     integer       binary
              ============ ============= ============ ============= ============= ============
               (100, 100)     284±30μs     358±60μs      311±20μs      267±10μs    134±0.4μs
               (200, 200)   1.20±0.02ms   1.88±0.2ms    1.34±0.1ms   1.16±0.07ms    525±1μs
               (300, 300)    4.58±0.6ms   5.88±0.4ms    2.97±0.1ms    4.29±0.7ms   2.70±0.7ms
               (400, 400)    8.36±0.8ms   12.0±0.9ms    5.92±0.2ms    7.82±0.8ms    4.84±1ms
               (100, 200)     213±10μs     211±20μs      212±7μs       199±8μs     255±0.5μs
               (200, 400)    2.13±0.6ms   2.10±0.6ms     753±40μs     2.12±0.6ms   2.36±0.6ms
               (300, 600)     4.91±1ms     4.85±1ms    1.68±0.02ms     4.78±1ms     5.39±1ms
               (400, 800)     8.93±2ms     8.99±2ms     3.16±0.1ms     8.72±2ms     9.77±2ms
              ============ ============= ============ ============= ============= ============


BENCHMARKS NOT SIGNIFICANTLY CHANGED.
```
</details>

**Comment by tylerjereddy** [comment]
Do we still need a space complexity/memory analysis or basically safe to merge now?

**Comment by mckib2** [comment]
Doing quick spot check, it seems that memory usage is not impacted very much at all (much to my surprise), so should be safe to merge.  I'll list the memory usage I measured below.

I got these rough-n-ready measurements by simply adding a `resource.getrusage(resource.RUSAGE_SELF).ru_maxrss` statement right after the `linear_sum_assignment` call in the benchmarks and choosing the max memory usage of each run.  (This may or may not be the right thing to do -- I'll rerun using the `memory_profiler` package to double check)

Memory usage for benchmarks,`master` vs `lsap-fix-unsafe-downcast` (in kilobytes):
- prob size (100, 100)
    - uniform: 53956 / 54128
    - spatial: 53892 / 54192
    - logarithmic: 54308 / 54528
    - integer: 54116 / 54288
    - binary: 54108 / 54288
- prob size (400, 800)
    - uniform: 61240 / 61400
    - spatial: 61336 / 61508
    - logarithmic: 61600 / 61760
    - integer: 61404 / 61560
    - binary: 61400 / 61564

Unless someone wants to do a better/more thorough analysis, this slight increase seems fine and I don't see any cause for concern

**Comment by tylerjereddy** [comment]
Thanks @mckib2
