### PR TITLE
BUG: special: Fixes for pro_rad1

### LINKED ISSUE #21058: BUG: `special.pro_rad1`: incorrect results
### Describe your issue.

In scipy 1.14.0 the special function pro_rad1 (prolate spheroidal radial wavefunction) is returning incorrect values.   The example code below is returning wrong results for all the input parameters I tried.  

```
print(scipy.special.pro_rad1(1,1,30,1.1))
print(scipy.__version__)
```

In scipy 1.14.0 the output is: 

```
(-93126.77064342781, 2390688.1114633614)
1.14.0
```

In scipy 1.11.4  (which I believe to be correct) the output is: 

```
print(scipy.special.pro_rad1(1,1,30,1.1))
print(scipy.__version__)
(0.009657798960703628, 3.253343602674869)
1.11.4
```
and which agree with Mathematica:
```
In[15]:= {SpheroidalS1[1, 1, 30, 1.1], SpheroidalS1Prime[1, 1, 30, 1.1]}
Out[15]= {0.00965787 + 0. I, 3.25337 + 0. I}
```
I don't know when between 1.11.4 and 1.14.0 the behavior changed.   

### Reproducing Code Example

```python
import scipy
print(scipy.special.pro_rad1(1,1,30,1.1))
print(scipy.__version__)
```

### Error message

```shell
no error messages.
```

### SciPy/NumPy/Python version and system information

```shell
1.14.0 1.26.4 sys.version_info(major=3, minor=12, micro=3, releaselevel='final', serial=0)
/opt/homebrew/Cellar/ipython/8.24.0/libexec/lib/python3.12/site-packages/scipy/__config__.py:154: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)
{
  "Compilers": {
    "c": {
      "name": "clang",
      "linker": "ld64",
      "version": "15.0.0",
      "commands": "cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.10",
      "commands": "cython"
    },
    "c++": {
      "name": "clang",
      "linker": "ld64",
      "version": "15.0.0",
      "commands": "c++"
    },
    "fortran": {
      "name": "gcc",
      "linker": "ld64",
      "version": "13.3.0",
      "commands": "gfortran"
    },
    "pythran": {
      "version": "0.16.1",
      "include directory": "../../../../../../private/var/folders/b3/2xm02wpd21qgrpkck5q1c6k40000gn/T/pip-build-env-n5qkg0as/overlay/lib/python3.12/site-packages/pythran"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "aarch64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    },
    "build": {
      "cpu": "aarch64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    },
    "cross-compiled": false
  },
  "Build Dependencies": {
    "blas": {
      "name": "accelerate",
      "found": true,
      "version": "unknown",
      "detection method": "extraframeworks",
      "include directory": "unknown",
      "lib directory": "unknown",
      "openblas configuration": "unknown",
      "pc file directory": "unknown"
    },
    "lapack": {
      "name": "accelerate",
      "found": true,
      "version": "unknown",
      "detection method": "extraframeworks",
      "include directory": "unknown",
      "lib directory": "unknown",
      "openblas configuration": "unknown",
      "pc file directory": "unknown"
    },
    "pybind11": {
      "name": "pybind11",
      "version": "2.12.0",
      "detection method": "config-tool",
      "include directory": "unknown"
    }
  },
  "Python Information": {
    "path": "/private/var/folders/b3/2xm02wpd21qgrpkck5q1c6k40000gn/T/cibw-run-4oat_w_z/cp312-macosx_arm64/build/venv/bin/python",
    "version": "3.12"
  }
}
```

### PR DESCRIPTION
**Pull request by steppi**
#### Reference issue

Closes #21058 

#### What does this implement/fix?

This PR fixes some mistakes that were made when `sphj` in `specfun` was translated from Fortran to C++. `sphj` is only used in `pro_rad1`,  and the existing test for `pro_rad1` did not cover the cases impacted by these mistakes. I've added a test using the failing example from #21058.

#### Additional information

The `rtol` for the test I've added is pretty high at `1e-5`, but the accuracy is now comparable (slightly better on my machine) to the old Fortran implementation.

### CODE REVIEW

File: scipy/special/special/specfun/specfun.h [hunk 1]
```diff
@@ -4318,7 +4318,7 @@ inline int msta2(double x, int n, int mp) {
         n1 = nn;
         f1 = f;
     }
-    return nn;
+    return nn + 10;
```
Comment (steppi) [inline scipy/special/special/specfun/specfun.h:4321]: https://github.com/scipy/scipy/blob/1d3a067c2ccd0a6efddeb3194163aa9a3879d26e/scipy/special/specfun/specfun.f#L1070

File: scipy/special/special/specfun/specfun.h [hunk 2]
```diff
@@ -4777,7 +4777,7 @@ inline void rmn1(int m, int n, T c, T x, int kd, T *df, T *r1f, T *r1d) {
 
     cx = c * x;
     nm2 = 2 * nm + m;
-    sphj(static_cast<T>(nm2), cx, &nm2, sj, dj);
+    sphj(cx, nm2, &nm2, sj, dj);
```
Comment (steppi) [inline scipy/special/special/specfun/specfun.h:4780]: The argument order of `sphj` was somehow switched during the translation, but it was still being called with the old order here.

https://github.com/scipy/scipy/blob/1d3a067c2ccd0a6efddeb3194163aa9a3879d26e/scipy/special/specfun/specfun.f#L9683

to

https://github.com/scipy/scipy/blob/1bd1e451561af13a76c66d84b8003391322d5e1e/scipy/special/special/specfun/specfun.h#L5572

File: scipy/special/special/specfun/specfun.h [hunk 3]
```diff
@@ -5597,7 +5597,7 @@ void sphj(T x, int n, int *nm, T *sj, T *dj) {
         }
         sj[0] = 1.0;
         if (n > 0) {
-            dj[0] = 1.0 / 3.0;
+            dj[1] = 1.0 / 3.0;
```
Comment (steppi) [inline scipy/special/special/specfun/specfun.h:5600]: dj is zero indexed in the Fortran as well, so this should be a 1 here

https://github.com/scipy/scipy/blob/1d3a067c2ccd0a6efddeb3194163aa9a3879d26e/scipy/special/specfun/specfun.f#L9699-L9708

File: scipy/special/special/specfun/specfun.h [hunk 4]
```diff
@@ -5621,7 +5621,7 @@ void sphj(T x, int n, int *nm, T *sj, T *dj) {
         f1 = 1e-100;
         for (k = m; k >= 0; k--) {
             f = (2.0*k + 3.0)*f1/x - f0;
-            if (k <= *nm) { sj[k - 1] = f; }
+            if (k <= *nm) { sj[k] = f; }
```
Comment (steppi) [inline scipy/special/special/specfun/specfun.h:5624]: This is what was causing the segfault. 

https://github.com/scipy/scipy/blob/1d3a067c2ccd0a6efddeb3194163aa9a3879d26e/scipy/special/specfun/specfun.f#L9730-L9732

File: scipy/special/special/specfun/specfun.h [hunk 5]
```diff
@@ -5631,7 +5631,7 @@ void sphj(T x, int n, int *nm, T *sj, T *dj) {
         }
     }
     for (k = 1; k <= *nm; k++) {
-        dj[k] = sj[k - 1] - (k + 1.0)*sj[k - 1]/x;
+        dj[k] = sj[k - 1] - (k + 1.0)*sj[k]/x;
```
Comment (steppi) [inline scipy/special/special/specfun/specfun.h:5634]: https://github.com/scipy/scipy/blob/1d3a067c2ccd0a6efddeb3194163aa9a3879d26e/scipy/special/specfun/specfun.f#L9742

File: scipy/special/special/specfun/specfun.h (hunk 2 above)
Comment (ilayn) [reply scipy/special/special/specfun/specfun.h:4780]: Not sure how this passed the compilation step. Probably we are not as strict as we should be with the compiler flags.

**Review by ilayn — APPROVED** [review]
I went over the changes and they seem to be complete. Thanks @steppi and apologies for the trouble again. A small comment about lax compiler options in our CI probably should apply but not really a show-stopper.

File: scipy/special/special/specfun/specfun.h (hunk 2 above)
Comment (steppi) [reply scipy/special/special/specfun/specfun.h:4780]: yeah, that's definitely something we should look into to

**Comment by steppi** [comment]
Thanks @ilhan. No worries. Adding stricter compiler flags in CI sounds like a good idea.

**Review by tylerjereddy — APPROVED** [review]
Core dev approval, CI passing, and looks quite clean with obvious regression test so in it goes.

I'll squash for backporting.
