### PR TITLE
FIX: Use pybind11::isinstace to check array dtypes

### LINKED ISSUE #10422: BUG: scipy.fft does not support multiprocessing
`scipy.fft` interacts badly with `joblib`, specifically when using the "processes" method. @peterbell10 tested and reports that it also fails for `multiprocessing.Pool` directly. But here was my MWE with joblib:
```Python
>>> import numpy as np
>>> from joblib import Parallel, delayed
>>> from scipy.fft import rfft
>>> [rfft(np.zeros(1)) for _ in range(2)]  # works
>>> Parallel(n_jobs=2, prefer='threads')(delayed(rfft)(np.zeros(1)) for _ in range(2))  # works
>>> Parallel(n_jobs=2, prefer='processes')(delayed(rfft)(np.zeros(1)) for _ in range(2))  # fails
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/larsoner/python/joblib/joblib/externals/loky/process_executor.py", line 418, in _process_worker
    r = call_item()
  File "/home/larsoner/python/joblib/joblib/externals/loky/process_executor.py", line 272, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/larsoner/python/joblib/joblib/_parallel_backends.py", line 567, in __call__
    return self.func(*args, **kwargs)
  File "/home/larsoner/python/joblib/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/home/larsoner/python/joblib/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/larsoner/python/scipy/scipy/fft/_basic.py", line 298, in rfft
    return _pocketfft.rfft(x, n, axis, norm, overwrite_x)
  File "/home/larsoner/python/scipy/scipy/fft/_pocketfft/basic.py", line 134, in rfft
    return pfft.r2c(tmp, (axis,), True, norm, None, _default_workers)
RuntimeError: unsupported data type
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/larsoner/python/joblib/joblib/parallel.py", line 934, in __call__
    self.retrieve()
  File "/home/larsoner/python/joblib/joblib/parallel.py", line 833, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/larsoner/python/joblib/joblib/_parallel_backends.py", line 521, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
RuntimeError: unsupported data type
```
Modifying the SciPy code to print the dtype and `__class__` of at least `tmp` shows `np.float64` and `np.ndarray` as expected, so I'm not sure what unsupported datatype we are getting.

### PR DESCRIPTION
**Pull request by peterbell10**
Fixes gh-10422

### CODE REVIEW

**Review by larsoner — APPROVED** [review]
+1 for merge assuming the CIs come back happy.

@grlee77 @mreineck want to look?

**Comment by mreineck** [comment]
Interesting, thanks for fixing this! I'll update the official pypocketfft as well.

Just curious, would it also have worked to replace `.is()` with `==` or `equals` (not sure ATM how to test Python object equality in pybind11)?

File: scipy/fft/_pocketfft/pypocketfft.cxx [hunk 1]
```diff
@@ -28,12 +28,12 @@ namespace py = pybind11;
 using ldbl_t = typename std::conditional<
   sizeof(long double)==sizeof(double), double, long double>::type;
 
-auto c64 = py::dtype("complex64");
-auto c128 = py::dtype("complex128");
-auto clong = py::dtype("longcomplex");
-auto f32 = py::dtype("float32");
-auto f64 = py::dtype("float64");
-auto flong = py::dtype("longfloat");
+using c64 = std::complex<float>;
```
Comment (grlee77) [inline scipy/fft/_pocketfft/pypocketfft.cxx]: I don't think I understand the relative merits of `using c64 = std::complex<float>;` vs `auto c64 = py::dtype("complex64");` .  Was that just a stylistic choice or was that change necessary for `py::isinstance` to work?

**Review by grlee77 — APPROVED** [review]
It looks good to me pending CI success. Nice to see a test case was added

**Comment by peterbell10** [comment]
> would it also have worked to replace `.is()` with `==` or `equals`.

In theory, I thought that `dtype.equals(f32)` would work but it didn't compile for me.

File: scipy/fft/_pocketfft/pypocketfft.cxx (hunk 1 above)
Comment (peterbell10) [reply scipy/fft/_pocketfft/pypocketfft.cxx]: `using` declares a type alias, similar to `typedef`.

**Comment by mreineck** [comment]
Is there any danger that we run in to similar problems with the `<whatever>.is(None)` tests in the code?

File: scipy/fft/_pocketfft/pypocketfft.cxx [hunk 2]
```diff
@@ -78,9 +78,9 @@ shape_t makeaxes(const py::array &in, const py::object &axes)
 #define DISPATCH(arr, T1, T2, T3, func, args) \
   { \
   auto dtype = arr.dtype(); \
```
Comment (mreineck) [inline scipy/fft/_pocketfft/pypocketfft.cxx]: This line has become unnecessary, I think.

**Comment by peterbell10** [comment]
>In theory, I thought that `dtype.equal(f32)` would work but it didn't compile for me.

I just checked and `.equal` is only in the latest version of pybind11.

>Is there any danger that we run in to similar problems with the <whatever>.is(None) tests in the code?

Not sure but maybe it would be safer to use `is_none()`?

**Comment by mreineck** [comment]
> Not sure but maybe it would be safer to use is_none()?

I didn't even know that exists :P  Perfect, I'll use it rigt away!

File: scipy/fft/_pocketfft/version.md [hunk 3]
```diff
@@ -13,4 +13,6 @@ SciPy currently vendors [pypocketfft][repo] at:
 
         New interface
 
+With the changes in `scipychanges.patch`
```
Comment (larsoner) [inline scipy/fft/_pocketfft/version.md]: @mreineck are you pushing the same changeset? If so then we don't need this right @peterbell10?

Comment (mreineck) [reply scipy/fft/_pocketfft/version.md]: I think you still need it, because `scipychanges.patch` refers to a specific (by now pretty outdated) commit in the pypocketfft repository.

**Comment by larsoner** [comment]
Okay, assuming Travis comes back happy I'll merge in a couple of hours, then, since we have a few +1's for merge (@mreineck feel free to block if I missed some comment above being unaddressed).

**Review by mreineck — APPROVED** [review]

File: scipy/fft/_pocketfft/version.md (hunk 3 above)
Comment (peterbell10) [reply scipy/fft/_pocketfft/version.md]: I see @mreineck has updated pypocketfft, I'll redo this.

Comment (peterbell10) [reply scipy/fft/_pocketfft/version.md]: @mreineck, `scipy.fft` is was actually up to date with pypocketfft master as of a few hours ago (#10393 merged).

Comment (mreineck) [reply scipy/fft/_pocketfft/version.md]: Sorry, I wasn't aware of this. I still assumed that this kind of synchronisation would be done once the dust of the first merge had settled.

**Comment by larsoner** [comment]
Thanks @peterbell10 for the quick fix!
